// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvaluatorInfo } from "./EvaluatorInfo";
import type { InvariantVerdict } from "./InvariantVerdict";

export type AuditProofReport = {
/**
 * On-disk schema version of this report shape.
 */
schema_version: string,
/**
 * ECAA spec version this package conforms to (§9.2). Required.
 */
ecaa_version: string,
/**
 * Minimum reader version required to consume the package (§9.2). Required.
 */
min_reader_version: string,
/**
 * Maximum reader version, when the emitter pins an upper bound (§9.2).
 */
max_reader_version?: string,
/**
 * IRI (or relative path) of the package's ro-crate-metadata.json.
 */
package_iri?: string,
/**
 * RFC-3339 timestamp the report was produced. Excluded from the
 * BagIt manifest so it does not break byte-reproducibility.
 */
evaluated_at?: string,
/**
 * Evaluator provenance (informative).
 */
evaluator: EvaluatorInfo,
/**
 * Per-invariant verdicts.
 */
verdicts: Array<InvariantVerdict>, };
