// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the stall monitor recommends the SME do. `BlockerCard` highlights
 * this as the default action; all three buttons are always offered.
 */
export type StallAction = "resize" | "retry" | "abort";
