//! 100× determinism replay test for
//! `composer_v4::plan`. Catches non-determinism that would escape the
//! per-module sort discipline (forward / backward / meet are each
//! deterministic individually; this checks the integrated planner is
//! byte-stable across replays given the same inputs).
//!
//! The replay harness serializes each `PlannerResult` through serde
//! JSON and SHA-256 hashes the bytes — comparing hashes catches every
//! drift, including ones that show up only in deeply-nested fields
//! (proof warnings, adapter id orderings, score tuple components).
//!
//! A cross-platform canonical-hash baseline gate is provided.
//! `emit_baseline_hashes` (ignored)
//! regenerates `.github/ci/determinism-baseline.json` on x86_64;
//! `cross_platform_hashes_match_baseline` runs on every Tier F nightly
//! matrix entry and fails on platform divergence.

use ecaa_workflow_core::archetype_registry::ArchetypeRegistry;
use ecaa_workflow_core::atom_registry::AtomRegistry;
use ecaa_workflow_core::composer_v4::{plan, PlannerResult, PlanningContext};
use ecaa_workflow_core::goal_spec::GoalSpec;
use ecaa_workflow_core::workflow_contracts::{
    data_product::DataProductContract,
    workflow_intent::{DesiredOutput, WorkflowIntent},
};
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::path::Path;

#[test]
fn plan_is_byte_stable_across_100_replays() {
    let atom_reg =
        AtomRegistry::load_from_dir(std::path::Path::new("../../config/stage-atoms")).unwrap();
    let archetype_reg =
        ArchetypeRegistry::load_from_dir(std::path::Path::new("../../config/archetypes")).unwrap();

    let de_goal = DataProductContract::sample_de_table();
    let goal_iri = de_goal.semantic_type.stable_id();

    let goal = GoalSpec {
        edam_data: goal_iri.clone(),
        edam_format: Some("format:3475".into()),
        modifiers: Default::default(),
        source_prose: Some("differential expression table from paired RNA-seq".into()),
        confidence: 0.9,
    };

    let intent = WorkflowIntent {
        id: "determinism_test".into(),
        schema_version: semver::Version::new(1, 0, 0),
        goal: "bulk RNA-seq DE".into(),
        modality: Some("bulk_rnaseq".into()),
        project_class: Some("research".into()),
        available_data: vec![DataProductContract::sample_paired_fastq()],
        desired_outputs: vec![DesiredOutput {
            label: "differential expression table".into(),
            edam_data: Some(goal_iri),
            edam_format: Some("format:3475".into()),
            human_readable: false,
        }],
        ..Default::default()
    };
    let mut ctx = PlanningContext::new(intent);
    ctx.max_branches = 32;
    ctx.max_depth = 6;
    ctx.max_alternatives = 3;

    let baseline = plan(&ctx, &goal, "research", &atom_reg, &archetype_reg);
    let baseline_hash = sha256(&baseline);

    for i in 0..100 {
        let replay = plan(&ctx, &goal, "research", &atom_reg, &archetype_reg);
        let replay_hash = sha256(&replay);
        assert_eq!(
            replay_hash, baseline_hash,
            "iteration {i}: planner output drifted from baseline; this indicates \
             non-deterministic iteration order in forward/backward/meet/scoring \
             (likely a HashMap that escaped the BTreeMap discipline)"
        );
    }
}

/// Hash a serializable value via SHA-256 over its JSON serialization.
/// `PlannerResult` carries `WorkflowDag` (with `f64`s in iteration
/// declarations) so we can't derive `Eq`; JSON-then-hash is the
/// established determinism pattern in this crate (see
/// `meet_in_the_middle` round-trip in `composer_v4_meet_in_middle.rs`).
fn sha256<T: serde::Serialize>(t: &T) -> String {
    let bytes = serde_json::to_vec(t)
        .expect("PlannerResult should be serde-serializable; if this panics, add Serialize derive");
    let mut hasher = Sha256::new();
    hasher.update(&bytes);
    format!("{:x}", hasher.finalize())
}

/// Sanity check: the helper itself is deterministic so a per-replay
/// failure can't be blamed on the harness.
#[test]
fn sha256_helper_is_deterministic() {
    let a = sha256(&"hello world");
    let b = sha256(&"hello world");
    assert_eq!(a, b);
    let _: PlannerResult = ecaa_workflow_core::composer_v4::PlannerResult {
        primary: ecaa_workflow_core::workflow_contracts::outcome::ComposeOutcome::PartialDag {
            dag: Default::default(),
            unresolved_gaps: Vec::new(),
        },
        alternatives: Vec::new(),
    };
}

// ---------------------------------------------------------------------------
// Round-2 G3 — cross-platform determinism CI gate
// ---------------------------------------------------------------------------

/// Path (relative to `crates/core/`) of the committed baseline file
/// regenerated by `emit_baseline_hashes` on x86_64 and asserted against
/// by `cross_platform_hashes_match_baseline` on every nightly matrix
/// entry (Linux x86_64, Linux ARM64, macOS).
const BASELINE_PATH: &str = "../../.github/ci/determinism-baseline.json";

/// Build a deterministic `PlanningContext` + `GoalSpec` keyed by a
/// modality slug. Mirrors the fixture shape used by
/// `plan_is_byte_stable_across_100_replays` and the
/// `composer_v4_bare_modality` corpus — same `PlanningContext`
/// budgets, same available-data shape, same `project_class` for the
/// `research`-routed modalities and the right project-class for the
/// project-class-routed ones.
///
/// Each fixture is small enough to compose quickly and stable enough
/// (no LLM, no runtime metadata) to produce identical bytes on
/// repeated runs of the same machine.
fn fixture_for_modality(modality: &str) -> (PlanningContext, GoalSpec, &'static str) {
    // Project-class default: the keyword-routable modalities live
    // under the `research` umbrella; `clinical_trial_analysis` and
    // `time_series_forecast` route by project_class with
    // generic_omics modality.
    let (project_class, goal_iri, goal_format, goal_prose) = match modality {
        "bulk_rnaseq" => (
            "research",
            "data:0951".to_string(),
            Some("format:3475".to_string()),
            "differential expression table from paired RNA-seq",
        ),
        "single_cell_rnaseq" => (
            "research",
            "data:0951".to_string(),
            Some("format:3475".to_string()),
            "single-cell clustering and marker discovery",
        ),
        "variant_calling" => (
            "research",
            "data:0951".to_string(),
            Some("format:3016".to_string()),
            "germline variant calling",
        ),
        "chip_seq" => (
            "research",
            "data:0951".to_string(),
            Some("format:3003".to_string()),
            "ChIP-seq peak calling",
        ),
        "generic_omics" => (
            "research",
            "data:9999".to_string(),
            None,
            "bare-modality intake (no goal phrase classified)",
        ),
        other => panic!("unsupported modality in determinism fixture: {other}"),
    };

    let goal = GoalSpec {
        edam_data: goal_iri.clone(),
        edam_format: goal_format.clone(),
        modifiers: Default::default(),
        source_prose: Some(goal_prose.into()),
        confidence: 0.9,
    };

    let intent = WorkflowIntent {
        id: format!("determinism_{modality}"),
        schema_version: semver::Version::new(1, 0, 0),
        goal: goal_prose.into(),
        modality: Some(modality.into()),
        project_class: Some(project_class.into()),
        available_data: vec![DataProductContract::sample_paired_fastq()],
        desired_outputs: vec![DesiredOutput {
            label: goal_prose.into(),
            edam_data: Some(goal_iri),
            edam_format: goal_format,
            human_readable: false,
        }],
        ..Default::default()
    };

    let mut ctx = PlanningContext::new(intent);
    ctx.max_branches = 32;
    ctx.max_depth = 6;
    ctx.max_alternatives = 3;

    (ctx, goal, project_class)
}

/// Compute canonical-hash entries for the given modality fixtures,
/// keyed by modality slug. `BTreeMap` for stable ordering.
fn emit_canonical_hashes(modalities: &[&str]) -> BTreeMap<String, String> {
    let atom_reg = AtomRegistry::load_from_dir(Path::new("../../config/stage-atoms")).unwrap();
    let archetype_reg =
        ArchetypeRegistry::load_from_dir(Path::new("../../config/archetypes")).unwrap();

    let mut out: BTreeMap<String, String> = BTreeMap::new();
    for m in modalities {
        let (ctx, goal, project_class) = fixture_for_modality(m);
        let result = plan(&ctx, &goal, project_class, &atom_reg, &archetype_reg);
        out.insert((*m).to_string(), sha256(&result));
    }
    out
}

/// Round-2 G3 baseline regenerator. Marked `#[ignore]` so it is *not*
/// part of the default test run — operators invoke it explicitly on the
/// canonical x86_64 dev machine to repopulate the baseline file when a
/// composition-affecting change lands (e.g. a new atom, a scoring
/// tweak, an archetype addition). The matching cross-platform gate
/// (`cross_platform_hashes_match_baseline`) runs on every Tier F
/// nightly matrix entry and fails on divergence.
///
/// Invocation:
/// ```bash
/// cargo test -p ecaa-workflow-core --test composer_v4_determinism \
/// --ignored emit_baseline_hashes -- --nocapture
/// ```
#[test]
#[ignore]
fn emit_baseline_hashes() {
    // Modality slugs covered. Spans the four keyword-routable
    // modalities currently covered by `composer_v4_bare_modality` plus
    // `generic_omics` (bare-modality fallback). Round-2 closure plan
    // §2.2 requires ≥5 entries spanning different modalities; this
    // satisfies that minimum.
    let modalities = [
        "bulk_rnaseq",
        "chip_seq",
        "generic_omics",
        "single_cell_rnaseq",
        "variant_calling",
    ];
    let hashes = emit_canonical_hashes(&modalities);

    let baseline_path = Path::new(BASELINE_PATH);
    if let Some(parent) = baseline_path.parent() {
        std::fs::create_dir_all(parent).expect("create .github/ci/ if missing");
    }

    let json = serde_json::to_string_pretty(&hashes).expect("serialize baseline JSON");
    std::fs::write(baseline_path, json + "\n").expect("write baseline file");

    eprintln!(
        "wrote {} canonical-hash baselines to {} on {}",
        hashes.len(),
        baseline_path.display(),
        std::env::consts::ARCH,
    );
    for (k, v) in &hashes {
        eprintln!("  {k}: {v}");
    }
}

/// Round-2 G3 cross-platform CI gate. Loads the committed baseline,
/// re-computes hashes on the current platform with the same fixtures,
/// and asserts equality. Designed to run on every Tier F nightly
/// matrix entry (`ubuntu-latest`, `ubuntu-latest-arm`, `macos-latest`)
/// — divergence on any platform fails the matrix job and surfaces a
/// platform-arch tag in the assertion message.
///
/// **Caveat:** the baseline is regenerated on x86_64; the first ARM64
/// / macOS run may FAIL if those platforms genuinely produce different
/// hashes. That's the gate's job — escalate to the user; do not
/// silently relax the assertion.
#[test]
#[ignore = ".github/ci/determinism-baseline.json not in OSS repo"]
fn cross_platform_hashes_match_baseline() {
    let baseline_path = Path::new(BASELINE_PATH);
    assert!(
        baseline_path.exists(),
        "baseline file missing at {}; regenerate via `cargo test -p ecaa-workflow-core \
         --test composer_v4_determinism --ignored emit_baseline_hashes -- --nocapture`",
        baseline_path.display()
    );

    let baseline_bytes =
        std::fs::read(baseline_path).expect("read .github/ci/determinism-baseline.json");
    let baseline: BTreeMap<String, String> =
        serde_json::from_slice(&baseline_bytes).expect("deserialize baseline JSON");

    assert!(
        baseline.len() >= 5,
        "baseline should cover ≥5 modalities (Round-2 closure plan §2.2); got {}",
        baseline.len()
    );

    let modalities: Vec<&str> = baseline.keys().map(|s| s.as_str()).collect();
    let observed = emit_canonical_hashes(&modalities);

    for (modality, expected) in &baseline {
        let actual = observed
            .get(modality)
            .unwrap_or_else(|| panic!("modality {modality} missing from observed hashes"));
        assert_eq!(
            actual,
            expected,
            "canonical-hash mismatch on arch={} modality={}\n  baseline (x86_64): {}\n  observed (this platform): {}",
            std::env::consts::ARCH,
            modality,
            expected,
            actual,
        );
    }
}
