//! L2 per-atom plot smoke test.
//!
//! For every entry in `runtime/plot-atoms-enumeration.json`, checks that the
//! corresponding renderer module produces every declared figure when driven
//! with synthetic stub data from `testdata/plot-stubs/<atom_id>/input/`.
//!
//! Behavior is controlled by `SWFC_PLOT_SMOKE_STRICT`:
//! - unset / "0": warn-only (print failures + skip summary, test passes)
//! - "1": hard failure on any renderer error, missing stub, or missing figure output
//!
//! Atoms without a stub directory under `testdata/plot-stubs/` are skipped and
//! counted in the skip summary; they cause failure in strict mode.
//!
//! PNG validity: the output file must be ≥ 4096 bytes and start with the
//! 8-byte PNG magic `\x89PNG\r\n\x1a\n`. PDF siblings must be non-empty
//! `%PDF-` files. The test never fakes these checks.
//!
//! Prerequisites (not asserted in tolerant mode):
//! - Python 3 with matplotlib + numpy installed
//! - `runtime/plot-atoms-enumeration.json` generated by
//!   `python3 scripts/enumerate_plot_atoms.py > runtime/plot-atoms-enumeration.json`
//!
//! Run with:
//!   cargo test -p ecaa-workflow-core --test per_atom_plot_smoke -- --nocapture
//! Or via `make atoms-l2`.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use serde::Deserialize;

const PNG_MAGIC: &[u8] = b"\x89PNG\r\n\x1a\n";
const PDF_MAGIC: &[u8] = b"%PDF-";

#[derive(Debug, Deserialize)]
struct PlotAtomEntry {
    atom_id: String,
    #[allow(dead_code)]
    semantic_type_iri: String,
    #[allow(dead_code)]
    renderer_module: String,
    figure_ids: Vec<String>,
    stage_id: String,
}

#[derive(Debug, Deserialize)]
struct FigureManifest {
    written: BTreeMap<String, String>,
    formats: BTreeMap<String, Vec<String>>,
    skipped: BTreeMap<String, String>,
    errors: BTreeMap<String, String>,
}

fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .to_path_buf()
}

fn load_entries(root: &Path) -> Vec<PlotAtomEntry> {
    let enum_path = root.join("runtime/plot-atoms-enumeration.json");
    if !enum_path.exists() {
        panic!(
            "runtime/plot-atoms-enumeration.json not found at {}.\n\
             Generate it first:\n  \
             python3 scripts/enumerate_plot_atoms.py > runtime/plot-atoms-enumeration.json",
            enum_path.display()
        );
    }
    let raw = fs::read_to_string(&enum_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", enum_path.display()));
    serde_json::from_str(&raw).unwrap_or_else(|e| {
        panic!(
            "failed to parse {}: {e}\n\
             Re-run: python3 scripts/enumerate_plot_atoms.py > runtime/plot-atoms-enumeration.json",
            enum_path.display()
        )
    })
}

/// Check that `path` is a valid PNG (magic bytes + size ≥ 4096).
fn is_valid_png(path: &Path) -> bool {
    match fs::read(path) {
        Ok(bytes) => bytes.len() >= 4096 && bytes.starts_with(PNG_MAGIC),
        Err(_) => false,
    }
}

/// Check that `path` is a valid PDF sibling (magic bytes + non-empty body).
fn is_valid_pdf(path: &Path) -> bool {
    match fs::read(path) {
        Ok(bytes) => bytes.len() >= 512 && bytes.starts_with(PDF_MAGIC),
        Err(_) => false,
    }
}

fn load_figure_manifest(output_dir: &Path) -> Result<FigureManifest, String> {
    let manifest_path = output_dir.join("manifest.json");
    let raw = fs::read_to_string(&manifest_path)
        .map_err(|e| format!("failed to read {}: {e}", manifest_path.display()))?;
    serde_json::from_str(&raw)
        .map_err(|e| format!("failed to parse {}: {e}", manifest_path.display()))
}

fn copy_dir_recursive(src: &Path, dst: &Path) -> std::io::Result<()> {
    fs::create_dir_all(dst)?;
    for entry in fs::read_dir(src)? {
        let entry = entry?;
        let src_path = entry.path();
        let dst_path = dst.join(entry.file_name());
        if src_path.is_dir() {
            copy_dir_recursive(&src_path, &dst_path)?;
        } else {
            fs::copy(&src_path, &dst_path)?;
        }
    }
    Ok(())
}

#[test]
fn per_atom_plot_smoke() {
    let strict = std::env::var("SWFC_PLOT_SMOKE_STRICT")
        .map(|v| v == "1")
        .unwrap_or(false);

    let root = workspace_root();
    let entries = load_entries(&root);

    let mut passed: Vec<String> = Vec::new();
    let mut failed: Vec<String> = Vec::new();
    let mut skipped_no_stub: Vec<String> = Vec::new();

    for entry in &entries {
        let atom_stub_root = root.join("testdata/plot-stubs").join(&entry.atom_id);
        let stub_dir = atom_stub_root.join("input");

        if !stub_dir.exists() {
            skipped_no_stub.push(entry.atom_id.clone());
            continue;
        }

        // Run renderers against a scratch copy of the stub. Some stages
        // emit interactive view_data next to outputs_dir; invoking them
        // directly on testdata/ would dirty the tracked fixture tree.
        let input_dir = tempfile::tempdir().unwrap_or_else(|e| {
            panic!("failed to create input tempdir for {}: {e}", entry.atom_id)
        });
        let scratch_atom_root = input_dir.path().join(&entry.atom_id);
        let scratch_input = scratch_atom_root.join("input");
        if let Err(e) = copy_dir_recursive(&atom_stub_root, &scratch_atom_root) {
            failed.push(format!(
                "atom={} stage={} failed to copy stub input: {e}",
                entry.atom_id, entry.stage_id
            ));
            continue;
        }

        // Create a temp directory for output figures.
        let output_dir = tempfile::tempdir()
            .unwrap_or_else(|e| panic!("failed to create tempdir for {}: {e}", entry.atom_id));

        let result = Command::new("python3")
            .args(["-m", "lib.plotting._cli", &entry.stage_id, "--input-dir"])
            .arg(&scratch_input)
            .arg("--output-dir")
            .arg(output_dir.path())
            .current_dir(&root)
            .output();

        let outcome = match result {
            Err(e) => {
                // python3 not found or similar OS-level failure.
                format!(
                    "atom={} stage={} OS error launching python3: {e}",
                    entry.atom_id, entry.stage_id
                )
            }
            Ok(out) => {
                let stderr = String::from_utf8_lossy(&out.stderr);
                if !out.status.success() {
                    format!(
                        "atom={} stage={} renderer exited {}: {}",
                        entry.atom_id,
                        entry.stage_id,
                        out.status.code().unwrap_or(-1),
                        stderr.trim()
                    )
                } else {
                    match load_figure_manifest(output_dir.path()) {
                        Err(e) => format!("atom={} stage={} {e}", entry.atom_id, entry.stage_id),
                        Ok(manifest) => {
                            let mut problems: Vec<String> = Vec::new();
                            if entry.figure_ids.is_empty() {
                                problems.push("enumeration declared no figure_ids".to_string());
                            }

                            for figure_id in &entry.figure_ids {
                                if let Some(reason) = manifest.errors.get(figure_id) {
                                    problems
                                        .push(format!("figure '{figure_id}' errored: {reason}"));
                                }
                                if let Some(reason) = manifest.skipped.get(figure_id) {
                                    problems
                                        .push(format!("figure '{figure_id}' skipped: {reason}"));
                                }
                                if !manifest.written.contains_key(figure_id) {
                                    problems.push(format!(
                                        "figure '{figure_id}' missing from manifest.written"
                                    ));
                                }

                                let png = output_dir.path().join(format!("{figure_id}.png"));
                                if !is_valid_png(&png) {
                                    problems.push(format!(
                                        "figure '{figure_id}' PNG missing or invalid at {}",
                                        png.display()
                                    ));
                                }

                                let pdf = output_dir.path().join(format!("{figure_id}.pdf"));
                                if !is_valid_pdf(&pdf) {
                                    problems.push(format!(
                                        "figure '{figure_id}' PDF missing or invalid at {}",
                                        pdf.display()
                                    ));
                                }

                                let formats = manifest.formats.get(figure_id);
                                let has_png_format = formats
                                    .map(|paths| paths.iter().any(|p| p.ends_with(".png")))
                                    .unwrap_or(false);
                                let has_pdf_format = formats
                                    .map(|paths| paths.iter().any(|p| p.ends_with(".pdf")))
                                    .unwrap_or(false);
                                if !has_png_format || !has_pdf_format {
                                    problems.push(format!(
                                        "figure '{figure_id}' manifest.formats missing png/pdf entries"
                                    ));
                                }
                            }

                            if problems.is_empty() {
                                passed.push(entry.atom_id.clone());
                                // No failure message — continue to next entry.
                                continue;
                            }

                            format!(
                                "atom={} stage={} expected_figures=[{}] problems: {}",
                                entry.atom_id,
                                entry.stage_id,
                                entry.figure_ids.join(", "),
                                problems.join("; ")
                            )
                        }
                    }
                }
            }
        };

        // Reached here = failure.
        failed.push(outcome);
    }

    if strict {
        for atom_id in &skipped_no_stub {
            failed.push(format!(
                "atom={atom_id} missing testdata/plot-stubs/<id>/input/ stub in strict mode"
            ));
        }
    }

    let total = entries.len();
    let n_passed = passed.len();
    let n_failed = failed.len();
    let n_skipped = skipped_no_stub.len();

    println!(
        "[per_atom_plot_smoke] total={total} passed={n_passed} failed={n_failed} \
         skipped_no_stub={n_skipped}"
    );

    if !skipped_no_stub.is_empty() {
        println!(
            "[per_atom_plot_smoke] skipped atoms (no testdata/plot-stubs/<id>/input/):\n  {}",
            skipped_no_stub.join(", ")
        );
    }

    if !failed.is_empty() {
        let report = failed.join("\n  ");
        if strict {
            panic!(
                "[per_atom_plot_smoke] {n_failed} failure(s) with SWFC_PLOT_SMOKE_STRICT=1:\n  {report}"
            );
        } else {
            println!(
                "[per_atom_plot_smoke] {n_failed} failure(s) (warn-only; set \
                 SWFC_PLOT_SMOKE_STRICT=1 to fail):\n  {report}"
            );
        }
    }
}
