// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resolution status of an `AdjudicationQueueEntry`.
 */
export type AdjudicationStatus = { "kind": "open" } | { "kind": "resolved", 
/**
 * Who resolved the entry.
 */
decided_by: string, 
/**
 * Free-text decision narrative.
 */
decision: string, 
/**
 * ISO-8601 UTC timestamp.
 */
decided_at: string, } | { "kind": "deferred_to_operator", 
/**
 * Free-text reason for the escalation.
 */
reason: string, };
