// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coarse intent classification attached to assistant turns. Used by the
 * UI to choose the appropriate rendering style (e.g. `SummaryConfirm` → show the
 * confirm card; `Blocker` → show the blocker card).
 */
export type AssistantIntent = "greeting" | "acknowledge" | "clarify" | "summary_confirm" | "recommend" | "post_emission" | "blocker";
