// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AtomSummary = { id: string, 
/**
 * String form of `AtomRole` — lowercase snake_case.
 */
role: string, edam_operation: string, 
/**
 * Optional on the underlying `AtomDefinition`; surfaced as an
 * empty string when absent so the JSON shape stays uniform.
 */
edam_data: string, edam_format: string, 
/**
 * Upstream atoms this atom consumes (by id). Ordering matches
 * the YAML's `depends_on:` list.
 */
depends_on: Array<string>, 
/**
 * Candidate tool ids from `attributes.candidate_tools`. Empty
 * when the atom doesn't expose runtime tool selection.
 */
candidate_tools: Array<string>, 
/**
 * Set when `method_choice.deferred_to` points at a discovery
 * atom (e.g. `discover_dtu_method`). Surfaces the discovery
 * wrapper so the LLM can chain proposals correctly.
 */
method_choice_deferred_to?: string, };
