// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AtomRoleFilter = "operation" | "discovery" | "validation" | "aggregator" | "sizing" | "selection" | "calibration" | "pilot" | "adversarial" | "monitor";
