// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire type for the branch endpoint's POST body (M1.3). Extends the
 * existing `CheckpointDecisionRequest.rationale` path with an optional
 * `task_id` that pins the branch to a specific DAG boundary.
 *
 * Exported via ts-rs so the UI and API contract stay in sync.
 */
export type BranchInput = { 
/**
 * Optional rationale for the branch (surfaced in the decision log).
 */
rationale?: string, 
/**
 * Optional task boundary. When set, the child session's DAG is
 * snapshotted with this task reset to Ready and its transitive
 * successors reset to Pending. None means a full session-scoped
 * branch (M1.1 behaviour).
 */
task_id?: string, };
