// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditorProcedure } from "./AuditorProcedure";
import type { ContentCommitment } from "./ContentCommitment";
import type { PolicyRuleId } from "./PolicyRuleId";
import type { SuppressionClass } from "./SuppressionClass";

/**
 * Required chain-of-custody fields on every provenance
 * record. Composed as `Option<ChainOfCustody>` on record types so
 * older records without custody info remain valid.
 */
export type ChainOfCustody = { 
/**
 * Class of suppression / redaction applied (matches a registered
 * taxonomy ID, e.g. `phi_strict`, `prompt_injection`,
 * `controlled_access_genotype`).
 */
suppression_class: SuppressionClass, 
/**
 * Subsystem identifier (e.g. `provenance_tiers::redact_record`,
 * `ingestion_safety::quarantine`).
 */
suppressing_component: string, 
/**
 * RFC3339 timestamp.
 */
suppression_timestamp: string, 
/**
 * Foreign key into the `policy_rules:` registry in
 * `config/assumption-policy.yaml`. Constructed via
 * [`PolicyRuleId::new`] in registry-aware contexts, or via
 * [`PolicyRuleId::unchecked`] (the `From<&str>` / `From<String>`
 * blanket impls) where the registry isn't reachable.
 */
policy_rule_id: PolicyRuleId, 
/**
 * Cryptographic commitment (BLAKE3 hash) over the suppressed
 * payload. `None` when the payload is structurally guessable from
 * a hash and a non-public commitment is filed under the
 * restricted-archive procedure.
 */
cryptographic_commitment?: ContentCommitment, 
/**
 * How an authorized auditor retrieves full content.
 */
auditor_access: AuditorProcedure, };
