// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConcordanceFlag } from "./ConcordanceFlag";
import type { EntityKind } from "./EntityKind";
import type { SourceKind } from "./SourceKind";

/**
 * One row from `claims_evidence_matrix.csv`: a contextualized
 * finding cross-referenced against prior literature.
 */
export type ClaimsEvidenceRow = { 
/**
 * Unique finding identifier within this analysis run.
 */
finding_id: string, 
/**
 * Entity name (gene, pathway, etc.).
 */
entity: string, 
/**
 * Biological entity type.
 */
entity_kind: EntityKind, 
/**
 * PMIDs of prior publications that reported findings on this entity.
 */
prior_pmids: Array<string>, 
/**
 * How the new finding relates to the prior literature.
 */
concordance_flag: ConcordanceFlag, 
/**
 * Verbatim quote from the evidence source.
 */
evidence_quote: string, 
/**
 * Where the evidence text was retrieved from.
 */
source_kind: SourceKind, };
