// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceEstimate } from "./ResourceEstimate";
import type { RetainedOptionalStage } from "./RetainedOptionalStage";

/**
 * Plan-summary card rendered by `propose_summary_confirmation`. Persisted
 * on the turn so the UI can re-render after page reload.
 */
export type ConfirmationCard = { 
/**
 * Markdown summary of the current plan presented to the SME for approval.
 */
summary_markdown: string, 
/**
 * SHA-256 hex digest of `summary_markdown`
 * at the moment the card was raised. The UI renders the leading
 * 12 hex chars as a "summary fingerprint" so the SME can verify
 * the durable audit record references the exact text they saw.
 * The `/confirm` endpoint attaches the same hash to the
 * `DecisionType::Confirm` audit record, so a later replayer can
 * match the recorded fingerprint to the text in `intake-conversation.jsonl`
 * and detect tampering / drift between the displayed card and the
 * confirmed text.
 *
 * `#[serde(default)]` so existing on-disk sessions whose cards
 * pre-date this field deserialize cleanly with an empty hash —
 * the legacy records carry no fingerprint, which is fine because
 * they also pre-date the matching audit-record field.
 */
summary_hash: string, 
/**
 * Coarse resource estimate aggregated from each
 * atom's `resource_profile`. Rendered inline so the SME sees a
 * "≈ N core-hours, peak M GB" cost preview before clicking
 * Accept. None for legacy / non-composer paths.
 */
resource_estimate?: ResourceEstimate, 
/**
 * Retained *optional* analysis stages still present in the composed
 * DAG at confirmation time. Surfaced so the SME can drop one before
 * emit (each entry renders as a removable chip in the confirmation
 * card; the UI's "remove" affordance posts an exclusion for the
 * `stage_id`, which rebuilds the DAG without it).
 *
 * "Optional" = the curated set
 * [`CURATED_OPTIONAL_STAGES`] (`pathway_enrichment`,
 * `contextualize_findings_with_literature`) intersected with the
 * stages actually present in the composed DAG. Empty when none of
 * the curated optional stages survived composition.
 *
 * `#[serde(default)]` so on-disk cards that pre-date this field
 * deserialize cleanly with an empty list; `skip_serializing_if`
 * keeps the wire payload unchanged for the common (empty) case.
 * (No `#[ts(optional)]`: ts-rs reserves that for `Option<T>`. A `Vec`
 * maps to a TS array that defaults to `[]`, and `skip_serializing_if`
 * keeps the wire payload unchanged for the common empty case.)
 */
retained_optional_stages?: Array<RetainedOptionalStage>, };
