// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceKind } from "./SourceKind";

/**
 * One entry from `evidence/manifest.json`: describes a source
 * document included in the literature evidence bundle.
 */
export type EvidenceManifestEntry = { 
/**
 * PubMed ID of the source article.
 */
pmid: string, 
/**
 * Where the evidence text was retrieved from.
 */
source_kind: SourceKind, 
/**
 * Relative path to the evidence file within the bundle.
 */
path: string, 
/**
 * Whether the source may be redistributed with the package.
 */
redistributable: boolean, };
