// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry on the `excluded_paths` list of
 * `BlockerKind::CompositionInfeasible`. Records an atom the
 * backward chain considered but excluded, plus the CEL expression
 * (verbatim from the atom's `excludes:` block) that matched. Lets
 * the SME see why a candidate was ruled out without re-running the
 * composer.
 */
export type ExcludedPath = { atom_id: string, exclusion_cel: string, };
