// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Single-use latch authorizing exactly one `start_execution`.
 */
export type ExecutionToken = { 
/**
 * The emission/run this token authorizes. Bound at mint time to the
 * session's current `pending_emission_id`.
 */
request_id: string, 
/**
 * When the SME pressed the Start button server-side.
 */
granted_at: string, 
/**
 * Single-use latch; `consume()` sets it and `authorizes()` then
 * returns false. `#[serde(default)]` keeps legacy on-disk tokens
 * (which have no `consumed` key) loadable as `consumed = false`.
 */
consumed: boolean, };
