// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteExecutionInfo } from "./RemoteExecutionInfo";

/**
 * Progress event posted by the harness to the server's `/progress` endpoint.
 * Batched by `harness_batch.rs` into synthetic assistant turns.
 */
export type HarnessEvent = { 
/**
 * Event kind string (e.g. `"task_started"`, `"task_completed"`, `"task_blocked"`).
 */
kind: string, 
/**
 * Task id the event refers to (matches a `WORKFLOW.json` task id).
 */
task_id: string, 
/**
 * Human-readable status label (e.g. `"Running"`, `"Completed"`).
 */
status: string, 
/**
 * Free-text detail message for this event.
 */
detail: string, 
/**
 * Remote-execution metadata when the harness is running against a
 * cloud backend. None for local execution. Additive-serde
 * (`#[serde(default, skip_serializing_if =...)]`) so existing
 * on-disk session JSON and existing ProgressClient payloads without
 * the field continue to deserialize.
 */
remote?: RemoteExecutionInfo, 
/**
 * UTC timestamp when the event was posted.
 */
timestamp: string, };
