// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Literature retrieval scope used when this session was emitted.
 */
export type LiteratureScope = "pmc_oa" | "pmc_oa_plus_abstracts" | "all_sources_local_only";
