// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaimsEvidenceRow } from "./ClaimsEvidenceRow";
import type { EntityKind } from "./EntityKind";
import type { EvidenceManifestEntry } from "./EvidenceManifestEntry";
import type { LiteratureScope } from "./LiteratureScope";
import type { PriorClaimRow } from "./PriorClaimRow";

/**
 * Full literature context for a single entity, returned by the
 * `get_literature_context` tool.
 */
export type LiteratureContext = { 
/**
 * Entity name that was queried (lowercased for matching; original
 * case preserved from the query).
 */
entity: string, 
/**
 * Entity type inferred or provided by the caller.
 */
entity_kind: EntityKind, 
/**
 * Prior published claims for this entity.
 */
prior_rows: Array<PriorClaimRow>, 
/**
 * New-finding cross-references for this entity.
 */
finding_rows: Array<ClaimsEvidenceRow>, 
/**
 * Evidence source documents associated with the results.
 */
source_artifacts: Array<EvidenceManifestEntry>, 
/**
 * Retrieval scope in effect when this package was emitted.
 */
source_scope: LiteratureScope, };
