// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A (node, port) call site that produced an opaque-typed value.
 */
export type OpaquePortRef = { 
/**
 * Task / atom node id.
 */
node: string, 
/**
 * Port name within that node.
 */
port: string, };
