// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Subset of `crates/core::dag::RemoteExecution` the harness reports on
 * progress events. Only the three fields the UI actually renders —
 * backend badge, instance id for the jobs feed, instance type for the
 * sizing chip — cross the session boundary. `command_id` and
 * `output_uri` stay in the DAG.
 */
export type RemoteExecutionInfo = { 
/**
 * Backend label (e.g. `"aws"`, `"slurm"`).
 */
backend: string, 
/**
 * Cloud/HPC instance identifier for the jobs feed.
 */
instance_id: string, 
/**
 * EC2 or SLURM partition instance type string.
 */
instance_type: string, };
