// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-refusal record carried in `BlockerKind::SandboxRefused`.
 * Mirrors `crates/core/src/sandbox_policy.rs::SandboxRefusal` but with
 * stringified discriminator + reason so the UI dispatch table can
 * render without depending on the harness crate.
 */
export type SandboxRefusalRecord = { kind: string, detail: string, };
