// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StructuredCaptureFieldKind } from "./StructuredCaptureFieldKind";

/**
 * One field inside a `StructuredCaptureTurnCard`. Matches the shape the
 * existing UI component `StructuredCaptureTurnCard.tsx` already consumes.
 * The `kind` field lets the UI pick an input type (integer vs. float
 * vs. plain string) and lets the harness reject inputs that violate
 * the declared type without a round-trip. The four AWS-sizing
 * canonical keys — `sample_count`, `coverage_depth`, `cell_count`,
 * `database_size_gb` — are documented here but not enumerated in the
 * Rust type (tool calls requesting them use these exact keys; the
 * sizing layer reads them back out of the captured values).
 */
export type StructuredCaptureField = { 
/**
 * Stable key the conversation service uses to round-trip the
 * value. For AWS-sizing fields use one of the canonical names:
 * sample_count, coverage_depth, cell_count, database_size_gb.
 */
key: string, 
/**
 * Human-readable field label shown above the input widget.
 */
label: string, 
/**
 * Optional placeholder text shown inside the input widget when empty.
 */
placeholder?: string, 
/**
 * If true, the SME must supply a non-empty value before the card can be submitted.
 */
required: boolean, 
/**
 * If true, render as a textarea instead of a single-line input.
 */
multiline: boolean, 
/**
 * Input-type hint. The UI renders everything as a text input
 * (the generic component doesn't type-switch) but the
 * conversation service validates captured values against this
 * kind before handing them to `IntakeFacts`.
 */
kind: StructuredCaptureFieldKind, };
