// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Closed taxonomy of suppression kinds. Maps to the §15.2 policy
 * table and to ingestion-safety quarantine reasons.
 */
export type SuppressionClass = "phi_strict" | "controlled_access_genotype" | "prompt_injection" | "structurally_guessable_identifier" | "raw_credential" | "user_supplied_free_text" | "proprietary_pipeline_detail";
