// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the SME supplied their input data to the session.
 */
export type UserInputKind = "local_path" | "uploaded_files";
