// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Closed vocabulary of actions a disposition can request. Adding a
 * new variant is a plan-level change — the apply loop in
 * `crates/server/src/chat_routes/dispositions.rs` must grow a match
 * arm, and UI copy in `DispositionReviewCard.tsx` must know how to
 * render it.
 *
 * `kind` is internally tagged (`#[serde(tag = "kind", rename_all =
 * "snake_case")]`) so on-wire JSON is flat — e.g.
 * `{"kind":"amend_method","target_stage":"...", "new_method":"..."}`.
 */
export type Action = { "kind": "amend_method", 
/**
 * Target stage.
 */
target_stage: string, 
/**
 * New method.
 */
new_method: string, 
/**
 * Rationale.
 */
rationale?: string, 
/**
 * Passed through; not consumed by the apply loop itself but
 * surfaced to the SME in the card preview. Retained so the
 * agent doesn't lose context when the disposition file is
 * rewritten with `status: "applied"`.
 */
per_compartment?: Array<string>, 
/**
 * v1 passthrough for the v0 `preserve_sme_pins` boolean. Not
 * consumed by the apply loop yet — `preserve_pin` is a v2
 * action kind (§4.1 of the plan).
 */
preserve_sme_pins: boolean, } | { "kind": "rerun", 
/**
 * Target stage.
 */
target_stage: string, 
/**
 * Reason.
 */
reason?: string, } | { "kind": "invalidate_slice", 
/**
 * From stage.
 */
from_stage: string, 
/**
 * Stages explicit.
 */
stages_explicit: Array<string>, 
/**
 * Optional passthrough from v0 `preserved_sme_pins_for_downstream_rerun`
 * so the audit trail survives normalisation.
 */
preserved_pins?: unknown | null, } | { "kind": "preserve_pin", 
/**
 * Target stage.
 */
target_stage: string, 
/**
 * Method.
 */
method: string, };
