// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdapterClass } from "./AdapterClass";
import type { AdapterSafety } from "./AdapterSafety";
import type { ValidatorRef } from "./ValidatorRef";

/**
 * A typed adapter spec. The composer treats adapters as
 * first-class `TaskNode`s when inserting them; the registry's
 * role is to look up the right adapter for an edge and return
 * the materialized `TaskNode` skeleton.
 */
export type AdapterSpec = { 
/**
 * Stable id (`gzip_decompress`, `bam_index`, `liftover_grch37_grch38`).
 */
id: string, 
/**
 * Human label.
 */
name: string, 
/**
 * Class.
 */
class: AdapterClass, 
/**
 * Safety.
 */
safety: AdapterSafety, 
/**
 * Optional source format IRI (e.g. `format:1929` for FASTA;
 * `None` matches any format).
 */
from_format?: string, 
/**
 * Optional destination format IRI.
 */
to_format?: string, 
/**
 * Optional source semantic type stable id.
 */
from_semantic_type?: string, 
/**
 * Optional destination semantic type stable id.
 */
to_semantic_type?: string, 
/**
 * Free-text rationale. Surfaces in `CompatibilityProof.rationale`
 * when this adapter is inserted.
 */
rationale?: string, 
/**
 * V3 alignment validators auto-attached to every
 * consumer port connected via this adapter. For Lossless adapters,
 * these are invariant checks (identity preservation, schema
 * preservation). For Lossy / Risky adapters, these are
 * postcondition checks.
 *
 * The F10 invariant: every Lossless adapter MUST carry at least
 * one validator so the contracted output shape is checked rather
 * than trusted. The starter set in `starter_adapters()` populates
 * at least one validator per Lossless entry; the property test
 * `f10_adapter_validator_presence.rs` locks the invariant.
 */
validators: Array<ValidatorRef>, };
