// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of work an adapter does. Mirrors design §14.
 */
export type AdapterClass = "format_conversion" | "compression" | "index_generation" | "sorting" | "filtering" | "normalization" | "identifier_mapping" | "coordinate_liftover" | "metadata_join" | "sample_sheet_generation" | "container_wrapping" | "schema_conversion" | "reference_download" | "qc_gate";
