// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Safety classification of an adapter. Drives whether the
 * composer can auto-insert it.
 */
export type AdapterSafety = "lossless" | "lossy_declared" | "scientifically_risky" | "policy_restricted";
