// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * AffordanceProof data.
 */
export type AffordanceProof = { 
/**
 * Output port semantic-type IRI or `LocalExtension` id the
 * affordance was resolved against.
 */
source_semantic_type: string, 
/**
 * Ordered ontology terms walked during resolution; empty for
 * `Registered`/`StructuralFallback`/`Deferred`.
 */
ontology_walk: Array<string>, 
/**
 * Snapshot id of the registry the resolution consulted; required
 * for replay determinism.
 */
registry_snapshot_id: string, 
/**
 * Theme version (`theme.json` file digest) used at render time.
 */
theme_version: string, 
/**
 * Human-readable rationale; surfaced in the UI badge.
 */
rationale: string, };
