// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AtomId } from "./AtomId";
import type { FigureExempt } from "./FigureExempt";

/**
 * An atom referenced from an archetype's scaffold. Carries the
 * per-call wiring overrides the composer applies on top of the
 * atom's intrinsic shape.
 */
export type ArchetypeAtomRef = { 
/**
 * Atom id (must exist in the AtomRegistry at composer time).
 */
atom_id: AtomId, 
/**
 * Optional alias used as the stage-id in the composed DAG.
 * Without an alias the atom_id is the stage id; alias-distinct
 * allows the same atom to appear twice in one composition
 * (e.g. a discovery atom paired with its operation atom).
 */
alias?: string, 
/**
 * Per-call dependency overrides the composer respects.
 */
depends_on: Array<string>, 
/**
 * Whether this atom is required or optional. When `optional`,
 * the composer skips it if the SME's intake doesn't supply
 * the inputs the atom needs.
 */
required: boolean, 
/**
 * Per-call figure override. When present, replaces the referenced
 * atom's `required_figures` for this archetype slot. This is used
 * when the same atom appears twice with different modalities.
 */
required_figures?: Array<string>, 
/**
 * Per-call plotting module override. Usually unnecessary because
 * the compiler falls back to the underlying atom id for aliased
 * stages, but useful for modality-specific shared modules.
 */
plot_stage_id?: string, 
/**
 * Per-call expected artifact override.
 */
expected_artifacts?: Array<string>, 
/**
 * Per-call required artifact override.
 */
required_artifacts?: Array<{ path: string; min_size_bytes?: number; schema_ref?: string }>, 
/**
 * Per-call figure-obligation lint exemption. When set, overrides the
 * atom's own `figure_exempt` for this archetype slot.
 */
figure_exempt?: FigureExempt, };
