// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReexecutionBucket } from "./ReexecutionBucket";

/**
 * Bucket assignment for a single artifact path.
 */
export type ArtifactClassification = { 
/**
 * Artifact path.
 */
artifact_path: string, 
/**
 * Bucket.
 */
bucket: ReexecutionBucket, 
/**
 * Reason.
 */
reason: string | null, };
