// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable reference to an assumption ledger entry. Carried in
 * `CompatibilityProof.assumptions` and rendered in the UI's
 * AssumptionCard.
 */
export type AssumptionRef = { 
/**
 * Id.
 */
id: string, };
