// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PolicyRuleId } from "./PolicyRuleId";

/**
 * How an assumption was resolved (or not). Variants cover the
 * full lifecycle: `Accepted`, `Rejected`, `ResolvedByValidator`,
 * `Contradicted`, and `WaivedWithRisk`.
 */
export type AssumptionResolution = { "kind": "unresolved" } | { "kind": "accepted", rationale: string, } | { "kind": "rejected", rationale: string, } | { "kind": "resolved_by_validator", 
/**
 * Validator id.
 */
validator_id: string, 
/**
 * Result ref.
 */
result_ref: string, } | { "kind": "contradicted", 
/**
 * Prior confirmation id.
 */
prior_confirmation_id: string, 
/**
 * Conflicting confirmation id.
 */
conflicting_confirmation_id: string, } | { "kind": "waived_with_risk", 
/**
 * Policy rule id.
 */
policy_rule_id: PolicyRuleId, 
/**
 * Rationale.
 */
rationale: string, 
/**
 * Credentials.
 */
credentials: Array<string>, };
