// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GovernanceStatus } from "./GovernanceStatus";

/**
 * Atom-registry governance lifecycle metadata (G4). Optional +
 * additive; `None` means "unmanaged" — allowed for non-Exec atoms,
 * refused for Exec atoms by the load gate.
 */
export type AtomGovernance = { 
/**
 * Lifecycle status. Defaults to `Draft`.
 */
status: GovernanceStatus, 
/**
 * Reviewer identity (team / individual). Author-supplied.
 */
reviewed_by?: string, 
/**
 * Author-supplied static `YYYY-MM-DD`. NOT `SystemTime::now()` —
 * deterministic emission requires the date be authored text.
 */
review_date?: string, 
/**
 * Atom id this revision supersedes, if any.
 */
supersedes?: string, };
