// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AtomOrigin } from "./AtomOrigin";

/**
 * Atom provenance — the paper-D.1 `provenance(origin, maintainer)`
 * axis. Author-set in YAML, never inferred (so emission stays
 * deterministic). Optional and additive.
 */
export type AtomProvenance = { 
/**
 * Where this atom came from.
 */
origin: AtomOrigin, 
/**
 * Responsible maintainer (team or handle). Free-form string.
 */
maintainer: string, };
