// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AtomAssignee } from "./AtomAssignee";
import type { AtomRole } from "./AtomRole";
import type { ContainerSpec } from "./ContainerSpec";
import type { FigureExempt } from "./FigureExempt";
import type { IterateSpec } from "./IterateSpec";
import type { JointlyWithConstraint } from "./JointlyWithConstraint";
import type { MethodChoiceRef } from "./MethodChoiceRef";
import type { PortContract } from "./PortContract";
import type { ResourceProfile } from "./ResourceProfile";
import type { RuntimePrereqs } from "./RuntimePrereqs";
import type { SafetyPolicy } from "./SafetyPolicy";

/**
 * One atom — the unit the composer reasons over. Loaded from
 * `config/stage-atoms/<id>.yaml` files; validated against
 * `_atom.schema.json` at load time per plan §S4.3.
 */
export type AtomDefinition = { 
/**
 * Unique atom id. Stable across reorganisations of the atom
 * library — the composer uses this as the cache key. Convention
 * is `<verb>_<noun>` (e.g. `align_reads`, `quantify_features`,
 * `discover_normalisation_method`).
 */
id: string, 
/**
 * Semver version. Stored as a free-form string; not currently
 * validated at load time. Future work will gate duplicate ids
 * with different versions in `validate_consistency`.
 */
version: string, 
/**
 * What kind of step this atom represents. Drives builder-side
 * expansion: `Operation` becomes a single execute task,
 * `Discovery` becomes a `discover_*` task that the agent
 * resolves at runtime, `Validation` becomes a `validate_*`
 * wrapper around the upstream operation, `Aggregator` becomes a
 * fan-in barrier.
 */
role: AtomRole, 
/**
 * Required when `role == Discovery`. Names the kind of decision
 * the agent makes (e.g. `method`, `threshold`, `panel`). Schema
 * enforces presence; the builder reads it.
 */
discovery_kind?: string, 
/**
 * Free-form English description. Surfaces in CONTEXT.md +
 * agent prompts; never machine-parsed.
 */
description: string, 
/**
 * EDAM operation IRI (e.g. `operation:0292` for Alignment). Use
 * `ecaax:<slug>` for in-house extensions per ADR 0004 (e.g.
 * `ecaax:scrnaseq_doublet_detection`). The schema regex enforces
 * the pattern; the curated subtype edges in
 * `crates/core/src/edam.rs` (S4.8) ground "is-a" lookups.
 */
edam_operation: string, 
/**
 * EDAM data class IRI for the primary input shape (e.g.
 * `data:1383` for "Sequence assembly"). Required for
 * `Operation` atoms; `None` for `Aggregator` (input shapes are
 * resolved at fan-in).
 */
edam_data?: string, 
/**
 * EDAM format IRI for the primary committed artifact (e.g.
 * `format:2572` for BAM, `format:3475` for tabular text). Used
 * by the cross-version diff to align "same kind" outputs.
 */
edam_format?: string, 
/**
 * Who runs this atom: an agent invocation or a human (SME)
 * decision. The schema constrains to `agent` | `sme`.
 */
assignee: AtomAssignee, 
/**
 * Atoms this atom requires output from. Ids are other atom ids
 * — the composer flattens the dependency graph to a DAG. Empty
 * for terminal "leaf" atoms whose inputs come from intake.
 */
depends_on: Array<string>, 
/**
 * Atoms that are mutually-exclusive with this one. The composer
 * rejects compositions that include conflicting atoms (e.g. a
 * pair of competing alignment methods when only one should win).
 * Accepts literal id lists today.
 */
excludes: Array<string>, 
/**
 * Free-form attribute map the composer reads to pick between
 * alternatives. Examples: `{"speed": "fast", "reference_free":
 * true, "memory_gb": 16}`. The discover_* runtime selector
 * reads compatible attribute subsets.
 */
attributes: Record<string, unknown>, 
/**
 * Multi-modal joint-source constraints. Each
 * entry declares that two of this atom's upstream dependencies
 * must share the same `attributes.source_atom` value (i.e.
 * originate from the same upstream sample / batch / dataset).
 * Composer post-validates at compose time and rejects when
 * the producers' `source_atom` attributes diverge.
 *
 * Example: a multi-modal integration atom that consumes both
 * scRNA-seq counts and CITE-seq protein expression must
 * declare `joint_with: [{lhs: "scrnaseq_counts", rhs:
 * "citeseq_protein"}]` so the composer rejects a DAG that
 * pairs counts from sample A with protein from sample B.
 */
joint_with: Array<JointlyWithConstraint>, 
/**
 * Explicit rich
 * input ports. Optional and additive: when absent, the
 * `compatibility::engine` synthesizes coarse ports from
 * `edam_data` / `edam_format` so legacy atoms keep working.
 * A future migration retires the legacy path once every atom
 * declares its inputs/outputs. The high-risk atom families
 * (FASTQ, BAM/CRAM, VCF/BCF, count matrix, single-cell object)
 * migrate first.
 */
inputs: Array<PortContract>, 
/**
 * Explicit rich
 * output ports. See `inputs` for the migration story.
 */
outputs: Array<PortContract>, 
/**
 * Pointer for runtime method selection. When set, the named
 * `discovery_*` atom (or stage in legacy taxonomies) carries
 * the method choice — the composer threads `method_choice` from
 * the discovery's runtime output into this atom's invocation.
 */
method_choice?: MethodChoiceRef, 
/**
 * Resource hint for sizing. Composer aggregates these into
 * `ResourceEstimate` for the SME cost-preview surface.
 */
resource_profile?: ResourceProfile, 
/**
 * Per-atom container pin (plan §S15.1 / S15.23). Composer
 * threads this through to `Task::container` (S15.2) so
 * `WORKFLOW.json` carries per-task pinning. The schema records
 * the field; the harness resolves image-digest at emit time.
 */
preferred_container?: ContainerSpec, 
/**
 * `claim_boundary` directive the LLM must restate during
 * confirmation. Carried verbatim into the `claimBoundary`
 * section of the emitted package's interpretation policy when
 * the atom is part of an interpretation slice.
 */
claim_boundary?: string, 
/**
 * Runtime-expanded iteration block. Required when
 * the atom's compiled stage carries `StageCardinality::IterateUntil`;
 * the builder emits a 4-template-task scaffold per S10.3 and
 * the agent fans out a linear chain of `<id>_iter_N` tasks until
 * the convergence metric drops below
 * `convergence.threshold` for `convergence.consecutive_iterations`
 * consecutive passes. `None` on every non-iterating atom — the
 * schema validator (S10.2) gates `Some` on `cardinality ==
 * iterate_until` so authoring slips fail at registry-load time
 * rather than at compose time.
 */
iterate?: IterateSpec, 
/**
 * Atom-level CEL gate. The
 * composer adapter (`composed_atom_to_stage_spec`) threads
 * this onto `StageSpec::condition`, which the builder's
 * `propagate_readiness` evaluates at runtime against the
 * upstream task results. When the expression returns
 * `false`, the task is short-circuited to
 * `TaskState::Skipped` with no agent dispatch.
 *
 * Example: `condition:
 * "discover_batch_correction.result.batch_correction_required == true"`
 * gates a `batch_correction` atom on the upstream
 * discovery's verdict. Composer doesn't compile the
 * expression; the builder's CEL interpreter
 * (`crate::expression::ExpressionEvaluator`) does, at
 * runtime.
 *
 * `None` (default) means the atom always runs when its
 * dependencies complete.
 */
condition?: string, 
/**
 * Figure ids the atom must produce under
 * `runtime/outputs/<stage_id>/figures/` when it is emitted as a
 * compute task. This mirrors `StageSpec::required_figures` so the
 * composer/archetype path preserves the same plotting contract as
 * legacy taxonomy YAMLs.
 */
required_figures: Array<string>, 
/**
 * Optional plotting module id when the emitted stage id is an alias
 * or uses different spelling than the shared plotting module. For
 * example, the `normalisation` atom renders via the
 * `runtime.plotting.stages.normalization` module, and aliased
 * cross-omics stages render via their underlying atom module.
 */
plot_stage_id?: string, 
/**
 * When set, this atom is exempt from the figure-obligation lint.
 * Use only for adapters or atoms whose output is structurally
 * non-plottable (e.g. sort/index adapters, intermediate data
 * products that are consumed by a downstream compute stage, or
 * pipeline-control atoms that never produce user-facing artifacts).
 * The reason is surfaced in provenance; category may be one of
 * `adapter`, `intermediate`, `non_plottable`.
 */
figure_exempt?: FigureExempt, 
/**
 * Headline output filenames the agent should produce under the task
 * output directory. Mirrors `StageSpec::expected_artifacts`.
 */
expected_artifacts: Array<string>, 
/**
 * Required artifacts the harness verifies before accepting a
 * completed task. Mirrors `StageSpec::required_artifacts`.
 */
required_artifacts: Array<{ path: string; min_size_bytes?: number; schema_ref?: string }>, 
/**
 * Validation-obligation ids that the harness
 * runs against this atom's artifacts after task completion.
 * Each id resolves against the runner registry
 * (`ValidatorRegistry`); typical values are
 * `p_value_in_unit_interval`, `gene_id_in_annotation`,
 * `coordinate_in_contig`,
 * `barcode_matrix_dim_consistency`,
 * `no_train_test_leakage`, `deterministic_or_bounded_variance`.
 * Empty default keeps legacy atoms unchanged. Populated to
 * `RequiredArtifact.validation_obligations` by both the v4
 * lowering pass (via `TaskNode.validators`) and the legacy
 * `build_dag_from_composition` path.
 */
validators: Array<string>, 
/**
 * Derived-image warm-up: system + language packages
 * this atom depends on at runtime. The emitter aggregates the
 * union of every reachable atom's declarations into
 * `policies/runtime-prereqs.json`; the harness pre-flight uses
 * that manifest to derive a content-addressed image before the
 * first iteration. At the atom level, only `system_packages`,
 * `language_packages`, and `system_check` are meaningful — the
 * `base_image` and `modality` fields belong on the
 * archetype/taxonomy and are ignored here. Empty default keeps
 * every legacy atom unaffected.
 */
runtime_packages: RuntimePrereqs, 
/**
 * Unifying safety classification. Composes with the
 * fine-grained `crate::sandbox_policy::SandboxPolicy` when
 * `sandbox != None`.
 */
safety: SafetyPolicy, };
