// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who runs an atom. The closed enum is the schema-allowlist for the
 * `assignee` field per plan §S4.3.
 */
export type AtomAssignee = "agent" | "sme";
