// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Provenance origin class. `#[non_exhaustive]` — adding a future
 * origin (e.g. `Vendor`) is a non-breaking minor change.
 */
export type AtomOrigin = "builtin" | "site_local" | "community";
