// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an authorized auditor can retrieve the suppressed content.
 * Tagged so the UI branches on retrieval kind rather than free text.
 */
export type AuditorProcedure = { "kind": "restricted_archive", ticket_template: string, } | { "kind": "permanently_deleted", 
/**
 * Deletion authority.
 */
deletion_authority: string, 
/**
 * Deletion id.
 */
deletion_id: string, } | { "kind": "authenticated_api", endpoint: string, scope: string, };
