// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvariantVerdict } from "./InvariantVerdict";

export type AuditProofReport = { schema_version: string, verdicts: Array<InvariantVerdict>, };
