// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * V4 typed bioinformatics modality enum.
 *
 * Used as the key for `OntologyScopeMatrix` lookups (D2 / F22)
 * and emitted as the typed substrate event payload. Today's
 * classifier code paths still operate on `Option<String>`
 * modality identifiers (per `config/modality-keywords.yaml`);
 * this enum is the canonical typed form. v3 P11 / v4 P6 widen
 * the keyword classifier so `BioinformaticsModality::from_str`
 * is the single source of truth.
 *
 * The variant set mirrors `config/_modality-ontology-coverage.schema.json`
 * exactly. Adding a modality requires (1) a new variant here,
 * (2) a row in `config/modality-ontology-coverage.yaml`, (3) a
 * schema enum bump, and (4) widening keyword-classification config.
 *
 * R2-N20 — `ModalityId(String)` was introduced
 * alongside this enum as a registry-validated newtype. The enum
 * remains the closed coarse-category type used by the ontology
 * scope matrix; `ModalityId` is the open-world identifier
 * consumed by the per-modality YAML registry under
 * `config/modalities/<id>.yaml`. `From<BioinformaticsModality>
 * for ModalityId` and `ModalityId::as_coarse_category()` bridge
 * the two; see `ModalityId` below.
 */
export type BioinformaticsModality = "bulk_rnaseq" | "single_cell_rnaseq" | "variant_calling" | "chip_seq" | "metagenomics" | "proteomics" | "metabolomics" | "spatial_omics" | "phylogenetics" | "structural_biology" | "multi_omics" | "generic_omics";
