// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One blocker on a draft composition. Maps to UI `BlockerCard`
 * dispatch via the `BlockerKind` taxonomy.
 */
export type BlockerContext = { 
/**
 * Stable id (so clients can dedupe / track resolution).
 */
id: string, 
/**
 * Blocker kind (mirrors today's `BlockerKind` discriminator
 * strings: `MissingReference`, `IncompatibleFormat`,
 * `UnsetMethod`, `UnknownSemanticType`, etc.).
 */
kind: string, 
/**
 * Human-readable statement.
 */
statement: string, 
/**
 * Optional CTA suggestion (`amend_stage_method`, `rerun_task`,
 * `confirm_assumption`).
 */
suggested_action?: string, 
/**
 * Affected task node ids.
 */
affected_nodes: Array<string>, };
