// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Context attached to a blocker. Separate from `BlockerKind` so that each
 * variant can be reasoned about in isolation while still carrying the
 * timestamp + optional recovery hints that every blocker needs.
 */
export type BlockerContext = { 
/**
 * ISO 8601 timestamp when the blocker was created.
 */
timestamp: string, 
/**
 * Optional free-form recovery hints for the SME or agent.
 */
recovery_hints: string | null, };
