// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockerKind } from "./BlockerKind";

/**
 * One entry in the per-session queue of active blockers. `SessionState::Blocked` carries `Vec<BlockerEntry>` so a
 * second concurrent blocker for a different task is appended rather
 * than overwriting the first.
 */
export type BlockerEntry = { 
/**
 * Stable per-entry id used by the UI as a React key.
 */
blocker_id: string, 
/**
 * Originating task id. Session-level blockers use `_session`.
 */
task_id: string, 
/**
 * Typed taxonomy used by the UI to pick the recovery affordance.
 */
kind: BlockerKind, 
/**
 * Human-readable summary for the card.
 */
message: string, 
/**
 * Optional recovery hint for this specific entry.
 */
recovery_hint?: string, 
/**
 * UTC timestamp this entry was first appended.
 */
at: string, };
