// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a single goal branch (one DAG node) was covered.
 */
export type BranchCoverage = "catalog" | "proposal";
