// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Confidence } from "./Confidence";

/**
 * Candidate metadata consumed by [`check_default_eligibility`].
 *
 * All fields have safe defaults so callers only need to populate the fields
 * they have. An all-default candidate passes every criterion that isn't
 * about blocking gates or contradictions (which default to zero).
 */
export type CandidateMetadata = { 
/**
 * Number of blocking quality-gate failures for this candidate.
 */
blocking_gate_failures: number, 
/**
 * Confidence tier as reported by the discovery step.
 */
confidence: Confidence, 
/**
 * Number of supporting evidence records.
 */
supporting_evidence_count: number, 
/**
 * Number of high-quality evidence records (official sources, benchmarks,
 * or primary literature as defined by `citationMinimum.highQualitySourceTypes`).
 */
high_quality_evidence_count: number, 
/**
 * Number of evidence records flagged as contradicted / mixed / unresolved
 * / retracted (the `contradiction.blockingStatuses` list in the policy).
 */
contradictory_evidence_count: number, 
/**
 * Whether the candidate's claim freshness is in an acceptable state.
 * Maps to `freshness.acceptableStatuses` in the policy.
 */
freshness_acceptable: boolean, 
/**
 * Whether the literature-eligibility flag is set for this candidate.
 */
literature_eligible: boolean, };
