// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Claim } from "./Claim";
import type { ClaimStatus } from "./ClaimStatus";
import type { ClaimStrength } from "./ClaimStrength";

/**
 * Per-claim verdict plus the source claim itself (so callers can
 * render the excerpt alongside the status without re-zipping).
 */
export type ClaimVerdict = { 
/**
 * Claim.
 */
claim: Claim, 
/**
 * Status.
 */
status: ClaimStatus, 
/**
 * Confirmatory-mode classification of the claim's
 * analytical discipline. `Prespecified` when the claim's supporting
 * stage has no `PostHocDeviation` record; `PostHoc` when at least
 * one deviation record covers the stage lineage; `Exploratory` when
 * the session was never confirmatory. The UI surfaces a red flag
 * when a `Prespecified` claim's lineage turns out to contain
 * deviations.
 */
strength: ClaimStrength, };
