// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-claim verdict.
 */
export type ClaimStatus = { "status": "verified" } | { "status": "mismatch", detail: string, } | { "status": "unverifiable", reason: string, };
