// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaimContract } from "./ClaimContract";
import type { Direction } from "./Direction";
import type { LiteratureEvidence } from "./LiteratureEvidence";
import type { QuantileKind } from "./QuantileKind";
import type { QuantileRowSet } from "./QuantileRowSet";

/**
 * One extracted narrative claim. Fields beyond `entity` and `excerpt`
 * are optional — if the narrative omits an effect size, the claim
 * still records the direction and the source table reference, and
 * the verifier falls back to verifying only what was provided.
 */
export type Claim = { 
/**
 * The entity name matched by one of the policy's entity patterns.
 */
entity: string, 
/**
 * Direction word captured in the same sentence, if any.
 */
direction?: Direction, 
/**
 * Numeric effect size captured from a log2FC / effect_size mention.
 */
effect_size?: number, 
/**
 * Numeric p-value / FDR captured from the sentence.
 */
pvalue?: number, 
/**
 * Source-table reference captured from a "Table S1" / "(Table 2)"
 * style mention in the sentence. Populated as a free string so
 * the verifier can fuzzy-match against the package's
 * `results/tables/*` index.
 */
source_table?: string, 
/**
 * The sentence the claim originates from, for operator review
 * of mismatches.
 */
excerpt: string, 
/**
 * Contract class assigned by heuristic during extraction. Defaults
 * to `NumericTableLookup` for backwards compatibility with claims
 * serialized before this field was introduced.
 */
contract: ClaimContract, 
/**
 * Literature-support evidence for a `LiteratureGrounded` claim. `None`
 * for every other contract class and for claims serialized before this
 * field existed.
 */
literature_evidence?: LiteratureEvidence, 
/**
 * The p-value-family keyword the narrative used for the parsed `pvalue`
 * ("padj"/"fdr"/"q…" → adjusted; "pvalue"/"p" → raw). Lets the verifier
 * reject a value quoted under the wrong label (a raw value labelled
 * "padj"). `None` when no p-value was parsed. (VF-8)
 */
matched_pvalue_keyword?: string, 
/**
 * A LINEAR fold-change magnitude parsed from prose ("induced 8-fold",
 * "2.3-fold higher"), distinct from the log2 `effect_size`. The verifier
 * compares its MAGNITUDE (`log2(linear_fold)`) against the table's
 * `|log2FC|`, so a linear-fold claim is reconciled against a log2 table.
 * Always a positive fold (>1×); direction is left to the direction/sign
 * checks. `None` when no linear-fold phrase was found. (VF-4)
 */
linear_fold?: number, 
/**
 * The aggregate kind for a [`ClaimContract::QuantileOfColumn`] claim
 * (median/mean). `None` for every other contract class. (Phase C)
 */
aggregate_kind?: QuantileKind, 
/**
 * The COLUMN the quantile of a [`ClaimContract::QuantileOfColumn`] claim is
 * taken over (e.g. `baseMean`). `None` for every other contract class.
 */
aggregate_column?: string, 
/**
 * The ROW SET a [`ClaimContract::QuantileOfColumn`] aggregate is computed
 * over (all rows vs tested genes). `None` for every other contract class.
 */
aggregate_rowset?: QuantileRowSet, 
/**
 * The asserted aggregate VALUE for a [`ClaimContract::QuantileOfColumn`]
 * claim, parsed from the sentence. `None` for every other contract class.
 */
aggregate_value?: number, 
/**
 * The COLLECTION key (database name: `KEGG`/`Reactome`/`GO`/…) for a
 * [`ClaimContract::KeyedTableCell`] claim. `None` for every other class.
 */
collection?: string, 
/**
 * The TERM key (set/pathway name: `Autophagy`/…) for a
 * [`ClaimContract::KeyedTableCell`] claim. `None` for every other class.
 */
term?: string, 
/**
 * The statistic COLUMN (`NES`/`adj_p_value`/…) addressed by a
 * [`ClaimContract::KeyedTableCell`] claim. `None` for every other class.
 */
keyed_column?: string, 
/**
 * The asserted VALUE for a [`ClaimContract::KeyedTableCell`] claim, parsed
 * from the sentence. `None` for every other contract class.
 */
keyed_value?: number, };
