// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassRequirementTag } from "./ClassRequirementTag";

/**
 * Per-class requirement. Three shapes:
 * - `"required"` — at least 1 passing validator of this class.
 * - `"optional"` — recorded if present but not gating.
 * - `{ min_count: N }` — at least `N` passing validators.
 */
export type ClassRequirement = ClassRequirementTag | { min_count: number, };
