// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of code runs inside the atom's container at runtime.
 */
export type CodeExecution = "none" | "vetted" | "generated_by_agent";
