// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComposePosition } from "./ComposePosition";

/**
 * Cross-archetype composition pointer.
 *
 * Extended with `id_prefix` (stage-id namespacing applied
 * to all atoms inherited from the named archetype, including their
 * `depends_on` references) and `replace_atoms` (per-atom substitutions
 * — replace `differential_expression` from the inherited archetype
 * with `mofa_factor_decomposition` from this one).
 *
 * Cross-omics archetypes use this to inherit two single-modality
 * pipelines without duplicating the atom lists. Example:
 * ```yaml
 * compose:
 * - { archetype_id: bulk_rnaseq, position: prefix, id_prefix: rnaseq_ }
 * - { archetype_id: proteomics, position: prefix, id_prefix: proteomics_ }
 * atoms:
 * - { atom_id: reporting,
 * alias: cross_omics_thematic_comparison,
 * depends_on: [rnaseq_differential_expression, proteomics_differential_abundance] }
 * ```
 */
export type ComposeRef = { 
/**
 * Other archetype id whose atoms are embedded.
 */
archetype_id: string, 
/**
 * Position to embed at: `prefix` (run before this archetype's
 * atoms), `suffix` (after), or `replace_atoms` (use the named
 * atoms only, ignore this archetype's own atom list).
 */
position: ComposePosition, 
/**
 * Optional stage-id prefix applied to every atom
 * inherited from the named archetype. The prefix is also rewritten
 * over inherited `depends_on` references so the inherited DAG
 * stays internally consistent. `None` keeps the inherited
 * stage-ids verbatim (only safe when the parent archetype's
 * stage-ids don't collide with this one's).
 */
id_prefix?: string, 
/**
 * Per-atom substitutions applied to the inherited
 * archetype's atom list. Keys are atom_ids in the inherited
 * archetype; values are atom_ids in this archetype's
 * `AtomRegistry`. Used to swap a single atom (e.g. replace
 * `differential_expression` with `mofa_factor_decomposition`)
 * without forking the rest of the inherited pipeline.
 */
replace_atoms: { [key in string]?: string }, };
