// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Policy weight configuration parsed from `compositeScoreWeights`.
 */
export type CompositeScoreWeights = { defaultSuitability: number, robustness: number, adoption: number, operationalFit: number, specMatch: number, 
/**
 * Axes in this list have their weight redistributed when the axis
 * has no input source (see module-level docs). Absent or empty →
 * literal multiplication (backward-compatible behaviour).
 */
renormalizeWhenAxisMissing: Array<string>, };
