// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ComposePosition discriminant.
 */
export type ComposePosition = "prefix" | "suffix" | "replace_atoms";
