// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClarificationOrValidationNeeded } from "./ClarificationOrValidationNeeded";
import type { CompatibilityProof } from "./CompatibilityProof";
import type { IncompatibilityReport } from "./IncompatibilityReport";
import type { TaskNode } from "./TaskNode";

/**
 * Result of a single edge's compatibility check.
 *
 * Note: derives `PartialEq` but not `Eq` because
 * `CompatibleWithAdapters.adapters: Vec<TaskNode>` references
 * `PortContract`/`SemanticType` which no longer implement `Eq` after
 * v4 P6 (`LocalExtensionMaturity::GraduationCandidate` carries an
 * `f32 success_rate`). Equality of two `CompatibilityResult`s is rare
 * outside test asserts; tests can match on `kind` and inspect fields.
 */
export type CompatibilityResult = { "kind": "compatible" } & CompatibilityProof | { "kind": "compatible_with_adapters", 
/**
 * Proof.
 */
proof: CompatibilityProof, 
/**
 * Adapters.
 */
adapters: Array<TaskNode>, } | { "kind": "incompatible" } & IncompatibilityReport | { "kind": "unknown" } & ClarificationOrValidationNeeded;
