// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssumptionLedger } from "./AssumptionLedger";
import type { BlockerContext } from "./BlockerContext";
import type { GapReport } from "./GapReport";
import type { RefusalReport } from "./RefusalReport";
import type { TaskNode } from "./TaskNode";
import type { ValidationObligation } from "./ValidationObligation";
import type { ValidationReport } from "./ValidationReport";
import type { WorkflowDag } from "./WorkflowDag";

/**
 * Typed outcome of a composition. Every composer call returns
 * exactly one of these — never an unstructured "no valid DAG."
 *
 * `Eq` not derived because `WorkflowDag` contains
 * `IterationDeclaration` with `f64`; round-trip equality tests
 * use serde snapshots instead.
 */
export type ComposeOutcome = { "kind": "validated_executable_dag", 
/**
 * Dag.
 */
dag: WorkflowDag, 
/**
 * Report.
 */
report: ValidationReport, } | { "kind": "draft_dag", 
/**
 * Dag.
 */
dag: WorkflowDag, 
/**
 * Assumptions.
 */
assumptions: AssumptionLedger, 
/**
 * Blockers.
 */
blockers: Array<BlockerContext>, } | { "kind": "partial_dag", 
/**
 * Dag.
 */
dag: WorkflowDag, 
/**
 * Unresolved gaps.
 */
unresolved_gaps: Array<GapReport>, } | { "kind": "novel_node_spec", 
/**
 * Node.
 */
node: TaskNode, 
/**
 * Required work.
 */
required_work: Array<ValidationObligation>, } | { "kind": "refusal", report: RefusalReport, };
