// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Direction agreement between a prior published claim and a new finding.
 */
export type ConcordanceFlag = "same_direction" | "opposite_direction" | "no_prior_finding" | "unverifiable";
