// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-emit latch token that binds the SME's `/confirm` click to a
 * specific pending emission. Prevents the LLM from calling
 * `emit_package` again after the SME confirmes plan A if the plan
 * was subsequently amended (plan B would need a fresh confirm).
 */
export type ConfirmationToken = { 
/**
 * The pending emission this token authorizes. Must match
 * `Session::pending_emission_id` at emit-time or the precondition
 * fails (forces re-confirmation).
 */
emission_id: string, 
/**
 * Hex SHA-256 of the SME-confirmed plan summary. Must match the
 * current summary hash at emit-time; drift indicates the plan was
 * amended after confirmation. Encoded as a lowercase 64-char hex
 * string to match [`crate::session::ConfirmationCard::summary_hash`].
 */
summary_hash: string, 
/**
 * When the SME's /confirm arrived server-side.
 */
granted_at: string, 
/**
 * Single-use latch. Set to `true` by `consume()` when
 * `emit_package` succeeds. A consumed token causes `authorizes()`
 * to return `false`, so a second `emit_package` call with the
 * same token is rejected — the SME must re-confirm before
 * re-emitting (e.g. after a cancelled + retried emit).
 *
 * `#[serde(default)]` keeps existing on-disk tokens (which have no
 * `consumed` key) deserializing as `consumed = false`, preserving
 * backward compatibility.
 */
consumed: boolean, };
