// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Hard/soft constraints block.
 */
export type ConstraintsBlock = { 
/**
 * Preferred backend (`local`, `aws`, `slurm`). Mirrors
 * `SWFC_EXECUTOR_MODE`.
 */
preferred_backend?: string, 
/**
 * True when network access must be denied for executor tasks.
 */
no_network: boolean, 
/**
 * True when only container-pinned tasks are allowed.
 */
container_only: boolean, 
/**
 * True when reproducibility is hard-required (composer
 * penalizes non-deterministic atoms).
 */
prefer_reproducible: boolean, 
/**
 * Free-text other constraints.
 */
free_text: Array<string>, };
