// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * BLAKE3 commitment over the suppressed payload. The algorithm name
 * is preserved verbatim in the record so future curators can add
 * alternate algorithms without ambiguity at read time.
 */
export type ContentCommitment = { 
/**
 * Algorithm name (always `"blake3"` for records produced by
 * `ChainOfCustody::with_commitment`).
 */
algorithm: string, 
/**
 * Hex-encoded digest. BLAKE3 produces 32 bytes → 64 hex chars.
 */
digest_hex: string, };
