// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typed `ContainerSpec.source` discriminator. `Image` is the historical
 * default and matches the pre-S15.1 wire shape (atom YAMLs that only
 * declared `image:` + `tag:` still deserialize as
 * `ContainerSource::Image`). `Host` opts back to bare-host execution
 * (no container).
 */
export type ContainerSource = { "kind": "image" } | { "kind": "conda", 
/**
 * Conda packages.
 */
conda_packages: { [key in string]?: Array<string> }, } | { "kind": "host" };
