// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BranchCoverage } from "./BranchCoverage";

/**
 * Durable goal-branch coverage statement emitted as
 * `runtime/coverage-statement.json`.
 */
export type CoverageStatement = { 
/**
 * Total goal branches considered (one per emitted DAG node).
 */
total_branches: number, 
/**
 * Branches satisfied by catalog atoms.
 */
catalog_covered: number, 
/**
 * Branches covered by a session proposal.
 */
proposal_covered: number, 
/**
 * True when every branch is catalog-covered (no proposal coverage).
 * The headline trust signal: a reviewer reads this first.
 */
fully_catalog_covered: boolean, 
/**
 * Sorted list of the proposal-covered branch ids, so a reviewer sees
 * exactly which strands rest on unverified proposals.
 */
proposal_branches: Array<string>, 
/**
 * Per-branch breakdown (BTreeMap for determinism).
 */
per_branch: { [key in string]?: BranchCoverage }, };
