// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * SME-legible projection of catalog-coverage confidence. Derived purely
 * from the composer's `ComposeOutcome` gap set — no new compose logic, no
 * new tool. Rendered by `CoverageConfidenceCard` before the confirmation
 * gate; also written to a durable `coverage-statement.json` (CC1-4) so the
 * signal survives outside the UI.
 */
export type CoverageConfidence = { 
/**
 * True when the composition is a fully validated executable DAG.
 */
fully_covered: boolean, 
/**
 * Modalities with partial catalog coverage (drafted but with gaps).
 */
partially_covered_modalities: Array<string>, 
/**
 * Modalities with NO catalog satisfier (from unsatisfiable-modality gaps).
 */
uncovered_modalities: Array<string>, 
/**
 * Total unresolved gap count.
 */
gap_count: number, };
