// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A cross-dependency edge that the composer wouldn't infer from
 * atom-level `depends_on` alone.
 */
export type CrossDependency = { 
/**
 * From.
 */
from: string, 
/**
 * To.
 */
to: string, 
/**
 * Free-form rationale carried into the composition rationale
 * log so reviewers can see why the edge exists.
 */
reason: string, };
