// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeRef } from "./EdgeRef";
import type { PortContract } from "./PortContract";
import type { PortRef } from "./PortRef";
import type { PortRole } from "./PortRole";
import type { RegistryQuery } from "./RegistryQuery";
import type { TaskNode } from "./TaskNode";

/**
 * What kind of mutation the proposal would apply. The variants are
 * intentionally narrow — strategies pick the closest shape rather
 * than smuggling arbitrary edits through a free-form blob.
 *
 * Note: `PartialEq` but not `Eq` because `TaskNode` and `PortContract`
 * can carry a `SemanticType::LocalExtension` whose `maturity` field
 * can be `LocalExtensionMaturity::GraduationCandidate { success_rate:
 * F32,.. }`. Callers that need set-style dedup compare on node id.
 */
export type DagModification = { "kind": "insert_converter", 
/**
 * Converter node.
 */
converter_node: TaskNode, 
/**
 * Source port.
 */
source_port: PortRef, 
/**
 * Sink port.
 */
sink_port: PortRef, } | { "kind": "insert_liftover", 
/**
 * From build.
 */
from_build: string, 
/**
 * To build.
 */
to_build: string, 
/**
 * Target edge.
 */
target_edge: EdgeRef, } | { "kind": "request_missing_metadata", 
/**
 * Field.
 */
field: string, 
/**
 * Applies to node.
 */
applies_to_node: string, } | { "kind": "substitute_producer", remove: string, add: TaskNode, } | { "kind": "query_registry", 
/**
 * Criteria.
 */
criteria: RegistryQuery, 
/**
 * Target gap.
 */
target_gap: string, } | { "kind": "rewrite_contract", 
/**
 * Node.
 */
node: string, 
/**
 * New contract.
 */
new_contract: PortContract, 
/**
 * Applies to.
 */
applies_to: PortRole, };
