// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a decision was a behaviour-defining *validated-execution*
 * action that passed a deterministic server-side gate, or a
 * *conversational* action that merely reduced overhead.
 *
 * This is the session-level analog of "validated invocation as the
 * unit of provenance/approval": a reviewer can mechanically prove that
 * no behaviour-defining action bypassed the gate by filtering the
 * decision log on `authority == SchemaValidated`.
 *
 * **Set deterministically by the dispatcher/handler** in
 * `record_decision_with_ip`, derived from [`DecisionActor`]. The LLM
 * never sets this — a `DecisionActor::Llm` tool-dispatch is always
 * `Conversational` because the behaviour-defining gate (the SME button
 * click that flips `session.user_confirmed`, the harness mirror) is the
 * `Sme`/`Harness` actor.
 */
export type DecisionAuthority = "conversational" | "schema_validated";
