// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DefectClass discriminant.
 */
export type DefectClass = "privacy_violation" | "genome_build_mismatch" | "strandedness_unknown" | "annotation_version_unknown" | "coordinate_convention_unknown" | "library_layout_unknown" | "sample_metadata_missing" | "reference_data_unspecified" | "novel_node_unverified" | "scientifically_risky_adapter" | "policy_restricted_adapter" | "ontology_mapping_unresolved" | "lossy_adapter_default";
