// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DiscoveryKind discriminant.
 */
export type DiscoveryKind = "best_practice" | "source" | "evidence" | "environment_probe" | { "custom": string };
