// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { DispositionStatus } from "./DispositionStatus";
import type { TaskId } from "./TaskId";

/**
 * Normalised in-memory shape of `sme_disposition.json`. The normalizer
 * in `from_raw_json` is tolerant of both v0 and v1 inputs.
 *
 * Fields not named here pass through `legacy_passthrough` as a free
 * `serde_json::Value` so audit fidelity is preserved across writes.
 */
export type Disposition = { 
/**
 * Written as [`DISPOSITION_SCHEMA_VERSION`] on re-write. Absent
 * fields in v0 files are normalised to 1 in memory.
 */
schema_version: number, 
/**
 * Task id.
 */
task_id: TaskId, 
/**
 * RFC-3339 UTC timestamp when the disposition was authored.
 * Optional on read (v0 files don't always have one) but always
 * written back.
 */
created_at?: string, 
/**
 * Free-form "what the agent concluded" prose. Shown at the top of
 * the `DispositionReviewCard`.
 */
authoritative_interpretation?: string, 
/**
 * Canonical action list. Authored directly in v1 files; derived
 * from `downstream_invalidation_request` in v0 files.
 */
actions: Array<Action>, 
/**
 * Opt-in v2 escape hatch: when both this flag and the
 * `ECAA_AUTO_APPLY_DISPOSITIONS=1` env var are set, the server
 * applies the disposition immediately on ingest without waiting
 * for an SME click. See §5.4 of the plan.
 */
auto_apply: boolean, 
/**
 * Status.
 */
status: DispositionStatus, 
/**
 * RFC-3339 UTC timestamp of the last status change. Server writes
 * on apply / reject; never generated by the agent.
 */
status_updated_at?: string, };
