// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Longitudinal ED/CF delta — diffs a child package's self-location against
 * its parent's across a lineage edge (amend/branch). Deterministic;
 * written as `runtime/ed-cf-delta.json` when lineage is set.
 */
export type EdCfDelta = { 
/**
 * child.ED − parent.ED.
 */
extensibility_delta: number, 
/**
 * child.CF − parent.CF.
 */
counterfactual_floor_delta: number, 
/**
 * ED mechanisms present in child but not parent (sorted).
 */
gained_extensibility_mechanisms: Array<string>, 
/**
 * ED mechanisms present in parent but not child (sorted).
 */
lost_extensibility_mechanisms: Array<string>, 
/**
 * CF mechanisms present in child but not parent (sorted).
 */
gained_counterfactual_mechanisms: Array<string>, 
/**
 * CF mechanisms present in parent but not child (sorted).
 */
lost_counterfactual_mechanisms: Array<string>, };
