// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typed discriminant for a composed-DAG edge. Replaces the prior
 * substring-keyed reject (`warnings.contains("incompatible")`) with a
 * pass/fail axis the scorer can branch on directly.
 *
 * `Unproven` is the default so any legacy `runtime/proofs.jsonl` row
 * or hand-written edge that omits `kind` is treated as the *strictest
 * failing* case — it is never silently waved through the gate.
 * Defaulting to `TypedDataFlow` would re-open the loophole.
 */
export type EdgeKind = "typed_data_flow" | "adapter_mediated" | "ordering_only" | "unproven";
