// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of evaluating `defaultEligibilityCriteria` for one candidate.
 */
export type EligibilityResult = { 
/**
 * `true` when the candidate passes ALL default-eligibility criteria.
 */
passes: boolean, 
/**
 * Names of the criteria the candidate failed (empty when `passes == true`).
 */
failed_criteria: Array<string>, };
