// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RobustnessClass } from "./RobustnessClass";

/**
 * Per-entity cross-method rollup. `per_method_*` maps are keyed by the
 * short method name (the tail of the variant stage-id after `__v_`).
 */
export type EntityMethodRow = { entity: string, 
/**
 * Signed effect per method (only methods whose artifact carried a
 * finite effect value for this entity).
 */
per_method_effect: { [key in string]?: number }, 
/**
 * Significance verdict per present method.
 */
per_method_significant: { [key in string]?: boolean }, 
/**
 * Fraction of the effect-bearing present methods sharing the majority
 * sign (1.0 when ≤1 method reported a finite effect).
 */
sign_agreement: number, 
/**
 * `max − min` of the per-method effects (0.0 when fewer than two
 * finite effects were reported).
 */
effect_range: number, n_methods_significant: number, robustness: RobustnessClass, 
/**
 * Median of the per-method finite effects (`None` when none reported).
 */
pooled_effect_median: number | null, };
