// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Evaluator provenance — informative per invariants.md §"audit-proof-report.json shape".
 */
export type EvaluatorInfo = {
/**
 * Implementation identifier.
 */
impl: string,
/**
 * Evaluator implementation version.
 */
version: string,
/**
 * Warn/fail policy: "warn-only" | "strict" (absent ⇒ normative defaults).
 */
policy: string, };
