// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppliedRemediation } from "./AppliedRemediation";
import type { ResourceTarget } from "./ResourceTarget";

/**
 * Per-task overrides written by the apply endpoint and read by the
 * executor at dispatch time. Lives at
 * `runtime/inputs/<task_id>/overrides.json`.
 */
export type ExecutorOverrides = { 
/**
 * Resources.
 */
resources?: ResourceTarget, 
/**
 * Disable spot.
 */
disable_spot: boolean, 
/**
 * Partition.
 */
partition?: string, 
/**
 * Availability zone.
 */
availability_zone?: string, 
/**
 * Library pins.
 */
library_pins: { [key in string]?: string }, 
/**
 * Stage parameters.
 */
stage_parameters: Record<string, unknown>, 
/**
 * Env passthrough.
 */
env_passthrough: { [key in string]?: string }, 
/**
 * Disable pilot.
 */
disable_pilot: boolean, 
/**
 * Number of remediation applies recorded so far. Capped at
 * [`MAX_REMEDIATION_ATTEMPTS`] by the apply endpoint.
 */
attempts_consumed: number, 
/**
 * Last applied suggestion id.
 */
last_applied_suggestion_id?: string, 
/**
 * Audit trail. Surfaced on the BlockerCard so the SME can see
 * what's been tried and the proposer can avoid recommending
 * the same fix twice.
 */
history: Array<AppliedRemediation>, };
