// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome of unifying one facet across producer/consumer.
 */
export type FacetUnification = "Exact" | { "Subtype": { rationale: string, } } | { "Substituted": { 
/**
 * Adapter id.
 */
adapter_id: string, 
/**
 * Rationale.
 */
rationale: string, } } | { "Unknown": { reason: string, } } | { "Incompatible": { rationale: string, } };
