// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One facet that diverged between producer + consumer ports.
 */
export type FacetMismatch = { 
/**
 * Facet name (`genome_build`, `annotation_version`, `strandedness`,
 * `units`, `normalization_state`, `coordinate_system`, …).
 */
facet: string, 
/**
 * Producer's value (may be empty string when unset).
 */
producer_value: string, 
/**
 * Consumer's required value (may be empty string when unset).
 */
consumer_value: string, };
