// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Factorial decomposition of the support signal across the two ensemble
 * axes plus the compounding-fragility (interaction) signal.
 */
export type FactorialAttribution = { 
/**
 * Per-method support rate (mean of support as 0/1 over that method's
 * support-bearing cells). Methods with no support-bearing cell are
 * omitted.
 */
by_method: { [key in string]?: number }, 
/**
 * Per-lens support rate, computed the same way as `by_method`.
 */
by_lens: { [key in string]?: number }, 
/**
 * Cell ids whose support verdict differs from BOTH its method-marginal
 * AND its lens-marginal majority — the compounding-fragility signal
 * (a finding that only one method×lens combination disagrees on).
 */
interaction_hotspots: Array<string>, };
