// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reference to a physical file format. Distinct from the semantic
 * type so two semantically-equivalent ports can match across
 * formats with an adapter (e.g. BAM ↔ CRAM).
 */
export type FormatRef = { 
/**
 * EDAM format IRI (e.g. `format:2572` for BAM) or `swfc:<slug>`
 * for in-house formats.
 */
iri: string, 
/**
 * Human label.
 */
label?: string, 
/**
 * File extension (no leading dot). Used for adapter routing.
 */
extension?: string, };
