// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One unresolved gap in a partial composition.
 */
export type GapReport = { 
/**
 * Stable id.
 */
id: string, 
/**
 * What is missing (free text).
 */
statement: string, 
/**
 * Required input port that has no producer.
 */
missing_port?: string, 
/**
 * Suggested resolutions (e.g. SME upload, registry import).
 */
suggestions: Array<string>, };
