// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable name of a gate in the promotion pipeline.
 */
export type GateName = "validator" | "sandbox" | "sme_signoff";
