// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GeneratedReviewStatus discriminant.
 */
export type GeneratedReviewStatus = "drafted" | "sandbox_validated" | "human_approved" | "rejected";
