// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Universal renderer primitives — operate on physical structure
 * alone, no semantic-type assumptions. Every `StructuralFallback`
 * resolves to one of these; the Python module
 * `lib/plotting/primitives/structural.py` is the authoritative
 * implementation, with R parity at
 * `lib/plotting_r/primitives/structural.R`.
 */
export type GenericPrimitive = "matrix_overview" | "distribution" | "categorical_summary" | "pairs" | "scalar_card";
