// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Optional GPU slice of a `ResourceRequirements`. Detached from the main
 * struct so presence is meaningful — absent means CPU-only.
 */
export type GpuRequirement = { 
/**
 * e.g. "nvidia-t4", "nvidia-a100", "nvidia-l4".
 */
kind: string, 
/**
 * Number of GPU devices required.
 */
count: number, };
