// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifier system — design §12. A data product can carry
 * multiple identifier systems with declared mapping authority and
 * lossiness when one IS lifts to another (e.g. gene symbol →
 * Ensembl).
 */
export type IdentifierSystem = { 
/**
 * Identifier authority (`ensembl`, `ncbi_gene`, `gene_symbol`,
 * `refseq`, `ucsc_known_gene`).
 */
authority: string, 
/**
 * Optional release pin.
 */
release?: string, 
/**
 * Mapping authority for cross-system lookups (`hgnc`,
 * `mygene`, `biomart`). `None` when no mapping is required.
 */
mapping_authority?: string, 
/**
 * True when conversions to other systems lose information
 * (e.g. gene symbol → Ensembl is lossy).
 */
lossy_conversion: boolean, };
