// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IncompatibilityReason } from "./IncompatibilityReason";

/**
 * A bundle of incompatibility reasons. Returned when the
 * compatibility engine concludes the edge cannot hold.
 */
export type IncompatibilityReport = { 
/**
 * Reasons.
 */
reasons: Array<IncompatibilityReason>, 
/**
 * Optional rationale for human reading.
 */
rationale?: string, };
