// Generated by ts-rs from Rust types — do not edit manually.
// Re-run: `make types`
//
// Core (compiler) types
export type { DAG } from "./DAG";
export type { Task } from "./Task";
export type { TaskKind } from "./TaskKind";
export type { TaskState } from "./TaskState";
export type { DiscoveryKind } from "./DiscoveryKind";
export type { Assignee } from "./Assignee";
export type { BlockedRecord } from "./BlockedRecord";
export type { ResolutionAttempt } from "./ResolutionAttempt";
export type { ResolutionStrategy } from "./ResolutionStrategy";
export type { EscalationPath } from "./EscalationPath";

// Conversation (LLM-mediated chat) types
export type { Session } from "./Session";
export type { SessionState } from "./SessionState";
export type { Turn } from "./Turn";
export type { TurnRole } from "./TurnRole";
export type { AssistantIntent } from "./AssistantIntent";
export type { ConfirmationCard } from "./ConfirmationCard";
export type { ResourceEstimate } from "./ResourceEstimate";
export type { ScoreEvidence } from "./ScoreEvidence";
export type { ExcludedPath } from "./ExcludedPath";
export type { ToolCallRecord } from "./ToolCallRecord";
export type { HarnessEvent } from "./HarnessEvent";
export type { ToolError } from "./ToolError";

// Full-lifecycle types (blockers, result review, cross-version diff)
export type { BlockerKind } from "./BlockerKind";
export type { BlockerEntry } from "./BlockerEntry";
export type { ClaimVerificationReport } from "./ClaimVerificationReport";
export type { CrossVersionReport } from "./CrossVersionReport";
export type { RowClassification } from "./RowClassification";

// Remediation surface (typed BlockerKind::ToolError follow-up).
export type { ToolErrorEnvelope } from "./ToolErrorEnvelope";
export type { RemediationKind } from "./RemediationKind";
export type { RemediationSuggestion } from "./RemediationSuggestion";
export type { ResourceTarget } from "./ResourceTarget";
export type { GpuTarget } from "./GpuTarget";
export type { MethodSwitchKind } from "./MethodSwitchKind";
export type { InputSwapKind } from "./InputSwapKind";
export type { ToolBinding } from "./ToolBinding";
export type { SuggestionConfidence } from "./SuggestionConfidence";
export type { ExecutorOverrides } from "./ExecutorOverrides";
export type { AppliedRemediation } from "./AppliedRemediation";
export type { RemediationOutcome } from "./RemediationOutcome";

// 2026-04-23 disposition-auto-apply plan — agent-authored SME
// mutation requests.
export type { Disposition } from "./Disposition";
export type { Action as DispositionAction } from "./Action";
export type { DispositionStatus } from "./DispositionStatus";

// Wave 8: cross-domain classes, confirmatory mode, checkpoint mode,
// and claim-strength (plan §8.B, §8.C, §8.D, §8.F).
export type { ProjectClass } from "./ProjectClass";
export type { SessionMode } from "./SessionMode";
export type { StageMode } from "./StageMode";
export type { CheckpointMode } from "./CheckpointMode";
export type { ClaimStrength } from "./ClaimStrength";

// Scorer rubric (PR-Rust 2026-04-27).
export type { RubricScore } from "./RubricScore";

// Decision log discriminated union — used by DecisionsTab for
// compile-time exhaustive switch on decision kinds.
export type { DecisionType } from "./DecisionType";
export type { DecisionActor } from "./DecisionActor";

// Server wire types (PR-Rust 2026-04-27 — partial migration).
export type { ExecutionStatusResponse } from "./ExecutionStatusResponse";
export type { ProgressSummary } from "./ProgressSummary";

// SME-supplied data inputs — registered via the Inputs inspector tab,
// surfaced in CONTEXT.md, consumed by the data_acquisition stage.
export type { UserInput } from "./UserInput";
export type { UserInputFile } from "./UserInputFile";
export type { UserInputKind } from "./UserInputKind";

// Plan §S5.15 — `IntakeFacts` is the Rust-side intake shape passed
// through `emit/mod.rs::emit_with_conversation_log` into the
// emitted package. Re-exported here so the UI can read the same
// type when surfacing intake-derived state without copy-pasting
// the field set.
export type { IntakeFacts } from "./IntakeFacts";
// Note: SessionStateSnapshot is exported from chatClient.ts since the
// hand-maintained shape there is the contract UI components consume;
// the generated SessionStateSnapshot.ts is available for direct use
// when callers want the strict shape.
