// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One extractor-surfaced candidate. Carries enough information for
 * the conversation service to call `register_input_path` and for the
 * UI to render a "Register?" affordance.
 */
export type InputPathHint = { 
/**
 * Verbatim token taken from prose. Surfaced so the SME sees
 * the same string they typed.
 */
raw_mention: string, 
/**
 * Absolute canonicalized path of the directory the SME would
 * register. When the prose pointed at a file we surface its
 * parent directory here, since the `register_input_path` endpoint
 * only accepts directories.
 */
canonical_root: string, 
/**
 * File extension (lowercase, sans dot) that triggered acceptance.
 */
matched_extension: string, 
/**
 * True when the prose pointed at a file (we resolved its parent);
 * false when the prose pointed at the directory directly. Surfaced
 * so the LLM can phrase the suggestion ("I see you mentioned the
 * file X — would you like to register its directory Y?").
 */
file_mention: boolean, 
/**
 * When `Some`, the relative filename inside `canonical_root` the
 * SME named. Lets downstream tooling pin the specific file the
 * SME meant rather than re-walking the whole directory.
 */
file_relpath: string | null, };
