// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * InputSwapKind discriminant.
 */
export type InputSwapKind = "reference" | "annotation" | "format" | "cohort_subset";
