// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PinnedAccession } from "./PinnedAccession";
import type { PinnedReferenceBundle } from "./PinnedReferenceBundle";
import type { ProjectClass } from "./ProjectClass";

/**
 * IntakeFacts data.
 */
export type IntakeFacts = { 
/**
 * Modality.
 */
modality: string, 
/**
 * Defaults to `Bioinformatics` so sessions persisted before this
 * field existed load unchanged.
 */
project_class: ProjectClass, 
/**
 * Organism taxon id.
 */
organism_taxon_id?: bigint, 
/**
 * Organism name.
 */
organism_name?: string, 
/**
 * Methods sourced from `ClassificationResult::methods_specified`.
 */
methods: Array<string>, 
/**
 * Populated from structured capture.
 */
sample_count?: number, 
/**
 * Coverage depth.
 */
coverage_depth?: number, 
/**
 * Cell count.
 */
cell_count?: number, 
/**
 * Database size gb.
 */
database_size_gb?: number, 
/**
 * Pinned data accessions. One entry per upstream
 * dataset (GEO/SRA/ENA/dbGaP/etc.) the SME committed to at
 * intake. Resolved once + frozen so re-emissions of the same
 * intake reference identical bytes; enables FAIR re-runnability
 * (RO-Crate `hasPart` SHA-256 entries cross-reference these).
 */
pinned_accessions: Array<PinnedAccession>, 
/**
 * Pinned reference bundles (assembly + annotation).
 * One entry per reference distribution committed at intake. The
 * fields together form the reproducibility-bearing key — assembly
 * (e.g. `GRCh38.p14`), source release tag (e.g. `Ensembl 115`),
 * and the SHA-256 of the FASTA + GTF tarball.
 */
pinned_reference_bundles: Array<PinnedReferenceBundle>, 
/**
 * Phase G of the literature-atom plan — SME opt-in for the
 * `review_prior_work` + `contextualize_findings_with_literature`
 * atom family. Default false; flipping to true causes the v4
 * composer to include the optional literature atoms in supported
 * archetypes (bulk_rnaseq_de, chip_seq_peaks, variant_calling).
 * Set via the existing `set_intake_field` mutation tool.
 */
literature_review_requested: boolean, 
/**
 * Sub-archetype small-task exclusion list — mirrors
 * `Session.excluded_atoms`. Defaults to empty; not surfaced in the
 * emitted policies/intake-facts.json when empty.
 */
excluded_atoms: Array<string>, };
