// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IterateConvergenceOp } from "./IterateConvergenceOp";

/**
 * Convergence rule. The agent reads the metric value
 * from the iteration's result.json, compares against `threshold`
 * using `operator`, and tracks consecutive passes that satisfy the
 * rule. Convergence fires when the consecutive count crosses
 * `consecutive_iterations`.
 */
export type IterateConvergence = { 
/**
 * CEL expression naming the metric field. Examples:
 * `result.silhouette`, `result.gradient_norm`,
 * `result.adjusted_rand`. The agent compiles this with
 * `cel-interpreter` v0.13.0 (S7.1) and evaluates against the
 * per-iteration result.json.
 */
metric_source: string, 
/**
 * Comparison operator. `Lt` is the typical "loss decreasing"
 * rule; `Gt` for metrics that should rise (silhouette);
 * `LtEq` / `GtEq` mirror.
 */
operator: IterateConvergenceOp, 
/**
 * Numeric threshold the metric is compared against.
 */
threshold: number, 
/**
 * How many *consecutive* iterations must satisfy the rule
 * before declaring convergence. Default 2 (one stable pass
 * rules out a stochastic dip). Schema enforces `>= 1`.
 */
consecutive_iterations: number, };
