// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IterateConvergence } from "./IterateConvergence";
import type { IterateMaxAction } from "./IterateMaxAction";

/**
 * Convergence + cap config for `StageCardinality::IterateUntil`.
 *
 * Mirrors the K8s reconciliation-loop pattern (Q5.1 Part 2): a
 * max-iterations ceiling, a min-iterations floor, and a convergence
 * rule that the agent evaluates each pass against a per-atom metric.
 * Composer treats iterate atoms as single nodes when ordering;
 * runtime expansion happens in the agent (S10.4).
 */
export type IterateSpec = { 
/**
 * Hard ceiling on iterations. The agent flips to
 * `BlockerKind::IterationDidNotConverge` when reached without
 * convergence. Schema enforces `> 0`.
 */
max_iterations: number, 
/**
 * Lower bound — useful when the convergence metric is noisy at
 * startup and a single early-pass match would underfit. Default
 * 1 (no floor beyond the implicit one); the schema rejects
 * `min_iterations > max_iterations`.
 */
min_iterations: number, 
/**
 * Convergence rule the agent re-evaluates each pass.
 */
convergence: IterateConvergence, 
/**
 * What to do when `max_iterations` is reached without
 * convergence. Default `Block` surfaces
 * `BlockerKind::IterationDidNotConverge` so the SME picks
 * (raise threshold / accept best so far / abort).
 */
on_max_iterations: IterateMaxAction, 
/**
 * Optional CEL expression naming the field in
 * `runtime/outputs/<task>/result.json` that ranks iterations
 * when the SME picks "accept best so far" — without it, the
 * last iteration is the default. Composer doesn't compile
 * this; the agent does, at iteration time.
 */
best_selector?: string, };
