// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AtomSummary } from "./AtomSummary";

export type ListAtomsResult = { atoms: Array<AtomSummary>, 
/**
 * Total atoms in the registry BEFORE filtering. Lets the LLM
 * orient ("the catalog has 73; you filtered down to 8").
 */
total_in_registry: number, 
/**
 * Atoms that matched the filter (pre-truncation).
 */
matched: number, 
/**
 * True when `matched > atoms.len()` — caller should narrow the
 * filter or bump `max_results`.
 */
truncated: boolean, };
