// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AtomRoleFilter } from "./AtomRoleFilter";

export type ListAtomsArgs = { 
/**
 * Filter to atoms referenced by the canonical archetype for the
 * given modality (e.g. `"long_read_rnaseq"`). Atoms themselves
 * don't carry a `modality_hint` field — the archetype does. The
 * handler resolves the archetype whose `modality_hint` matches
 * and intersects its atom-id list with the atom registry.
 */
modality: string | null, 
/**
 * Filter to atoms with the given role.
 */
role: AtomRoleFilter | null, 
/**
 * Filter to atoms that defer their tool choice to a discovery
 * atom (i.e. `method_choice.deferred_to` is set).
 */
has_method_choice: boolean | null, 
/**
 * Filter to atoms whose primary output EDAM data IRI matches.
 * e.g. `"data:0951"` (effect-size + adjusted p-value).
 */
produces_edam_data: string | null, 
/**
 * Cap on returned rows. Default `DEFAULT_MAX_RESULTS` (100);
 * hard-capped at `MAX_RESULTS_HARD_CAP` (500). Set high to
 * dump the full catalog; lower it when the LLM only needs a
 * few representative atoms.
 */
max_results: number | null, };
