// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Three-state LLM availability surfaced to the UI via
 * `GET /api/chat/llm-availability`. The tagged-enum shape matches the
 * other chat session-state wire types so the React `kind`-switch
 * idiom keeps working.
 */
export type LlmAvailability = { "kind": "available" } | { "kind": "unavailable", reason: string, retry_after_seconds: bigint | null, } | { "kind": "disabled", reason: string, set_by: string, };
