// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pointer to a discovery atom whose runtime output supplies the
 * method-choice for this atom. Replaces the today's id-prefix
 * convention (`discover_<x>` → `<x>`) per plan §3.3.
 */
export type MethodChoiceRef = { 
/**
 * Atom id of the discovery step that produces the choice.
 */
deferred_to: string, };
