// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BioinformaticsModality } from "./BioinformaticsModality";
import type { OntologySet } from "./OntologySet";

/**
 * One modality's ontology coverage envelope.
 */
export type ModalityCoverage = { 
/**
 * Modality.
 */
modality: BioinformaticsModality, 
/**
 * Primary ontologies.
 */
primary_ontologies: OntologySet, 
/**
 * Secondary ontologies.
 */
secondary_ontologies: OntologySet, 
/**
 * Forbidden ontologies.
 */
forbidden_ontologies: OntologySet, };
