// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObservableBound } from "./ObservableBound";
import type { ObservableKind } from "./ObservableKind";

/**
 * One promised scalar quantity: where its value lives, what dimensional kind
 * it is, what population it quantifies, how tightly it is asserted, and
 * whether the host can recompute it.
 *
 * Every field carries a serde default. Two guarantees depend on that: a
 * declaration authored today survives the addition of any later field, and a
 * partially authored declaration parses and is then rejected by
 * [`ObservableSchema::validate`] with the offending index named — a locatable
 * error instead of an opaque parse failure.
 */
export type Observable = { 
/**
 * Dotted key path into the stage's `result.json`, e.g. `counts.n_retained`.
 *
 * Matched literally, never fuzzily: exact-match binding is what stops a
 * quantity from attaching itself to a similarly named scalar belonging to
 * a different stage.
 */
key: string, 
/**
 * Additional accepted key paths (agent may emit a synonym). Resolution
 * tries `key` first, then each alias in order — the same declared-then-
 * aliases discipline the tabular contract uses for column names. The
 * candidates live in the atom's declaration, never in the resolving code.
 * Empty (the default) means only `key` is accepted.
 */
aliases: Array<string>, 
/**
 * Dimensional kind of the quantity. Prevents an incommensurable
 * comparison: a cardinality and a probability-scale number can carry the
 * same textual value and mean unrelated things, and only a declared kind
 * makes that distinction available to a checker.
 */
quantity_kind: ObservableKind, 
/**
 * What the quantity is *of*. Must reference a declared port id or an
 * abstract population name — never a domain noun. Two quantities of the
 * same kind over different populations are not comparable, so this is the
 * field that keeps a checker from equating them.
 */
population: string, 
/**
 * Surface forms a narrative may legitimately use for `population`.
 *
 * `aliases` is defined over key PATHS and cannot carry this: two names for
 * the same counted set is a different relation from two paths to the same
 * value. Without a channel for it, a checker comparing a narrative noun to
 * `population` must either reject every synonym — condemning "22,369 genes
 * retained" against a population declared as features — or accept every
 * noun, which is what let a count of matrix cells bind to a feature total.
 *
 * Empty means the declaration speaks only for `population` itself, and a
 * different noun is UNDECLARED rather than wrong: strictness is opt-in by
 * completeness, so an author is never convicted for a synonym they were
 * never asked to declare.
 */
population_terms: Array<string>, 
/**
 * How tightly the value is asserted. Prevents convicting a deliberately
 * one-sided or hedged statement for failing an exact-equality check.
 */
bound_kind: ObservableBound, 
/**
 * Set when the value is recomputable by the host from primary bytes, so
 * the registry can mark it authoritative rather than agent-asserted.
 * Defaults to `false`: an undeclared provenance is the weaker claim, so
 * silence can never upgrade an assertion into an authoritative value.
 */
host_derivable: boolean, 
/**
 * Optional unit for non-count quantities (QUDT-style symbol or CURIE).
 * Absent means dimensionless. A unit on a [`ObservableKind::Count`] is
 * rejected by [`ObservableSchema::validate`], because a cardinality of a
 * declared population has no unit to carry and a spurious one would make
 * an incommensurable comparison look well-typed.
 */
unit?: string, };
