// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The dimensional kind of a declared observable, in the spirit of a QUDT
 * quantity kind. Enforces that two quantities are only ever compared when
 * they are the same kind of thing; prevents the class of false conviction
 * where a checker matches a narrative number against a value of an unrelated
 * dimension that happens to be numerically close.
 *
 * `#[non_exhaustive]` because the set of kinds grows as declarations do, and
 * growing it must stay a minor change for downstream consumers.
 */
export type ObservableKind = "count" | "sum" | "extremum" | "difference" | "ratio" | "proportion" | "significance" | "effect" | "threshold" | "duration" | "other";
