// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Observable } from "./Observable";

/**
 * The scalar observables an atom promises to report, so a narrative quantity
 * can be bound to a declared observable instead of resolved by name search.
 *
 * Empty (the [`Default`]) is a legal declaration and serializes to nothing:
 * an atom that promises no scalar keeps its previous emitted bytes exactly,
 * which is what lets this hang off an existing registry entry as an optional
 * block without editing a single existing declaration.
 */
export type ObservableSchema = { 
/**
 * The promised observables, in authoring order. Order is load-bearing
 * twice over: it is the resolution order of [`ObservableSchema::get`],
 * and it is the order every serialization emits, so an emitted package
 * stays byte-reproducible instead of depending on iteration order.
 */
observables: Array<Observable>, };
