// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How tightly a declared observable's value is asserted. Enforces that a
 * bound is checked as a bound; prevents convicting a one-sided or hedged
 * statement for failing an exact-equality check, and conversely prevents an
 * exact promise from being graded loosely.
 *
 * `#[non_exhaustive]` so a further modifier can be added without a breaking
 * change for downstream consumers.
 */
export type ObservableBound = "point" | "upper" | "lower" | "range" | "approximate";
