// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reference to an additional ontology term. Used on
 * `PortContract.ontology_terms` to capture multi-ontology
 * annotations (e.g. a count matrix typed as both an EDAM data class
 * and a CL cell type).
 */
export type OntologyTermRef = { 
/**
 * Compact IRI.
 */
iri: string, 
/**
 * Optional human label for UI rendering.
 */
label?: string, 
/**
 * Ontology release.
 */
ontology_version?: string, };
