// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnionToken } from "./UnionToken";

/**
 * An ontology set per matrix cell — either the literal token `union`
 * (meaning "union across every modality's set") or an explicit set
 * of ontology prefixes (e.g. `["GO", "SO", "EDAM"]`).
 */
export type OntologySet = UnionToken | Array<string>;
