// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModalityCoverage } from "./ModalityCoverage";

/**
 * The full coverage matrix loaded from
 * `config/modality-ontology-coverage.yaml`.
 */
export type OntologyScopeMatrix = { 
/**
 * Semver-shaped matrix version (asserted by schema).
 */
version: string, 
/**
 * One row per `BioinformaticsModality`.
 */
coverage: Array<ModalityCoverage>, };
