// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpaquePortRef } from "./OpaquePortRef";

/**
 * One entry persisted to `_opaque_registry.jsonl`. Tracks observation
 * counts, distinct sessions, and the producer→consumer ports that
 * surfaced the opaque type.
 */
export type OpaqueRegistryEntry = { 
/**
 * Stable hash of the opaque type's description (typically a
 * `blake3:<hex>` content hash). Distinct hashes mean distinct
 * opaque types even if the human-readable description differs by
 * whitespace; equal hashes collapse into the same entry.
 */
opaque_hash: string, 
/**
 * RFC3339 timestamp of the first observation.
 */
first_seen: string, 
/**
 * RFC3339 timestamp of the most recent observation.
 */
last_seen: string, 
/**
 * Cumulative number of observations (across all sessions).
 */
occurrence_count: number, 
/**
 * Distinct sessions in which this opaque type was observed. Used
 * by `registry_improvement_candidates` to decide whether the type
 * has crossed the "≥3 distinct sessions" threshold.
 */
session_ids: Array<string>, 
/**
 * Distinct (node, port) call sites that produced the opaque type.
 * Useful for the operator's `make doctor` report so the prompt
 * can name the offending stage.
 */
ports: Array<OpaquePortRef>, };
