// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An archetype-author declaration that a `depends_on` edge between two
 * stages is a *workflow-ordering* relation, not a port-typed data flow.
 * The composer honors this as an explicit, auditable exemption: a
 * declared edge that fails port unification becomes
 * [`crate::workflow_contracts::edge::EdgeKind::OrderingOnly`]
 * (non-blocking in Draft); an *undeclared* non-unifying edge is
 * `Unproven` and rejects.
 */
export type OrderingOnlyEdge = { 
/**
 * Producer stage id (or stage alias) — the `depends_on` target.
 */
from: string, 
/**
 * Consumer stage id — the stage that declares the `depends_on`.
 */
to: string, };
