// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a per-task parameter override came from. Only `Sme` today; the enum
 * exists so an audit reader can distinguish an SME-mandated value from any
 * future machine-derived source. `#[non_exhaustive]` keeps adding a source a
 * non-breaking minor change for ts-rs / RO-Crate consumers.
 */
export type OverrideSource = "sme";
