// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Severity bucket. Drives the `overall_action` precedence in
 * `IngestionSafetyReport`.
 */
export type PatternSeverity = "low" | "medium" | "high" | "critical";
