// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Amendment context carried from `AmendStart` to the
 * next `emit_package` so RO-Crate lineage (`prov:wasDerivedFrom`,
 * `UpdateAction`) and `policies/amendment-lineage.json` populate
 * correctly. Modeled here (not in `core::emitter::AmendContext`) so
 * the conversation crate can persist it across the
 * AmendStart → AmendReady → EmitPackageStart hops without depending
 * on crate-private state.
 */
export type PendingAmendment = { 
/**
 * The stage whose method is being replaced.
 */
target_stage: string, 
/**
 * Downstream task ids invalidated by the method swap (transitive closure).
 */
invalidated_tasks: Array<string>, 
/**
 * Parent package path captured at `AmendStart`-time from
 * `session.emitted_package_path`. The next `emit_package` call
 * will overwrite that field with the child path; we capture the
 * parent here so `EmitConfig::amend_from` can point at the parent
 * crate.
 */
parent_package_path: string, 
/**
 * Optional SME-supplied rationale for the method swap. Threaded
 * into `AmendContext::reason` and surfaced on the `UpdateAction`
 * entity's `description` field.
 */
rationale?: string, };
