// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One PHI leak finding produced by `detect_phi_leak`.
 * Stable record so the UI and SME-facing refusal reports can render
 * the offending line, the JSON pointer, and the matched pattern.
 */
export type PhiLeak = { 
/**
 * 1-based line number in the scanned JSONL stream.
 */
line: number, 
/**
 * JSON pointer (`/foo/bar`) to the offending value. Empty when
 * the match was at the document root.
 */
field: string, 
/**
 * Stable pattern name (`mrn`, `dob`, `phone`, `ssn`, `email`,
 * `gps_coords`).
 */
pattern_name: string, };
