// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AffordanceProof } from "./AffordanceProof";
import type { GeneratedReviewStatus } from "./GeneratedReviewStatus";
import type { GenericPrimitive } from "./GenericPrimitive";

/**
 * PlotAffordance discriminant.
 */
export type PlotAffordance = { "kind": "registered", 
/**
 * Figure ids.
 */
figure_ids: Array<string>, 
/**
 * Renderer module.
 */
renderer_module: string, 
/**
 * Proof.
 */
proof: AffordanceProof, } | { "kind": "inherited_via_ontology", 
/**
 * Parent term.
 */
parent_term: string, 
/**
 * Figure ids.
 */
figure_ids: Array<string>, 
/**
 * Renderer module.
 */
renderer_module: string, 
/**
 * Proof.
 */
proof: AffordanceProof, } | { "kind": "structural_fallback", 
/**
 * Primitive.
 */
primitive: GenericPrimitive, 
/**
 * Figure id.
 */
figure_id: string, 
/**
 * Warning.
 */
warning: string, 
/**
 * Proof.
 */
proof: AffordanceProof, } | { "kind": "generated_sandboxed", 
/**
 * Renderer module.
 */
renderer_module: string, 
/**
 * Figure ids.
 */
figure_ids: Array<string>, 
/**
 * Review status.
 */
review_status: GeneratedReviewStatus, 
/**
 * Proof.
 */
proof: AffordanceProof, } | { "kind": "deferred", 
/**
 * Data artifact relpath.
 */
data_artifact_relpath: string, 
/**
 * Recommendation.
 */
recommendation: string, 
/**
 * Sme check required.
 */
sme_check_required: boolean, 
/**
 * Proof.
 */
proof: AffordanceProof, };
