// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Foreign key into the `policy_rules:` registry in
 * `config/assumption-policy.yaml`. Construct via [`PolicyRuleId::new`]
 * (registry-validated) or [`PolicyRuleId::unchecked`] (legacy / test
 * path).
 */
export type PolicyRuleId = string;
