// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PolicyCheck } from "./PolicyCheck";
import type { PopulationWaiver } from "./PopulationWaiver";

/**
 * One policy bundle. Bundles are loaded from
 * `config/downstream-policy/*.json` at composer startup.
 */
export type PolicyBundle = { 
/**
 * Stable id (filename without the `.json`).
 */
id: string, 
/**
 * Human label (rendered in UI policy cards).
 */
label: string, 
/**
 * Free-text description.
 */
description?: string, 
/**
 * Active policy checks.
 */
checks: Array<PolicyCheck>, 
/**
 * Regulatory citation (e.g. "21 CFR Part 11 §11.10(a)").
 */
regulatory_citation?: string, 
/**
 * v3 P9 §11.X — population waivers signed against this bundle.
 * Empty for fresh bundles; populated via the
 * `POST /api/chat/session/:id/population-waiver` endpoint when the
 * SME's clinical lead signs off on an out-of-coverage sample
 * cohort. The composer's `classify_outcome_with_policy` consults
 * this list before emitting a `PopulationOutOfCoverage` refusal;
 * a matching waiver suppresses the refusal and the decision is
 * emitted into `runtime/decisions.jsonl` as durable provenance.
 */
population_waivers: Array<PopulationWaiver>, };
