// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssumptionPolicyPrivacyClass } from "./AssumptionPolicyPrivacyClass";
import type { DefectClass } from "./DefectClass";

/**
 * v3 §10.2 follow-up — one row in the `policy_rules:` registry. Every
 * `PolicyRuleId` referenced by a `ChainOfCustody`, `DecisionRecord`,
 * `PopulationWaiver`, or `LifecycleTransition::ForbiddenWaiverAttempt`
 * must construct against a row here.
 */
export type PolicyRule = { 
/**
 * Stable foreign-key id. Snake-case ASCII with optional `:` for
 * namespace separation (e.g. `phi_strict_v1`,
 * `genome_build_mismatch:research`).
 */
id: string, 
/**
 * Human-facing description used by the operator UI and the
 * adjudication queue card.
 */
description: string, 
/**
 * Privacy class this rule scopes to. Reuses the existing
 * `PolicyPrivacyClass` enum so the registry and the
 * `(defect_class × privacy_class)` entry table share a vocabulary.
 */
privacy_class: AssumptionPolicyPrivacyClass, 
/**
 * Defect class this rule scopes to. Reuses the existing
 * `DefectClass` enum.
 */
defect_class: DefectClass, };
