// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A declared parameter constraint on a port. The compatibility engine
 * (P6) checks `required` satisfaction + `allowed_values` intersection
 * between a producer output parameter and a consumer input parameter.
 * Port-level (not atom-level) so the engine stays port-pure. The engine
 * checks *declared* compatibility only — it never selects a method
 * (method neutrality).
 */
export type PortParameter = { 
/**
 * Parameter name (matched by name across producer/consumer).
 */
name: string, 
/**
 * Permitted values. Empty = unconstrained. The engine refuses an
 * edge when producer and consumer both constrain a same-named
 * parameter and the value sets are disjoint.
 */
allowed_values: Array<unknown>, 
/**
 * When true the consumer requires this parameter be declared by
 * the producer; an unmet required parameter is incompatible.
 */
required: boolean, };
