// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortCardinality } from "./PortCardinality";

/**
 * One rule mapping an intake-facts field name to its EDAM type
 * signature.
 */
export type PortMapping = { 
/**
 * Intake field name, e.g. `samples` or `reference_genome`.
 */
intake_field: string, 
/**
 * EDAM data class IRI the value represents.
 */
edam_data: string, 
/**
 * EDAM format IRI when the field's value names a file path.
 * `None` for non-path fields like `sample_count`.
 */
edam_format?: string, 
/**
 * Whether the field carries a single value or a list of them.
 * Single is the default; the composer fans out collection
 * fields into per-element atom invocations.
 */
cardinality: PortCardinality, 
/**
 * Phase-3 hook — WINGS-style constraint reasoning per [DEC
 * Part 2]. Schema records the field; v1 composer ignores it.
 */
constraints: Array<string>, };
