// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome the dispatch is projected to produce — the UI uses this to
 * preview the recovery. Maps 1:1 onto `ComposeOutcome`'s success
 * variants so the SME can read "Waive → ValidatedExecutableDag" as
 * "approving this waiver will produce an executable DAG."
 */
export type ProjectedOutcome = "validated_executable_dag" | "draft_dag" | "partial_dag" | "novel_node_spec";
