// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StateRequirements } from "./StateRequirements";

/**
 * Top-level policy shape. Mirrors the YAML schema.
 *
 * `states` is keyed by the `LifecycleState::canonical_name()` snake-
 * case form so config edits don't have to track Rust enum variant
 * names.
 */
export type PromotionGatePolicy = { 
/**
 * Version.
 */
version: string, 
/**
 * States.
 */
states: { [key in string]?: StateRequirements }, };
