// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Supporting evidence for a `CompatibilityProof`. Stable enough to
 * replay in determinism tests.
 */
export type ProofEvidence = { "kind": "registry_snapshot", 
/**
 * Registry.
 */
registry: string, 
/**
 * Snapshot id.
 */
snapshot_id: string, } | { "kind": "validator_run", 
/**
 * Validator id.
 */
validator_id: string, 
/**
 * Result ref.
 */
result_ref: string, } | { "kind": "citation", uri: string, label: string, };
