// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SandboxRefusal } from "./SandboxRefusal";

/**
 * Why a proposal is in the [`ProposalLifecycle::Blocked`] state.
 * Surfaces in the chat-pane card as the SME-facing recovery hint.
 */
export type ProposalBlockerReason = { "kind": "validator_failed", failures: Array<string>, } | { "kind": "sandbox_refused", refusals: Array<SandboxRefusal>, } | { "kind": "materialization_failed", reason: string, } | { "kind": "sme_rejected", 
/**
 * Rationale.
 */
rationale?: string, };
