// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The five proposal shapes the composer accepts. Each maps to a
 * specific mutation on the in-flight DAG.
 */
export type ProposalKind = "node_addition" | "edge_addition" | "node_replacement" | "contract_mutation" | "assumption_resolution";
