// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProposalBlockerReason } from "./ProposalBlockerReason";

/**
 * Promotion-pipeline lifecycle of a proposal. Tagged with
 * `serde(tag = "kind")` so the UI can dispatch on `lifecycle.kind`
 * instead of guessing which variant is present.
 *
 * `Promoted` / `Blocked` / `Rejected` are terminal — [`crate::hypothesized_proposal::ProposalLifecycle`]
 * callers (see `crates/conversation/src/proposal_gate.rs`) treat
 * them as no-ops when re-advancing.
 */
export type ProposalLifecycle = { "kind": "pending_validation" } | { "kind": "pending_sandbox" } | { "kind": "awaiting_signoff" } | { "kind": "promoted", task_node_id: string, } | { "kind": "blocked", reason: ProposalBlockerReason, } | { "kind": "rejected", 
/**
 * Rationale.
 */
rationale?: string, };
