// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConstraintSeverity } from "./ConstraintSeverity";

/**
 * Per-artifact QC metric contract. Populated by the dataset
 * profiler and consumed by the `QcGate` adapter family. Atoms
 * declare quality requirements here; the harness enforces them
 * at dispatch time.
 */
export type QualityMetricContract = { 
/**
 * Stable metric id (`mapping_rate`, `q30_pct`, `mt_pct`).
 */
id: string, 
/**
 * Threshold expression (CEL). E.g. `value >= 0.85`.
 */
threshold: string, 
/**
 * `Hard` rejects, `Soft` warns + assumption-ledgers.
 */
severity: ConstraintSeverity, 
/**
 * Human description of the rule.
 */
description?: string, };
