// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which row SET a [`ClaimContract::QuantileOfColumn`] aggregate is computed
 * over. "tested genes" restricts to rows whose adjusted p-value is present
 * (non-NA) — the DE convention for the set of genes that survived independent
 * filtering — whereas an unqualified aggregate is over every row.
 */
export type QuantileRowSet = "all_rows" | "tested_genes";
