// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReadAllowanceScope } from "./ReadAllowanceScope";

/**
 * One declared read-allowance entry (see `AtomDefinition::read_allowance`).
 */
export type ReadAllowance = { 
/**
 * How broad the sanctioned read scope is.
 */
scope: ReadAllowanceScope, 
/**
 * Human-readable justification, surfaced in provenance
 * (`ecaax:provenanceReadAllowance` on the emitted RO-Crate's root
 * Dataset) so a reader can see why the broad read was sanctioned
 * rather than flagged.
 */
rationale: string, };
