// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReexecutionReport } from "./ReexecutionReport";

export type ReexecuteResult = { env_tier: string, report: ReexecutionReport, unprovisionable: boolean, };
