// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefusalKind } from "./RefusalKind";
import type { UnblockPath } from "./UnblockPath";

/**
 * Refusal report — composer declines to produce a DAG.
 *
 * `kind` is the typed `RefusalKind` enum; the report carries a
 * `Vec<UnblockPath>` enumerating the actionable recovery affordances
 * the SME can dispatch.
 *
 * The invariant ("every refusal carries actionable unblock paths or
 * is unconditional hard policy") is enforced at the type boundary by
 * `RefusalReport::validate()`: hard-policy kinds
 * (`HardPolicyViolation`, `PhiLeakBlocked`, `PrivacyViolation`) may
 * carry an empty `unblock_paths` vector; every other kind must carry
 * at least one populated path.
 */
export type RefusalReport = { 
/**
 * Stable id.
 */
id: string, 
/**
 * Typed refusal kind. Drives UI per-card dispatch and the F21
 * invariant. See `RefusalKind` for the closed taxonomy.
 */
kind: RefusalKind, 
/**
 * Human-readable explanation.
 */
statement: string, 
/**
 * Optional pointers (policy ids, regulation citations).
 */
references: Array<string>, 
/**
 * Actionable recovery affordances. Empty only for
 * `permits_no_unblock_paths()` kinds; every other kind is
 * rejected by `validate()` when this vec is empty.
 */
unblock_paths: Array<UnblockPath>, };
