// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SandboxRefusalCategory } from "./SandboxRefusalCategory";

/**
 * Typed refusal taxonomy. Drives UI dispatch and the F21
 * "must carry actionable recovery" invariant.
 *
 * The three "hard policy" kinds (`HardPolicyViolation`,
 * `PhiLeakBlocked`, `PrivacyViolation`) permit empty `unblock_paths`
 * because they're refusals where the SME has no recovery affordance
 * short of branching the session — the system MUST refuse. Every
 * other kind requires at least one populated `UnblockPath` (see
 * `RefusalReport::validate`).
 */
export type RefusalKind = { "kind": "hard_policy_violation" } | { "kind": "privacy_violation" } | { "kind": "clinical_gate_failed" } | { "kind": "phi_leak_blocked" } | { "kind": "license_missing" } | { "kind": "goal_underspecified" } | { "kind": "population_out_of_coverage", 
/**
 * Workflow id.
 */
workflow_id: string, 
/**
 * Sample label.
 */
sample_label: string, 
/**
 * Validated labels.
 */
validated_labels: Array<string>, 
/**
 * Suggested waiver authority.
 */
suggested_waiver_authority: string, } | { "kind": "semantic_loss_not_authorized" } | { "kind": "sandbox_refused", category: SandboxRefusalCategory, } | { "kind": "promotion_refused" } | { "kind": "uncategorized_blocker" };
