// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lookup criteria for `DagModification::QueryRegistry`. Used by the
 * repair-strategy `query_registry_for_match` when an existing atom
 * is suspected to exist but wasn't reachable from the search.
 */
export type RegistryQuery = { 
/**
 * Semantic-type IRI to match against `atom.outputs[*].semantic_type`.
 */
semantic_type: string, 
/**
 * Optional modality bucket to filter on.
 */
modality?: string, };
