// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Trust tier of an external registry. `Community` is the conservative
 * default; `Curated` is operator-declared (see `ECAA_EXTERNAL_CURATED_DIRS`).
 */
export type RegistryTier = "community" | "curated";
