// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One registry-improvement signal surfaced from the recurring-
 * `Unknown` aggregator.
 */
export type RegistryImprovementSignal = { 
/**
 * Stable id (the offending `SemanticType.stable_id()` value).
 */
semantic_type_id: string, 
/**
 * Variant key (`opaque` / `local_extension` / `ontology_term`).
 */
variant_key: string, 
/**
 * Distinct sessions in which the type appeared.
 */
sessions_seen: Array<string>, 
/**
 * Latest session timestamp (RFC3339) seen — `None` when no
 * session carried a `last_activity` field.
 */
last_seen_at?: string, 
/**
 * Human description (best-effort) — for `Opaque`, this is the
 * stored reason; for `LocalExtension`, the definition. Truncated
 * to 200 chars.
 */
description?: string, };
