// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typed rejection reasons. Free-text fits inside `Other` so the typed
 * vocabulary stays stable while the substrate keeps every refusal
 * recoverable.
 */
export type RejectionReason = { "kind": "cycle_introduction" } | { "kind": "required_input_unsatisfied", port: string, } | { "kind": "incompatible_semantic_type", producer: string, consumer: string, } | { "kind": "policy_violation", 
/**
 * Bundle id.
 */
bundle_id: string, 
/**
 * Check kind.
 */
check_kind: string, } | { "kind": "per_node_policy", node_id: string, check_kind: string, } | { "kind": "schema_invalid", statement: string, } | { "kind": "other", statement: string, };
