// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which component issued the rejection. The six variants partition
 * the verifier surface so post-hoc filtering can attribute refusals
 * to a single subsystem.
 */
export type RejectingComponent = "compatibility_engine" | "policy_gate" | "promotion_gate" | "planner" | "schema_validator" | "site_local";
