// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputSwapKind } from "./InputSwapKind";
import type { MethodSwitchKind } from "./MethodSwitchKind";
import type { ResourceTarget } from "./ResourceTarget";
import type { StageId } from "./StageId";
import type { TaskId } from "./TaskId";

/**
 * Closed remediation taxonomy. Ten variants, each mapping to one
 * `ToolBinding`.
 */
export type RemediationKind = { "kind": "bump_resources", 
/**
 * Target.
 */
target: ResourceTarget, 
/**
 * Prior.
 */
prior?: ResourceTarget, } | { "kind": "switch_method", stage_id: StageId, from: string, 
/**
 * To.
 */
to: string, 
/**
 * Switch kind.
 */
switch_kind: MethodSwitchKind, } | { "kind": "pin_library_version", 
/**
 * Library.
 */
library: string, 
/**
 * From.
 */
from?: string, 
/**
 * To.
 */
to: string, } | { "kind": "override_parameter", stage_id: StageId, param: string, 
/**
 * From.
 */
from?: unknown | null, 
/**
 * To.
 */
to: unknown, } | { "kind": "swap_input_data", 
/**
 * Field.
 */
field: string, 
/**
 * From.
 */
from?: string, 
/**
 * To.
 */
to: string, 
/**
 * Swap kind.
 */
swap_kind: InputSwapKind, } | { "kind": "rerun_upstream", 
/**
 * Producer task id.
 */
producer_task_id: TaskId, 
/**
 * Nested.
 */
nested: RemediationKind, } | { "kind": "tweak_executor", 
/**
 * Disable spot.
 */
disable_spot: boolean, 
/**
 * Partition.
 */
partition?: string, 
/**
 * Availability zone.
 */
availability_zone?: string, } | { "kind": "retry_as_is", reason: string, } | { "kind": "rebuild_environment", 
/**
 * Capability.
 */
capability: string, 
/**
 * Operator command hint.
 */
operator_command_hint: string, } | { "kind": "manual_review", 
/**
 * Summary.
 */
summary: string, 
/**
 * Suggested next steps.
 */
suggested_next_steps: Array<string>, };
