// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * RemediationOutcome discriminant.
 */
export type RemediationOutcome = "resolved" | "recurred" | "new_error" | "not_yet_attempted";
