// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DAG-side copy of a required-artifact declaration. Populated by the
 * builder from `StageSpec.required_artifacts`; threaded into
 * WORKFLOW.json so the harness can read it without re-loading the
 * taxonomy.
 */
export type RequiredArtifact = { 
/**
 * Path relative to `runtime/outputs/<task_id>/`.
 */
path: string, 
/**
 * Optional minimum size. Zero or absent = "non-empty file" check.
 */
min_size_bytes?: bigint, 
/**
 * Optional JSON-schema reference (path relative to the package
 * root). When present and the artifact is JSON, the harness
 * validates the body against the schema post-completion.
 */
schema_ref?: string, 
/**
 * Validation-obligation ids that the harness runs against this
 * artifact after task completion. Empty by default so legacy
 * WORKFLOW.json shapes load unchanged. Populated by the v4 lowering
 * pass from `TaskNode.validators`, where each validator name is the
 * obligation id the runner
 * registry resolves at dispatch time
 * (`p_value_in_unit_interval`, `gene_id_in_annotation`, etc.).
 * Failures append to `runtime/validation-reports.jsonl` and
 * re-block the task with `BlockerKind::ValidationFailed`.
 */
validation_obligations: Array<string>, };
