// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GpuRequirement } from "./GpuRequirement";

/**
 * Abstract compute requirements consumed by the cloud-specific mapping
 * logic. Cloud-agnostic on purpose — the Phase A data model ships the
 * struct so downstream waves can fill in scaling logic without churning
 * the type.
 */
export type ResourceRequirements = { 
/**
 * Number of virtual CPUs required.
 */
vcpus: number, 
/**
 * Memory required in gigabytes.
 */
memory_gb: number, 
/**
 * Ephemeral storage required in gigabytes.
 */
storage_gb: number, 
/**
 * Optional GPU requirement; absent means CPU-only.
 */
gpu: GpuRequirement | null, };
