// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resource hint for the composer's `ResourceEstimate` aggregator
 * (plan §3.1 row "ResourceEstimate computed from atom
 * resource_profile"). Coarse buckets — exact sizing happens via the
 * existing `compute-profiles/` machinery + pilot.
 */
export type ResourceProfile = { 
/**
 * Coarse CPU bucket (e.g. `light`, `moderate`, `heavy`,
 * `very_heavy`). Maps to per-stage profiles in
 * `config/compute-profiles/profiles.yaml`.
 */
cpu?: string, 
/**
 * Coarse memory bucket (`small`, `medium`, `large`, `xl`).
 */
memory?: string, 
/**
 * True when the atom needs a GPU.
 */
gpu: boolean, 
/**
 * Coarse runtime bucket in human-readable form (e.g. `seconds`,
 * `minutes`, `hours`). Pilot replaces these with concrete
 * projections at emit time.
 */
runtime_class?: string, };
