// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Significance } from "./Significance";

/**
 * Declares how to read a terminal atom's primary tabular result
 * artifact. `artifact` is a path relative to the stage's output
 * directory (e.g. `de_results.tsv`); `entity_column` names the row
 * identifier (gene, pathway, variant_id, ...). `significance` and
 * `signed_effect_column` are both optional — a schema with neither
 * still yields the reduced (unsigned, unfiltered) contract.
 */
export type ResultSchema = { artifact: string, entity_column: string, 
/**
 * Additional accepted header names for the entity column (e.g. an atom
 * whose canonical `entity_column` is `gene` but whose agent may emit the
 * row identifier under a synonym like `gene_id`/`gene_name`/`symbol`):
 * resolution tries `entity_column` then each alias, in order. Data-driven
 * — the candidate names live in the atom's declaration, never hardcoded in
 * the assembler. Empty (the default) means only `entity_column` is
 * accepted.
 */
entity_column_aliases: Array<string>, significance?: Significance, signed_effect_column?: string, 
/**
 * Additional accepted header names for the signed-effect column (e.g. a
 * DESeq2-native name + its ECAA-canonical alias): resolution tries
 * `signed_effect_column` then each alias, in order. Data-driven — the
 * candidate names live in the atom's declaration, never hardcoded in the
 * assembler. Empty (the default) means only `signed_effect_column` is
 * accepted.
 */
signed_effect_aliases: Array<string>, grouping_column?: string, };
