// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Review status of a generated implementation. Determines whether
 * the implementation may run in production or is restricted to
 * the sandbox executor.
 */
export type ReviewStatus = "unreviewed" | "auto_reviewed" | "human_reviewed" | "rejected";
