// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-row classification. See module docs for semantics.
 */
export type RowClassification = "robust" | "concordant" | "discordant" | "new_in_child" | "dropped_in_parent" | "entity_missing" | { "numerics_incomplete": { 
/**
 * Human-readable list of the missing numeric columns,
 * e.g. `"parent:log2FC"` or `"parent:log2FC,child:log2FC"`.
 */
which_missing: string, } };
