// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RowClassification } from "./RowClassification";

/**
 * One entity's cross-version diff. Both raw and adjusted p-values are
 * surfaced independently so the UI can spot rows that move between
 * adjustment regimes.
 */
export type RowDiff = { 
/**
 * Entity.
 */
entity: string, 
/**
 * Classification.
 */
classification: RowClassification, 
/**
 * Parent effect.
 */
parent_effect?: number, 
/**
 * Child effect.
 */
child_effect?: number, 
/**
 * Parent pvalue raw.
 */
parent_pvalue_raw?: number, 
/**
 * Parent pvalue adjusted.
 */
parent_pvalue_adjusted?: number, 
/**
 * Child pvalue raw.
 */
child_pvalue_raw?: number, 
/**
 * Child pvalue adjusted.
 */
child_pvalue_adjusted?: number, 
/**
 * Per-row contribution to the Pearson correlation of effect sizes
 * across the overlap. Rows with positive contribution agree with
 * the trend; negative contribution pulls against it. Sum of
 * contributions equals `pearson_r` (up to float rounding).
 */
effect_correlation_contribution: number, };
