// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the 9-dimension rubric. Each dimension is scored 0–2.
 * `hardware_awareness` is the 9th dimension, added to gate against
 * transcripts that invent thread counts / GPU flags in chat instead
 * of deferring to the execution agent's runtime envelope.
 */
export type RubricScore = { 
/**
 * Naturalness: conversation feels like SME chat, not form-filling (0–10).
 */
naturalness: number, 
/**
 * Continuity: no topic drift between turns (0–10).
 */
continuity: number, 
/**
 * One-question discipline: assistant never stacks multiple questions (0–10).
 */
one_question: number, 
/**
 * Method neutrality: assistant never recommends specific methods unprompted (0–10).
 */
method_neutrality: number, 
/**
 * Claim boundary: assistant never reports results as its own (0–10).
 */
claim_boundary: number, 
/**
 * Tool efficiency: no redundant tool calls in a single turn (0–10).
 */
tool_efficiency: number, 
/**
 * Confirmation discipline: emit_package only fires after SME confirm (0–10).
 */
confirmation: number, 
/**
 * Recovery: blockers are resolved cleanly without looping (0–10).
 */
recovery: number, 
/**
 * Rewards transcripts that defer hardware decisions
 * (--threads N, BLAS env vars, GPU flag selection) to the
 * execution agent at runtime. Penalizes transcripts that quote
 * specific numeric thread counts or `--use_accelerator=True` in
 * chat. Absent on scorer outputs produced before this dimension
 * is present — the parser treats the dimension as 0 with an INFO
 * comment so historical rubric runs don't need to be re-scored.
 */
hardware_awareness: number, };
