// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScoringValue } from "./ScoringValue";

/**
 * 17-component scoring tuple. Lower is better; comparison is
 * lexicographic.
 *
 * Shape is stable; the planner computes each component at plan time.
 */
export type ScoringTuple = { 
/**
 * 1. Hard policy violation.
 */
hard_policy_violation: ScoringValue, 
/**
 * 2. Required contract unsatisfied.
 */
required_contract_unsatisfied: ScoringValue, 
/**
 * 3. User-constraint violation (preferred backend, no-network,
 *    container-only, prefer-reproducible).
 */
user_constraint_violation: ScoringValue, 
/**
 * 4. Scientific appropriateness penalty (claim_boundary /
 *    method-fit signals).
 */
scientific_appropriateness_penalty: number, 
/**
 * 5. Goal/modality-relevance penalty (Pillar B). Count of
 *    goal-IRRELEVANT nodes: nodes whose backing atom is
 *    affiliated (via the archetype catalog) with a modality
 *    that the request never asked for and that are not
 *    synthesis/companion/terminal nodes. Placed AFTER the
 *    hard-reject / user-constraint / scientific terms and
 *    BEFORE `untrusted_node_count` so a semantically-aligned
 *    DAG outranks a structurally-cheaper but off-modality one,
 *    without masking genuine hard defects. Designed to be `0`
 *    on every coherent DAG.
 */
goal_relevance_penalty: number, 
/**
 * 6. Production-trust ratio (lower count of trusted nodes is
 *    worse). Stored as `u32::MAX - count` so lower is better
 *    after sort.
 */
untrusted_node_count: number, 
/**
 * 7. Unresolved blocking-assumption count.
 */
unresolved_assumptions: number, 
/**
 * 8. Risky-adapter count.
 */
risky_adapter_count: number, 
/**
 * 9. Total adapter count (lossless + lossy + risky).
 */
total_adapter_count: number, 
/**
 * 10. Validation coverage score (lower-is-better encoding).
 */
validation_coverage_penalty: number, 
/**
 * 11. Evidence quality (lower-is-better encoding).
 */
evidence_quality_penalty: number, 
/**
 * 12. Reproducibility score penalty.
 */
reproducibility_penalty: number, 
/**
 * 13. Explainability score penalty (Opaque types penalize).
 */
explainability_penalty: number, 
/**
 * 14. Backend availability penalty.
 */
backend_availability_penalty: number, 
/**
 * 15. Runtime cost estimate (compute hours).
 */
runtime_cost_estimate: number, 
/**
 * 16. Data movement cost.
 */
data_movement_cost: number, 
/**
 * 17. Stable lexical tie-breaker (sorted TaskNodeId chain).
 */
stable_lexical_id: string, };
