// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for `POST /api/chat/session/:id/turn`.
 */
export type SendTurnRequest = { 
/**
 * SME message text to append as a user turn.
 */
message: string, 
/**
 * Optional client-generated user turn id. When present, the
 * server uses this id for the persisted user Turn instead of
 * minting its own. Lets the optimistic UI append + 60s
 * reconciliation poll dedupe via turn_id (closes the
 * dup-user-turn drift after long-lived sessions).
 */
user_turn_id?: string, };
