// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdjudicationQueueEntry } from "./AdjudicationQueueEntry";
import type { CheckpointMode } from "./CheckpointMode";
import type { ConfirmationToken } from "./ConfirmationToken";
import type { DecisionRecord } from "./DecisionRecord";
import type { HarnessEvent } from "./HarnessEvent";
import type { InputPathHint } from "./InputPathHint";
import type { ProjectClass } from "./ProjectClass";
import type { SessionLineage } from "./SessionLineage";
import type { SessionMode } from "./SessionMode";
import type { SessionState } from "./SessionState";
import type { ToolCallRecord } from "./ToolCallRecord";
import type { Turn } from "./Turn";
import type { UserInput } from "./UserInput";

/**
 * Live chat session. Holds all intake state, conversation history, and
 * execution context for one SME interaction. Persisted to disk as JSON
 * on every mutation via `SessionStore`. The state machine lives in
 * `transitions.rs`; construction is in `mod.rs`.
 */
export type Session = { 
/**
 * Migration rail for the session schema. v1 = legacy taxonomy-driven
 * build; v2 = archetype path; v3 = backward-chain composer.
 *
 * Stored as `semver::Version`. The
 * `crate::migration::schema_version_serde` adapter accepts both
 * legacy bare-`u64` values and canonical SemVer strings on read,
 * so on-disk sessions persisted under the old `u32` shape
 * deserialize unchanged. Writes always emit the canonical SemVer
 * string. `#[serde(default = "default_schema_version")]` returns
 * the current SemVer for sessions persisted before this field
 * existed; new sessions get the current default via
 * `Session::new`.
 */
schema_version: string, 
/**
 * Which composer this session committed to. Distinct from
 * `schema_version` because a session's data shape and its
 * composer choice can evolve independently. v1 = legacy
 * taxonomy-driven build (always the value today); v2 = archetype
 * fast-path; v3 = backward-chain composer. Pinned at session
 * creation; amendments stay on the same composer so re-emission
 * is byte-deterministic. `#[serde(default = "default_composer_version")]`
 * returns 1 for sessions persisted before this field existed.
 */
composer_version: number, 
/**
 * Pilot sizing actuation. Set by the server's
 * `POST /api/chat/session/:id/progress` handler when the
 * harness reports a `sizing_pilot_complete` event with a full
 * `PilotReport` payload. Read by the AwsExecutor /
 * SlurmExecutor at provisioning time so the full-run
 * instance-type / sbatch shape uses the pilot's projection
 * rather than the conservative default.
 *
 * Stored as a JSON Value rather than a typed `PilotReport`
 * because the type lives in `crates/harness::executor::pilot`
 * (which `crates/conversation` doesn't depend on by design).
 * The executor reads it back via `serde_json::from_value` at
 * the dispatch site.
 *
 * Default `None` for sessions persisted before this field
 * existed; set once per session lifecycle (post-pilot, before
 * the first non-pilot task runs).
 */
pilot_recommendation: unknown | null, 
/**
 * Stable session identifier (UUID v4).
 */
id: string, 
/**
 * UTC timestamp when the session was first created.
 */
created_at: string, 
/**
 * UTC timestamp of the most recent turn or mutation.
 */
last_activity: string, 
/**
 * Current position in the session state machine.
 */
state: SessionState, 
/**
 * `Arc<Vec<Turn>>`. Tool-loop iterations clone the Arc
 * (pointer bump) instead of the full Vec. Mutations use
 * `Arc::make_mut(&mut session.conversation).push(...)` which
 * copies-on-write only when there's more than one holder — and
 * the tool loop's shared holder drops before the next mutation
 * anyway, so the typical mutation is still in-place.
 */
conversation: Array<Turn>, 
/**
 * Accumulated free-form text describing the analysis the SME wants to run.
 */
intake_prose: string, 
/**
 * Populated once the classifier has run. Defaults to
 * `Bioinformatics` so sessions persisted before this field
 * existed load unchanged. The LLM reads this via
 * `get_session_state`; it does not author it.
 */
project_class: ProjectClass, 
/**
 * Session-level confirmatory/exploratory discipline. Locked at
 * first `POST /confirm`. Defaults to `Exploratory` so sessions
 * persisted before this field existed load unchanged.
 */
mode: SessionMode, 
/**
 * True once `POST /confirm` has fired, which locks `mode` for the
 * remainder of the session.
 */
mode_locked: boolean, 
/**
 * Project-level checkpoint discipline. Defaults to `Gated` so
 * sessions persisted before this field existed load unchanged.
 */
checkpoint_mode: CheckpointMode, 
/**
 * Per-emit confirmation latch. `None` means the SME has NOT
 * approved the current plan shape (or never has). `Some(token)`
 * binds the SME's `/confirm` click to a specific
 * `(emission_id, summary_hash)` pair; `emit_package` verifies the
 * token authorizes the current pending emission AND that the
 * plan summary hasn't drifted since the SME clicked.
 *
 * Backward-compat: the custom serde adapter
 * [`deserialize_confirmation_token_legacy`] accepts the legacy
 * `user_confirmed: bool` field shape and folds it through to
 * `None` (fail-safe re-confirm requirement) so sessions
 * persisted before this migration force one re-confirm round
 * on next interaction. The `#[serde(alias = "user_confirmed")]`
 * lets serde read the legacy key transparently on disk; new
 * writes go to the canonical `confirmation_token` key.
 *
 * Wire-shape stability: external tooling that read the legacy
 * `user_confirmed: bool` should switch to reading
 * `SessionStateSnapshot::user_confirmed` (the server-side wire
 * projection in `chat_routes/sessions.rs`), which still has the
 * boolean type and the legacy field name. The session
 * persistence file's internal shape is not a contracted external
 * API.
 */
confirmation_token: ConfirmationToken | null, 
/**
 * The pending emission this session is about to perform. Populated
 * when transitioning into `PendingConfirmation`; cleared when the
 * state machine leaves that state (Confirm → ReadyToEmit retains
 * it through emit, Reject / amend clears it). The confirmation
 * token's `emission_id` must equal this exact UUID for the
 * `emit_package` precondition to pass.
 *
 * `#[serde(default)]` so sessions persisted before this field
 * existed deserialize cleanly with `None` (the token deser legacy
 * fallback handles the matching `user_confirmed: bool` field).
 */
pending_emission_id: string | null, 
/**
 * Filesystem path of the most recently emitted RO-Crate package.
 */
emitted_package_path: string | null, 
/**
 * Streaming progress events posted by the harness (batch-flushed into a synthetic assistant turn).
 */
harness_events: Array<HarnessEvent>, 
/**
 * Rolling audit log of tool calls made during this session.
 */
tool_call_log: Array<ToolCallRecord>, 
/**
 * Append-only SME decision audit trail. One record per high-leverage
 * checkpoint (confirm, reject, unblock, branch, emit, amend, rerun,
 * sensitivity winner). Serialized into `runtime/decisions.jsonl` at
 * emit time and registered as an RO-Crate `CreativeWork`.
 */
decisions: Array<DecisionRecord>, 
/**
 * When true, routes every turn to the Opus 4.8 escalation tier regardless of state or confidence.
 */
careful_mode: boolean, 
/**
 * When this session was
 * branched from a parent, this carries the parent's session id +
 * the timestamp the branch happened + the conversation turn index
 * the branch was taken from. None for root sessions. Persisted
 * across reloads so the SessionTree endpoint can rebuild the
 * lineage graph at any time.
 */
lineage: SessionLineage | null, 
/**
 * Operator-visible short name for this session. Populated lazily
 * via `POST /api/chat/session/:id/auto-title`, which runs a
 * single Haiku 4.5 call over the first few turns through
 * `ModelPolicy::for_side_call()`. Persists across reloads;
 * idempotent once set (the route short-circuits when
 * `title.is_some()` rather than re-invoking the LLM). `None` for
 * sessions persisted before this field existed via
 * `#[serde(default)]` so they load unchanged; the UI falls back
 * to a shortened session id when rendering the session tree.
 */
title?: string, 
/**
 * Session-level soft budget cap in USD. SME-authored via
 * `POST /api/chat/session/:id/budget`; None means no cap.
 * Persists across reloads.
 */
budget_usd?: number, 
/**
 * Who set the budget — SME username from the session envelope, or
 * "env-default" when populated from `ECAA_DEFAULT_SESSION_BUDGET_USD`.
 */
budget_set_by?: string, 
/**
 * When the budget was last set / changed.
 */
budget_set_at?: string, 
/**
 * SME-supplied data inputs registered before / during intake.
 * When non-empty, the data_acquisition stage's discovery layer
 * prefers `sme_supplied_local_path` / `sme_supplied_uploaded_files`
 * over public-repository fetchers. See `crates/server/src/chat_routes/inputs.rs`
 * for the registration endpoints and `config/downstream-policy/best-practice-scoring-policy.json`
 * for the candidate-method definitions. Defaults to empty so
 * sessions persisted before this field existed load unchanged.
 */
inputs: Array<UserInput>, 
/**
 * Filesystem paths the path-hint extractor pulled out of SME
 * intake prose that resolve under `ECAA_INPUT_ROOTS` but the SME
 * hasn't formally registered yet. The LLM sees these via
 * `get_session_state` and the UI renders them as a "Detected
 * inputs — register?" affordance. Auto-registered + cleared
 * during `append_intake_prose` when `ECAA_AUTO_REGISTER_PROSE_PATHS`
 * is enabled. Empty for sessions persisted before this field
 * existed (`#[serde(default)]`).
 */
pending_input_hints: Array<InputPathHint>, 
/**
 * Owner of this session. Today (single-tenant) this defaults to
 * "local". Once a fronting auth proxy is in place the
 * `X-Scripps-User` (or `X-Forwarded-User`) header populates this
 * at session-create time. Listing endpoints will filter by this
 * in Phase F. Stored, not yet enforced — that's a separate
 * permission layer (read-only mode for non-owners).
 */
owner_user: string, 
/**
 * Active policy bundle id for this session.
 * `None` = no policy enforcement; v4 composition runs the
 * per-node policy gate against the matching bundle when set.
 * Activated by `POST /api/chat/session/:id/policy-bundle`
 * (typically wired through `ClinicalConfirmGate` for clinical-
 * trial sessions). Persisted across reloads so re-emission
 * preserves the policy stance.
 *
 * Recognized values:
 * - `clinical_trial` → `PolicyContext::clinical_trial_bundle()`
 * - `phi_strict` → `PolicyContext::phi_strict_bundle()`
 *
 * Unknown values resolve to no-op (logged as a warning).
 */
active_policy_bundle?: string, 
/**
 * V3 session-scoped adjudication queue for the six
 * non-monotonic lifecycle edges from design §7. Populated by
 * `tools::rebuild_dag` when a non-monotonic lifecycle edge fires.
 */
adjudication_queue: Array<AdjudicationQueueEntry>, 
/**
 * The `run_id` (UUID v4 string) of the most recently emitted package.
 * Set by the conversation emit wrapper after a successful
 * `emit_with_conversation_log` call. Exposed via `get_session_state`
 * so the UI's Performance tab + harness progress handler can correlate
 * events to the package that generated them. `None` until the first
 * successful emission. `#[serde(default)]` so sessions persisted
 * before this field existed load cleanly with `None`.
 */
last_emitted_run_id?: string, 
/**
 * Outstanding disambiguation pair the SME hasn't answered.
 * When set, `propose_quick_replies` surfaces the pair's prompt
 * instead of the LLM's natural follow-up question. Cleared
 * when the SME selects a quick reply via
 * `clear_disambiguation_on_selection`.
 */
pending_disambiguation?: string, };
