// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputPathHint } from "./InputPathHint";
import type { ProgressSummary } from "./ProgressSummary";
import type { SessionState } from "./SessionState";

/**
 * Snapshot of a session's state machine position and progress counters.
 * Returned by `GET /api/chat/session/:id/state`.
 */
export type SessionStateSnapshot = { 
/**
 * Session identifier.
 */
session_id: string, 
/**
 * Current state-machine state.
 */
state: SessionState, 
/**
 * Whether the SME has clicked the Confirm button.
 */
user_confirmed: boolean, 
/**
 * Timestamp of the most recent activity in this session.
 */
last_activity: string, 
/**
 * Total number of tasks in the emitted DAG; zero before emission.
 */
task_count: number, 
/**
 * Aggregated task-state counts.
 */
progress: ProgressSummary, 
/**
 * Absolute path to the emitted package, once `emit_package` has run.
 * None while the session is still in Intake / ReadyToEmit. Exposed so
 * test harnesses (and, eventually, UI components that link to the
 * package) can read the server-assigned path rather than trying to
 * route an `output_dir` through the LLM's prose — the `emit_package`
 * tool's schema intentionally hides `output_dir`.
 */
emitted_package_path?: string | null, 
/**
 * operator-visible short name, populated by
 * `POST /api/chat/session/:id/auto-title`. Absent until the
 * Haiku-powered side call has fired for this session, or
 * persistently absent when the feature flag is off. The UI title
 * bar renders this when present and falls back to the short
 * session id otherwise.
 */
title: string | null, 
/**
 * parent session linkage when this session was branched
 * from another via `branch_session`. Carries the parent's session
 * id so the Plan tab header can render a "Branch of …" chip +
 * Switch-to-parent link. Null on root sessions.
 */
parent_session_id: string | null, 
/**
 * task ids currently in `blocked` state. Drives the
 * "Needs your input" header chip + deep-link to the first blocked
 * task in the Plan tab. Empty when nothing is blocked.
 */
blocked_tasks: Array<string>, 
/**
 * Filesystem paths the path-hint extractor pulled out of SME
 * intake prose. Drives the UI's "Detected inputs — register?"
 * affordance and is mirrored to the LLM via the
 * `get_session_state` tool. Empty when no validated hints exist
 * (and elided from the JSON when empty so callers that don't
 * know about this field stay happy).
 */
pending_input_hints: Array<InputPathHint>, };
