// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Records this session's parent
 * + when/where the branch was taken.
 */
export type SessionLineage = { 
/**
 * Schema version. `#[serde(default)]` so old session
 * Files (written before the field) deserialize as the
 * canonical SemVer.
 *
 * v3 P7 — promoted from `u32` to `semver::Version`. The
 * `schema_version_serde` adapter accepts both legacy `u64` JSON
 * values and canonical SemVer strings, so pre-P7 lineage records
 * round-trip without migration.
 */
schema_version: string, 
/**
 * Session id of the parent (branched-from) session.
 */
parent_session_id: string, 
/**
 * UTC timestamp when the branch was created.
 */
branched_at: string, 
/**
 * Index into the parent's `conversation` Vec at the moment the
 * branch was taken, so the UI can render where the divergence
 * happened. None when the branch was taken from intake state
 * (no conversation yet).
 */
branched_from_turn_index?: number, 
/**
 * parent's emitted package path at the moment
 * the branch was taken, used by the cross-version diff at child-
 * emit time to locate `results/tables/*.{csv,tsv}`. None when the
 * parent had not yet emitted at branch time.
 */
parent_emitted_package_path?: string, 
/**
 * Task id at whose boundary the branch was taken (M1.3). When set,
 * the child DAG was snapshotted with this task reset to Ready and all
 * its transitive successors reset to Pending. None for session-scoped
 * branches (M1.1 behaviour) and for lineage records written before
 * this field was added (`serde(default)` gives those None).
 */
branched_from_task_id?: string, };
