// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StageMode } from "./StageMode";

/**
 * SessionMode discriminant.
 */
export type SessionMode = { "kind": "exploratory" } | { "kind": "confirmatory", 
/**
 * Prespecified stages.
 */
prespecified_stages: Array<string>, } | { "kind": "hybrid", 
/**
 * Stage modes.
 */
stage_modes: { [key in string]?: StageMode }, };
