// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverrideSource } from "./OverrideSource";

/**
 * One concrete value bound to a named atom parameter.
 */
export type SmeParameterOverride = { 
/**
 * The concrete value the agent must apply verbatim.
 */
value: unknown, 
/**
 * Provenance of this override.
 */
source: OverrideSource, };
