// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A run-time substitution of the data source a task actually read for
 * the one intake requested.
 *
 * This type is BOTH the payload of [`DecisionType::DataSourceDeviation`]
 * and the on-disk contract for the `source_deviation` object an
 * executing agent writes into its task's `result.json` (the
 * RECORD-WHAT-YOU-DID clause carried by ingestion atoms). One
 * definition keeps the agent-facing key shape and the audit-trail
 * shape from drifting apart.
 *
 * Deliberately modality-agnostic: `used_kind` is a free string
 * (`package`, `accession`, `local_path`, `url`, `synthetic`, …) rather
 * than an enum, so any ingestion atom — sequencing, proteomics,
 * imaging, tabular, survey — can name its own substrate class without
 * a core change.
 *
 * Not `#[non_exhaustive]`: the harness constructs this struct with
 * literal syntax from another crate, which `#[non_exhaustive]` forbids.
 * The SemVer surface downstream consumers `match` on is the
 * [`DecisionType`] variant that carries it, not this payload.
 */
export type SourceDeviation = { 
/**
 * The source intake asked for, verbatim — a local path, an
 * accession, a URL, a package name.
 *
 * `#[serde(default)]` (like every other field) so ANY JSON object
 * an agent writes under `result.json::source_deviation` parses
 * into this type. A malformed / half-filled block must reach the
 * harness obligation as an empty-field FAILURE, not vanish behind
 * a deserialization error that reads as "no deviation declared".
 */
requested: string, 
/**
 * Whether the requested source was reachable at execution time.
 * `false` = the substitution was forced (the requested source was
 * absent / unreachable). `true` = the agent swapped a source that
 * WAS available, which is the stronger deviation.
 */
requested_available: boolean, 
/**
 * The source actually read. See `requested` for why this is
 * `#[serde(default)]` rather than mandatory.
 */
used: string, 
/**
 * Class of the source actually read (`package`, `accession`,
 * `local_path`, `url`, `synthetic`, …). Free string on purpose —
 * see the modality-agnostic note above.
 */
used_kind: string, 
/**
 * Version / accession / revision pinning `used`. `None` when the
 * substitute carries no version handle.
 */
used_version?: string, 
/**
 * The agent's justification for the substitution.
 */
reason: string, 
/**
 * Content digests of the materialized inputs, keyed by artifact
 * path or file name. `BTreeMap` so the serialized order is
 * deterministic.
 */
checksums: { [key in string]?: string }, };
