// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassRequirement } from "./ClassRequirement";
import type { RequiredApproval } from "./RequiredApproval";

/**
 * Per-state evidence requirements. Each of the six §18 validation
 * classes has an independent requirement; `required_approvals` adds
 * the credential-class gate the production state needs.
 */
export type StateRequirements = { 
/**
 * Contract.
 */
contract: ClassRequirement, 
/**
 * Golden.
 */
golden: ClassRequirement, 
/**
 * Metamorphic.
 */
metamorphic: ClassRequirement, 
/**
 * Biological invariant.
 */
biological_invariant: ClassRequirement, 
/**
 * Statistical sanity.
 */
statistical_sanity: ClassRequirement, 
/**
 * Reproducibility.
 */
reproducibility: ClassRequirement, 
/**
 * Notes.
 */
notes: string, 
/**
 * Required approvals.
 */
required_approvals: Array<RequiredApproval>, };
