// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityMethodRow } from "./EntityMethodRow";

/**
 * Top-level `stat-distribution.json` payload: the method roster, the
 * per-entity robustness rollup, the class-count histogram, and a pooled
 * consensus single-artifact view shaped exactly like a `ReportData`
 * artifact.
 */
export type StatDistribution = { 
/**
 * Short method names of the variants whose artifact was actually
 * present on disk (sorted; absent variants are skipped).
 */
methods: Array<string>, 
/**
 * One row per entity present in any present method, sorted by entity.
 */
entities: Array<EntityMethodRow>, n_robust: bigint, n_concordant: bigint, n_fragile: bigint, n_discordant: bigint, };
