// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StructuredCaptureField } from "./StructuredCaptureField";

/**
 * Inline structured-capture card the LLM can render when dense input
 * would make the freeform composer awkward. The AWS sizing layer
 * uses this to prompt for
 * sample_count/coverage_depth/cell_count/database_size_gb; captured
 * values flow into `IntakeFacts`.
 */
export type StructuredCaptureTurnCard = { 
/**
 * Card heading shown to the SME.
 */
title: string, 
/**
 * Optional explanatory subtitle shown below the card heading.
 */
description?: string, 
/**
 * Ordered list of fields the SME must fill in.
 */
fields: Array<StructuredCaptureField>, 
/**
 * Preseeded values the card should render as defaults. Optional.
 */
initial_values: Record<string, string>, };
