// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RowDiff } from "./RowDiff";

/**
 * One table's diff. Aggregates per-row classifications, a Pearson
 * correlation, and a Spearman correlation on overlapping effect sizes.
 */
export type TableDiff = { 
/**
 * Table name.
 */
table_name: string, 
/**
 * N rows parent.
 */
n_rows_parent: number, 
/**
 * N rows child.
 */
n_rows_child: number, 
/**
 * N overlap.
 */
n_overlap: number, 
/**
 * N robust.
 */
n_robust: number, 
/**
 * N concordant.
 */
n_concordant: number, 
/**
 * N discordant.
 */
n_discordant: number, 
/**
 * Rows where the entity key is absent from one side after normalization.
 */
n_entity_missing: number, 
/**
 * Rows where the entity is present on both sides but effect-size values
 * are missing or non-numeric.
 */
n_numerics_incomplete: number, 
/**
 * Pearson r.
 */
pearson_r?: number, 
/**
 * Spearman rank correlation of overlapping effect sizes.
 * More robust than Pearson for heavy-tailed biological effect-size
 * distributions (e.g. log2FC with extreme fold-changes).
 */
spearman_rho?: number, 
/**
 * Rows.
 */
rows: Array<RowDiff>, };
