// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParameterSpec } from "./ParameterSpec";

/**
 * Response for `GET .../task/:task_id/parameters`.
 *
 * `Deserialize` is derived alongside `Serialize` so tests can round-trip the
 * response body; the wire contract is serialize-only in production.
 */
export type TaskParametersResponse = { 
/**
 * The task the parameters belong to.
 */
task_id: string, 
/**
 * The atom id that backs this task, if the DAG recorded one.
 */
source_atom_id: string | null, 
/**
 * The atom's declared, typed parameter schema (empty when the atom
 * declares no `parameters:` block or can't be resolved).
 */
parameters: Array<ParameterSpec>, 
/**
 * The SME's currently-set overrides for this task (`name -> value`).
 */
current_overrides: Record<string, unknown>, 
/**
 * The SME-recorded method for this stage, if any.
 */
current_method: string | null, };
