// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Assignee } from "./Assignee";
import type { ContainerSpec } from "./ContainerSpec";
import type { RequiredArtifact } from "./RequiredArtifact";
import type { ResolutionStrategy } from "./ResolutionStrategy";
import type { ResourceClass } from "./ResourceClass";
import type { SafetyPolicy } from "./SafetyPolicy";
import type { TaskId } from "./TaskId";
import type { TaskKind } from "./TaskKind";
import type { TaskState } from "./TaskState";

/**
 * Task data.
 */
export type Task = { 
/**
 * Kind.
 */
kind: TaskKind, 
/**
 * State.
 */
state: TaskState, 
/**
 * Depends on.
 */
depends_on: Array<TaskId>, 
/**
 * Assignee.
 */
assignee: Assignee, 
/**
 * Description.
 */
description: string, 
/**
 * Spec.
 */
spec: unknown | null, 
/**
 * Resolution.
 */
resolution: ResolutionStrategy | null, 
/**
 * Result ref.
 */
result_ref: string | null, 
/**
 * Hardware resource class — drives parallel scheduler slot
 * accounting and the agent's hardware envelope hints.
 * Absent on WORKFLOW.json files emitted before this
 * field was added; deserialization fills in the default
 * (`CpuHeavy`) so pre-existing packages keep working unchanged.
 */
resource_class: ResourceClass, 
/**
 * When true, dispatch pauses on any task whose
 * depends_on chain hits this task until the SME posts
 * `/api/chat/session/:id/confirm { stage: "<task_id>" }`.
 * Serde-default `false` keeps older WORKFLOW.json files
 * readable. Populated from the stage's
 * `requires_sme_review: true` YAML flag at build time.
 */
requires_sme_review: boolean, 
/**
 * Artifacts the agent must produce before the harness considers
 * the task complete. The silent-completion guard verifies each
 * entry exists and is non-empty; absence on an otherwise
 * `Completed` task re-blocks with `BlockerKind::MissingArtifact`.
 * Empty vec = no artifact check.
 */
required_artifacts: Array<RequiredArtifact>, 
/**
 * Per-task container pin resolved at compose /
 * build time. Composer threads the result of
 * `resolve_task_container` (precedence: atom, then archetype,
 * then profile, then package, then host) onto every Task so
 * `WORKFLOW.json` is the reproducibility-bearing source of truth
 * for which image ran each task. `None` = host-mode (legacy /
 * unset). Schema is additive: pre-S15 packages have no container
 * field; serde default gives them `None` and the agent wrappers
 * fall back to `policies/container.json` per the legacy path.
 */
container?: ContainerSpec, 
/**
 * Source atom id this task was emitted from. Allows
 * executors / blocker emitters / claim verifiers to back-reference
 * the originating atom without threading the id through every call.
 * Optional for back-compat with pre-A.S6 WORKFLOW.json files.
 */
source_atom_id: string | null, 
/**
 * Per-task safety classification, threaded through
 * from the source atom at emit time.
 */
safety: SafetyPolicy, };
