// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssumptionRef } from "./AssumptionRef";
import type { Constraint } from "./Constraint";
import type { Deprecation } from "./Deprecation";
import type { EvidenceSet } from "./EvidenceSet";
import type { Implementation } from "./Implementation";
import type { LifecycleState } from "./LifecycleState";
import type { NodeStatus } from "./NodeStatus";
import type { PortContract } from "./PortContract";
import type { Provenance } from "./Provenance";
import type { RiskClass } from "./RiskClass";
import type { SemVer } from "./SemVer";
import type { TrustLevel } from "./TrustLevel";
import type { ValidatorRef } from "./ValidatorRef";

/**
 * A typed task node — the central IR shape. Maps 1:1 to today's
 * atom-but-richer; later phases consume the typed fields without
 * having to migrate atoms one-by-one.
 *
 * Note: derives `PartialEq` but not `Eq` because `PortContract` does
 * not implement `Eq` (the v4 P6 `LocalExtensionMaturity::GraduationCandidate`
 * variant carries an `f32 success_rate`). Callers needing `Eq`
 * semantics compare on `id` instead.
 */
export type TaskNode = { 
/**
 * Stable id within a `WorkflowDag` / registry.
 */
id: string, 
/**
 * Human-friendly name (UI / logs).
 */
human_name: string, 
/**
 * Machine name — short kebab-cased identifier the agent reads
 * (`align_reads`, `quantify_features`).
 */
machine_name: string, 
/**
 * Status (`Active` / `Disabled` / `Quarantined`).
 */
status: NodeStatus, 
/**
 * Free-form description of intent (one line).
 */
intent: string, 
/**
 * Typed input ports.
 */
inputs: Array<PortContract>, 
/**
 * Typed output ports.
 */
outputs: Array<PortContract>, 
/**
 * Preconditions on inputs (CEL or schema). Threaded into the
 * compatibility engine.
 */
preconditions: Array<Constraint>, 
/**
 * Postconditions on outputs.
 */
postconditions: Array<Constraint>, 
/**
 * Assumption ledger references this node depends on.
 */
assumptions: Array<AssumptionRef>, 
/**
 * What this node actually does (container / composite /
 * generated / manual / etc.).
 */
implementation: Implementation, 
/**
 * Validators required to pass before this node is treated as
 * having executed correctly. Cooperates with the existing
 * claim_extractor/claim_verifier.
 */
validators: Array<ValidatorRef>, 
/**
 * Validation/promotion evidence accumulated over time.
 */
evidence: EvidenceSet, 
/**
 * Risk class (drives planner scoring + policy gates).
 */
risk: RiskClass, 
/**
 * Provenance metadata.
 */
provenance: Provenance, 
/**
 * Semver version (mirrors `AtomDefinition.version`).
 */
version: SemVer, 
/**
 * Lifecycle state — drives the promotion gate.
 */
lifecycle_state: LifecycleState, 
/**
 * Trust level — separate axis from lifecycle.
 */
trust_level: TrustLevel, 
/**
 * Optional deprecation notice.
 */
deprecation?: Deprecation, 
/**
 * Free-form attribute map mirroring today's
 * `AtomDefinition.attributes`. Stable for backwards
 * compatibility; entries that graduate to typed facets are
 * retired here.
 */
attributes: Record<string, unknown>, };
