// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Audit record for a single tool call made during a turn.
 */
export type ToolCallRecord = { 
/**
 * Turn this tool call belongs to.
 */
turn_id: string, 
/**
 * Canonical snake_case name of the tool (matches `Tool::name()`).
 */
tool_name: string, 
/**
 * Arguments the LLM passed to the tool.
 */
args: unknown, 
/**
 * Serialized `ToolResult` returned by the dispatcher.
 */
result: unknown, 
/**
 * True when the dispatcher returned a `ToolError`.
 */
is_error: boolean, 
/**
 * Anthropic model id that produced this tool call.
 */
model: string, 
/**
 * UTC timestamp when the tool was dispatched.
 */
timestamp: string, };
