// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Trust level — separate axis from lifecycle. A `Production` node
 * imported from a `LocalRegistry` may still be `Untrusted` until a
 * human signs off.
 */
export type TrustLevel = "unverified" | "static_checked" | "reviewed" | "dual_reviewed";
