// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RiskClass } from "./RiskClass";

/**
 * One uncertainty (SME-stated or LLM-inferred).
 */
export type UncertaintyEntry = { 
/**
 * Field or topic the uncertainty applies to.
 */
topic: string, 
/**
 * Free-text statement.
 */
statement: string, 
/**
 * Best-effort risk classification.
 */
risk: RiskClass, };
