// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * SME-facing explanation style. Renders into LLM tone + UI density.
 */
export type UserExplanationStyle = "domain_friendly" | "technical" | "minimal";
