// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reference to a validator implementation. Resolved by the harness
 * verify endpoint against `claim_extractor` + `claim_verifier` and
 * numeric/structural validators.
 */
export type ValidatorRef = { 
/**
 * Stable validator id (`p_value_in_unit_interval`,
 * `gene_id_in_annotation`, `coordinate_in_contig`).
 */
id: string, 
/**
 * Optional version pin.
 */
version?: string, 
/**
 * Optional inline parameters (e.g. {"max_p": 1.0}). Schema is
 * validator-specific; the composer treats this as opaque.
 */
parameters?: Record<string, unknown>, };
