// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VerifierDiff = { check: string, recorded: unknown, fresh: unknown, diverged: boolean, note?: string, };
