// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Top-level typed parameter (W4). Sourced ONLY from intake facts the SME
 * supplied — organism/genome/sample counts — never a synthesized method.
 */
export type WorkflowParameter = { 
/**
 * Parameter name (e.g. `organism`, `sample_count`, `cell_count`).
 */
name: string, 
/**
 * JSON-schema-ish type tag (`string` / `integer`).
 */
type: string, 
/**
 * The intake value (canonicalized; no timestamps).
 */
value: unknown, 
/**
 * Provenance of the value. Always `"intake"` for now.
 */
source: string, };
