// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Paper §D.2 metadata (W3). All fields deterministic from compiler state.
 */
export type WorkflowMetadata = { 
/**
 * Deterministic bucket from step count: `<5 simple / 5..=15 moderate /
 * >15 complex`. NOT a calibrated metric — purely a size band.
 */
complexity: string, 
/**
 * Sorted+deduped tag set (modality, project class, distinct TaskKind labels).
 */
tags: Array<string>, 
/**
 * `[modality_stratum]` when known, else empty.
 */
categories: Array<string>, 
/**
 * Intake goal-pattern modifiers (sorted keys), e.g. `per-sample`,
 * `with_pathway_enrichment`. Empty when no goal modifiers were captured.
 */
use_cases: Array<string>, };
