// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConditionalEdge } from "./ConditionalEdge";
import type { EdgeContract } from "./EdgeContract";
import type { IterationDeclaration } from "./IterationDeclaration";
import type { ScatterDeclaration } from "./ScatterDeclaration";
import type { TaskNode } from "./TaskNode";

/**
 * Logical workflow template — conditionals, scatter/gather, and
 * bounded iteration are explicit. Lowered to `WorkflowDag` (and
 * ultimately `crates/core/src/dag.rs::DAG`) via
 * `WorkflowJsonEmitter::emit`; see `backend_emitters::mod` for the
 * migration note explaining the `BackendEmitter` trait removal.
 *
 * Today's archetype YAMLs are lowered into this shape by the
 * composer; today's builder lowers a `WorkflowTemplate` into the
 * expanded `DAG` via the existing `condition` / per-sample /
 * `iterate` mechanisms.
 *
 * `Eq` not derived because `IterationDeclaration` carries `f64`.
 */
export type WorkflowTemplate = { 
/**
 * Stable id (e.g. `bulk_rnaseq_de_v4`).
 */
id: string, 
/**
 * Human-readable name.
 */
name: string, 
/**
 * Description.
 */
description?: string, 
/**
 * Typed nodes in topological order. Sorted by `TaskNodeId`
 * for byte-stable serialization.
 */
nodes: Array<TaskNode>, 
/**
 * Edges (compatibility-proof carrying).
 */
edges: Array<EdgeContract>, 
/**
 * Conditional edges — gate node `gate_node_id` runs only when
 * `expression` (CEL) evaluates true given prior task outputs.
 */
conditionals: Array<ConditionalEdge>, 
/**
 * Scatter/gather declarations — node `scatter_node_id`
 * expands per-sample (or per-shard) at lowering time.
 */
scatters: Array<ScatterDeclaration>, 
/**
 * Iterative declarations — node `iterate_node_id` runs in a
 * bounded loop until the convergence metric drops below the
 * declared threshold for the declared consecutive count.
 */
iterations: Array<IterationDeclaration>, };
