// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssumptionLedger } from "./AssumptionLedger";
import type { EdgeContract } from "./EdgeContract";
import type { TaskNode } from "./TaskNode";

/**
 * Lowered DAG with proof-carrying edges + ledger. The lowering
 * pass emits this plus the four sidecars
 * (proofs/assumptions/validation-reports/policy-decisions).
 *
 * `Eq` not derived (`IterationDeclaration` carries `f64`); use
 * stable JSON snapshots in determinism tests instead of
 * `PartialEq` over the struct.
 */
export type WorkflowDag = { 
/**
 * Stable id (matches the originating template).
 */
id: string, 
/**
 * Lowered nodes (post-expansion: per-sample tasks materialized).
 */
nodes: Array<TaskNode>, 
/**
 * Proof-carrying edges.
 */
edges: Array<EdgeContract>, 
/**
 * Assumption ledger.
 */
assumptions: AssumptionLedger, 
/**
 * Source template id, if any. `None` for ad-hoc compositions.
 */
source_template?: string, };
