// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Adapter policy controlling which adapter safety classes may be auto-inserted.
 */
export type AdapterPolicy = { 
/**
 * True when the engine may auto-insert `Lossless` adapters.
 */
allow_lossless: boolean, 
/**
 * True when `LossyDeclared` adapters may be auto-inserted
 * behind an assumption-ledger entry.
 */
allow_lossy_with_assumption: boolean, 
/**
 * True when `ScientificallyRisky` adapters may be inserted
 * (only with explicit SME confirmation).
 */
allow_risky_with_confirmation: boolean, };
