// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdjudicationStatus } from "./AdjudicationStatus";
import type { LifecycleTransition } from "./LifecycleTransition";

/**
 * One entry on the session-scoped adjudication queue. Persisted on
 * `Session::adjudication_queue`; surfaced through
 * `BlockerKind::AdjudicationRequired` and the
 * `LifecycleAdjudicationCard` UI.
 */
export type AdjudicationQueueEntry = { 
/**
 * Stable id (`adj_<12hex>` per session). Used by the
 * `POST /api/chat/session/:id/adjudication/:entry_id/resolve`
 * endpoint and the `BlockerKind::AdjudicationRequired::queue_entry_id`
 * field.
 */
id: string, 
/**
 * ISO-8601 UTC timestamp the entry was queued.
 */
created_at: string, 
/**
 * The lifecycle transition that triggered the queue entry.
 */
transition: LifecycleTransition, 
/**
 * Resolution status. Defaults to `Open` at creation.
 */
status: AdjudicationStatus, };
