// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArchetypeAtomRef } from "./ArchetypeAtomRef";
import type { ComposeRef } from "./ComposeRef";
import type { ContainerSpec } from "./ContainerSpec";
import type { CrossDependency } from "./CrossDependency";
import type { RuntimePrereqs } from "./RuntimePrereqs";
import type { SlotManifest } from "./SlotManifest";

/**
 * One archetype — a named composition of atoms.
 */
export type ArchetypeDefinition = { 
/**
 * Schema-layout version. Validated against
 * [`CURRENT_ARCHETYPE_SCHEMA_VERSION`] at registry-load time.
 * Distinct from [`ArchetypeDefinition::version`] (content
 * semver per [DEC QX.5]).
 */
schema_version: string, 
/**
 * Stable archetype id (e.g. `single_cell_de`,
 * `bulk_rnaseq_disease_vs_healthy`). The composer uses this as
 * the cache key for the matched-archetype fast path.
 */
id: string, 
/**
 * Semver. [DEC QX.5] — bump on additive changes (new optional
 * slot, new atom in the scaffold) so existing sessions don't
 * silently re-route to a refined archetype mid-amendment. The
 * `archetype_snapshot` field on Session pins the version a
 * session committed to (S6.9 Cargo.lock-style pinning).
 */
version: string, 
/**
 * Free-form English description. Used for the `propose_summary
 * _confirmation` card and contributor-facing docs.
 */
description: string, 
/**
 * One-sentence hook used in the SME-facing classifier (per
 * [DEC Q2.4] score-based ranking with 5% tie-surfacing). When
 * the classifier surfaces an archetype tie to the SME, this is
 * the prose the dual-option card renders.
 */
sme_summary: string, 
/**
 * EDAM data class IRI of the GoalSpec this archetype produces
 * (per [GoalSpec §S6.1]). Composer matches a goal's
 * `edam_data` against this field for fast-path lookup before
 * falling through to backward-chaining.
 */
goal_data: string, 
/**
 * Optional EDAM format IRI for the goal's primary committed
 * artifact. When `Some`, the composer narrows fast-path matches
 * to archetypes that produce the exact format.
 */
goal_format?: string, 
/**
 * Atoms the archetype's scaffold uses. Order is the canonical
 * composition order; the composer's deterministic ordering
 * rule preserves it across runs.
 */
atoms: Array<ArchetypeAtomRef>, 
/**
 * Slot mappings: `intake_field` → composer slot reference.
 * Wired through `intake_port_mapper` so the SME-named samples /
 * contrast / organism fields fan into the right atom inputs without
 * per-archetype custom code.
 */
slot_mappings: { [key in string]?: string }, 
/**
 * Optional cross-archetype `compose:` pointers. Used today by
 * `time-series-forecast.yaml`-style derived archetypes that
 * reuse another archetype's scaffold + add a tail of their own
 * atoms.
 */
compose: Array<ComposeRef>, 
/**
 * Optional slot manifest. When set, the archetype is a "base"
 * archetype and atoms `= self.atoms ∪ slot_value.extra_atoms`
 * where slot_value is picked by classifier keyword scan against
 * `slot.values[].keywords`. Loaded from sibling
 * `<archetype_id>.slots.yaml` at registry-load time.
 */
slots?: SlotManifest, 
/**
 * Cross-dependency hints. The atoms field gives the composer
 * the set of nodes; this gives the explicit edges the composer
 * wouldn't infer from `depends_on` alone (e.g. when an
 * aggregator must run after a discovery even though it
 * doesn't consume the discovery's output directly).
 */
cross_dependencies: Array<CrossDependency>, 
/**
 * `claim_boundary` directive carried into the emitted package's
 * interpretation policy. Mirrors the field on `AtomDefinition`
 * but at the archetype level the boundary is the union of every
 * atom's boundary plus the archetype-level addendum.
 */
claim_boundary?: string, 
/**
 * Project class this archetype targets. Constrains classifier-
 * driven matching: a clinical-trial archetype only matches
 * sessions where `project_class == ClinicalTrial`.
 */
project_class: string, 
/**
 * Modality hint to disambiguate goal-shape ties.
 * Multiple archetypes can produce the same `goal_data /
 * goal_format` (e.g. `data:0951 / format:3475` is the goal of
 * `bulk_rnaseq_de`, `long_read_rnaseq`, and
 * `metagenomics_taxonomic` — all 3 score 6 on goal+format+class
 * alone). When the classifier identifies an input modality
 * (`bulk_rnaseq`, `long_read_rnaseq`, `metagenomics`, etc.),
 * `score_archetype` adds +2 for an exact modality match,
 * breaking the tie. Optional: archetypes that genuinely span
 * multiple modalities leave it unset and stay tied (the
 * composer surfaces `TieRequiresSmeDecision` per [DEC Q2.4]).
 */
modality_hint?: string, 
/**
 * Sub-modality disambiguator via the goal pattern's
 * `modifiers.kind` field. When the classifier matched a
 * `goal_pattern` whose `modifiers.kind` matches this hint,
 * `score_archetype` adds +2 — resolves the proteomics DDA-vs-DIA
 * tie where both archetypes share `modality_hint: proteomics` +
 * `goal_data: data:2976` and would otherwise tie at score 8. The
 * DDA archetype declares `goal_kind_hint: proteomics_dda` and the
 * DIA archetype declares `goal_kind_hint: proteomics_dia`; SME prose
 * mentioning "DDA" routes to the DDA goal pattern (kind:
 * proteomics_dda) which lifts proteomics_dda to score 10 and
 * proteomics_dia stays at 8.
 */
goal_kind_hint?: string, 
/**
 * Archetype-level container default. Composer
 * (S15.2) precedence is `atom > archetype > profile > package
 * > host`. Atom-level `preferred_container` wins over this;
 * this wins over `compute-profiles/profiles.yaml` per-stage
 * defaults. `None` = no archetype-level pin (fall through).
 * `clinical_trial` archetypes typically pin a hardened image
 * + `NetworkPolicy::None { allowlist }` per ADR 0028 / D-R14.
 */
preferred_container?: ContainerSpec, 
/**
 * Modality-level baseline of runtime prereqs for derived-image
 * warm-up. Provides `base_image`, `modality`, and the
 * modality-default system + language packages every atom in this
 * archetype implicitly inherits. Composed with each atom's own
 * `runtime_packages` at emit time via
 * `crate::runtime_prereqs::RuntimePrereqs::merge`. Empty default
 * (modality + base_image both `None`) means the modality opts out
 * of the derived-image pipeline and packages emitted from it fall
 * back to the host-mode (or per-task `container.image`) path at
 * runtime.
 */
runtime_baseline: RuntimePrereqs, 
/**
 * Modalities this archetype is authored to span when the SME asks
 * for cross-omics. Empty (default) for single-modality archetypes;
 * ≥2 entries for cross-omics archetypes (e.g.
 * `["bulk_rnaseq", "proteomics"]` for
 * `cross_omics_rnaseq_proteomics.yaml`). The composer's
 * `find_match_cross_omics` reads this set as an order-insensitive
 * match against
 * `ClassificationResult.{modality, additional_modalities}`.
 * Unrelated to `modality_hint`, which is the single-modality
 * disambiguator for goal-shape ties.
 */
cross_omics_modalities: Array<string>, };
