// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AtomId } from "./AtomId";

/**
 * Where an assumption came from.
 */
export type AssumptionSource = { "kind": "sme_accepted", rationale: string, } | { "kind": "llm_inferred", confidence: string, } | { "kind": "lossy_adapter", adapter_node_id: string, } | { "kind": "profiler_degraded", reason: string, } | { "kind": "policy_exception", policy_id: string, } | { "kind": "ontology_mapping_unresolved", type_id: string, } | { "kind": "registry_default", atom_id: AtomId, default_taken: string, } | { "kind": "ontology_adapter_inserted", 
/**
 * From iri.
 */
from_iri: string, 
/**
 * To iri.
 */
to_iri: string, 
/**
 * Reason.
 */
reason: string, } | { "kind": "seed_heuristic", strategy: string, };
