// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PolicyRule } from "./PolicyRule";

/**
 * AssumptionPolicyTable data.
 */
export type AssumptionPolicyTable = { 
/**
 * Version.
 */
version: string, 
/**
 * v3 §10.2 follow-up — `policy_rules:` registry. Keyed by
 * [`PolicyRule::id`] so look-ups are O(log n). Empty when the
 * loaded YAML predates the current schema bump.
 */
rules: { [key in string]?: PolicyRule }, };
