// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PolicyPrivacyClass discriminant.
 */
export type AssumptionPolicyPrivacyClass = "phi" | "controlled_access" | "research" | "public";
