// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Assumption } from "./Assumption";

/**
 * A bag of assumptions. Materialized either inline on a
 * `WorkflowDag` or as a projection over `runtime/decisions.jsonl`.
 */
export type AssumptionLedger = { 
/**
 * Entries.
 */
entries: Array<Assumption>, };
