// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable handle for an atom in the operation × input-type × output-type catalog.
 *
 * `Arc<str>`-backed for cheap clone across the planner's BFS frontier.
 * `Borrow<str>` enables `BTreeMap<AtomId, V>::get("literal")` without
 * an extra allocation.
 */
export type AtomId = string;
