// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-axis scores in [0.0, 5.0].
 */
export type AxisScores = { default_suitability: number, robustness: number, adoption: number, operational_fit: number, 
/**
 * `None` when the specMatch axis has no input source (empty
 * `spec_preferred_methods`). `Some(v)` when the axis was scored —
 * even if `v == 0.0` (candidate is not in the preferred list, but
 * the list itself is non-empty).
 */
spec_match: number | null, };
