// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnsupportedConstraint } from "./UnsupportedConstraint";

/**
 * What semantic constraints from the `WorkflowDag` did the backend
 * emitter fail to represent in the emitted artifact? Returned from
 * every backend's `compile()` method alongside the artifact.
 */
export type BackendCapabilityReport = { 
/**
 * Backend identifier (e.g. `"workflow_json"`, `"cwl"`,
 * `"nextflow"`). Matches the emitter's `name()` method.
 */
backend: string, 
/**
 * Per-constraint losses. Empty when the backend round-trips the
 * full IR shape (today's `workflow_json` case).
 */
losses: Array<UnsupportedConstraint>, };
