// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-cell rollup of one method × interpretive-lens interpretation cell.
 *
 * One cell corresponds to `runtime/outputs/<cell_id>/result.json`, where
 * `cell_id == biological_interpretation__m_<method>__lens_<lens>`. The
 * [`verification`](Self::verification) slot carries the serialized
 * [`ClaimVerificationReport`](crate::claim_verifier::ClaimVerificationReport)
 * when the cell's narrative was cross-checked against its method-variant
 * result table (see [`assemble_ensemble_distribution`]); it is `None` when
 * there was nothing to verify (no embedded interpretation policy, no
 * narrative, or the method-variant table dir was absent).
 */
export type CellRollup = { cell_id: string, 
/**
 * Statistical-method axis parsed from the cell id (empty when the id
 * does not match the canonical `..__m_<method>__lens_<lens>` shape).
 */
method: string, 
/**
 * Interpretive-lens axis parsed from the cell id (empty on a
 * non-matching id).
 */
lens: string, 
/**
 * Hypothesis-support verdict read from the cell's result.json (see
 * [`SUPPORT_KEYS`]); `None` when absent or not coercible to a bool.
 */
support: boolean | null, 
/**
 * Serialized per-cell [`ClaimVerificationReport`](crate::claim_verifier::ClaimVerificationReport):
 * `Some` when the cell's narrative was checked for consistency with its
 * method-variant result table, `None` when nothing was verifiable. A
 * report with `n_mismatch > 0` (`has_mismatch()`) tags the cell as
 * pruned — it is RETAINED here with its verdict but excluded from the
 * ensemble consensus/marginals.
 */
verification: unknown | null, };
