// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaimVerdict } from "./ClaimVerdict";

/**
 * Rollup of every claim in one narrative artifact.
 */
export type ClaimVerificationReport = { 
/**
 * N checked.
 */
n_checked: number, 
/**
 * N verified.
 */
n_verified: number, 
/**
 * N mismatch.
 */
n_mismatch: number, 
/**
 * N unverifiable.
 */
n_unverifiable: number, 
/**
 * Verdicts.
 */
verdicts: Array<ClaimVerdict>, 
/**
 * Dual-channel audit cross-reference.
 * Path (relative to the emitted package root) of the task's
 * agent-runtime decision log, when present. The UI links it from
 * the verification badge so reviewers can cross-check
 * SME-visible `decisions.jsonl` deviations against the runtime
 * decisions the agent recorded while executing the stage. `None`
 * when the agent did not write a runtime log (older packages /
 * non-instrumented agents).
 */
runtime_decision_log_path?: string, };
