// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaimContract } from "./ClaimContract";
import type { Direction } from "./Direction";

/**
 * One extracted narrative claim. Fields beyond `entity` and `excerpt`
 * are optional — if the narrative omits an effect size, the claim
 * still records the direction and the source table reference, and
 * the verifier falls back to verifying only what was provided.
 */
export type Claim = { 
/**
 * The entity name matched by one of the policy's entity patterns.
 */
entity: string, 
/**
 * Direction word captured in the same sentence, if any.
 */
direction?: Direction, 
/**
 * Numeric effect size captured from a log2FC / effect_size mention.
 */
effect_size?: number, 
/**
 * Numeric p-value / FDR captured from the sentence.
 */
pvalue?: number, 
/**
 * Source-table reference captured from a "Table S1" / "(Table 2)"
 * style mention in the sentence. Populated as a free string so
 * the verifier can fuzzy-match against the package's
 * `results/tables/*` index.
 */
source_table?: string, 
/**
 * The sentence the claim originates from, for operator review
 * of mismatches.
 */
excerpt: string, 
/**
 * Contract class assigned by heuristic during extraction. Defaults
 * to `NumericTableLookup` for backwards compatibility with claims
 * serialized before this field was introduced.
 */
contract: ClaimContract, };
