// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Structured cohort descriptor. Both the workflow's validated cohorts
 * and the SME's sample-cohort claim use this type so `covers()` can
 * match them by structural fields.
 */
export type CohortDescriptor = { 
/**
 * Free-text label (e.g. "GIAB Ashkenazi trio", "1000 Genomes EUR").
 */
label: string, 
/**
 * Optional structured population code (NIH MOR taxonomy, OMOP).
 */
population_code?: string, 
/**
 * Age range covered (e.g. "adult", "pediatric", "all").
 */
age_band?: string, 
/**
 * Sample type (e.g. "solid_tumor", "liquid_biopsy", "germline").
 */
sample_type?: string, 
/**
 * Sample size for the cohort.
 */
n?: number, };
