// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How `Significance::threshold` is compared against a row's value in
 * `Significance::column`. `Lt` (e.g. `padj < 0.05`) and `Gt` (e.g. a
 * score `> 0.9`) cover the comparators declared atoms need today;
 * `#[non_exhaustive]` leaves room to add more without a breaking change.
 */
export type Comparator = "lt" | "gt";
