// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Conditional gate on an edge.
 */
export type ConditionalEdge = { 
/**
 * Node id whose execution is conditioned.
 */
gate_node_id: string, 
/**
 * CEL expression. Composer doesn't compile; harness/agent does.
 */
expression: string, 
/**
 * Optional human rationale.
 */
rationale?: string, };
