// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ConstraintSeverity discriminant.
 */
export type ConstraintSeverity = "hard" | "soft" | "warn";
