// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConstraintSeverity } from "./ConstraintSeverity";

/**
 * A typed constraint attached to a port (precondition or
 * postcondition). CEL or schema constraints are recorded here and
 * evaluated by the compatibility engine and harness at dispatch.
 */
export type Constraint = { 
/**
 * Stable id within the constraint set (so proofs can reference
 * "constraint X satisfied").
 */
id: string, 
/**
 * Human-readable statement.
 */
statement: string, 
/**
 * CEL or schema expression. The composer doesn't compile this;
 * the harness/agent does at dispatch.
 */
expression?: string, 
/**
 * Severity bucket. `Hard` constraints reject incompatible
 * edges; `Soft` ones produce a warning + assumption-ledger
 * entry.
 */
severity: ConstraintSeverity, };
