// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * SME-authored authorization for a single class of
 * `UnsupportedConstraint`. `constraint_kind` matches the snake-case
 * variant tag from `UnsupportedConstraint`; one ack authorizes
 * every loss of the matching kind on the same emit.
 */
export type ConstraintLossAck = { 
/**
 * Matches an `UnsupportedConstraint` variant tag (snake_case).
 */
constraint_kind: string, 
/**
 * Free-text justification the SME provided.
 */
rationale: string, 
/**
 * Authorizing party (SME initials, oncall, etc.).
 */
authorized_by: string, };
