// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerSource } from "./ContainerSource";
import type { NetworkPolicy } from "./NetworkPolicy";

/**
 * Per-atom container pin. Composer threads
 * this through to `Task::container` so `WORKFLOW.json` is the
 * reproducibility-bearing source of truth for which image ran each
 * task. Image-digest resolution happens at emit time per ADR 0025.
 */
export type ContainerSpec = { 
/**
 * Image reference (e.g. `ghcr.io/scripps/scripps-bio-base`).
 */
image: string, 
/**
 * Tag (semver-like). Pinned to a specific release; composer
 * resolves `:latest` style refs to a digest at emit time.
 */
tag: string, 
/**
 * SHA-256 digest, populated at emit time per ADR 0025. v1
 * schema accepts an empty string here when the atom YAML
 * declares only image + tag; the emitter rewrites it.
 */
digest: string, 
/**
 * Architecture allowlist. Default `["amd64"]` per plan §3.6
 * non-goal #22 ("Not building cross-arch images by default").
 */
arch: Array<string>, 
/**
 * True when the image needs GPU passthrough (`--nv` /
 * `--gpus=all`). Cross-checks with `resource_profile.gpu`.
 */
gpu_required: boolean, 
/**
 * Typed network policy. `Bridge` = inherit harness default +
 * harness's own bridge interface; `None { allowlist }` =
 * `--network=none` plus iptables / apptainer network-args
 * resolving the allowlist hostnames at task launch (DNS rotation
 * safety). Default `None` = inherit (atom YAML left the field
 * unset).
 *
 * Deprecated: the canonical location is
 * `AtomDefinition.safety.network`. The field is retained on
 * `ContainerSpec` for back-compat YAML deserialization + the
 * `ContainerNetworkOverride` lint; new atoms must declare
 * network policy under `safety.network` only.
 */
network?: NetworkPolicy, 
/**
 * Image source. `Image` = pull from registry directly using
 * `image:tag`; `Conda` = on-demand build via Wave/Seqera
 * resolver materializing per-tool images from conda-lock;
 * `Host` = run on the bare host (no container). Default
 * `Image` for back-compat with atoms whose YAML only declared
 * `image` + `tag`.
 */
source: ContainerSource, };
