// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TableDiff } from "./TableDiff";

/**
 * Whole-package cross-version report. Written to
 * `runtime/cross-version-diff.json` in the child package.
 */
export type CrossVersionReport = { 
/**
 * Parent package.
 */
parent_package: string, 
/**
 * Child package.
 */
child_package: string, 
/**
 * Tables.
 */
tables: Array<TableDiff>, 
/**
 * Fraction of overlapping classified rows (Robust | Concordant) over
 * total overlapping classified rows. 0.0 when no overlap.
 */
overall_concordance: number, 
/**
 * Describes how this diff was anchored: `"package-pair"` (default,
 * compares entire packages) or `"task-pair"` (anchored to a specific
 * task boundary, set when the child session branched from a named task
 * via `branched_from_task_id`). Backward-compatible: absent on reports
 * written before this field was added; `serde(default)` fills in
 * `"package-pair"`.
 */
anchor_kind: string, 
/**
 * The task id used as the diff anchor when `anchor_kind == "task-pair"`.
 * `None` for `"package-pair"` diffs and for older reports that predate
 * this field.
 */
anchored_task_id?: string, };
