// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Task } from "./Task";
import type { TaskId } from "./TaskId";

/**
 * DAG data.
 */
export type DAG = { 
/**
 * Version.
 */
version: string, 
/**
 * Workflow id.
 */
workflow_id: string, 
/**
 * Current task.
 */
current_task: TaskId | null, 
/**
 * Tasks.
 */
tasks: { [key in TaskId]?: Task }, 
/**
 * Stable package-level run id (UUID v4) assigned at emit time.
 * Written to `WORKFLOW.json::meta.run_id` and to the RO-Crate root
 * Dataset's `additionalProperty` list so downstream consumers can
 * correlate a package's artifacts without path-chasing. Absent on
 * packages emitted before this field was added; `#[serde(default)]`
 * gives them `None` so they load unchanged. Never mutated after
 * first emission — re-emission of an amendment retains the parent's
 * `run_id` so the lineage chain is traceable by id.
 */
run_id?: string, };
