// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChainOfCustody } from "./ChainOfCustody";
import type { DecisionActor } from "./DecisionActor";
import type { DecisionType } from "./DecisionType";

/**
 * One audit-trail entry. Append-only; the emitter writes these into
 * `runtime/decisions.jsonl` one record per line.
 */
export type DecisionRecord = { 
/**
 * ISO-8601 UTC timestamp when the decision fired.
 */
timestamp: string, 
/**
 * The session the decision was recorded against. For branch
 * decisions this is the *parent*; the child session's own log
 * starts fresh.
 */
session_id: string, 
/**
 * Decision.
 */
decision: DecisionType, 
/**
 * Free-form SME-supplied justification. Optional — the LLM-driven
 * paths (`emit_package`, `amend_stage_method`) do not always carry
 * one.
 */
rationale?: string, 
/**
 * Actor.
 */
actor: DecisionActor, 
/**
 * Chain-of-custody for the record when its payload
 * carries suppressed content. `None` for ordinary records.
 * Older records without the field deserialize cleanly.
 */
chain_of_custody?: ChainOfCustody, 
/**
 * Closes the security-remediation gap "no audit logging of SME
 * action provenance."
 * Best-effort capture of the client IP that originated the
 * decision, populated from the request's `X-Forwarded-For`
 * header (when present and the operator's reverse proxy is
 * trusted) or the per-connection `ConnectInfo<SocketAddr>`
 * extension. `None` when the call site has not yet been wired
 * to extract a request address (LLM-side tool dispatch,
 * harness-side decision recording, scripted offline tests).
 * The audit deliverable is that the field is AVAILABLE in the
 * type; downstream call sites can backfill the value
 * incrementally without breaking the on-disk JSONL format —
 * the `#[serde(default, skip_serializing_if = "Option::is_none")]`
 * guard keeps every legacy record round-trippable.
 */
source_ip?: string, };
