// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One desired output as the SME stated it.
 */
export type DesiredOutput = { 
/**
 * Free-text label (`"differential expression table"`).
 */
label: string, 
/**
 * Optional EDAM data IRI typing the deliverable.
 */
edam_data?: string, 
/**
 * Optional EDAM format IRI.
 */
edam_format?: string, 
/**
 * True when the output must be human-readable (figure, report)
 * rather than machine-readable.
 */
human_readable: boolean, };
