// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What to do when a pattern fires.
 *
 * Precedence (higher value wins): `Refuse` (2) > `Quarantine` (1) >
 * `Annotate` (0). Used by `IngestionSafetyReport::overall_action`.
 */
export type DetectionAction = "quarantine" | "refuse" | "annotate";
