// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle status of a disposition on disk. Written back by the
 * server after apply / reject. `partial` means apply started, one or
 * more actions succeeded, and then one failed — the applied ones are
 * not rolled back (the server never reverts executed mutations) and
 * the card stays expanded with per-action retry affordance.
 */
export type DispositionStatus = "pending" | "applied" | "rejected" | "partial";
