// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A duplicate candidate surfaced by `detect_duplicates`. `jaccard`
 * is the similarity score against the input being minted.
 */
export type DuplicateCandidate = { 
/**
 * Stable id of the existing extension.
 */
iri: string, 
/**
 * Human label of the existing extension.
 */
label: string, 
/**
 * Jaccard similarity to the input being minted (0.0–1.0).
 */
jaccard: number, };
