// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DuplicateCandidate } from "./DuplicateCandidate";

/**
 * Result of running duplicate detection. `near_duplicates` >=
 * `jaccard_near_duplicate_threshold` (typically auto-merge candidates
 * requiring SME confirmation); `candidate_matches` >=
 * `jaccard_candidate_match_threshold` (worth surfacing in the UI but
 * not auto-merging).
 */
export type DuplicateDetectionResult = { near_duplicates: Array<DuplicateCandidate>, candidate_matches: Array<DuplicateCandidate>, };
