// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RubricAxis } from "./RubricAxis";

/**
 * The system's self-located ED/CF coordinates. Informational / warn-only —
 * it locates, it does not validate.
 */
export type EdCfSelfAssessment = { 
/**
 * Schema version of this sidecar shape.
 */
schema_version: string, 
/**
 * Extensibility Dimension — how many extension mechanisms are present.
 */
extensibility: RubricAxis, 
/**
 * Counterfactual Floor — how strict the gates that prevent unsafe
 * emission/execution are.
 */
counterfactual_floor: RubricAxis, 
/**
 * Explicit disclaimer surfaced in the UI + report.
 */
disclaimer: string, };
