// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChainOfCustody } from "./ChainOfCustody";
import type { CompatibilityProof } from "./CompatibilityProof";
import type { EdgeKind } from "./EdgeKind";

/**
 * One edge in a `WorkflowDag`. Connects a producer port to a
 * consumer port and carries the compatibility proof or report
 * explaining why the edge exists.
 */
export type EdgeContract = { 
/**
 * Producer task node id.
 */
from_node: string, 
/**
 * Producer port name (must be a member of the producer's
 * `outputs`).
 */
from_port: string, 
/**
 * Consumer task node id.
 */
to_node: string, 
/**
 * Consumer port name (must be a member of the consumer's
 * `inputs`).
 */
to_port: string, 
/**
 * Compatibility proof. Carried inline so consumers don't need
 * a side lookup to render "why this edge exists."
 */
proof: CompatibilityProof, 
/**
 * Typed edge classification. Defaults to [`EdgeKind::Unproven`] so
 * legacy proofs.jsonl rows (and any edge constructed before this
 * field existed) deserialize to the strictest failing case.
 */
kind: EdgeKind, 
/**
 * Chain-of-custody for the edge when one or both
 * endpoints carry suppressed content. `None` for ordinary
 * non-suppressed edges. Older records without the field
 * deserialize cleanly.
 */
chain_of_custody?: ChainOfCustody, 
/**
 * When set, this edge is one member of a mutually-exclusive one-of
 * input group named here; sibling members are alternatives resolved
 * to a single authoritative edge by observed-provenance (Phase 2).
 */
mutually_exclusive_group?: string, };
