// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CellRollup } from "./CellRollup";
import type { FactorialAttribution } from "./FactorialAttribution";
import type { LitFinding } from "./LitFinding";

/**
 * Top-level `ensemble-distribution.json` payload: the per-cell rollups,
 * the ensemble-wide agreement fraction, the factorial attribution, the
 * deduplicated literature union across the cells, its coverage, and the
 * fixed consensus label.
 */
export type EnsembleDistribution = { 
/**
 * One rollup per cell whose result.json was present on disk (sorted by
 * cell id; absent cells are skipped).
 */
cells: Array<CellRollup>, 
/**
 * Fraction of the SURVIVING (non-pruned) support-bearing cells that
 * agree with the majority support verdict (1.0 when ≤1 such cell; 0.0
 * when none).
 */
agreement: number, 
/**
 * Count of cells excluded from the consensus because their per-cell
 * verification carried a `Mismatch` (a narrative inconsistent with its
 * method-variant result table). Pruned cells are RETAINED in `cells`
 * with their verdict attached; they simply do not vote.
 */
n_pruned: bigint, attribution: FactorialAttribution, 
/**
 * PMID-deduplicated union of any [`LitFinding`]s surfaced across the
 * cells' result.jsons (sorted-cell, then in-cell order).
 */
literature_union: Array<LitFinding>, 
/**
 * Unique PMID count across `literature_union`.
 */
coverage: bigint, 
/**
 * Always `"model agreement across N cells — not verified truth"`, where
 * N is the number of cells carrying a support verdict.
 */
consensus_label: string, };
