// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * EscalationPath discriminant.
 */
export type EscalationPath = "escalate_to_sme" | "escalate_block";
