// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValidatorRef } from "./ValidatorRef";

/**
 * Validation/promotion evidence attached to a `TaskNode`.
 */
export type EvidenceSet = { 
/**
 * Validator runs that have already passed for this node.
 */
passed_validators: Array<ValidatorRef>, 
/**
 * Benchmarks completed (required for `BenchmarkValidatedNode` promotion).
 */
benchmarks: Array<string>, 
/**
 * Citations and reference data versions.
 */
citations: Array<string>, 
/**
 * Free-form notes for human review.
 */
notes?: string, };
