// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Requirement } from "./Requirement";

/**
 * One expected claim the package should produce a verified result for.
 */
export type ExpectedClaim = { 
/**
 * The expected entity / subject (gene symbol, endpoint code, or a
 * stage-level subject token when no specific entity is named).
 */
entity: string, 
/**
 * The contrast / comparison the claim is about, when the intake
 * names one (e.g. "treated_vs_control"). `None` for cohort- or
 * output-level expectations.
 */
contrast?: string, 
/**
 * The result table the confirmatory stage is expected to write,
 * used by the verifier to disambiguate twin candidate tables.
 * `None` when the stage's output table cannot be named at emit time.
 */
expected_output_table?: string, 
/**
 * Required vs Optional.
 */
requirement: Requirement, 
/**
 * EDAM data IRI typing the expected output, when known.
 */
edam_data?: string, };
