// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExpectedClaim } from "./ExpectedClaim";

/**
 * Deterministic manifest of expected claims for a package. Serialized
 * into `policies/interpretation-policy.json` under
 * `verifiableEntities.expected` (an additive promotion of the existing
 * block, not a new subgraph).
 */
export type ExpectedClaimManifest = { 
/**
 * On-disk shape version of the `expected` block.
 */
schema_version: string, 
/**
 * Expected entries, deterministically ordered.
 */
entries: Array<ExpectedClaim>, };
