// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FacetMatchKind } from "./FacetMatchKind";

/**
 * Per-facet match decision in a `CompatibilityProof`. Stable shape
 * so UI rendering is consistent across facets.
 */
export type FacetMatch = { 
/**
 * Facet name (`genome_build`, `organism`, `modality`, etc.).
 */
facet: string, 
/**
 * Producer's value (free-form because facet types are
 * heterogeneous).
 */
producer: string, 
/**
 * Consumer's value.
 */
consumer: string, 
/**
 * `Exact` / `Subtype` / `Substituted` / `Unknown`.
 */
kind: FacetMatchKind, 
/**
 * Optional rationale (e.g. "GRCh37 → GRCh38 via UCSC
 * liftover").
 */
rationale?: string, };
