// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Free-form facet value. Used for extensibility: new facets can be
 * added without schema bumps. Recommended convention is to graduate
 * stable facets to typed first-class fields once they prove
 * load-bearing.
 */
export type FacetValue = boolean | bigint | string | string | Array<string>;
