// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FigureClassification } from "./FigureClassification";

export type FigureDiffEntry = { stage_id: string, figure_id: string, classification: FigureClassification, 
/**
 * SHA-256 of the parent PNG; None when the figure is NewInChild
 * or the parent's PNG is absent.
 */
parent_png_sha?: string, 
/**
 * SHA-256 of the child PNG; None when the figure is DroppedInParent
 * or the child's PNG is absent.
 */
child_png_sha?: string, 
/**
 * SHA-256 of the parent PDF, if produced.
 */
parent_pdf_sha?: string, 
/**
 * SHA-256 of the child PDF, if produced.
 */
child_pdf_sha?: string, };
