// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FigureDiffEntry } from "./FigureDiffEntry";

export type FigureDiffReport = { parent_package: string, child_package: string, n_identical: number, n_drifted: number, n_new_in_child: number, n_dropped_in_parent: number, entries: Array<FigureDiffEntry>, };
