// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FigureClassification = "identical" | "drifted" | "new_in_child" | "dropped_in_parent";
