// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Explicit figure-obligation lint exemption. When present on an
 * `AtomDefinition`, the lint skips the atom rather than flagging it
 * as a violation. Use only for atoms that genuinely cannot or should
 * not produce user-facing figures:
 *
 * - `category: "adapter"` — sort/index/compression adapters that
 *   transform a format without producing a new data product.
 * - `category: "intermediate"` — atoms whose output is immediately
 *   consumed by a downstream compute stage; the downstream stage
 *   carries the figure obligation.
 * - `category: "non_plottable"` — atoms that produce metadata,
 *   manifests, or control signals (e.g. sample-sheet generators,
 *   schema converters) with no meaningful visual representation.
 *
 * The `reason` field is surfaced in RO-Crate provenance and in
 * the figure-obligation lint report so catalog reviewers can audit
 * exemptions at a glance.
 */
export type FigureExempt = { 
/**
 * Human-readable justification for the exemption. Required.
 */
reason: string, 
/**
 * Optional category — `adapter`, `intermediate`, `non_plottable`.
 */
category?: string, };
