// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coarse-grained classification of an unsatisfied gap. The repair
 * registry routes strategies by matching this discriminator. Strategies
 * then refine via gap.facet_mismatches / structural inspection.
 */
export type GapKind = "missing_producer" | "missing_metadata" | "ambiguous_match" | "version_mismatch" | "reference_mismatch" | "annotation_mismatch" | "contract_gap";
