// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GateName } from "./GateName";

/**
 * One per-gate outcome record. Append-only on
 * [`HypothesizedProposal::gate_outcomes`] so the chat-pane card can
 * render a per-gate timeline.
 */
export type GateOutcome = { 
/**
 * Which gate produced this outcome.
 */
gate: GateName, 
/**
 * True when the gate cleared the proposal; false when it
 * produced refusals / failures.
 */
passed: boolean, 
/**
 * Free-form detail strings (one per refusal kind or obligation
 * id). Stable formatting; sorted by the caller.
 */
details: Array<string>, 
/**
 * Unix-epoch seconds. Set by [`HypothesizedProposal::record_gate`]
 * at the moment the outcome is recorded.
 */
recorded_at: bigint, };
