// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One gene entry inside a contrast bucket. The `rationale` is
 * SME-facing prose explaining why the gene belongs in this bucket
 * (e.g. "Matrix metalloproteinase; canonical cartilage degradation
 * marker").
 */
export type GeneEntry = { 
/**
 * Symbol.
 */
symbol: string, 
/**
 * Rationale.
 */
rationale?: string, };
