// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the SME wants the analysis to produce.
 */
export type GoalSpec = { 
/**
 * EDAM data class IRI naming the goal's primary committed
 * shape. Set by the LLM from the SME's prose ("differential
 * expression results" → `data:0951` / "an annotated
 * AnnData" → `data:3917`).
 */
edam_data: string, 
/**
 * EDAM format IRI for the committed artifact (e.g.
 * `format:3475` for tabular text, `format:3590` for HDF5).
 * Optional — when the SME hasn't named a format, the composer
 * uses `find_producers` with format=None and ranks atoms whose
 * `edam_format` is a subtype of the goal's preferred default.
 */
edam_format?: string, 
/**
 * Free-form modifiers the LLM read from prose. Examples:
 * `{"granularity": "per-sample", "with_pathway_enrichment":
 * "true", "compare_arms": "true"}`. The composer's slot-fill
 * reads these to enable / disable optional atoms in the
 * matched archetype.
 */
modifiers: { [key in string]?: string }, 
/**
 * The original SME prose the LLM read. Carried so
 * the composer can include it in the rationale log when an
 * atom doesn't fit and the SME needs a "why isn't this
 * available?" explanation.
 */
source_prose?: string, 
/**
 * LLM confidence in the extraction (0.0–1.0). Used by the
 * classifier-tightening path (D-R3) to gate fast-path
 * archetype matching: when confidence is below the
 * configured threshold, the composer falls through to the
 * SME-facing tie-surfacing card.
 */
confidence: number, };
