// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Atom-registry governance lifecycle status (G4). Answers who may
 * publish/review/retire an atom. The only load-bearing rule is "Exec
 * atoms require status: reviewed" (`atom_safety::validate_atom_governance`).
 */
export type GovernanceStatus = "draft" | "reviewed" | "deprecated" | "retired";
