// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GpuTarget data.
 */
export type GpuTarget = { 
/**
 * Backend-agnostic GPU class (e.g. "nvidia-a10",
 * "nvidia-a100", "nvidia-t4"). Backends map to their own
 * instance/partition surface.
 */
kind: string, 
/**
 * Count.
 */
count: number, };
