// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GateOutcome } from "./GateOutcome";
import type { ProposalId } from "./ProposalId";
import type { ProposalLifecycle } from "./ProposalLifecycle";

/**
 * The typed proposal record. Persisted on
 * `Session::proposals: BTreeMap<ProposalId, HypothesizedProposal>`
 * in the conversation crate.
 */
export type HypothesizedProposal = { 
/**
 * Stable id (`proposal-<12 hex>`).
 */
id: ProposalId, 
/**
 * Snake_case identifier for the proposed node (e.g. `doublet_score`).
 */
node_id: string, 
/**
 * One-sentence SME intent (what this node should do).
 */
intent: string, 
/**
 * Parent ontology terms the LLM proposed for compatibility
 * subsumption (EDAM or `swfc:<slug>`). Drives the synthesized
 * output port's semantic type.
 */
parent_terms: Array<string>, 
/**
 * LLM-summarized assumptions the proposal relies on. Surfaces
 * in the card; not gate-blocking.
 */
assumptions: Array<string>, 
/**
 * LLM-enumerated failure modes the validators are meant to
 * catch. Surfaces in the card; not gate-blocking.
 */
failure_modes: Array<string>, 
/**
 * Validation obligation ids the SME / LLM has declared apply to
 * this node. The validator gate runs these against the transient
 * TaskNode.
 */
validation_tests: Array<string>, 
/**
 * Atom-ids the proposed node depends on. When promoted these
 * become the new node's `depends_on` so the lowered DAG has at
 * least one upstream edge; without them the promoted node would
 * render as an orphan with no input data.
 */
upstream_atom_ids: Array<string>, 
/**
 * LLM's free-text rationale (from prior chat turns).
 */
llm_rationale: string, 
/**
 * Current lifecycle state.
 */
lifecycle: ProposalLifecycle, 
/**
 * Append-only gate-outcome timeline.
 */
gate_outcomes: Array<GateOutcome>, 
/**
 * Unix-epoch seconds — proposal creation timestamp.
 */
created_at: bigint, 
/**
 * Unix-epoch seconds — last lifecycle transition or
 * `record_gate` call.
 */
last_transition_at: bigint, };
