// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OciImageRef } from "./OciImageRef";
import type { RegistryRef } from "./RegistryRef";
import type { ReviewStatus } from "./ReviewStatus";

/**
 * What a node actually does. Design §7 — all seven variants. The
 * composer treats these uniformly for graph-correctness purposes;
 * the harness/agent dispatches per variant.
 */
export type Implementation = { "kind": "existing_workflow", registry_ref: RegistryRef, } | { "kind": "container_command", 
/**
 * Image.
 */
image: OciImageRef, 
/**
 * Argv-style command template. Tokens like `${input.bam}`
 * are resolved by the agent at dispatch.
 */
command_template: Array<string>, } | { "kind": "composite_dag", subgraph_id: string, } | { "kind": "wasm_plugin", module_ref: string, } | { "kind": "generated_code", 
/**
 * Repository ref.
 */
repository_ref: string, 
/**
 * Review status.
 */
review_status: ReviewStatus, 
/**
 * Artifact digest (sha256) for byte-pinning.
 */
artifact_digest?: string, } | { "kind": "manual_protocol", sop_ref: string, } | { "kind": "unimplemented" };
