// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LifecycleState } from "./LifecycleState";
import type { TrustLevel } from "./TrustLevel";

/**
 * Why a node is ineligible for a target lifecycle state.
 */
export type IneligibleReason = { "kind": "invalid_transition", 
/**
 * From.
 */
from: LifecycleState, 
/**
 * To.
 */
to: LifecycleState, } | { "kind": "no_local_validators" } | { "kind": "no_benchmarks" } | { "kind": "container_digest_missing" } | { "kind": "insufficient_trust", 
/**
 * Required.
 */
required: TrustLevel, 
/**
 * Current.
 */
current: TrustLevel, } | { "kind": "dual_review_required" } | { "kind": "generated_code_unreviewed" } | { "kind": "node_is_deprecated" } | { "kind": "implementation_missing" };
