// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DetectionAction } from "./DetectionAction";
import type { InjectionDetection } from "./InjectionDetection";

/**
 * Result of scanning a single import's metadata against the catalog.
 *
 * Field order: `source_id` first so downstream filters / `jq` queries
 * have a stable key. `detections` is BTreeMap-equivalent order
 * (catalog order); `overall_action` is the precedence-max.
 */
export type IngestionSafetyReport = { 
/**
 * Caller-supplied stable id (e.g. registry kind + entry id).
 */
source_id: string, 
/**
 * Every match across the metadata. Ordered by catalog order.
 */
detections: Array<InjectionDetection>, 
/**
 * Precedence-max of per-detection actions. Refuse > Quarantine >
 * Annotate. `Annotate` for zero detections.
 */
overall_action: DetectionAction, };
