// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DetectionAction } from "./DetectionAction";
import type { PatternCategory } from "./PatternCategory";
import type { PatternSeverity } from "./PatternSeverity";

/**
 * One pattern-firing record.
 */
export type InjectionDetection = { 
/**
 * Catalog `id` (kebab-case).
 */
pattern_id: string, 
/**
 * Catalog `category`.
 */
category: PatternCategory, 
/**
 * Catalog `severity`.
 */
severity: PatternSeverity, 
/**
 * Which metadata key triggered (e.g. `description`, `label`).
 */
field: string, 
/**
 * First 200 chars around the match (50 before, 50 after). Used
 * in UI surfaces + operator runbook output.
 */
match_excerpt: string, 
/**
 * Action this detection contributes to the `overall_action`
 * projection.
 */
action: DetectionAction, };
