// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InjectionPattern } from "./InjectionPattern";

/**
 * The deserialized YAML envelope. One per `config/ingestion-safety/
 * injection-patterns.yaml` file.
 */
export type InjectionPatternCatalog = { 
/**
 * Semver-shaped catalog version (asserted by schema).
 */
version: string, 
/**
 * Ordered list of patterns. Order is preserved across load/save
 * for determinism in `IngestionSafetyReport` ordering.
 */
patterns: Array<InjectionPattern>, };
