// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputGroupKind } from "./InputGroupKind";

/**
 * A constraint grouping several input ports. `OneOf` means the atom is
 * satisfied when at least `min_bound` members bind to a compatible
 * producer; unbound members are legitimate unused alternatives, not gaps.
 * Used to model method-conditioned substrate choice (e.g. a DE count input
 * that is raw for count-GLM tools and normalized for rank tools) WITHOUT
 * the compiler selecting the method.
 */
export type InputGroup = { 
/**
 * Group name, unique within the atom (e.g. `counts`).
 */
name: string, 
/**
 * Constraint kind governing how `members` are evaluated.
 */
kind: InputGroupKind, 
/**
 * Port names (or dependency atom ids) that are members of this
 * group.
 */
members: Array<string>, 
/**
 * Minimum number of members that must bind for the group to be
 * satisfied. Defaults to `1`.
 */
min_bound: number, };
