// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * IterateConvergenceOp discriminant.
 */
export type IterateConvergenceOp = "lt" | "lt_eq" | "gt" | "gt_eq";
