// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Multi-modal joint-source constraint between two
 * upstream dependencies of an atom. The composer's post-validation
 * asserts both `lhs` and `rhs` producers carry an
 * `attributes.source_atom` field with the same value. Used by
 * integration atoms (scRNA-seq + CITE-seq from the same sample,
 * bulk RNA-seq + ATAC-seq from the same arm) to prevent pairing
 * outputs from different upstream samples / batches.
 *
 * Both `lhs` and `rhs` are atom ids that appear in the atom's
 * `depends_on` list. When the composer cannot identify the
 * producer of either (atom not in registry or absent from the
 * composition), it surfaces a typed `CompositionError` rather
 * than silently dropping the constraint.
 */
export type JointlyWithConstraint = { 
/**
 * First atom id that must share `attributes.source_atom`.
 */
lhs: string, 
/**
 * Second atom id that must share `attributes.source_atom`.
 */
rhs: string, };
