// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reference to a JSON Schema validating the on-disk shape of an
 * artifact. Used for structural validation in addition to the
 * semantic type.
 */
export type JsonSchemaRef = { 
/**
 * Path or URI of the schema.
 */
uri: string, 
/**
 * Optional version pin.
 */
version?: string, };
