// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle state — which trust band a node sits in.
 */
export type LifecycleState = "hypothesized" | "contracted" | "implemented" | "locally_validated" | "benchmark_validated" | "production" | "deprecated";
