// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PolicyRuleId } from "./PolicyRuleId";

/**
 * The six non-monotonic lifecycle edges from v3 §7.
 *
 * `#[serde(tag = "kind", rename_all = "snake_case")]` produces flat
 * JSON shapes like `{"kind":"same_user_contradiction","actor":"alan",
 *...}` so wire consumers can pattern-match on the discriminator
 * without inspecting the payload first.
 */
export type LifecycleTransition = { "kind": "same_user_contradiction", 
/**
 * The actor who authored both records.
 */
actor: string, 
/**
 * The `assumption_id` both records reference.
 */
assumption_id: string, 
/**
 * `DecisionRecord` id of the prior resolution.
 */
prior_record_id: string, 
/**
 * `DecisionRecord` id of the contradicting resolution.
 */
new_record_id: string, } | { "kind": "cross_user_conflict", 
/**
 * First actor.
 */
actor_a: string, 
/**
 * Second actor.
 */
actor_b: string, 
/**
 * The `assumption_id` both actors are arguing over.
 */
assumption_id: string, 
/**
 * `DecisionRecord` ids participating in the conflict.
 */
records: Array<string>, } | { "kind": "upstream_invalidation", 
/**
 * The `assumption_id` whose contract changed.
 */
assumption_id: string, 
/**
 * Short description of what changed under the assumption
 * (e.g. `"affects_nodes: [old] → [new]"`).
 */
invalidating_change: string, 
/**
 * Task node ids the change propagates to.
 */
affected_downstream: Array<string>, } | { "kind": "forbidden_waiver_attempt", 
/**
 * Actor who attempted the waiver.
 */
actor: string, 
/**
 * The `assumption_id` the actor tried to waive.
 */
assumption_id: string, 
/**
 * `(defect_class, privacy_class)` policy-rule id from
 * `AssumptionPolicyTable` (e.g. `"genome_build_mismatch:clinical"`).
 * V3 §10.2 registry-validated when minted via
 * [`PolicyRuleId::new`]; legacy ids round-trip via the
 * permissive deserialization path.
 */
policy_rule_id: PolicyRuleId, } | { "kind": "verifier_unresolvability", 
/**
 * The `assumption_id` the verifier flagged.
 */
assumption_id: string, 
/**
 * Verifier identifier (stage id, task id, validator id).
 */
verifier: string, 
/**
 * Free-text reason from the verifier.
 */
reason: string, } | { "kind": "production_node_revocation", 
/**
 * The `TaskNode` id whose production rating was revoked.
 */
node_id: string, 
/**
 * Stringified `LifecycleState` the node was in before the
 * revocation (typically `"production"`).
 */
prior_state: string, 
/**
 * Free-text reason for the revocation (CVE id, registry
 * yank notice, deprecation citation).
 */
reason: string, 
/**
 * DAG ids that depended on the revoked node.
 */
affected_dags: Array<string>, };
