// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Literature-support evidence attached to a [`ClaimContract::LiteratureGrounded`]
 * claim: the upstream finding the narrative is grounding and the PMIDs the
 * narrative cites for it. The verifier cross-checks these against the
 * `claims_evidence_matrix.csv` row for `finding_id`.
 */
export type LiteratureEvidence = { 
/**
 * Upstream finding id the claim grounds (matches the `finding_id`
 * column of `claims_evidence_matrix.csv`).
 */
finding_id: string, 
/**
 * PMIDs the narrative cites in support, as parsed integers.
 */
cited_pmids: Array<bigint>, };
