// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LitFinding = { entity: string, pmid: string, evidence_quote: string, effect: number | null, };
