// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typed network policy on `ContainerSpec`.
 * `Bridge` inherits the harness network (the catalog default for most
 * archetypes). `None { allowlist }` is the strict default for the
 * clinical_trial archetype: `--network=none` plus a sidecar allowlist
 * of hostnames the entrypoint helper resolves at launch (allowlist
 * hostnames, not pinned IPs, so DNS rotation still works).
 *
 * Note: most archetypes default to `Bridge` (the historical
 * behavior); the clinical_trial-specific `None`-by-default override
 * happens at archetype-load time, not via the `Default` impl. The
 * derived `Default` is here for ergonomic constructors only.
 */
export type NetworkPolicy = { "kind": "bridge" } | { "kind": "none", allowlist: Array<string>, };
