// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of a node — separate from lifecycle. `Active` is the
 * happy path; `Disabled` excludes from planning; `Quarantined`
 * allows draft outcomes only.
 */
export type NodeStatus = "active" | "disabled" | "quarantined";
