// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reference to an OCI image. Mirrors today's `atom::ContainerSpec`
 * shape so atom→TaskNode conversion is information-preserving.
 */
export type OciImageRef = { 
/**
 * Image reference (e.g. `ghcr.io/scripps/scripps-bio-base`).
 */
image: string, 
/**
 * Tag.
 */
tag: string, 
/**
 * SHA-256 digest (`sha256:...`). Empty until digest resolution
 * at emit time per ADR 0025.
 */
digest: string, 
/**
 * Architecture allowlist; defaults to `["amd64"]` in the
 * converter.
 */
arch: Array<string>, 
/**
 * True when image needs GPU passthrough.
 */
gpu: boolean, };
