// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageTier } from "./PackageTier";

/**
 * Which features an imported package supports, decided by physical file
 * presence. `tabs` carries per-tab availability keyed by a stable tab id.
 */
export type PackageCapabilities = { 
/**
 * Cosmetic completeness label. Gating reads the boolean flags, not this.
 */
tier_label: PackageTier, 
/**
 * Package carries the minimum crate substrate needed to explore
 * (`WORKFLOW.json` + `ro-crate-metadata.json`).
 */
explore: boolean, 
/**
 * Audit-proof re-verification can run (crate metadata + audit report).
 */
reverify: boolean, 
/**
 * Replay Tier-1 (integrity) is available (audit report + claim
 * verification present).
 */
replay_tier1: boolean, 
/**
 * Replay Tier-2 (reproduce) is available (execution order + at least one
 * re-executable task surface).
 */
replay_tier2: boolean, 
/**
 * Per-tab availability keyed by a stable tab id.
 */
tabs: { [key in string]?: boolean }, };
