// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Port wiring projected from an edge. Mirrors the edge endpoints but keyed
 * for consumption ("what feeds this step's input").
 */
export type ParameterMapping = { 
/**
 * Producing step id.
 */
source_step: string, 
/**
 * Producing output port.
 */
source_output: string, 
/**
 * Consuming step id.
 */
target_step: string, 
/**
 * Consuming input port.
 */
target_input: string, };
