// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SmeParameterOverride } from "./SmeParameterOverride";

/**
 * Per-task parameter overrides: `task_id -> (param name -> override)`.
 * `BTreeMap` at both levels for byte-deterministic emission.
 */
export type ParameterOverrides = { [key in string]?: { [key in string]?: SmeParameterOverride } };
