// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParameterType } from "./ParameterType";

/**
 * One typed parameter on an atom — the paper-D.1 parameter axis.
 * Schema-validated at registry load (unlike the legacy untyped
 * `attributes` bag). Optional and additive: atoms that declare a
 * `parameters:` block get typed validation; legacy atoms keep
 * `attributes`.
 */
export type ParameterSpec = { 
/**
 * Parameter name (stable key the agent/runtime reads).
 */
name: string, 
/**
 * Declared type. `Enum` means the legal set is `allowed_values`.
 */
type: ParameterType, 
/**
 * Whether the parameter must be supplied. Default false.
 */
required: boolean, 
/**
 * Default value applied when the parameter is omitted.
 */
default?: unknown, 
/**
 * Closed legal value set (load-bearing for `ParameterType::Enum`).
 */
allowed_values: Array<unknown>, 
/**
 * Illustrative example values; never enforced.
 */
examples: Array<unknown>, 
/**
 * Human description; surfaces in CONTEXT.md, never machine-parsed.
 */
description?: string, };
