// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coarse category for UI dispatch. Not load-bearing for the
 * `IngestionSafetyReport.overall_action` projection.
 */
export type PatternCategory = "instruction_injection" | "fake_ontology_term" | "dependency_confusion" | "hidden_html_comment" | "credential" | "url_exfiltration";
