// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One upstream accession with provenance hash.
 *
 * The four fields capture the reproducibility-bearing identity:
 * where the data lives (`repo`), what to ask for (`accession`),
 * when the bytes were anchored (`version_or_date_accessed`), and a
 * content hash so re-fetched bytes can be byte-compared. Per Round-4
 * §22.12, this is the right primitive for our scale — DataLad / DVC
 * / lakeFS are out-of-scope for the compiler.
 */
export type PinnedAccession = { 
/**
 * Repository identifier — `geo`, `sra`, `ena`, `dbgap`,
 * `proteomexchange`, `metabolights`, `zenodo`, `figshare`,
 * `bioproject`, etc. Lower-case slug; the validator accepts an
 * open enumeration (new repos can be added without a code change).
 */
repo: string, 
/**
 * Accession id as known to the repo (e.g. `GSE123456`,
 * `SRX9876543`, `ERP123456`, `phs001234.v1.p1`,
 * `PXD019987`, `MTBLS321`, `10.5281/zenodo.7654321`).
 */
accession: string, 
/**
 * Either a version tag from the upstream repo (e.g. `v1.p1` for
 * dbGaP) or an ISO-8601 date the bytes were anchored on.
 */
version_or_date_accessed: string, 
/**
 * Content hash for byte-equality across re-fetches. Format:
 * `sha256:<hex>` or `md5:<hex>`. None when the upstream repo
 * doesn't publish a stable manifest hash; in that case the
 * SHA-256 is computed locally on first download and pinned.
 */
content_hash?: string, };
