// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One pinned reference bundle.
 *
 * Per Round-4 §22.12 the reproducibility-bearing key is `(assembly,
 * release, hash)`. GRCh39 is "indefinitely postponed" so GRCh38.p14
 * stays current; capturing the patch number is non-optional.
 */
export type PinnedReferenceBundle = { 
/**
 * Genome assembly identifier including patch (e.g.
 * `GRCh38.p14`, `GRCm39`, `Pf3D7v68`). Patch number is part of
 * the identity — bumping the patch is a separate amendment.
 */
assembly: string, 
/**
 * Source release tag (e.g. `Ensembl 115`, `GENCODE 47`,
 * `RefSeq release 224`, `Custom TruSeq Stranded mRNA`). Tells
 * the SME *and* the FAIR consumer which annotation set was
 * pinned alongside the assembly.
 */
release: string, 
/**
 * SHA-256 of the FASTA + GTF tarball, format `sha256:<hex>`.
 * Computed at intake time on the first download; pinned for the
 * session lifetime. Re-emissions verify against this hash.
 */
content_hash: string, };
