// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PlotSafety discriminant.
 */
export type PlotSafety = "validated" | "inheritance_warn" | "generic" | "generated" | "none";
