// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable-discriminator enum so callers can ask "does any
 * bundle require X?" without pattern-matching the full
 * `PolicyCheck`.
 */
export type PolicyCheckKind = "validated_nodes_only" | "require_pinned_containers" | "no_generated_code" | "no_policy_restricted_adapters" | "no_scientifically_risky_adapters" | "no_privacy_widening" | "no_network" | "pinned_reference_data_only" | "human_signoff_required" | "audit_trail_required" | "site_local";
