// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PolicyBundle } from "./PolicyBundle";
import type { PrivacyClass } from "./PrivacyClass";

/**
 * Top-level policy context. Sessions opt in to one or more
 * policy bundles; the composer evaluates every active bundle
 * for each edge.
 */
export type PolicyContext = { 
/**
 * Active policy bundles by id (`clinical_v1`, `phi_strict`,
 * `cfr_part11_v2`).
 */
bundles: { [key in string]?: PolicyBundle }, 
/**
 * Default privacy class applied to data products with no
 * explicit class.
 */
default_privacy_class: PrivacyClass, };
