// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChainOfCustody } from "./ChainOfCustody";

/**
 * Recorded policy decision row, persisted to
 * `runtime/policy-decisions.jsonl` at emit time and surfaced on
 * the Composition UI tab. One entry per (active bundle × node ×
 * failed/recorded check). v1/v2/v3 sessions never produce these;
 * v4 sessions populate them via the per-node policy gate.
 */
export type PolicyDecisionRecord = { 
/**
 * Active policy bundle id (e.g. `clinical_trial`, `phi_strict`).
 */
bundle_id: string, 
/**
 * Policy check kind expressed as the snake_case string the UI
 * renders directly (`require_pinned_containers`,
 * `audit_trail_required`, etc.).
 */
kind: string, 
/**
 * Node id the decision applies to. `None` for bundle-wide
 * recorded decisions (audit-trail / human-signoff).
 */
node_id: string | null, 
/**
 * Human-readable rationale; one short sentence.
 */
statement: string, 
/**
 * `true` for blocking violations (refusal); `false` for
 * recorded informational decisions.
 */
blocking: boolean, 
/**
 * Chain-of-custody for the record when the gated
 * statement contains suppressed content. `None` for ordinary
 * non-suppressed policy decisions. Older records without the
 * field deserialize cleanly.
 */
chain_of_custody?: ChainOfCustody, };
