// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CohortDescriptor } from "./CohortDescriptor";

/**
 * Workflow-level, config-authored statement of which sample cohorts
 * the workflow was validated on.
 *
 * Loaded from `config/population-coverage/<workflow_id>.yaml`.
 */
export type PopulationCoverageStatement = { 
/**
 * Workflow (archetype) id this statement applies to.
 */
workflow_id: string, 
/**
 * Validation cohorts the workflow was evaluated on.
 */
validated_cohorts: Array<CohortDescriptor>, 
/**
 * Populations explicitly outside validation scope. Surfaces in
 * the UI as "the workflow was tested but NOT validated for these
 * cohorts" so the SME can see explicit gaps, not just an absence.
 */
explicitly_untested: Array<CohortDescriptor>, 
/**
 * Cite sources for the validation claim (DOIs or PMIDs). At least
 * one is recommended for clinical-grade workflows.
 */
citations: Array<string>, };
