// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cardinality } from "./Cardinality";
import type { Constraint } from "./Constraint";
import type { FormatRef } from "./FormatRef";
import type { JsonSchemaRef } from "./JsonSchemaRef";
import type { OntologyTermRef } from "./OntologyTermRef";
import type { PortPrivacyClass } from "./PortPrivacyClass";
import type { SemanticType } from "./SemanticType";
import type { ValidatorRef } from "./ValidatorRef";

/**
 * A typed port — input or output of a `TaskNode`. Design §1 + §12.
 *
 * All facet-bearing fields are optional because atoms synthesized from
 * `AtomDefinition.edam_data` / `edam_format` provide only the EDAM
 * pair; richer ports supply genome build, coordinate system, and other
 * biological facets inline.
 *
 * Note: derives `PartialEq` but not `Eq` because `SemanticType` does
 * not implement `Eq` (`LocalExtensionMaturity::GraduationCandidate`
 * carries an `f32 success_rate`). Callers needing `Eq` semantics
 * compare on `name` or `semantic_type.stable_id()` instead.
 */
export type PortContract = { 
/**
 * Port name. Stable within the `TaskNode` (used as the edge
 * endpoint identifier).
 */
name: string, 
/**
 * Semantic type (open-world: ontology term / local extension /
 * opaque).
 */
semantic_type: SemanticType, 
/**
 * Physical file format. `None` for opaque blobs or in-memory
 * values.
 */
physical_format?: FormatRef, 
/**
 * JSON Schema validating the on-disk shape (design §1
 * `schema`).
 */
structural_schema?: JsonSchemaRef, 
/**
 * Additional ontology hits beyond `semantic_type` (design §1
 * `ontology_terms`).
 */
ontology_terms: Array<OntologyTermRef>, 
/**
 * Modality bucket (`bulk_rnaseq`, `single_cell_rnaseq`, etc.).
 */
modality?: string, 
/**
 * Organism (e.g. `Homo sapiens`, `Mus musculus`). Composer
 * blocks edges where producer/consumer organisms diverge.
 */
organism?: string, 
/**
 * Genome build (e.g. `GRCh38.p14`, `GRCm39`). Mismatches are
 * the canonical source of "two BAM files but incompatible"
 * false matches.
 */
genome_build?: string, 
/**
 * Annotation version (e.g. `Ensembl 110`, `GENCODE 44`).
 */
annotation_version?: string, 
/**
 * Coordinate system (e.g. `0-based half-open`, `1-based
 * closed`). VCF vs BED vs GFF clash here.
 */
coordinate_system?: string, 
/**
 * Units (e.g. `TPM`, `CPM`, `raw counts`, `log2 fold change`).
 */
units?: string, 
/**
 * Normalization state (e.g. `raw`, `tpm`, `quantile`,
 * `vsn`). The first source of "matrix shape correct, values
 * wrong" failures.
 */
normalization_state?: string, 
/**
 * Statistical state (e.g. `unprocessed`, `de_tested`,
 * `multiple_testing_corrected`).
 */
statistical_state?: string, 
/**
 * Privacy class.
 */
privacy_class: PortPrivacyClass, 
/**
 * Cardinality (one / optional / many / iterate-until).
 */
cardinality: Cardinality, 
/**
 * Validators that must pass on data flowing through this port.
 * References to validator implementations live in the
 * `EvidenceSet`/`ValidatorRef` registry and are evaluated by
 * the harness verify endpoint.
 */
validators: Array<ValidatorRef>, 
/**
 * Constraints (preconditions/postconditions) on values flowing
 * through this port, evaluated as part of the compatibility proof.
 */
constraints: Array<Constraint>, 
/**
 * Extensible facet map. Stable facets graduate to typed
 * fields above; this map carries the long tail without
 * requiring schema bumps for niche cases.
 */
facets: Record<string, unknown>, };
