// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which side of an edge a `RewriteContract` targets. Inputs are the
 * consumer's required shape; outputs are the producer's promised
 * shape.
 */
export type PortRole = "input" | "output";
