// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Slim per-port EDAM projection surfaced into `WORKFLOW.json`. Carries
 * only the ontology data IRI + physical format IRI from a
 * `PortContract`; the full contract stays in the proof-carrying IR and
 * `runtime/proofs.jsonl`. Additive and presentational — no execution
 * path reads it.
 */
export type PortEdam = { 
/**
 * Port name (stable within the task).
 */
name: string, 
/**
 * EDAM data-class IRI (e.g. `data:3754`). `None` for opaque ports.
 */
edam_data?: string, 
/**
 * EDAM format IRI (e.g. `format:3475`). `None` when unspecified.
 */
edam_format?: string, };
