// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrivacyClass } from "./PrivacyClass";

/**
 * Privacy/regulatory flags block.
 */
export type PrivacyBlock = { 
/**
 * Default privacy class for un-tagged data products.
 */
default_class: PrivacyClass, 
/**
 * True when HIPAA constraints apply.
 */
hipaa: boolean, 
/**
 * True when 21 CFR Part 11 constraints apply.
 */
cfr_part11: boolean, 
/**
 * Free-text other regulatory contexts.
 */
regulatory_context: Array<string>, };
