// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Privacy class for data products — separate from the port-side
 * classification because data carries its own privacy regardless
 * of the consuming port's declared class.
 */
export type PrivacyClass = "public" | "internal" | "sensitive" | "phi" | "restricted";
