// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Authority that promoted a node along its lifecycle.
 */
export type PromotionAuthority = { 
/**
 * Authority kind (`automated_ci`, `human`, `external_registry`).
 */
kind: string, 
/**
 * Authority id (CI run id, human user id, registry name).
 */
id: string, 
/**
 * Promotion timestamp (ISO 8601). May be redacted in exportable
 * provenance when suppression policy applies.
 */
at: string, };
