// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IneligibleReason } from "./IneligibleReason";
import type { LifecycleState } from "./LifecycleState";

/**
 * Result of a promotion check.
 */
export type PromotionDecision = { "kind": "eligible", 
/**
 * From.
 */
from: LifecycleState, 
/**
 * To.
 */
to: LifecycleState, } | { "kind": "blocked", 
/**
 * From.
 */
from: LifecycleState, 
/**
 * To.
 */
to: LifecycleState, 
/**
 * Reasons.
 */
reasons: Array<IneligibleReason>, };
