// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable id for a [`HypothesizedProposal`]. Conventionally formatted
 * as `proposal-<12 hex chars>` but the constructor accepts any
 * non-empty string so test scaffolding + future generators can
 * override.
 */
export type ProposalId = string;
