// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Runtime package-install policy.
 */
export type ProvisioningPolicy = "sealed" | "declared_only" | "allowlisted";
