// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortContract } from "./PortContract";
import type { SafetyPolicy } from "./SafetyPolicy";

/**
 * MCP-shaped published tool descriptor. The typed input/output
 * `PortContract`s are the inter-tool data contract; `SafetyPolicy` is
 * the safety contract; `depends_on` is the inter-tool dependency
 * declaration the paper's MCP extension proposes. Deterministic
 * (BTreeMap-ordered fields via the atom, no timestamps).
 */
export type PublishedToolDescriptor = { 
/**
 * Tool id (== atom id).
 */
id: string, 
/**
 * Semver string.
 */
version: string, 
/**
 * Human description.
 */
description: string, 
/**
 * EDAM operation IRI.
 */
edam_operation: string, 
/**
 * Typed input ports (the data contract).
 */
inputs: Array<PortContract>, 
/**
 * Typed output ports (the data contract).
 */
outputs: Array<PortContract>, 
/**
 * Inter-tool dependency declaration.
 */
depends_on: Array<string>, 
/**
 * Safety contract.
 */
safety: SafetyPolicy, };
