// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The aggregate statistic a [`ClaimContract::QuantileOfColumn`] claim asserts
 * over a column: the median (the 50th-percentile order statistic) or the
 * arithmetic mean. The verifier recomputes the named statistic from the cited
 * column over the claimed row set and compares it within tolerance.
 */
export type QuantileKind = "median" | "mean";
