// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScoringTuple } from "./ScoringTuple";
import type { WorkflowDag } from "./WorkflowDag";

/**
 * One alternative composition produced by the planner. The
 * `score` is what the ranking algorithm produces; UI surfaces
 * `summary` directly.
 *
 * `Eq` not derived because `WorkflowDag` carries `f64`
 * (`IterationDeclaration.threshold`); use stable JSON snapshots
 * for determinism comparisons.
 *
 * `source` records which planner stage
 * produced the alternative. Today's values:
 *
 * - `"archetype"` — `ArchetypeRegistry::find_match` produced a
 *   matching archetype scaffold and the planner lifted it into a
 *   typed DAG.
 * - `"search"` — forward/backward/meet-in-the-middle search
 *   produced a connected (or partially-connected) DAG.
 *
 * New stages may add new strings without breaking serde
 * compatibility (the field defaults to empty string for
 * historical-session compatibility). The UI's
 * `AlternativeDagComparisonCard` is decoupled from this field via
 * its own `AlternativeSummary` projection.
 */
export type RankedAlternative = { 
/**
 * Dag.
 */
dag: WorkflowDag, 
/**
 * Score.
 */
score: ScoringTuple, 
/**
 * Compact human-readable summary ("3-stage pipeline,
 * 2 lossless adapters, GRCh38 throughout").
 */
summary: string, 
/**
 * Which planner stage produced this alternative
 * (`"archetype"` / `"search"` / future stages).
 */
source: string, };
