// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Redaction policy. Site-local installations can extend this to
 * cover additional PHI/secret patterns beyond the minimum set.
 */
export type RedactionPolicy = { 
/**
 * Decision-log fields to clear when emitting at the
 * `RedactedAudit` tier.
 */
redact_at_audit: Array<string>, 
/**
 * Decision-log fields to clear (or fully drop entries) when
 * emitting at the `ExportablePublic` tier.
 */
redact_at_public: Array<string>, };
