// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReexecutionReport } from "./ReexecutionReport";

export type ReexecuteResult = { env_tier: string, report: ReexecutionReport, unprovisionable: boolean, 
/**
 * Whether the recorded per-task BLAS/OpenMP thread budget could be
 * re-injected into the replay container (`"recorded"`) or the replay ran
 * at the REPLAY host's thread count (`"not_recorded"`). An unpinned
 * thread budget changes floating-point reduction order, so this is a
 * disclosure, not a pass/fail.
 */
thread_budget: string, };
