// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cached registry snapshot. Stored on disk under
 * `~/.ecaa-workflow/external-snapshots/<registry>/<id>.json`
 * so determinism tests can replay against a stable bytes set.
 */
export type RegistrySnapshot = { 
/**
 * Stable snapshot id (e.g. `2026-05-08T12:00:00Z`).
 */
snapshot_id: string, 
/**
 * Registry kind.
 */
registry: string, 
/**
 * Entry id.
 */
id: string, 
/**
 * Free-form metadata blob the importer parses.
 */
metadata: Record<string, unknown>, };
