// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reference to an entry in an external registry (bio.tools,
 * Dockstore, GA4GH TRS, etc.). Populated by the external registry
 * importer when `ExistingWorkflow` tasks are dispatched.
 */
export type RegistryRef = { 
/**
 * Registry kind (`bio_tools`, `dockstore`, `workflowhub`,
 * `trs`, `local_cwl`, etc.).
 */
registry: string, 
/**
 * Entry id within the registry.
 */
id: string, 
/**
 * Optional version pin.
 */
version?: string, 
/**
 * Optional URL for human inspection / provenance.
 */
url?: string, };
