// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * RegisteredAffordance data.
 */
export type RegisteredAffordance = { 
/**
 * Semantic type.
 */
semantic_type: string, 
/**
 * Figure ids.
 */
figure_ids: Array<string>, 
/**
 * Renderer module.
 */
renderer_module: string, 
/**
 * Theme version.
 */
theme_version: string, };
