// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemediationKind } from "./RemediationKind";
import type { SuggestionConfidence } from "./SuggestionConfidence";
import type { ToolBinding } from "./ToolBinding";

/**
 * One ranked remediation proposed for a `BlockerKind::ToolError`.
 */
export type RemediationSuggestion = { 
/**
 * Stable id (UUID-short) used by the apply endpoint to
 * dispatch the right action.
 */
id: string, 
/**
 * Kind.
 */
kind: RemediationKind, 
/**
 * LLM-authored prose: why this is likely to fix the observed
 * error. Rendered verbatim under the suggestion header.
 */
rationale: string, 
/**
 * Confidence.
 */
confidence: SuggestionConfidence, 
/**
 * Names of envelope fields that motivated the suggestion
 * (`error_class`, `signal`, `peak_memory_mb`,...). Used by the
 * UI to render evidence chips so the SME can sanity-check.
 */
evidence: Array<string>, 
/**
 * Tool binding.
 */
tool_binding: ToolBinding, 
/**
 * Approximate cost-delta in USD when applying this remediation
 * on a remote backend (instance-type bumps, on-demand swaps).
 * `None` for local + free remediations.
 */
estimated_cost_delta_usd?: number, };
