// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReexecuteResult } from "./ReexecuteResult";
import type { ReplayVerdict } from "./ReplayVerdict";
import type { ReverifyResult } from "./ReverifyResult";
import type { SkippedStage } from "./SkippedStage";

export type ReplayReport = { schema_version: string, package_iri: string, reader_version: string, min_reader_version: string | null, reverify: ReverifyResult | null, reexecute: ReexecuteResult | null, skipped: Array<SkippedStage>, verdict: ReplayVerdict, };
