// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ResolutionPolicy discriminant.
 */
export type ResolutionPolicy = "blocking" | "non_blocking" | "waivable_with_credentials";
