// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EscalationPath } from "./EscalationPath";

/**
 * ResolutionStrategy data.
 */
export type ResolutionStrategy = { 
/**
 * Primary.
 */
primary: string, 
/**
 * Fallback.
 */
fallback: string | null, 
/**
 * Escalation.
 */
escalation: EscalationPath, 
/**
 * Policy ref.
 */
policy_ref: string | null, };
