// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregated resource estimate for a composition. Coarse
 * numeric form so the SME sees ballpark numbers instead of opaque
 * "moderate/large" buckets. Pilot sizing replaces these projections
 * with measured numbers at execution time; this is the pre-approval
 * preview.
 *
 * Bucket → number table (intentionally conservative; tuned to
 * over-estimate slightly so the SME isn't surprised):
 * - `cpu`: light → 2, moderate → 8, heavy → 32, very_heavy → 64 cores
 * - `memory`: small → 4, medium → 16, large → 64, xl → 256 GB
 * - `runtime_class`: seconds → 0.01, minutes → 0.5, hours → 4 hr
 */
export type ResourceEstimate = { 
/**
 * Sum of per-atom `memory` bucket midpoints, in GB.
 */
total_memory_gb: number, 
/**
 * Largest single-atom `memory` bucket midpoint, in GB. Bounds
 * the worst-case instance footprint.
 */
peak_memory_gb: number, 
/**
 * Sum across atoms of `cpu_cores × runtime_hours`. Coarse
 * rollup; the SME-facing card renders this as "≈ N core-hours".
 */
total_core_hours: number, 
/**
 * Count of atoms whose `resource_profile.gpu` is true.
 */
gpu_task_count: number, 
/**
 * Optional dollar projection — left `None` here (pilot's
 * `estimate_cost_usd` populates it when SWFC_PILOT_ENABLED=1
 * surfaces the per-atom cost rate).
 */
estimated_cost_usd?: number, };
