// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-task hardware resource class. The parallel scheduler uses
 * this to decide whether a task draws against the CPU semaphore or the
 * GPU semaphore; the agent envelope uses it to compute
 * `concurrent_peers_by_class`. The enum is intentionally closed — new
 * variants require a scheduler policy decision, not just a schema
 * change.
 */
export type ResourceClass = "cpu_heavy" | "io_heavy" | "memory_heavy" | "gpu";
