// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Risk class — drives planner scoring and policy gates. Aligned
 * with design §3 + §15 risk language.
 */
export type RiskClass = "negligible" | "low" | "moderate" | "high" | "clinical";
