// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One rubric axis with a 0.0–1.0 score and the human-readable mechanisms
 * that produced it.
 */
export type RubricAxis = { 
/**
 * Score in [0.0, 1.0], deterministically derived.
 */
score: number, 
/**
 * Mechanisms counted toward this score (sorted, human-readable).
 */
mechanisms: Array<string>, };
