// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SafetyLevel } from "./SafetyLevel";
import type { SafetyLevelCounts } from "./SafetyLevelCounts";

/**
 * Aggregate per-package safety summary
 * surfaced through `PackageSafetyBanner` in the UI. `worst_case_level`
 * is the maximum-severity level across the package's tasks (ordered
 * Safe < Network < Compute < Exec); `level_counts` is the per-level
 * task tally so the SME can spot a single Exec task in a Compute-heavy
 * package at a glance.
 */
export type SafetySummary = { 
/**
 * Worst case level.
 */
worst_case_level: SafetyLevel, 
/**
 * Level counts.
 */
level_counts: SafetyLevelCounts, };
