// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * SafetyLevelCounts data.
 */
export type SafetyLevelCounts = { 
/**
 * Safe.
 */
safe: number, 
/**
 * Network.
 */
network: number, 
/**
 * Compute.
 */
compute: number, 
/**
 * Exec.
 */
exec: number, };
