// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodeExecution } from "./CodeExecution";
import type { NetworkPolicy } from "./NetworkPolicy";
import type { ProvisioningPolicy } from "./ProvisioningPolicy";
import type { SafetyLevel } from "./SafetyLevel";
import type { SandboxRequirement } from "./SandboxRequirement";

/**
 * Unifying safety policy on AtomDefinition. Composes with the
 * fine-grained `crate::sandbox_policy::SandboxPolicy` — SafetyPolicy
 * is the coarse atom-level declaration; SandboxPolicy is the
 * implementation-level enforcement that kicks in when sandbox != None.
 */
export type SafetyPolicy = { 
/**
 * Level.
 */
level: SafetyLevel, 
/**
 * Moved from ContainerSpec.network. Default is the "deny all
 * egress" form (None with empty allowlist) — required for
 * Compute / Safe level lint consistency. See design §4.2.
 */
network: NetworkPolicy, 
/**
 * Code execution.
 */
code_execution: CodeExecution, 
/**
 * Sandbox.
 */
sandbox: SandboxRequirement, 
/**
 * Provisioning.
 */
provisioning: ProvisioningPolicy, 
/**
 * When true this task operates on controlled-access data (e.g.
 * dbGaP-restricted genotypes) that must not be forwarded to a
 * third-party LLM inference endpoint. The harness dispatch gate
 * checks this flag before launching the Claude agent wrapper and
 * emits `BlockerKind::ControlledAccessViolation` if the executor
 * would route the data through an external LLM. Default `false`
 * keeps existing WORKFLOW.json files backward-compatible.
 */
controlled_access: boolean, };
