// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Process-isolation requirement above the container's default.
 */
export type SandboxRequirement = "none" | "process_isolation" | "hardware_enclave";
