// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a generated-code implementation was refused for
 * execution. Surfaces as `BlockerKind::SandboxRefused` in the
 * harness; `BlockerKind::ValidationFailed` for output-schema
 * failures.
 */
export type SandboxRefusal = { "kind": "static_analysis_required" } | { "kind": "dependency_not_allowed", dep: string, } | { "kind": "container_required" } | { "kind": "network_denied" } | { "kind": "secrets_denied" } | { "kind": "host_fs_denied" } | { "kind": "memory_limit_exceeded", requested_mb: number, limit_mb: number, } | { "kind": "wall_timeout_exceeded" } | { "kind": "signed_artifact_required" } | { "kind": "human_review_required" } | { "kind": "review_status_rejected" } | { "kind": "output_schema_validation_failed", reason: string, };
