// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sandbox policy applied to generated-code implementations.
 */
export type SandboxPolicy = { 
/**
 * Stable id for the policy (e.g. `default_v1`,
 * `clinical_v1`).
 */
id: string, 
/**
 * Human label.
 */
label: string, 
/**
 * True when static analysis must pass before execution.
 */
require_static_analysis: boolean, 
/**
 * Allowed dependencies. Empty = empty-allowlist mode (no
 * dependencies allowed at all). Use a wildcard policy
 * (`vec!["*".into()]`) only for development environments.
 */
dependency_allowlist: Array<string>, 
/**
 * True when the implementation must run in a container.
 */
require_container: boolean, 
/**
 * True when network access is blocked.
 */
deny_network: boolean, 
/**
 * True when secrets cannot be mounted.
 */
deny_secrets: boolean, 
/**
 * True when host filesystem access is blocked except for
 * the explicit workdir.
 */
deny_host_fs: boolean, 
/**
 * Memory ceiling in MB (`None` = unlimited).
 */
memory_limit_mb: number | null, 
/**
 * Wall-clock timeout in seconds (`None` = unlimited).
 */
wall_timeout_secs: number | null, 
/**
 * True when artifacts must be signed.
 */
require_signed_artifacts: boolean, 
/**
 * True when high-risk implementations require explicit
 * human review (separate from static analysis).
 */
require_human_review_for_high_risk: boolean, 
/**
 * True when output schema must be validated against the
 * node's `postconditions` and any
 * `RequiredArtifact.schema_ref`. Failure → `Blocked
 * { ValidationFailed }` regardless of exit code.
 */
validate_output_schema: boolean, 
/**
 * Strict env-var allowlist. When non-empty, only these env var
 * names are passed through to sandboxed subprocesses; everything
 * else is `--unsetenv`'d. Independent of `deny_secrets` (which
 * scrubs by name pattern). Empty default means pass-through.
 */
allow_envs: Array<string>, };
