// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Scatter/gather declaration.
 */
export type ScatterDeclaration = { 
/**
 * Node id that scatters per shard.
 */
scatter_node_id: string, 
/**
 * Shard key — typically `"sample"` or a custom key on
 * `attributes`.
 */
shard_key: string, 
/**
 * Optional gather node id where shards collapse back into one.
 */
gather_node_id?: string, };
