// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-component scoring breakdown. Surfaces *why* an
 * archetype matched (or didn't) so the UI rationale card (S6.15) can
 * render the evidence inline.
 */
export type ScoreEvidence = { 
/**
 * +3 when `archetype.goal_data` exactly matches target.
 */
goal_data_exact: number, 
/**
 * +2 when one is a subtype of the other (partial credit).
 */
goal_data_subtype: number, 
/**
 * +2 when `archetype.goal_format` matches target format.
 */
goal_format_match: number, 
/**
 * +1 when `archetype.project_class` matches target class.
 */
project_class_match: number, 
/**
 * +2 when `archetype.modality_hint` exactly matches the
 * classifier's modality (e.g. `bulk_rnaseq`, `long_read_rnaseq`).
 * Disambiguates DE-shaped goals where multiple archetypes produce
 * the same goal_data/goal_format pair.
 */
modality_match: number, 
/**
 * +2 when `archetype.goal_kind_hint` matches the classifier's
 * `goal.modifiers.kind`. Sub-modality disambiguator that resolves
 * the proteomics DDA-vs-DIA tie.
 */
goal_kind_match: number, 
/**
 * Sum of all components.
 */
total: number, };
