// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Semantic version.
 */
export type SemVer = { 
/**
 * Major.
 */
major: number, 
/**
 * Minor.
 */
minor: number, 
/**
 * Patch.
 */
patch: number, 
/**
 * Optional pre-release tag (`-alpha.1`, `-rc.2`).
 */
pre_release?: string, };
