// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Comparator } from "./Comparator";

/**
 * Names the column + threshold + comparator the assembler uses to
 * split a result artifact into "significant" vs the full set.
 */
export type Significance = { column: string, threshold: number, comparator: Comparator, };
