// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArchetypeAtomRef } from "./ArchetypeAtomRef";

/**
 * SlotValue data.
 */
export type SlotValue = { 
/**
 * Slot value id, must appear in archetype id (e.g. `diablo` for
 * `cross_omics_rnaseq_proteomics_diablo` family).
 */
id: string, 
/**
 * Tokens the classifier scans for (case-insensitive, substring).
 * Empty for the `default` value — it wins when nothing else does.
 */
keywords: Array<string>, 
/**
 * Atoms appended to the base archetype when this slot is chosen.
 * Ordering preserved; depends_on must reference base atoms or
 * earlier slot-fill atoms.
 */
extra_atoms: Array<ArchetypeAtomRef>, };
