// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlotValue } from "./SlotValue";

/**
 * SlotManifest data.
 */
export type SlotManifest = { 
/**
 * Slot name, e.g. "integrator", "protocol".
 */
slot_name: string, 
/**
 * Currently only `closed_enum` supported. Future: `open_text`.
 */
slot_kind: string, 
/**
 * Fallback value when no value's keywords match.
 */
default: string, 
/**
 * Values.
 */
values: Array<SlotValue>, };
