// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SmeValidationBound } from "./SmeValidationBound";

/**
 * An ordered set of SME validation bounds. `Vec` (not a map) so authored order
 * is preserved deterministically into the merged contract.
 */
export type SmeValidationBounds = Array<SmeValidationBound>;
