// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable handle for a stage in the workflow taxonomy. Backed by `Arc<str>`.
 */
export type StageId = string;
