// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire-compatible mirror of the harness-internal `StallSignal` enum.
 * The harness crate cannot be pulled into `core` (no tokio, no harness
 * deps), so stall signals cross the crate boundary in this flattened
 * shape. `#[serde(tag = "kind", rename_all = "snake_case")]` produces
 * `{"kind":"cpu_starvation","avg_cpu_pct":2.3,"window_mins":34}`.
 */
export type StallSignalWire = { "kind": "cpu_starvation", avg_cpu_pct: number, window_mins: bigint, } | { "kind": "memory_pressure", pct: number, window_mins: bigint, } | { "kind": "gpu_idle_during_training", window_mins: bigint, } | { "kind": "runtime_over_expected", actual_secs: bigint, expected_secs: bigint, };
