// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a compatibility unification failed. Mirrors the variants of
 * `crate::compatibility::reports::IncompatibilityReason` but lives in
 * the substrate's own type so the substrate file is decoupled from
 * the engine's exact field layout (substrate consumers should not
 * have to reach into the engine module). Each variant carries the
 * minimum fields needed to reconstruct the failure intent.
 *
 * `ts-rs` renames the export to `SubstrateIncompatibilityReason` so
 * the binding file doesn't collide with the engine's same-named type.
 */
export type SubstrateIncompatibilityReason = { "kind": "semantic_type_mismatch", 
/**
 * Producer.
 */
producer: string, 
/**
 * Consumer.
 */
consumer: string, } | { "kind": "facet_mismatch", 
/**
 * Facet.
 */
facet: string, 
/**
 * Producer.
 */
producer: string, 
/**
 * Consumer.
 */
consumer: string, 
/**
 * Rationale.
 */
rationale: string, } | { "kind": "privacy_class_widening", 
/**
 * Producer.
 */
producer: string, 
/**
 * Consumer.
 */
consumer: string, } | { "kind": "cardinality_mismatch", 
/**
 * Producer.
 */
producer: string, 
/**
 * Consumer.
 */
consumer: string, } | { "kind": "policy_violation", 
/**
 * Bundle id.
 */
bundle_id: string, 
/**
 * Check kind.
 */
check_kind: string, 
/**
 * Statement.
 */
statement: string, } | { "kind": "other", 
/**
 * Statement.
 */
statement: string, };
