// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * OS-level packages keyed by package manager. `apt` covers
 * Debian/Ubuntu base images; `dnf` covers RHEL/Fedora/Alma. Other
 * managers can be added behind new fields when their first consumer
 * shows up; the schema is `additionalProperties: false` so unknown
 * keys fail at load time rather than silently dropping.
 */
export type SystemPackages = { 
/**
 * Apt.
 */
apt: Array<string>, 
/**
 * Dnf.
 */
dnf: Array<string>, };
