// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable, semantically-named handle for a task in the workflow DAG.
 *
 * Backed by `Arc<str>` — clones are atomic refcount bumps. The wire
 * format is a bare string; the TypeScript type is `string`.
 */
export type TaskId = string;
