// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscoveryKind } from "./DiscoveryKind";

/**
 * TaskKind discriminant.
 */
export type TaskKind = { "discovery": DiscoveryKind } | "computation" | "validation" | "review" | "gate";
