// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockedRecord } from "./BlockedRecord";
import type { RemoteExecution } from "./RemoteExecution";

/**
 * TaskState discriminant.
 */
export type TaskState = { "status": "pending" } | { "status": "ready" } | { "status": "running", 
/**
 * Started at.
 */
started_at: string, 
/**
 * Remote execution metadata. None for local execution. Kept as
 * Option with skip_serializing_if so WORKFLOW.json stays
 * byte-identical for local-mode packages (no `remote: null`
 * field appears) and pre-AWS-A packages still deserialize.
 */
remote?: RemoteExecution, } | { "status": "completed", 
/**
 * Result.
 */
result: unknown, } | { "status": "failed", 
/**
 * Reason.
 */
reason: string, } | { "status": "blocked", 
/**
 * Record.
 */
record: BlockedRecord, };
