// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Structured failure envelope written by every backend. The shape is
 * stable across `local | aws | slurm` so the server's blocker-mapper
 * and the remediation proposer can consume one type.
 */
export type ToolErrorEnvelope = { 
/**
 * Task that failed.
 */
task_id: string, 
/**
 * Stage class the task implements (e.g. "alignment",
 * "differential_expression"). Used by the proposer to consult
 * the relevant taxonomy snippet.
 */
stage_id: string, 
/**
 * Library / binary the proposer should reason about
 * (e.g. "STAR", "DESeq2", "cellranger"). `None` when the
 * failure precedes any tool invocation.
 */
library?: string, 
/**
 * Library version when extractable. The proposer uses this to
 * suggest version-specific remediations (e.g. known-bug downgrades).
 */
library_version?: string, 
/**
 * Coarse error class. Stable string vocabulary so the UI can
 * show a typed chip and the proposer can match without parsing
 * the full traceback. See [`classify_error`] for the heuristics.
 */
error_class: string, 
/**
 * One-line summary for the BlockerCard header.
 * Bounded to [`MESSAGE_MAX_LEN`] chars.
 */
message: string, 
/**
 * Tail of stderr, oldest first. Bounded by [`STDERR_TAIL_LIMIT`].
 */
stderr_tail: Array<string>, 
/**
 * Tail of stdout, oldest first. Bounded by [`STDOUT_TAIL_LIMIT`].
 */
stdout_tail: Array<string>, 
/**
 * Python traceback frames when the failure was a Python
 * exception. Bounded by [`TRACEBACK_FRAME_LIMIT`].
 */
traceback?: Array<string>, 
/**
 * Process exit code when the task ran to completion.
 */
exit_code?: number, 
/**
 * Signal name when the process was terminated by signal
 * (SIGKILL = OOM, SIGTERM = wallclock, SIGSEGV = crash).
 */
signal?: string, 
/**
 * Wall-clock seconds consumed before the failure.
 */
wallclock_secs?: bigint, 
/**
 * Peak resident-set memory observed in MiB. Local: VmHWM from
 * `/proc/<pid>/status`. AWS: CloudWatch agent. SLURM: sacct MaxRSS.
 */
peak_memory_mb?: bigint, 
/**
 * Hash-summary of inputs at the time of failure: shapes, sizes,
 * key column names. Never carries raw data — strictly metadata.
 */
input_summary: Record<string, unknown>, 
/**
 * Backend that ran the task. Matches `Executor::name()`.
 */
executor: string, 
/**
 * Backend-native context: instance_type for AWS, partition for
 * SLURM, host for local.
 */
executor_context: { [key in string]?: string }, 
/**
 * Wall-clock RFC 3339 timestamp at capture.
 */
captured_at: string, 
/**
 * Monotonic per-task attempt number. Lets the proposer see
 * prior remediation outcomes via the overrides history.
 */
attempt: number, 
/**
 * Schema version. `1` is the only value today; bump on any
 * breaking change to the on-disk shape.
 */
schema_version: number, };
