// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * TriggerCondition data.
 */
export type TriggerCondition = { 
/**
 * Slot name.
 */
slot_name?: string, 
/**
 * Candidate values.
 */
candidate_values: Array<string>, 
/**
 * Classified modality.
 */
classified_modality?: string, 
/**
 * Prose contains any.
 */
prose_contains_any: Array<string>, 
/**
 * Tied modalities.
 */
tied_modalities: Array<string>, 
/**
 * Max confidence below.
 */
max_confidence_below?: number, };
