// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Paper §D.2 edge with full port-level endpoints (the data
 * `lower_to_workflow_json` collapses into `depends_on`).
 */
export type TypedEdge = { 
/**
 * Deterministic id: `"{from_node}.{from_port}->{to_node}.{to_port}"`.
 */
edge_id: string, 
/**
 * `EdgeContract.from_node`.
 */
source_node_id: string, 
/**
 * `EdgeContract.to_node`.
 */
target_node_id: string, 
/**
 * `EdgeContract.from_port` — the producer port name preserved.
 */
source_output: string, 
/**
 * `EdgeContract.to_port` — the consumer port name preserved.
 */
target_input: string, 
/**
 * T6.2 — `EdgeContract.mutually_exclusive_group`. When set, this edge is
 * one member of a mutually-exclusive one-of input group; sibling members
 * are ALTERNATIVES (only one is read at runtime, resolved to a single
 * authoritative edge by observed-provenance in the RO-Crate). Preserved
 * here so a generic consumer of `workflow-typed.json` sees the one-of
 * structure — matching `proofs.jsonl` — and does NOT read an unread
 * alternative as an authoritative data flow. `None` for ordinary edges.
 */
mutually_exclusive_group?: string, };
