// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Paper §D.2 step. `tool_id` is the source atom; `parameters` is a curated
 * subset of `TaskNode.attributes` (method axes / required figures), NEVER a
 * synthesized method choice (method-neutrality).
 */
export type TypedStep = { 
/**
 * `TaskNode.id`.
 */
step_id: string, 
/**
 * `TaskNode.attributes["atom_id"]` (the key the lowering reads).
 * `None` when the node carries no atom id.
 */
tool_id?: string, 
/**
 * Curated step parameters (sorted-key map). Empty for steps with no
 * method/figure attributes.
 */
parameters: Record<string, unknown>, 
/**
 * Incoming `from_node`s, sorted + deduped. Equals the lowered
 * `Task.depends_on` for this step (W6 asserts equality).
 */
dependencies: Array<string>, 
/**
 * Static `ResourceClass`-derived estimate in seconds. Deterministic
 * lookup, NOT wall-clock.
 */
estimated_duration: bigint, };
