// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Paper §D.2 edge with full port-level endpoints (the data
 * `lower_to_workflow_json` collapses into `depends_on`).
 */
export type TypedEdge = { 
/**
 * Deterministic id: `"{from_node}.{from_port}->{to_node}.{to_port}"`.
 */
edge_id: string, 
/**
 * `EdgeContract.from_node`.
 */
source_node_id: string, 
/**
 * `EdgeContract.to_node`.
 */
target_node_id: string, 
/**
 * `EdgeContract.from_port` — the producer port name preserved.
 */
source_output: string, 
/**
 * `EdgeContract.to_port` — the consumer port name preserved.
 */
target_input: string, };
