// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Single-variant marker matching the literal YAML string `"union"`.
 */
export type UnionToken = "union";
