// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Validation obligation a `NovelNodeSpec` must satisfy before
 * promoting toward production. Evaluated by the
 * claim_extractor/claim_verifier substrate.
 */
export type ValidationObligation = { 
/**
 * Stable id (`p_value_in_unit_interval`,
 * `gene_id_in_annotation`, etc.).
 */
id: string, 
/**
 * Obligation kind (`contract_test`, `golden_test`,
 * `metamorphic_test`, `biological_invariant`,
 * `statistical_sanity`, `reproducibility`, `security`,
 * `resource_bound`).
 */
kind: string, 
/**
 * Human-readable statement.
 */
statement: string, 
/**
 * Optional reference (script path, fixture file).
 */
reference?: string, };
