// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiteratureClaimFailureKind } from "./LiteratureClaimFailureKind";

/**
 * Structured failure cause for [`BlockerKind::ValidationFailed`]. Phase A
 * of the literature-atom plan — extends `ValidationFailed` with an
 * optional typed payload for validators that produce structured failure
 * reasons (e.g. literature-row-anchored errors). `None` preserves the
 * legacy path where the `check` + `message` string pair is the only
 * failure information.
 */
export type ValidationFailureCause = { "cause_kind": "literature_claim", row_index: bigint, artifact: string, kind: LiteratureClaimFailureKind, };
