// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Top-level validation rule (W4). Strictly richer than the paper: preserves
 * the opaque CEL `expression` and the Hard/Soft/Warn `severity`. The
 * compiler does NOT compile the expression — downstream consumers must not
 * assume it is pre-validated.
 */
export type ValidationRule = { 
/**
 * Composite stable id: `"{target_step}:{constraint_id}"`.
 */
rule_id: string, 
/**
 * Step this rule constrains.
 */
target_step: string, 
/**
 * Opaque CEL/schema expression (uncompiled). `None` when the
 * constraint declared no expression.
 */
expression?: string, 
/**
 * `"hard"` / `"soft"` / `"warn"`.
 */
severity: string, };
