// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coarse verification-method class tag reported per verdict and tallied into
 * the persisted header's per-class counts. Total over every verdict: every
 * verdict maps to exactly one class, so the per-class counts always sum to
 * `n_checked`.
 */
export type VerdictClass = "numeric_table" | "directional" | "entity_presence" | "literature_quotation";
