// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VerdictClass } from "./VerdictClass";

/**
 * The reconstructable audit tuple for a single verdict. When the numeric gate
 * compared a claimed quantity against a table cell the numeric slots are
 * populated; for a non-numeric verdict only `class`/`verifier_version`/
 * `entity_value` are set. Persisted verbatim into
 * `runtime/claim-verification.json` and the signed sink so a reviewer can
 * reconstruct *what was compared against what, and how*.
 */
export type VerdictAudit = { 
/**
 * The verification-method class for this verdict.
 */
class: VerdictClass, 
/**
 * Package-relative (or basename) reference of the table the observed value
 * was read from.
 */
source_table?: string, 
/**
 * The table's entity column the row was resolved by (e.g. `gene`).
 */
entity_column?: string, 
/**
 * The claim's entity value used for the row lookup (e.g. `CRISPLD2`).
 */
entity_value?: string, 
/**
 * The table column the observed value was read from (e.g. `padj`).
 */
measurement_column?: string, 
/**
 * The numeric value asserted in the claim text.
 */
claimed_value?: number, 
/**
 * The numeric value observed in the table cell.
 */
observed_value?: number, 
/**
 * The comparison performed (`order_of_magnitude` for p-values, `absolute`
 * for log2FC / effect sizes).
 */
comparison_operator?: string, 
/**
 * Absolute tolerance used (log2FC / effect size).
 */
absolute_tolerance?: number, 
/**
 * Relative / order-of-magnitude tolerance used (p-values, in orders of
 * magnitude).
 */
relative_tolerance?: number, 
/**
 * Any unit conversion applied before comparison (e.g. `linear_fold->log2`);
 * `None` when the claim and table share units.
 */
unit_conversion?: string, 
/**
 * The verifier-implementation version that produced this verdict.
 */
verifier_version: string, 
/**
 * Human-readable rationale for the verdict.
 */
rationale?: string, 
/**
 * Fraction of numeric tokens found in the claim text that were actually
 * compared against a table cell (parse-coverage metric). `1.0` when there
 * were no numeric tokens or all were compared; `< 1.0` when a token was
 * unparseable or its entity/column could not be resolved.
 */
parse_coverage: number, };
