// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single atom whose version changed between two catalogs.
 */
export type VersionBump = { 
/**
 * Atom id.
 */
id: string, 
/**
 * Version in the old catalog.
 */
from: string, 
/**
 * Version in the new catalog.
 */
to: string, };
