// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SmeValidationBound } from "./SmeValidationBound";

/**
 * Branch-to-edit payload: the method, parameter, and validation-bound changes
 * an SME stages in the branch modal, applied atomically to the freshly-forked
 * child before it auto-emits. All fields optional/defaulted so a plain branch
 * (no edits) keeps its existing wire shape.
 */
export type BranchEdits = { 
/**
 * Optional method change on the branched task (the SME's explicit choice).
 */
method: string | null, 
/**
 * Concrete parameter overrides on the branched task (`name -> value`).
 */
parameters: Record<string, unknown>, 
/**
 * SME-authored validation bounds to attach to the child's contract.
 */
validation_bounds: Array<SmeValidationBound>, };
