// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from `GET /api/chat/session/:id/execution`.
 */
export type ExecutionStatusResponse = { 
/**
 * OS process ID of the harness subprocess.
 */
pid: number, 
/**
 * Timestamp when the harness was launched.
 */
started_at: string, 
/**
 * Absolute path to the package directory the harness is executing against.
 */
package_dir: string, 
/**
 * Full agent command string passed to the harness.
 */
agent_command: string, 
/**
 * One of `running` | `pausing` | `paused` | `stopping` | `exited`.
 */
status: string, 
/**
 * Exit code when `status == "exited"`; absent while the process is live.
 */
exit_code?: number, 
/**
 * Timestamp when the harness was last paused; absent when not paused.
 */
paused_at?: string, 
/**
 * Timestamp when a stop was requested; absent when not stopping.
 */
stop_requested_at?: string, 
/**
 * POSIX process group ID used by `/execution/kill` to terminate the harness tree.
 */
pgid: number, };
