// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Closed set of literature-claim validator failure kinds. Maps 1:1 onto
 * the validator obligations in `validation_obligations.rs::literature_obligations`.
 */
export type LiteratureClaimFailureKind = "pmid_malformed" | "pmid_not_found" | "evidence_artifact_missing" | "quote_not_in_source" | "quote_offset_wrong" | "redistributable_tag_inconsistent" | "finding_id_orphan" | "invalid_concordance_flag";
