// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Declared parameter type. `#[non_exhaustive]` so adding a future
 * type (e.g. a `Duration` scalar) is a non-breaking minor change for
 * downstream `ts-rs` / RO-Crate consumers.
 */
export type ParameterType = "string" | "number" | "integer" | "boolean" | "array" | "object" | "enum";
