// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ProjectClass discriminant.
 */
export type ProjectClass = "bioinformatics" | "clinical_trial" | "time_series_forecast";
