// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockerContext } from "./BlockerContext";
import type { BlockerEntry } from "./BlockerEntry";
import type { BlockerKind } from "./BlockerKind";

/**
 * State-machine node for a chat session. Drives the LLM dispatch
 * loop, tool precondition checks, and UI recovery affordances.
 * The `transitions.rs` module owns the full transition table;
 * the `#[non_exhaustive]` attribute preserves forward compatibility
 * with downstream consumers.
 */
export type SessionState = { "kind": "greeting" } | { "kind": "intake" } | { "kind": "intake_followup" } | { "kind": "pending_confirmation", 
/**
 * Stage id awaiting confirmation, if the confirmation is stage-scoped.
 */
stage?: string, } | { "kind": "ready_to_emit" } | { "kind": "emitting" } | { "kind": "emitted" } | { "kind": "amending", 
/**
 * The stage whose method the SME is swapping.
 */
target_stage: string, 
/**
 * Downstream task ids that were invalidated (transitive closure)
 * — surfaced so the UI Jobs tab can explain which tasks are
 * about to rerun.
 */
invalidated_tasks: Array<string>, } | { "kind": "blocked", 
/**
 * Queue of active blockers. New sessions populate this
 * alongside the legacy fields below so concurrent task-level
 * blockers are not overwritten by the latest one.
 */
blockers: Array<BlockerEntry>, 
/**
 * Legacy human-readable reason — kept as the canonical wire field
 * for serde forward-/backward-compat with sessions persisted
 * before the typed migration. Populated alongside `blocker_kind`
 * for every new transition; callers prefer `blocker_kind` for
 * structured dispatch.
 */
reason: string, 
/**
 * Legacy recovery hint. Same migration rationale as `reason`.
 */
recovery_hint: string, 
/**
 * Typed blocker taxonomy. Absent on sessions persisted before
 * the typed migration — callers fall back to synthesizing
 * `BlockerKind::AgentError { message: reason }` when None. The
 * 30-day session TTL auto-expires the None branch.
 */
blocker_kind?: BlockerKind, 
/**
 * Structured context (timestamp + recovery hints) alongside the
 * typed kind.
 */
context?: BlockerContext, };
