// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One SME-authored validation bound, shaped so it lowers directly into a
 * validation-contract `stages.<stage_class>.assertions[]` entry.
 */
export type SmeValidationBound = { 
/**
 * Stage class the bound applies to (contract key `stages.<stage_class>`).
 */
stage_class: string, 
/**
 * Assertion type — must be one of `SUPPORTED_ASSERTION_TYPES`.
 */
assertion_type: string, 
/**
 * Relative artifact path the assertion reads (e.g. `results/tables/de.json`).
 */
target: string, 
/**
 * Type-specific check object (json_pointer/op/value, substrings, …).
 */
check: unknown, 
/**
 * `required` (blocks) or `recommended` (warns).
 */
severity: string, 
/**
 * Stable id — replaced idempotently when the same id is set again.
 */
id: string, 
/**
 * Human description surfaced in the Decisions / Claims UI.
 */
description: string, };
