// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One aggregated tier result as exposed by the Performance tab tile.
 * Fields map directly to display columns in `ValueAddTile`.
 */
export type TierResult = { 
/**
 * Dotted tier identifier, e.g. `"15.1"`, `"16.2"`.
 */
tier: string, 
/**
 * Single-letter eval bucket the tier belongs to: A, B, C, D, E, or F.
 */
bucket: string, 
/**
 * Whether the most recent run for this tier passed its threshold.
 */
passed: boolean, 
/**
 * Primary score read out of the JSONL row.
 */
score: number, 
/**
 * Pass/fail threshold the runner used on its last run.
 */
threshold: number, 
/**
 * Unix epoch milliseconds of the most recent row for this tier.
 */
last_run_ms: number, };
