// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TierResult } from "./TierResult";

/**
 * Top-level response for `GET /api/chat/session/:id/value-add-metrics`.
 */
export type ValueAddMetricsResponse = { 
/**
 * Latest result per tier, sorted by tier id (lexicographic).
 */
tier_results: Array<TierResult>, 
/**
 * Unix epoch milliseconds when the most recent row was written.
 */
last_updated_ms: number, };
