//! Small data-shape types shared across the metrics module: per-model
//! counters, token buckets, per-surface roll-ups, per-task agent counters,
//! blocker / affordance summary records, and the convergence histogram
//! bucket constant.
//!
//! Pure data definitions plus the `TokenBucket::add_from` and
//! `Default for PerTaskAgentCounters` helpers. No cost arithmetic and no
//! store/IO logic — those live in sibling submodules.

use crate::model_policy::ModelId;
use serde::{Deserialize, Serialize};

/// One entry in the catalog-gap summary surfaced to the UI.
/// Populated from the session-scoped `AffordanceFallbackCounter` at
/// metrics-snapshot time; sorted by count descending, then
/// `semantic_type` ascending, then `primitive` ascending so the UI's
/// catalog-gaps card shows the highest-frequency misses first.
///
/// Not ts-rs-derived intentionally (see the `SessionMetrics` note above
/// about `bigint`; `count` is `u32` and safe as `number` but for
/// consistency we follow the same hand-mirror pattern).
#[derive(Clone, Debug, Serialize, Deserialize, schemars::JsonSchema)]
pub struct AffordanceFallbackSummary {
    /// EDAM or CURIE semantic type IRI for the missing affordance.
    pub semantic_type: String,
    /// Primitive renderer kind requested but absent from the catalog.
    pub primitive: String,
    /// Number of times this `(semantic_type, primitive)` pair was requested.
    pub count: u32,
}

/// Per-model token + turn counters. Keyed by `ModelId` so adding Haiku
/// or a future variant is additive — no new fields, no migrations.
#[derive(Debug, Default, Clone, Serialize, Deserialize, schemars::JsonSchema)]
pub struct ModelCounters {
    /// Number of turns using this model.
    pub count: u64,
    /// Total input tokens billed for this model.
    pub input_tokens: u64,
    /// Total output tokens generated by this model.
    pub output_tokens: u64,
    /// Input tokens served from prompt cache (lower rate).
    pub cache_read_tokens: u64,
    /// Input tokens written into prompt cache (higher rate).
    pub cache_creation_tokens: u64,
}

/// Where a given block of token usage came from. Chat turns and agent
/// task executions both consume the Anthropic API but travel through
/// different code paths and are billed separately by the UI — the SME
/// sees chat cost (per-turn, bounded) vs agent cost (per-task, bounded
/// by sizing policy) on different lines so operator spend decisions
/// stay legible.
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Hash,
    Serialize,
    Deserialize,
    schemars::JsonSchema,
)]
#[serde(rename_all = "snake_case")]
pub enum TurnSource {
    /// Token usage from the SME↔LLM conversation (chat surface).
    Chat,
    /// Token usage from task-execution agent runs (agent surface).
    Agent,
}

/// A single blocker event within a session, persisted into
/// `runtime/session-metrics.jsonl`. Mirrors `BlockerEvent` in
/// `crates/eval-adapters/src/aggregators/sme_experience.rs` so the
/// Tier 16.4 runner can decode the field directly.
///
/// `#[derive(Serialize)]` is sufficient here — the read path is
/// in eval-adapters (which derives Deserialize). This struct carries only
/// the three fields the tier runner needs; the full `BlockerKind` payload
/// lives in the session state and in `decisions.jsonl` for debugging.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
pub struct BlockerEventRecord {
    /// Serialised `BlockerKind` variant name, e.g. `"ToolError"`,
    /// `"ValidationFailed"`, `"DataShape"`. Derived from the
    /// `Debug` representation of `BlockerKind` so new variants are
    /// automatically included without a metrics.rs change.
    pub blocker_kind: String,
    /// Set to `false` when the blocker is first recorded; flipped to
    /// `true` by `record_blocker_recovered` when the session leaves
    /// `Blocked` via the `/unblock` handler.
    pub recovered: bool,
    /// Optional description of the recovery path (e.g.
    /// `"amend_stage_method"`, `"rerun_task"`, `"branch_session"`).
    /// Populated by the service-layer `/unblock` handler that knows the
    /// originating SME action.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub recovery_path: Option<String>,
}

/// Bucket boundaries (lower-inclusive) for the
/// `converged_at_iter` histogram. 7 buckets covering 1, 2, 4, 8,
/// 16, 32, 64+ iterations. Stable across releases because the
/// counter file persists this shape.
pub const ITERATIONS_HISTOGRAM_BUCKETS: &[u64] = &[1, 2, 4, 8, 16, 32, 64];

/// Token counts broken out by cost surface. Sum across all four surfaces
/// equals the flat `total_*_tokens` fields on `SessionMetrics`.
#[derive(Debug, Default, Clone, Serialize, Deserialize, schemars::JsonSchema)]
pub struct PerSurfaceTokens {
    /// Tokens consumed by the SME chat surface.
    pub chat: TokenBucket,
    /// Tokens consumed by execution-agent task runs.
    pub agent: TokenBucket,
    /// Tokens consumed by the rubric scorer (operator-triggered).
    pub scorer: TokenBucket,
    /// Tokens consumed by out-of-band side calls (auto-title, remediation).
    pub side_call: TokenBucket,
}

/// Four token counts for one cost surface (or one model within a surface).
#[derive(Debug, Default, Clone, Copy, Serialize, Deserialize, schemars::JsonSchema)]
pub struct TokenBucket {
    /// Input tokens billed (excluding cache reads).
    pub input_tokens: u64,
    /// Output tokens generated.
    pub output_tokens: u64,
    /// Input tokens served from prompt cache.
    pub cache_read_tokens: u64,
    /// Input tokens written into prompt cache.
    pub cache_creation_tokens: u64,
}

impl TokenBucket {
    pub(super) fn add_from(&mut self, c: &ModelCounters) {
        self.input_tokens = self.input_tokens.saturating_add(c.input_tokens);
        self.output_tokens = self.output_tokens.saturating_add(c.output_tokens);
        self.cache_read_tokens = self.cache_read_tokens.saturating_add(c.cache_read_tokens);
        self.cache_creation_tokens = self
            .cache_creation_tokens
            .saturating_add(c.cache_creation_tokens);
    }
}

/// F1 — per-task agent counter entry. Serialized into the session
/// sidecar so a restart doesn't lose the per-task history.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
pub(crate) struct PerTaskAgentCounters {
    pub(crate) model: ModelId,
    pub(crate) counters: ModelCounters,
    /// Populated at snapshot time from the Session's DAG
    /// (`spec.stage_class`) so the UI's stage-class rollup (F4) can
    /// group without a second data lookup. `None` when the task id
    /// isn't present in the DAG — which shouldn't happen for agent-run
    /// tasks, but degrades gracefully.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) stage_class: Option<String>,
    /// Wall-clock start time in epoch-ms, captured on the first
    /// `task_started` event. None until the harness fires it. Cleared
    /// once `task_completed` materialises `elapsed_secs`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) started_at_ms: Option<u64>,
    /// Wall-clock seconds from task_started → task_completed. Populated
    /// in `record_task_completed`. None for in-flight or for tasks
    /// where no `task_started` was recorded (e.g. pre-existing
    /// sessions that preceded this tracking).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) elapsed_secs: Option<f64>,
}

impl Default for PerTaskAgentCounters {
    fn default() -> Self {
        Self {
            model: ModelId::Sonnet46,
            counters: ModelCounters::default(),
            stage_class: None,
            started_at_ms: None,
            elapsed_secs: None,
        }
    }
}

/// One entry in the per-task agent cost list surfaced to the UI via
/// `SessionMetrics::per_task_agent`. Sorted by `cost_usd` descending.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
pub struct PerTaskAgentSnapshot {
    /// Task identifier from the emitted DAG.
    pub task_id: String,
    /// Serialised `ModelId` variant name used for this task's agent run.
    pub model: String,
    /// Stage class (e.g. `"alignment"`) if available from the DAG spec.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stage_class: Option<String>,
    /// Input tokens billed for this task's agent execution.
    pub input_tokens: u64,
    /// Output tokens generated by the agent for this task.
    pub output_tokens: u64,
    /// Prompt-cache read tokens for this task.
    pub cache_read_tokens: u64,
    /// Prompt-cache creation tokens for this task.
    pub cache_creation_tokens: u64,
    /// Estimated USD cost for this task's agent tokens.
    pub cost_usd: f64,
    /// Wall-clock seconds the task consumed, from task_started →
    /// task_completed. None when the task hasn't completed or when the
    /// harness didn't fire a matching start event. UI uses the populated
    /// entries (grouped by `stage_class`) to compute per-class median
    /// durations for in-flight-task ETAs.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub elapsed_secs: Option<f64>,
}
