//! Depositable-package export.
//!
//! A completed ECAA package carries two kinds of content side by side: the
//! audit / review / re-execution surface a depositor wants to archive, and a
//! pile of reproducible bloat (conda caches, R libraries, `__pycache__`,
//! per-run logs, heartbeats, `.git`) that is large, host-specific, and
//! regenerable. The exporter copies only the keep-tiers (A + B) into a clean
//! tree, re-seals the BagIt manifest + RO-Crate over that smaller payload, and
//! strips the version-control internals — yielding a deposit-ready directory
//! that [`zip_dir`] packs into a single `.zip` for the web download / CLI.
//!
//! Tier policy (single source of truth — see `depositable-export-plan.md`):
//! classification is by package-relative path, first match wins (E, C, D, B,
//! then A). A file is copied iff its tier is A or B ([`is_kept`]); C / D / E and
//! `.git/` are dropped (D is regenerated by the post-copy reseal).

use anyhow::{Context, Result};
use std::path::{Path, PathBuf};

/// Deposit tier of a package-relative path. Order of the variants is the
/// first-match classification order documented on [`classify`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum DepositTier {
    /// Keep (everything else): result tables, `*.md` reports, `figures/`,
    /// `view_data/`, `evidence/` snapshots, verdict + provenance JSON/JSONL,
    /// per-task result/spec/validation JSON, `policies/`, `lib/`, crate
    /// substrate (`ro-crate-metadata.json`, `WORKFLOW.json`, `bagit.txt`, …).
    A,
    /// Keep (re-execution): anything under `…/scripts/`, `env.lock`,
    /// `agent-code.json`, `runtime/plotting{,_r}/*`, `inputs/*`, `counts.tsv`,
    /// `samples.csv`.
    B,
    /// Drop (operational): per-run logs, heartbeats, container/agent state.
    C,
    /// Regenerate (skip copy; rebuilt by the post-copy reseal): the BagIt
    /// payload + tag manifests.
    D,
    /// Drop (reproducible bloat): caches, R libraries, `.git/`, compiled
    /// Python, `__pycache__/`, intermediates.
    E,
}

/// Whether a file of tier `t` is copied into the depositable export.
///
/// True for tiers A and B (the audit/review/deposit + re-execution surface),
/// false for C (operational), D (regenerated by reseal), and E (reproducible
/// bloat).
pub(crate) fn is_kept(t: DepositTier) -> bool {
    matches!(t, DepositTier::A | DepositTier::B)
}

/// Classify a package-relative path into its [`DepositTier`].
///
/// Classification is purely lexical (no filesystem access) and uses a fixed
/// first-match order: **E, then C, then D, then B, then A**. `rel` MUST be a
/// path relative to the package root (e.g.
/// `runtime/outputs/de/de_results.tsv`), using `/` separators; an absolute or
/// `..`-bearing path is classified on its components as given.
pub(crate) fn classify(rel: &Path) -> DepositTier {
    // Normalize once to a `/`-joined lossy string for substring containment
    // checks, and collect components for directory-name membership tests. Both
    // are needed: containment catches `…/cache/…` / `…/intermediates/…` at any
    // depth, while the basename match keys off `rel.file_name()`.
    let rel_str = rel.to_string_lossy().replace('\\', "/");
    let basename = rel
        .file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .unwrap_or_default();

    // A path component equals `name` anywhere in `rel` (so `cache`, `.git`,
    // `__pycache__`, `intermediates` match at any depth, not just as a
    // substring of some longer component).
    let has_component = |name: &str| {
        rel.components().any(|c| {
            matches!(c, std::path::Component::Normal(s) if s.to_string_lossy() == name)
        })
    };

    // --- Tier E — drop (reproducible bloat) ------------------------------
    // runtime/cache/, runtime/r-libs/, any …/cache/…, .git/, *.pyc,
    // __pycache__/, any …/intermediates/….
    if rel_str.starts_with("runtime/cache/")
        || rel_str == "runtime/cache"
        || rel_str.starts_with("runtime/r-libs/")
        || rel_str == "runtime/r-libs"
        || has_component("cache")
        || has_component(".git")
        || basename.ends_with(".pyc")
        || has_component("__pycache__")
        || has_component("intermediates")
    {
        return DepositTier::E;
    }

    // --- Tier C — drop (operational) -------------------------------------
    if basename.ends_with(".log")
        || basename == ".heartbeat"
        || basename == ".container-state.json"
        || basename == "agent-usage.json"
        || basename == "state.patch.applied.json"
        || basename == ".blas-probe.json"
        || basename == ".sme-auto-approve-discoveries"
    {
        return DepositTier::C;
    }

    // --- Tier D — regenerate (skip copy; rebuilt by reseal) --------------
    if basename == "manifest-sha512.txt" || basename == "tagmanifest-sha512.txt" {
        return DepositTier::D;
    }

    // --- Tier B — keep (re-execution) ------------------------------------
    if has_component("scripts")
        || basename == "env.lock"
        || basename == "agent-code.json"
        || rel_str.starts_with("runtime/plotting/")
        || rel_str.starts_with("runtime/plotting_r/")
        || rel_str.starts_with("inputs/")
        || basename == "counts.tsv"
        || basename == "samples.csv"
    {
        return DepositTier::B;
    }

    // --- Tier A — keep (everything else) ---------------------------------
    DepositTier::A
}

/// Outcome of an [`export_depositable_package`] run.
pub struct ExportReport {
    /// Number of source files copied into the export (tier A + B).
    pub kept: usize,
    /// Number of source files dropped (tier C, D, E, and anything under
    /// `.git/`).
    pub dropped: usize,
    /// Root of the export tree on disk (echoes the `dst` argument).
    pub dst: PathBuf,
}

/// Export the A+B-tier (audit/review/deposit + re-execution) surface of the
/// package at `src` into a clean deposit-ready tree at `dst`.
///
/// Steps:
/// 1. Walk `src` recursively; copy each file whose tier [`is_kept`] to
///    `dst/<rel>`, preserving layout (parent dirs created on demand). `.git/`
///    is skipped explicitly (it is also tier E, but the explicit skip avoids
///    walking thousands of loose objects).
/// 2. Re-seal the BagIt manifest over `dst` (rebuilds `manifest-sha512.txt` +
///    `tagmanifest-sha512.txt` over the kept set) via the existing
///    [`crate::emitter::regenerate_bagit_manifest`] with a wall clock.
/// 3. Re-register produced output tables, then prune `@graph` entries whose
///    `@id` is a package-relative path absent on disk in `dst`
///    ([`prune_rocrate_dangling`]) so `ro-crate-metadata.json` carries no
///    dangling reference to a dropped C/D/E file. The prune mutates a
///    manifested file, so the BagIt manifest is re-sealed once more afterwards.
/// 4. If `src/.git` exists, write `dst/runtime/execution-lineage.txt` from
///    `git -C <src> log --stat --no-color` (best-effort; ignored if git is
///    absent or fails).
pub fn export_depositable_package(src: &Path, dst: &Path) -> Result<ExportReport> {
    use crate::clock::WallClock;

    std::fs::create_dir_all(dst)
        .with_context(|| format!("creating export destination {}", dst.display()))?;

    let mut kept = 0usize;
    let mut dropped = 0usize;

    // Walk source; copy only kept (A+B) files, preserving layout. `.git/` is
    // pruned at the directory level so the walk never descends into VCS
    // internals.
    for entry in walkdir::WalkDir::new(src)
        .sort_by_file_name()
        .into_iter()
        .filter_entry(|e| {
            // Skip the `.git` directory entirely (and any `.git` file).
            e.file_name() != std::ffi::OsStr::new(".git")
        })
    {
        let entry = entry.with_context(|| format!("walking {}", src.display()))?;
        if !entry.file_type().is_file() {
            continue;
        }
        let abs = entry.path();
        let rel = abs
            .strip_prefix(src)
            .with_context(|| format!("stripping {} from {}", src.display(), abs.display()))?;

        if is_kept(classify(rel)) {
            let dest_path = dst.join(rel);
            if let Some(parent) = dest_path.parent() {
                std::fs::create_dir_all(parent)
                    .with_context(|| format!("creating {}", parent.display()))?;
            }
            std::fs::copy(abs, &dest_path).with_context(|| {
                format!("copying {} -> {}", abs.display(), dest_path.display())
            })?;
            kept += 1;
        } else {
            dropped += 1;
        }
    }

    // Re-seal BagIt over the kept set (rebuilds manifest + tagmanifest).
    let clock = WallClock;
    crate::emitter::regenerate_bagit_manifest(dst, &clock)
        .context("re-sealing BagIt manifest over export")?;

    // Re-finalize the RO-Crate over the export, then prune dangling @ids that
    // referenced dropped files. `register_produced_output_tables` is idempotent
    // and only ever adds entries for tables that ARE on disk, so it never
    // re-introduces a dangling reference.
    crate::ro_crate::register_produced_output_tables(dst)
        .map_err(anyhow::Error::from)
        .context("re-registering produced output tables over export")?;
    let pruned = prune_rocrate_dangling(dst).context("pruning dangling RO-Crate @ids")?;
    if pruned > 0 {
        // The prune rewrote `ro-crate-metadata.json` (a manifested file), so
        // re-seal once more to keep the BagIt manifest self-consistent.
        crate::emitter::regenerate_bagit_manifest(dst, &clock)
            .context("re-sealing BagIt manifest after RO-Crate prune")?;
    }

    // Execution lineage: best-effort `git log` of the source working tree.
    if src.join(".git").exists() {
        write_execution_lineage(src, dst);
    }

    Ok(ExportReport {
        kept,
        dropped,
        dst: dst.to_path_buf(),
    })
}

/// Write `dst/runtime/execution-lineage.txt` from `git -C <src> log --stat
/// --no-color`. Best-effort: any failure (git absent, not a repo, write error)
/// is swallowed — the lineage file is a convenience, not a correctness
/// guarantee, and the export is already self-consistent without it.
fn write_execution_lineage(src: &Path, dst: &Path) {
    let output = match std::process::Command::new("git")
        .arg("-C")
        .arg(src)
        .args(["log", "--stat", "--no-color"])
        .output()
    {
        Ok(o) if o.status.success() => o.stdout,
        _ => return,
    };
    let runtime_dir = dst.join("runtime");
    if std::fs::create_dir_all(&runtime_dir).is_err() {
        return;
    }
    let _ = std::fs::write(runtime_dir.join("execution-lineage.txt"), output);
}

/// Drop `@graph` entries from `dst/ro-crate-metadata.json` whose `@id` is a
/// package-relative path that does not exist on disk under `dst`.
///
/// Only entries whose `@id` looks like a package-relative file/dir path are
/// candidates: fragment ids (`#…`), absolute IRIs (`http://…` / `https://…`),
/// and the root self-reference (`./`) are always retained. A directory id
/// (trailing `/`) is kept iff the directory exists. Returns the number of
/// entries removed. No-op (`Ok(0)`) when the descriptor is missing or
/// unparseable.
fn prune_rocrate_dangling(dst: &Path) -> Result<usize> {
    use serde_json::Value;

    let descriptor = dst.join("ro-crate-metadata.json");
    let Ok(bytes) = std::fs::read(&descriptor) else {
        return Ok(0);
    };
    let Ok(mut doc) = serde_json::from_slice::<Value>(&bytes) else {
        return Ok(0);
    };
    let Some(graph) = doc.get_mut("@graph").and_then(Value::as_array_mut) else {
        return Ok(0);
    };

    // A package-relative `@id` dangles iff its target is absent on disk under
    // `dst`; the crate root (`./`), `#`-fragment entities, and absolute IRIs
    // are never path-backed and are always kept.
    let is_dangling = |id: &str| -> bool {
        if id == "./"
            || id.starts_with('#')
            || id.starts_with("http://")
            || id.starts_with("https://")
        {
            return false;
        }
        // A directory id carries a trailing `/`; `Path::exists` handles both.
        !dst.join(id.trim_end_matches('/')).exists()
    };

    // First pass: collect the ids that will be pruned, so the second pass can
    // also scrub references TO them. A dropped file's `@id` left inside another
    // entry's `hasPart`/`object`/`result` array dangles, and consumers (e.g.
    // runcrate) choke on the unresolvable reference.
    let pruned: std::collections::HashSet<String> = graph
        .iter()
        .filter_map(|e| e.get("@id").and_then(Value::as_str))
        .filter(|id| is_dangling(id))
        .map(String::from)
        .collect();

    let before = graph.len();
    graph.retain(|entry| {
        entry
            .get("@id")
            .and_then(Value::as_str)
            .is_none_or(|id| !pruned.contains(id))
    });
    let removed = before - graph.len();

    // Second pass: scrub references to pruned ids from the surviving entries so
    // no `hasPart`/`object`/`result`/… reference points at a dropped node.
    if !pruned.is_empty() {
        let is_pruned_ref = |v: &Value| -> bool {
            v.get("@id")
                .and_then(Value::as_str)
                .is_some_and(|id| pruned.contains(id))
        };
        for entry in graph.iter_mut() {
            let Some(obj) = entry.as_object_mut() else {
                continue;
            };
            let keys: Vec<String> = obj.keys().cloned().collect();
            for k in keys {
                match obj.get_mut(&k) {
                    Some(Value::Array(arr)) => arr.retain(|it| !is_pruned_ref(it)),
                    Some(v) if is_pruned_ref(v) => {
                        obj.remove(&k);
                    }
                    _ => {}
                }
            }
        }
    }

    if removed > 0 {
        let serialized = serde_json::to_vec_pretty(&doc)
            .context("re-serializing pruned ro-crate-metadata.json")?;
        std::fs::write(&descriptor, serialized)
            .with_context(|| format!("writing pruned {}", descriptor.display()))?;
    }
    Ok(removed)
}

/// Write every file under `src_dir` into the zip writer `out` at its
/// `src_dir`-relative path, Deflated. Directories are emitted as explicit
/// entries (trailing `/`) so empty dirs survive the round-trip; entries are
/// written in sorted order for determinism.
pub fn zip_dir(src_dir: &Path, out: &mut (impl std::io::Write + std::io::Seek)) -> Result<()> {
    use std::io::Read;
    use zip::write::SimpleFileOptions;

    let mut writer = zip::ZipWriter::new(out);
    let options = SimpleFileOptions::default().compression_method(zip::CompressionMethod::Deflated);

    for entry in walkdir::WalkDir::new(src_dir).sort_by_file_name() {
        let entry = entry.with_context(|| format!("walking {}", src_dir.display()))?;
        let abs = entry.path();
        let rel = abs
            .strip_prefix(src_dir)
            .with_context(|| format!("stripping {} from {}", src_dir.display(), abs.display()))?;
        if rel.as_os_str().is_empty() {
            // The root dir itself — no entry.
            continue;
        }
        let rel_str = rel.to_string_lossy().replace('\\', "/");

        if entry.file_type().is_dir() {
            writer
                .add_directory(format!("{rel_str}/"), options)
                .with_context(|| format!("adding zip directory {rel_str}"))?;
        } else if entry.file_type().is_file() {
            writer
                .start_file(&rel_str, options)
                .with_context(|| format!("starting zip entry {rel_str}"))?;
            let mut f = std::fs::File::open(abs)
                .with_context(|| format!("opening {}", abs.display()))?;
            let mut buf = Vec::new();
            f.read_to_end(&mut buf)
                .with_context(|| format!("reading {}", abs.display()))?;
            std::io::Write::write_all(&mut writer, &buf)
                .with_context(|| format!("writing zip entry {rel_str}"))?;
        }
    }

    writer.finish().context("finalizing zip archive")?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::{Cursor, Read};

    // --- Task 1: tier classifier ----------------------------------------

    #[test]
    fn classify_maps_paths_to_expected_tiers() {
        let cases: &[(&str, DepositTier)] = &[
            (
                "runtime/outputs/differential_expression/de_results.tsv",
                DepositTier::A,
            ),
            ("runtime/outputs/x/agent-claude.log", DepositTier::C),
            ("runtime/cache/conda-envs/e/f", DepositTier::E),
            ("runtime/r-libs/DESeq2/DESCRIPTION", DepositTier::E),
            ("runtime/outputs/x/scripts/01.R", DepositTier::B),
            ("runtime/outputs/x/env.lock", DepositTier::B),
            ("manifest-sha512.txt", DepositTier::D),
            (".git/config", DepositTier::E),
            ("runtime/outputs/x/intermediates/t.tsv", DepositTier::E),
            (
                "runtime/outputs/x/state.patch.applied.json",
                DepositTier::C,
            ),
            ("ro-crate-metadata.json", DepositTier::A),
        ];
        for (path, expected) in cases {
            let got = classify(Path::new(path));
            assert_eq!(
                got, *expected,
                "classify({path:?}) = {got:?}, expected {expected:?}"
            );
        }
    }

    #[test]
    fn is_kept_keeps_a_and_b_only() {
        assert!(is_kept(DepositTier::A), "tier A must be kept");
        assert!(is_kept(DepositTier::B), "tier B must be kept");
        assert!(!is_kept(DepositTier::C), "tier C must be dropped");
        assert!(!is_kept(DepositTier::D), "tier D must be dropped");
        assert!(!is_kept(DepositTier::E), "tier E must be dropped");
    }

    // --- Task 2: export_depositable_package ------------------------------

    /// Build a tiny fixture package under `root` exercising each tier.
    fn build_fixture_package(root: &Path) {
        let write = |rel: &str, body: &str| {
            let p = root.join(rel);
            std::fs::create_dir_all(p.parent().expect("fixture path has parent"))
                .expect("create fixture parent dir");
            std::fs::write(&p, body).expect("write fixture file");
        };
        write("runtime/outputs/t/de_results.tsv", "gene\tpadj\nA\t0.01\n"); // A
        write("runtime/outputs/t/agent-claude.log", "log line\n"); // C
        write("runtime/cache/x/y", "cached bytes\n"); // E
        write("runtime/outputs/t/scripts/s.R", "print('hi')\n"); // B
        write(".git/config", "[core]\n"); // E / explicit .git skip
        write("manifest-sha512.txt", "stale manifest\n"); // D
        write(
            "ro-crate-metadata.json",
            r#"{"@context":"https://w3id.org/ro/crate/1.1/context","@graph":[{"@id":"ro-crate-metadata.json","@type":"CreativeWork","about":{"@id":"./"}},{"@id":"./","@type":"Dataset","hasPart":[]}]}"#,
        ); // A
        write("bagit.txt", "BagIt-Version: 1.0\nTag-File-Character-Encoding: UTF-8\n");
    }

    #[test]
    fn export_copies_only_a_and_b_and_reseals() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let src = tmp.path().join("src");
        let dst = tmp.path().join("dst");
        build_fixture_package(&src);

        let report = export_depositable_package(&src, &dst).expect("export succeeds");

        // A + B present.
        assert!(
            dst.join("runtime/outputs/t/de_results.tsv").is_file(),
            "tier-A de_results.tsv must be copied"
        );
        assert!(
            dst.join("runtime/outputs/t/scripts/s.R").is_file(),
            "tier-B scripts/s.R must be copied"
        );
        assert!(
            dst.join("ro-crate-metadata.json").is_file(),
            "tier-A ro-crate-metadata.json must be copied"
        );
        // C / E / .git absent.
        assert!(
            !dst.join("runtime/outputs/t/agent-claude.log").exists(),
            "tier-C log must NOT be copied"
        );
        assert!(
            !dst.join("runtime/cache").exists(),
            "tier-E runtime/cache must NOT be copied"
        );
        assert!(
            !dst.join(".git").exists(),
            ".git must NOT be copied"
        );

        // The manifest was regenerated (D is skipped at copy then rebuilt by
        // reseal): it exists and lists the kept files only.
        let manifest_path = dst.join("manifest-sha512.txt");
        assert!(manifest_path.is_file(), "manifest-sha512.txt must be regenerated");
        let manifest = std::fs::read_to_string(&manifest_path).expect("read manifest");
        assert!(
            manifest.contains("runtime/outputs/t/de_results.tsv"),
            "manifest must list kept tier-A table, got:\n{manifest}"
        );
        assert!(
            !manifest.contains("agent-claude.log"),
            "manifest must NOT list the dropped tier-C log, got:\n{manifest}"
        );
        assert!(
            !manifest.contains("runtime/cache"),
            "manifest must NOT list dropped tier-E cache, got:\n{manifest}"
        );

        // No path in dst classifies as C/D/E except regenerated D manifests.
        for entry in walkdir::WalkDir::new(&dst) {
            let entry = entry.expect("walk dst");
            if !entry.file_type().is_file() {
                continue;
            }
            let rel = entry.path().strip_prefix(&dst).expect("strip dst");
            let tier = classify(rel);
            let basename = rel.file_name().unwrap_or_default().to_string_lossy();
            let is_regenerated_manifest =
                basename == "manifest-sha512.txt" || basename == "tagmanifest-sha512.txt";
            assert!(
                is_kept(tier) || is_regenerated_manifest,
                "exported file {} classified as {:?} but is not a regenerated manifest",
                rel.display(),
                tier
            );
        }

        assert!(report.kept >= 3, "expected >=3 kept files, got {}", report.kept);
        assert!(report.dropped >= 3, "expected >=3 dropped files, got {}", report.dropped);
        assert_eq!(report.dst, dst, "report.dst must echo the dst arg");
    }

    #[test]
    fn prune_rocrate_drops_absent_keeps_present() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let dst = tmp.path();

        // A present file and an absent file, both referenced in @graph.
        std::fs::write(dst.join("present.tsv"), "x\n").expect("write present file");
        let descriptor = r##"{
          "@graph": [
            {"@id": "ro-crate-metadata.json", "@type": "CreativeWork"},
            {"@id": "./", "@type": "Dataset", "hasPart": [{"@id": "present.tsv"}, {"@id": "removed.log"}]},
            {"@id": "#step-x", "@type": "HowToStep", "result": {"@id": "removed.log"}},
            {"@id": "https://w3id.org/ro/crate/1.1", "@type": "CreativeWork"},
            {"@id": "present.tsv", "@type": "File"},
            {"@id": "removed.log", "@type": "File"}
          ]
        }"##;
        std::fs::write(dst.join("ro-crate-metadata.json"), descriptor)
            .expect("write descriptor");

        let removed = prune_rocrate_dangling(dst).expect("prune succeeds");
        assert_eq!(removed, 1, "exactly the absent removed.log entry must be pruned");

        let doc: serde_json::Value = serde_json::from_slice(
            &std::fs::read(dst.join("ro-crate-metadata.json")).expect("read pruned descriptor"),
        )
        .expect("parse pruned descriptor");
        let ids: Vec<&str> = doc["@graph"]
            .as_array()
            .expect("graph array")
            .iter()
            .filter_map(|e| e["@id"].as_str())
            .collect();
        assert!(ids.contains(&"present.tsv"), "present file entry must be kept");
        assert!(!ids.contains(&"removed.log"), "absent file entry must be dropped");
        assert!(ids.contains(&"#step-x"), "fragment id must be kept");
        assert!(
            ids.contains(&"https://w3id.org/ro/crate/1.1"),
            "IRI id must be kept"
        );
        assert!(ids.contains(&"./"), "root self-reference must be kept");

        // Reference scrub: no surviving entry may still reference the pruned id
        // (else consumers like runcrate choke on the unresolvable @id).
        let graph = doc["@graph"].as_array().expect("graph array");
        let root = graph
            .iter()
            .find(|e| e["@id"] == "./")
            .expect("root entry");
        let has_part: Vec<&str> = root["hasPart"]
            .as_array()
            .map(|a| a.iter().filter_map(|x| x["@id"].as_str()).collect())
            .unwrap_or_default();
        assert!(
            !has_part.contains(&"removed.log"),
            "pruned id must be scrubbed from hasPart, got {has_part:?}"
        );
        assert!(
            has_part.contains(&"present.tsv"),
            "present ref must survive in hasPart, got {has_part:?}"
        );
        let step = graph
            .iter()
            .find(|e| e["@id"] == "#step-x")
            .expect("step entry");
        assert!(
            step.get("result").is_none(),
            "a single-object reference to the pruned id must be removed, got {step:?}"
        );
    }

    // --- Task 3: zip_dir round-trip --------------------------------------

    #[test]
    fn zip_dir_round_trips() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let src = tmp.path().join("tree");
        std::fs::create_dir_all(src.join("sub")).expect("create sub dir");
        std::fs::write(src.join("a.txt"), b"alpha contents").expect("write a.txt");
        std::fs::write(src.join("sub/b.txt"), b"beta contents").expect("write b.txt");

        let mut cursor = Cursor::new(Vec::new());
        zip_dir(&src, &mut cursor).expect("zip_dir succeeds");

        let mut archive = zip::ZipArchive::new(cursor).expect("re-open zip");
        let read_entry = |archive: &mut zip::ZipArchive<Cursor<Vec<u8>>>, name: &str| -> Vec<u8> {
            let mut f = archive
                .by_name(name)
                .unwrap_or_else(|_| panic!("entry {name} present in archive"));
            let mut buf = Vec::new();
            f.read_to_end(&mut buf).expect("read zip entry");
            buf
        };
        assert_eq!(
            read_entry(&mut archive, "a.txt"),
            b"alpha contents",
            "a.txt bytes must round-trip"
        );
        assert_eq!(
            read_entry(&mut archive, "sub/b.txt"),
            b"beta contents",
            "sub/b.txt bytes must round-trip"
        );
    }
}
