//! Depositable-package export.
//!
//! A completed ECAA package carries two kinds of content side by side: the
//! audit / review / re-execution surface a depositor wants to archive, and a
//! pile of reproducible bloat (conda caches, R libraries, `__pycache__`,
//! per-run logs, heartbeats, `.git`) that is large, host-specific, and
//! regenerable. The exporter copies only the keep-tiers (A + B) into a clean
//! tree, re-seals the BagIt manifest + RO-Crate over that smaller payload, and
//! strips the version-control internals — yielding a deposit-ready directory
//! that [`zip_dir`] packs into a single `.zip` for the web download / CLI.
//!
//! Tier policy (single source of truth — see `depositable-export-plan.md`):
//! classification is by package-relative path, first match wins (E, C, D, B,
//! then A). A file is copied iff its tier is A or B ([`is_kept`]); C / D / E and
//! `.git/` are dropped (D is regenerated by the post-copy reseal).

use anyhow::{Context, Result};
use std::path::{Path, PathBuf};

/// Deposit tier of a package-relative path. Order of the variants is the
/// first-match classification order documented on [`classify`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum DepositTier {
    /// Keep (everything else): result tables, `*.md` reports, `figures/`,
    /// `evidence/` snapshots, verdict + provenance JSON/JSONL, per-task
    /// result/spec/validation JSON, `policies/`, `lib/`, crate substrate
    /// (`ro-crate-metadata.json`, `WORKFLOW.json`, `bagit.txt`, …).
    /// (`view_data/` is Tier C — a regenerable UI projection, dropped.)
    A,
    /// Keep (re-execution): anything under `…/scripts/`, `env.lock`,
    /// `agent-code.json`, `runtime/plotting{,_r}/*`, `inputs/*`, `counts.tsv`,
    /// `samples.csv`.
    B,
    /// Drop (operational): per-run logs, heartbeats, container/agent state.
    C,
    /// Regenerate (skip copy; rebuilt by the post-copy reseal): the BagIt
    /// payload + tag manifests.
    D,
    /// Drop (reproducible bloat): caches, R libraries, `.git/`, compiled
    /// Python, `__pycache__/`, intermediates.
    E,
}

/// Whether a file of tier `t` is copied into the depositable export.
///
/// True for tiers A and B (the audit/review/deposit + re-execution surface),
/// false for C (operational), D (regenerated by reseal), and E (reproducible
/// bloat).
pub(crate) fn is_kept(t: DepositTier) -> bool {
    matches!(t, DepositTier::A | DepositTier::B)
}

/// Classify a package-relative path into its [`DepositTier`].
///
/// Classification is purely lexical (no filesystem access) and uses a fixed
/// first-match order: **E, then C, then D, then B, then A**. `rel` MUST be a
/// path relative to the package root (e.g.
/// `runtime/outputs/de/de_results.tsv`), using `/` separators; an absolute or
/// `..`-bearing path is classified on its components as given.
pub(crate) fn classify(rel: &Path) -> DepositTier {
    // Normalize once to a `/`-joined lossy string for substring containment
    // checks, and collect components for directory-name membership tests. Both
    // are needed: containment catches `…/cache/…` / `…/intermediates/…` at any
    // depth, while the basename match keys off `rel.file_name()`.
    let rel_str = rel.to_string_lossy().replace('\\', "/");
    let basename = rel
        .file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .unwrap_or_default();

    // A path component equals `name` anywhere in `rel` (so `cache`, `.git`,
    // `__pycache__`, `intermediates` match at any depth, not just as a
    // substring of some longer component).
    let has_component = |name: &str| {
        rel.components().any(|c| {
            matches!(c, std::path::Component::Normal(s) if s.to_string_lossy() == name)
        })
    };

    // --- Tier E — drop (reproducible bloat) ------------------------------
    // runtime/cache/, runtime/r-libs/, any …/cache/…, .git/, *.pyc,
    // __pycache__/, any …/intermediates/….
    if rel_str.starts_with("runtime/cache/")
        || rel_str == "runtime/cache"
        || rel_str.starts_with("runtime/r-libs/")
        || rel_str == "runtime/r-libs"
        || has_component("cache")
        || has_component(".git")
        || basename.ends_with(".pyc")
        || has_component("__pycache__")
        || has_component("intermediates")
    {
        return DepositTier::E;
    }

    // --- Tier C — drop (operational) -------------------------------------
    // `view_data/` holds UI-render JSON projections of the result tables
    // (e.g. `view_data/mean_variance.json` is a plot-ready re-encoding of
    // `mean_variance.tsv`). It is read only by the live server Dashboard,
    // is NOT a registered RO-Crate `@id`, and is not consumed by
    // re-execution — so it is operational bloat for a deposit. The
    // human-readable `.tsv`/`.csv` source of truth and the rendered
    // `figures/` are kept; the regenerable JSON projection is dropped.
    if basename.ends_with(".log")
        || basename == ".heartbeat"
        || basename == ".container-state.json"
        || basename == "agent-usage.json"
        || basename == "state.patch.applied.json"
        || basename == ".blas-probe.json"
        || basename == ".sme-auto-approve-discoveries"
        || has_component("view_data")
        // Harness operational telemetry at the runtime root: per-run logs,
        // session metrics, harness health, the internal dispatch / invocation /
        // atom-picker logs, the package install transcript, the orphan-policy
        // open-sweep sink, and the harness exit-status file. None is consumed by
        // re-execution or by the audit-proof / claim-verifier (which read
        // decisions.jsonl / proofs.jsonl / claim-verification.json / …), so they
        // are operational bloat for a deposit. The audit & provenance sidecars
        // (audit-proof-report.json, claim-verification.json, decisions.jsonl,
        // proofs.jsonl, assumptions.jsonl, validation-*, cost-ledger.jsonl,
        // repair-*, reexecution.json, …) are deliberately NOT listed here and
        // stay Tier A. Anchored to the `runtime/` root so a same-named file in a
        // task output dir is never matched by accident.
        || rel_str == "runtime/LOG.jsonl"
        || rel_str == "runtime/invocations.jsonl"
        || rel_str == "runtime/dispatches.jsonl"
        || rel_str == "runtime/session-metrics.jsonl"
        || rel_str == "runtime/harness-health.json"
        || rel_str == "runtime/install-log.jsonl"
        || rel_str == "runtime/picker-decisions.jsonl"
        || rel_str == "runtime/policy-opens.jsonl"
        || rel_str == "runtime/.execution_status.json"
    {
        return DepositTier::C;
    }

    // --- Tier D — regenerate (skip copy; rebuilt by reseal) --------------
    if basename == "manifest-sha512.txt" || basename == "tagmanifest-sha512.txt" {
        return DepositTier::D;
    }

    // --- Tier B — keep (re-execution) ------------------------------------
    if has_component("scripts")
        || basename == "env.lock"
        || basename == "agent-code.json"
        || rel_str.starts_with("runtime/plotting/")
        || rel_str.starts_with("runtime/plotting_r/")
        || rel_str.starts_with("inputs/")
        || basename == "counts.tsv"
        || basename == "samples.csv"
    {
        return DepositTier::B;
    }

    // --- Tier A — keep (everything else) ---------------------------------
    DepositTier::A
}

/// Outcome of an [`export_depositable_package`] run.
pub struct ExportReport {
    /// Number of source files copied into the export (tier A + B).
    pub kept: usize,
    /// Number of source files dropped (tier C, D, E, and anything under
    /// `.git/`).
    pub dropped: usize,
    /// Root of the export tree on disk (echoes the `dst` argument).
    pub dst: PathBuf,
}

/// Which surface of a completed package a deposit export carries.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum DepositProfile {
    /// Everything Tier A+B (the historical default): audit + re-execution + all
    /// policy docs and conventional crate components.
    #[default]
    Full,
    /// Lean re-executable: `Full` minus the policy-doc catalog and the
    /// redundant/convenience artifacts (`package.ttl`, `ro-crate-preview.html`,
    /// the `execution-lineage.txt` git-log, `ed-cf-self-assessment.json`). Keeps
    /// the re-execution tier; still replays — the container snapshot digest lives
    /// in each task's `determinism-env.json`, not `policies/container.json`.
    ReExecutable,
    /// Minimal audit/review: `ReExecutable` minus the re-execution tier (per-task
    /// `scripts/`, `env.lock`, the plotting environments, raw `inputs/`, `lib/`).
    /// Carries the accountability + provenance surface needed to re-verify every
    /// recorded verdict offline, with nothing to replay.
    MinimalAudit,
}

impl std::str::FromStr for DepositProfile {
    type Err = String;
    fn from_str(s: &str) -> std::result::Result<Self, Self::Err> {
        match s.trim().to_ascii_lowercase().replace('_', "-").as_str() {
            "full" => Ok(Self::Full),
            "re-executable" | "reexecutable" | "executable" => Ok(Self::ReExecutable),
            "minimal" | "minimal-audit" | "audit" => Ok(Self::MinimalAudit),
            other => Err(format!(
                "unknown deposit profile {other:?} (expected: full, re-executable, minimal)"
            )),
        }
    }
}

impl std::fmt::Display for DepositProfile {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            Self::Full => "full",
            Self::ReExecutable => "re-executable",
            Self::MinimalAudit => "minimal",
        })
    }
}

/// Serialized binary compute objects an analysis stage writes to pass state
/// downstream (or as working scratch): R/Python/HDF5 matrix + model
/// serializations and alignment binaries. These are **never** registered as a
/// V result `Table` — [`crate::ro_crate::register_produced_output_tables`]'
/// `collect_output_tables` only registers `.tsv` / `.csv` / `.parquet`, so a
/// serialized object can only ever be a zero-dark `File` entity, never a
/// `CreateAction` `result`. They are re-execution working state, not part of the
/// audit/result surface — out of scope for the `MinimalAudit` ("audit-complete,
/// NOT re-executable") profile. Matched case-insensitively on the basename so
/// new stages/layouts are covered automatically (not a per-path blocklist).
const SERIALIZED_OBJECT_EXTS: &[&str] = &[
    ".rds", ".rdata", ".h5", ".h5ad", ".hdf5", ".loom", ".npy", ".npz", ".pkl", ".pickle",
    ".joblib", ".feather", ".arrow", ".mtx", ".mtx.gz", ".bam", ".cram", ".bai", ".crai",
    ".bw", ".bigwig", ".bigbed", ".2bit",
];

/// Package-relative `@id`s the source `ro-crate-metadata.json` references as a
/// `CreateAction` `result` or `object` (PROV `used`). These are
/// provenance-load-bearing: dropping one would dangle a `result`/`object` edge
/// and break Provenance Run Crate conformance, so the lean-profile working-data
/// drop ([`profile_extra_drop`]) never removes a path in this set. Read once
/// from `src` before the copy loop. Best-effort: a missing/unparseable
/// descriptor yields an empty set (then the working-data drop applies only to the
/// serialized-object class, which is never a `result` anyway — still safe).
fn collect_provenance_referenced_paths(src: &Path) -> std::collections::BTreeSet<String> {
    use serde_json::Value;
    let mut out = std::collections::BTreeSet::new();
    let Ok(bytes) = std::fs::read(src.join("ro-crate-metadata.json")) else {
        return out;
    };
    let Ok(doc) = serde_json::from_slice::<Value>(&bytes) else {
        return out;
    };
    let Some(graph) = doc.get("@graph").and_then(Value::as_array) else {
        return out;
    };
    let is_action = |e: &Value| match e.get("@type") {
        Some(Value::String(s)) => s == "CreateAction",
        Some(Value::Array(a)) => a.iter().any(|t| t.as_str() == Some("CreateAction")),
        _ => false,
    };
    let mut add_ref = |out: &mut std::collections::BTreeSet<String>, v: &Value| match v {
        Value::Object(o) => {
            if let Some(id) = o.get("@id").and_then(Value::as_str) {
                out.insert(id.to_string());
            }
        }
        Value::Array(a) => {
            for x in a {
                if let Some(id) = x.get("@id").and_then(Value::as_str) {
                    out.insert(id.to_string());
                }
            }
        }
        _ => {}
    };
    for e in graph.iter().filter(|e| is_action(e)) {
        if let Some(r) = e.get("result") {
            add_ref(&mut out, r);
        }
        if let Some(o) = e.get("object") {
            add_ref(&mut out, o);
        }
    }
    out
}

/// Keep the shipped per-run conda env (`runtime/cache/conda-envs/…`) for the
/// re-execution-bearing profiles (`Full`, `ReExecutable`), overriding its
/// Tier-E (`runtime/cache/`) classification.
///
/// When the analysis libraries were materialised into a per-run conda env at
/// execution time (e.g. R + DESeq2 under `ecaa-bioc`) rather than baked into the
/// container image, that env IS the re-execution runtime — dropping it as
/// "regenerable cache" would make the deposit non-replayable, breaking the
/// profile's "still replays" contract. `MinimalAudit` (audit-only, explicitly
/// NOT re-executable) still drops it via the ordinary Tier-E gate.
/// Recreate a symlink `link` pointing at `target` (verbatim). Unix uses a real
/// symlink; other platforms have no portable equivalent for arbitrary targets,
/// so this is a no-op-safe error there (the deposit paths are Unix in practice).
#[cfg(unix)]
fn symlink_verbatim(target: &Path, link: &Path) -> std::io::Result<()> {
    std::os::unix::fs::symlink(target, link)
}

#[cfg(not(unix))]
fn symlink_verbatim(_target: &Path, _link: &Path) -> std::io::Result<()> {
    Err(std::io::Error::new(
        std::io::ErrorKind::Unsupported,
        "symlink recreation is only supported on Unix",
    ))
}

/// Extra per-profile drop, applied on top of the [`is_kept`] tier gate. `Full`
/// drops nothing extra. The lean profiles drop the policy-doc catalog and the
/// redundant/convenience artifacts the deposit adversarial audit flagged as
/// needed for neither re-execution nor auditability; `MinimalAudit` additionally
/// drops the re-execution tier AND the re-execution **working data** that lives
/// under stage-output subdirs (serialized binary objects + re-staged inputs),
/// gated on `protected` so no provenance-load-bearing output is removed.
fn profile_extra_drop(
    profile: DepositProfile,
    rel: &Path,
    protected: &std::collections::BTreeSet<String>,
) -> bool {
    if matches!(profile, DepositProfile::Full) {
        return false;
    }
    let rel_str = rel.to_string_lossy().replace('\\', "/");
    let basename = rel
        .file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .unwrap_or_default();
    let has_component = |name: &str| {
        rel.components()
            .any(|c| matches!(c, std::path::Component::Normal(s) if s.to_string_lossy() == name))
    };
    // Lean profiles (re-executable + minimal): the policy-doc catalog + the
    // redundant Turtle copy, the human preview, the informational
    // self-assessment, and the informational git-log lineage. The lineage is
    // also skipped at the write site, but dropping it here as well makes the
    // exclusion robust when the *source* already carries one (e.g. re-exporting
    // a previously-exported full deposit, which appends it post-copy).
    if rel_str.starts_with("policies/")
        || rel_str == "package.ttl"
        || rel_str == "ro-crate-preview.html"
        || rel_str == "runtime/ed-cf-self-assessment.json"
        || rel_str == "runtime/execution-lineage.txt"
    {
        return true;
    }
    // Minimal only: also drop the re-execution tier …
    if matches!(profile, DepositProfile::MinimalAudit) {
        if has_component("scripts")
            || basename == "env.lock"
            || rel_str.starts_with("runtime/plotting/")
            || rel_str.starts_with("runtime/plotting_r/")
            || rel_str.starts_with("inputs/")
            || rel_str.starts_with("lib/")
        {
            return true;
        }
        // … and the operational / duplicate / redundant sidecars that are not in
        // the RO-Crate `@graph`, not read by `replay --tier verify`, and have no
        // analog in real deposited crates. Per-task re-execution captures, input
        // provisioning, figure manifests, the task-spec (duplicated in
        // WORKFLOW.json), navigation indexes/summaries (ARTIFACTS.md supersedes),
        // the repair process detail (repair-status + AUDIT-REPORT carry the
        // audit need), and the tiny choice records duplicated in decisions.jsonl.
        // Duplicate-format figures: the PNGs are registered in the `@graph`, the
        // PDFs are not — drop the dark duplicate (full / re-executable keep both).
        let under_outputs = rel_str.starts_with("runtime/outputs/");
        if (under_outputs && basename == "manifest.json")
            || basename == "determinism-env.json"
            || basename == "provisioning.json"
            || basename == "task-spec.json"
            || basename == "sme-selection.json"
            || rel_str.ends_with(".pdf")
            || (under_outputs
                && (basename.ends_with("_index.json")
                    || basename.ends_with("_summary.json")
                    || basename == "summary_stats.json"))
            || rel_str == "runtime/claim-repair-plan.json"
            || rel_str == "runtime/repair-log.jsonl"
            || rel_str == "runtime/repair-requests.jsonl"
            || rel_str == "runtime/typed-blocker.json"
            || rel_str == "runtime/validation-warnings.jsonl"
            || rel_str == "runtime/env_capability.json"
            || basename.starts_with("sme-review-confirmed")
            // The verifier's low-level type-unification trace (~1 MB): its
            // conclusions are the proven edges in proofs.jsonl + AUDIT-REPORT.md;
            // the trace itself is verifier-debug, not science provenance.
            || rel_str == "runtime/verifier-decisions.jsonl"
            // Dependency lock = re-execution metadata; the audit-only minimal
            // already drops the re-execution tier, and the deps are declared as
            // `#dep/*` SoftwareApplication entities in the `@graph`.
            || rel_str == "runtime/dependency-lock.json"
        {
            return true;
        }
        // Re-execution WORKING DATA under stage-output subdirs. The classifier's
        // tier-E `intermediates/` drop and the top-level `inputs/` drop above
        // catch the conventional locations, but a stage is free to write large
        // working data anywhere under its own `runtime/outputs/<stage>/…` dir,
        // where it lands in Tier A ("keep everything else"). On data-heavy
        // analyses this dominates the deposit (e.g. an scRNA SCT-residuals
        // `.rds`, or re-staged multi-omic input matrices) — defeating the
        // "minimal" intent. The `MinimalAudit` profile is audit-complete and
        // explicitly NOT re-executable, so this working data is out of scope.
        //
        // Two intrinsic classes, BOTH gated on `protected` (the source graph's
        // CreateAction `result`/`object` set) so a provenance-load-bearing output
        // is never dropped — that would dangle an edge and fail Provenance Run
        // Crate. The post-copy prune then scrubs each dropped file's zero-dark
        // `File` node, preserving the zero-dark-payload invariant.
        if under_outputs && !protected.contains(rel_str.as_str()) {
            // (a) serialized binary compute objects (matrices / model objects /
            //     alignments) — never a registered result table, pure
            //     re-execution working state. Matched on the file's intrinsic
            //     type, not a path, so new stages are covered automatically.
            let lc = basename.to_ascii_lowercase();
            if SERIALIZED_OBJECT_EXTS.iter().any(|e| lc.ends_with(e)) {
                return true;
            }
            // (b) re-staged raw inputs / fetched references: `data_acquisition`
            //     (and other stages) copy SME inputs + downloaded references into
            //     a `…/<stage>/data/` subdir. These are re-fetchable from source
            //     and not part of the audit/result surface — the produced,
            //     registered output copies (which ARE in `protected`) are kept.
            if has_component("data") {
                return true;
            }
        }
    }
    false
}

/// Export the A+B-tier (audit/review/deposit + re-execution) surface of the
/// package at `src` into a clean deposit-ready tree at `dst`.
///
/// Steps:
/// 1. Walk `src` recursively; copy each file whose tier [`is_kept`] to
///    `dst/<rel>`, preserving layout (parent dirs created on demand). `.git/`
///    is skipped explicitly (it is also tier E, but the explicit skip avoids
///    walking thousands of loose objects).
/// 2. Re-seal the BagIt manifest over `dst` (rebuilds `manifest-sha512.txt` +
///    `tagmanifest-sha512.txt` over the kept set) via the existing
///    [`crate::emitter::regenerate_bagit_manifest`] with a wall clock.
/// 3. Re-register produced output tables, then prune `@graph` entries whose
///    `@id` is a package-relative path absent on disk in `dst`
///    ([`prune_rocrate_dangling`]) so `ro-crate-metadata.json` carries no
///    dangling reference to a dropped C/D/E file. The prune mutates a
///    manifested file, so the BagIt manifest is re-sealed once more afterwards.
/// 4. Re-record `runtime/audit-proof-report.json` over the (now pruned)
///    deposit graph via [`super::ecaa::write_audit_proof_report`], so the
///    recorded verdicts a downloader reads agree with the fresh verdicts their
///    offline `replay` recomputes over the same graph — the prune in step 3
///    drops the embedded Claim / InvariantVerdict nodes, so the source
///    package's report would otherwise ship a stale `cross_graph_integrity`
///    verdict about nodes the deposit no longer carries. The report is BagIt-
///    manifest-excluded, so no re-seal is needed.
/// 5. Write `dst/AUDIT-REPORT.md` — a human-readable Markdown summary of the
///    audit/provenance sidecars (claim verification, audit-proof invariants,
///    decisions, assumptions, typed proofs, validation, re-execution, repair,
///    cost) — and re-seal once more to fold it into the manifest. Runs after
///    step 4 so its invariant table reflects the deposit's own verdicts.
/// 6. (`Full` profile only) If `src/.git` exists, write
///    `dst/runtime/execution-lineage.txt` from `git -C <src> log --stat
///    --no-color` (best-effort; ignored if git is absent or fails).
pub fn export_depositable_package(src: &Path, dst: &Path) -> Result<ExportReport> {
    export_depositable_package_with_profile(src, dst, DepositProfile::Full)
}

/// [`export_depositable_package`] with an explicit [`DepositProfile`]. `Full`
/// reproduces the historical behavior; the lean profiles additionally apply
/// [`profile_extra_drop`] in the copy loop and skip the execution-lineage write.
pub fn export_depositable_package_with_profile(
    src: &Path,
    dst: &Path,
    profile: DepositProfile,
) -> Result<ExportReport> {
    use crate::clock::WallClock;

    std::fs::create_dir_all(dst)
        .with_context(|| format!("creating export destination {}", dst.display()))?;

    let mut kept = 0usize;
    let mut dropped = 0usize;

    // Provenance-load-bearing paths (CreateAction result/object) from the source
    // graph — the lean-profile working-data drop must never remove one. Read once
    // up front (empty for `Full`, which drops nothing extra anyway).
    let protected = if matches!(profile, DepositProfile::Full) {
        std::collections::BTreeSet::new()
    } else {
        collect_provenance_referenced_paths(src)
    };

    // Walk source; copy only kept (A+B) files, preserving layout. `.git/` is
    // pruned at the directory level so the walk never descends into VCS
    // internals.
    for entry in walkdir::WalkDir::new(src)
        .sort_by_file_name()
        .into_iter()
        .filter_entry(|e| {
            // Skip the `.git` directory entirely (and any `.git` file).
            e.file_name() != std::ffi::OsStr::new(".git")
        })
    {
        let entry = entry.with_context(|| format!("walking {}", src.display()))?;
        let ft = entry.file_type();
        // Plain directories are created implicitly when their contents are
        // written. Symlinks (even to directories) are NOT skipped here: the
        // shipped conda env carries ~1.5k relative symlinks that must survive
        // the export or the env is broken. `WalkDir` does not follow symlinks,
        // so a symlinked dir is yielded once as a symlink and never descended.
        if ft.is_dir() {
            continue;
        }
        let abs = entry.path();
        let rel = abs
            .strip_prefix(src)
            .with_context(|| format!("stripping {} from {}", src.display(), abs.display()))?;

        let keep = is_kept(classify(rel)) && !profile_extra_drop(profile, rel, &protected);
        if !keep {
            dropped += 1;
            continue;
        }
        let dest_path = dst.join(rel);
        if let Some(parent) = dest_path.parent() {
            std::fs::create_dir_all(parent)
                .with_context(|| format!("creating {}", parent.display()))?;
        }
        if ft.is_symlink() {
            // Recreate the link verbatim; shipped conda-env targets are
            // relative and resolve after relocation. Idempotent over re-export.
            let target = std::fs::read_link(abs)
                .with_context(|| format!("reading symlink {}", abs.display()))?;
            let _ = std::fs::remove_file(&dest_path);
            symlink_verbatim(&target, &dest_path).with_context(|| {
                format!("recreating symlink {} -> {}", dest_path.display(), target.display())
            })?;
        } else {
            std::fs::copy(abs, &dest_path).with_context(|| {
                format!("copying {} -> {}", abs.display(), dest_path.display())
            })?;
        }
        kept += 1;
    }

    // Drop byte-data-duplicate output tables the per-task agent sometimes writes
    // under two names (e.g. `de_results.tsv` + `de_table.tsv`, identical data
    // rows differing only in the header). Runs after the copy and BEFORE the
    // reseal + RO-Crate prune below, so the manifest and `@graph` reflect the
    // deduplicated set; the prune then drops each deleted table's `@graph` File
    // entity and its `#action/<path>` CreateAction. Counted out of `kept`.
    let deduped = dedup_duplicate_output_tables(dst)
        .context("de-duplicating output tables over export")?;
    kept = kept.saturating_sub(deduped);
    dropped += deduped;

    // Minimal: drop per-task sidecars that carry NO information — `agent-code.json`
    // holding only the ~57 KB boilerplate prompt (empty `executed_code` +
    // `response_text`; redundant with PROMPT.md / AGENT-EXECUTOR.md / the
    // WORKFLOW.json task specs) and `curated_pools.json` that is all-empty arrays.
    // Content-aware, so a run that DOES record the agent's code, or a non-empty
    // pool set (e.g. the method-survey stage), is kept.
    if matches!(profile, DepositProfile::MinimalAudit) {
        let pruned = prune_content_empty_outputs(dst)
            .context("pruning content-empty per-task sidecars")?;
        kept = kept.saturating_sub(pruned);
        dropped += pruned;
    }

    // Re-seal BagIt over the kept set (rebuilds manifest + tagmanifest).
    let clock = WallClock;
    crate::emitter::regenerate_bagit_manifest(dst, &clock)
        .context("re-sealing BagIt manifest over export")?;

    // Re-finalize the RO-Crate over the export, then prune dangling @ids that
    // referenced dropped files. `register_produced_output_tables` is idempotent
    // and only ever adds entries for tables that ARE on disk, so it never
    // re-introduces a dangling reference.
    crate::ro_crate::register_produced_output_tables(dst)
        .map_err(anyhow::Error::from)
        .context("re-registering produced output tables over export")?;
    let pruned = prune_rocrate_dangling(dst).context("pruning dangling RO-Crate @ids")?;
    if pruned > 0 {
        // The prune rewrote `ro-crate-metadata.json` (a manifested file), so
        // re-seal once more to keep the BagIt manifest self-consistent.
        crate::emitter::regenerate_bagit_manifest(dst, &clock)
            .context("re-sealing BagIt manifest after RO-Crate prune")?;
    }

    // Re-record the audit-proof report against the deposit-scoped graph. The
    // prune above drops the embedded `C:*` Claim and `A:*` InvariantVerdict
    // nodes (their prefix-tagged `@id`s are not on-disk paths), so the
    // full-package report copied in from `src` can assert verdicts about graph
    // nodes the deposit no longer carries — most visibly a stale
    // `cross_graph_integrity = fail` whose dangling-`supported_by` Claim nodes
    // are gone, which a consumer's offline `replay` recomputes as `pass` and
    // flags as a recorded-vs-fresh divergence. Re-running the audit-proof here
    // computes the verdicts over the deposit as it actually ships, so the
    // "recorded" sidecar a downloader reads agrees with the "fresh" verdicts
    // their replay recomputes over the same graph. `write_audit_proof_report`
    // uses the same `NoopWrrocValidator` + `WallClock` path as that re-verify,
    // so recorded and fresh match by construction. Runs AFTER the prune so it
    // sees the final deposit graph; the report is on the BagIt manifest
    // exclusion list (`emitter::bagit`) and its `@graph` file node carries no
    // content hash, so rewriting it perturbs no seal (no re-seal required).
    super::ecaa::write_audit_proof_report(dst)
        .context("re-recording audit-proof report over the deposit graph")?;

    // Deposit readability transforms (all pure functions of the exported tree,
    // none touch the `@graph`): reorder `WORKFLOW.json` tasks into execution
    // order (execution-safe — the harness re-sorts `tasks` into a BTreeMap and
    // runs from `execution_order`), write the `ARTIFACTS.md` per-step file map,
    // and append the README navigation section. Each is best-effort + idempotent
    // and leaves its file untouched on any sanity-check failure.
    super::readability::reorder_workflow_tasks(dst)
        .context("reordering WORKFLOW.json tasks into execution order")?;
    super::readability::write_artifacts_manifest(dst)
        .context("writing ARTIFACTS.md over the deposit")?;

    // Human-readable Markdown summary of the audit/provenance sidecars, written
    // into every deposit so a reviewer gets the claim-verification, audit-proof
    // invariants, decisions, assumptions, typed proofs, validation, re-execution,
    // repair, and cost surface without reading JSON. Runs AFTER the audit-proof
    // re-record so its invariant table reflects the deposit's own verdicts.
    super::audit_report::write_audit_report(dst)
        .context("writing AUDIT-REPORT.md over the deposit")?;

    // README navigation section links AUDIT-REPORT.md + ARTIFACTS.md (just
    // written) and inlines the execution-order table; run last so its
    // existence checks see the artifacts above. A final reseal then folds the
    // reordered WORKFLOW.json + ARTIFACTS.md + AUDIT-REPORT.md + README into the
    // BagIt manifest (all derived deterministically, so the seal is stable).
    super::readability::augment_readme(dst)
        .context("augmenting README.md over the deposit")?;

    // Zero dark payload: register every kept file not yet in the RO-Crate
    // `@graph` as a `File` entity in the root `hasPart`, so the deposit declares
    // all of its payload (matching the discipline of the most detailed real-world
    // WRROC crates). Runs LAST, after every generated file (reordered
    // WORKFLOW.json, ARTIFACTS.md, AUDIT-REPORT.md, README) exists, so all are
    // captured. No re-prune follows — every registered `@id` is a file on disk.
    let registered = super::readability::register_deposit_entities(dst)
        .context("registering deposit payload into the RO-Crate @graph")?;

    // Adding `File` nodes for on-disk files does not change the audit-proof
    // invariants (they concern Claim / decision / proof / equivalence nodes, not
    // file completeness), but re-record over the now-final graph so the recorded
    // verdicts match a downloader's fresh `replay` exactly, then regenerate the
    // audit report so its `evaluated_at` matches the final report.
    if registered > 0 {
        super::ecaa::write_audit_proof_report(dst)
            .context("re-recording audit-proof after @graph registration")?;
        super::audit_report::write_audit_report(dst)
            .context("regenerating AUDIT-REPORT.md after @graph registration")?;
    }

    crate::emitter::regenerate_bagit_manifest(dst, &clock)
        .context("re-sealing BagIt manifest after readability transforms")?;

    // Execution lineage: best-effort `git log` of the source working tree.
    // Full profile only — the lean profiles treat it as droppable convenience.
    if matches!(profile, DepositProfile::Full) && src.join(".git").exists() {
        write_execution_lineage(src, dst);
    }

    Ok(ExportReport {
        kept,
        dropped,
        dst: dst.to_path_buf(),
    })
}

/// Write `dst/runtime/execution-lineage.txt` from `git -C <src> log --stat
/// --no-color`. Best-effort: any failure (git absent, not a repo, write error)
/// is swallowed — the lineage file is a convenience, not a correctness
/// guarantee, and the export is already self-consistent without it.
fn write_execution_lineage(src: &Path, dst: &Path) {
    let output = match std::process::Command::new("git")
        .arg("-C")
        .arg(src)
        .args(["log", "--stat", "--no-color"])
        .output()
    {
        Ok(o) if o.status.success() => o.stdout,
        _ => return,
    };
    let runtime_dir = dst.join("runtime");
    if std::fs::create_dir_all(&runtime_dir).is_err() {
        return;
    }
    let _ = std::fs::write(runtime_dir.join("execution-lineage.txt"), output);
}

/// Drop byte-data-duplicate output tables. A per-task agent sometimes writes the
/// same result table under two names (e.g. `de_results.tsv` + `de_table.tsv`)
/// whose DATA rows are byte-identical and differ only in the header line. For
/// each `runtime/outputs/<task>/` directory, `.tsv`/`.csv` files with an
/// identical data-row digest form a duplicate set; the copy referenced by the
/// most `@graph` mentions is kept (the lexicographically-smallest relative path
/// breaks ties), and the rest are deleted from disk. The caller's subsequent
/// [`prune_rocrate_dangling`] then drops each deleted file's now-dangling
/// `@graph` File entity, its `#action/<path>` CreateAction, and references to
/// it. Tables that differ in their data (e.g. by rounding) are NOT duplicates
/// and are left untouched. Returns the number of files deleted. Best-effort:
/// an unreadable directory or descriptor yields no deletions for that scope.
/// Remove per-task `runtime/outputs/<task>/` sidecars that carry NO information,
/// content-aware so populated files survive:
///   * `agent-code.json` whose `executed_code` AND `response_text` are both
///     empty/absent — only the boilerplate prompt, redundant with `PROMPT.md` /
///     `AGENT-EXECUTOR.md` / the `WORKFLOW.json` task specs.
///   * `curated_pools.json` whose every value is an empty array — a placeholder
///     with no candidate pools (a populated pool set, e.g. the method-survey
///     stage's, is kept).
/// Returns the number removed.
fn prune_content_empty_outputs(dst: &Path) -> Result<usize> {
    use serde_json::Value;
    let root = dst.join("runtime").join("outputs");
    if !root.exists() {
        return Ok(0);
    }
    let mut removed = 0usize;
    for entry in walkdir::WalkDir::new(&root) {
        let entry = match entry {
            Ok(e) => e,
            Err(_) => continue,
        };
        let name = entry.file_name().to_string_lossy().into_owned();
        if !entry.file_type().is_file() || (name != "agent-code.json" && name != "curated_pools.json")
        {
            continue;
        }
        let v: Value = match std::fs::read(entry.path())
            .ok()
            .and_then(|b| serde_json::from_slice(&b).ok())
        {
            Some(v) => v,
            None => continue,
        };
        let drop = if name == "agent-code.json" {
            let empty = |k: &str| {
                v.get(k)
                    .and_then(Value::as_str)
                    .map(|s| s.trim().is_empty())
                    .unwrap_or(true)
            };
            empty("executed_code") && empty("response_text")
        } else {
            // curated_pools.json: an object whose every value is an empty array.
            v.as_object()
                .map(|o| {
                    !o.is_empty()
                        && o.values()
                            .all(|val| val.as_array().map(|a| a.is_empty()).unwrap_or(false))
                })
                .unwrap_or(false)
        };
        if drop {
            std::fs::remove_file(entry.path())
                .with_context(|| format!("removing {}", entry.path().display()))?;
            removed += 1;
        }
    }
    Ok(removed)
}

fn dedup_duplicate_output_tables(dst: &Path) -> Result<usize> {
    // BTreeMap (not HashMap) per the emit-path determinism invariant
    // (`check-no-hashmap-in-emitter`): a stable digest→files grouping order.
    use std::collections::BTreeMap;

    // How many times each relative path is mentioned anywhere in the crate
    // descriptor — a proxy for "how connected / consumed" a table is. The
    // consumed twin (referenced by a downstream task's input + its own File +
    // CreateAction) outscores an unconsumed near-duplicate.
    let meta = std::fs::read_to_string(dst.join("ro-crate-metadata.json")).unwrap_or_default();
    let ref_count = |rel: &str| -> usize { meta.matches(rel).count() };

    let outputs = dst.join("runtime").join("outputs");
    if !outputs.is_dir() {
        return Ok(0);
    }
    let Ok(task_dirs) = std::fs::read_dir(&outputs) else {
        return Ok(0);
    };
    let mut deleted = 0usize;
    for task in task_dirs.flatten() {
        let task = task.path();
        if !task.is_dir() {
            continue;
        }
        // Group same-directory result tables by the digest of their DATA rows
        // (everything after the first/header line): identical digest ⇒ identical
        // data ⇒ a true duplicate regardless of the header column name.
        let mut groups: BTreeMap<String, Vec<PathBuf>> = BTreeMap::new();
        let Ok(entries) = std::fs::read_dir(&task) else {
            continue;
        };
        for ent in entries.flatten() {
            let p = ent.path();
            if !p.is_file() {
                continue;
            }
            if !matches!(p.extension().and_then(|e| e.to_str()), Some("tsv") | Some("csv")) {
                continue;
            }
            let Ok(bytes) = std::fs::read(&p) else {
                continue;
            };
            let data = match bytes.iter().position(|&b| b == b'\n') {
                Some(i) => &bytes[i + 1..],
                None => &bytes[..],
            };
            let digest = blake3::hash(data).to_hex().to_string();
            groups.entry(digest).or_default().push(p);
        }
        let rel_of = |p: &Path| -> String {
            p.strip_prefix(dst)
                .unwrap_or(p)
                .to_string_lossy()
                .replace('\\', "/")
        };
        for (_digest, files) in groups {
            if files.len() < 2 {
                continue;
            }
            // Keep the most-referenced copy; lexicographically-smallest relative
            // path breaks ties (deterministic). Delete the rest.
            let Some(keep) = files.iter().max_by_key(|p| {
                let rel = rel_of(p);
                (ref_count(&rel), std::cmp::Reverse(rel))
            }) else {
                continue;
            };
            let keep = keep.clone();
            for p in &files {
                if p != &keep && std::fs::remove_file(p).is_ok() {
                    deleted += 1;
                }
            }
        }
    }
    Ok(deleted)
}

/// Drop `@graph` entries from `dst/ro-crate-metadata.json` whose `@id` is a
/// package-relative path that does not exist on disk under `dst`.
///
/// Only entries whose `@id` looks like a package-relative file/dir path are
/// candidates: fragment ids (`#…`), absolute IRIs (`http://…` / `https://…`),
/// and the root self-reference (`./`) are always retained. A directory id
/// (trailing `/`) is kept iff the directory exists. Returns the number of
/// entries removed. No-op (`Ok(0)`) when the descriptor is missing or
/// unparseable.
fn prune_rocrate_dangling(dst: &Path) -> Result<usize> {
    use serde_json::Value;

    let descriptor = dst.join("ro-crate-metadata.json");
    let Ok(bytes) = std::fs::read(&descriptor) else {
        return Ok(0);
    };
    let Ok(mut doc) = serde_json::from_slice::<Value>(&bytes) else {
        return Ok(0);
    };
    let Some(graph) = doc.get_mut("@graph").and_then(Value::as_array_mut) else {
        return Ok(0);
    };

    // A package-relative `@id` dangles iff its target is absent on disk under
    // `dst`; the crate root (`./`), `#`-fragment entities, and absolute IRIs
    // are never path-backed and are always kept.
    let is_dangling = |id: &str| -> bool {
        if id == "./"
            || id.starts_with('#')
            || id.starts_with("http://")
            || id.starts_with("https://")
        {
            return false;
        }
        // A directory id carries a trailing `/`; `Path::exists` handles both.
        !dst.join(id.trim_end_matches('/')).exists()
    };

    // First pass: collect the ids that will be pruned, so the second pass can
    // also scrub references TO them. A dropped file's `@id` left inside another
    // entry's `hasPart`/`object`/`result` array dangles, and consumers (e.g.
    // runcrate) choke on the unresolvable reference.
    let mut pruned: std::collections::HashSet<String> = graph
        .iter()
        .filter_map(|e| e.get("@id").and_then(Value::as_str))
        .filter(|id| is_dangling(id))
        .map(String::from)
        .collect();

    // Also remove the `#action/<path>` CreateAction node keyed off each pruned
    // path (the emitter's per-output action-id convention) — e.g. the
    // de_table.tsv producer action once a duplicate table is dropped — so no
    // resultless action lingers. A derived id that matches no node is a no-op.
    let derived_action_ids: Vec<String> = pruned.iter().map(|p| format!("#action/{p}")).collect();
    pruned.extend(derived_action_ids);

    let before = graph.len();
    graph.retain(|entry| {
        entry
            .get("@id")
            .and_then(Value::as_str)
            .is_none_or(|id| !pruned.contains(id))
    });
    let removed = before - graph.len();

    // Second pass: scrub references to pruned ids from the surviving entries so
    // no `hasPart`/`object`/`result`/… reference points at a dropped node.
    if !pruned.is_empty() {
        let is_pruned_ref = |v: &Value| -> bool {
            v.get("@id")
                .and_then(Value::as_str)
                .is_some_and(|id| pruned.contains(id))
        };
        for entry in graph.iter_mut() {
            let Some(obj) = entry.as_object_mut() else {
                continue;
            };
            let keys: Vec<String> = obj.keys().cloned().collect();
            for k in keys {
                match obj.get_mut(&k) {
                    Some(Value::Array(arr)) => arr.retain(|it| !is_pruned_ref(it)),
                    Some(v) if is_pruned_ref(v) => {
                        obj.remove(&k);
                    }
                    _ => {}
                }
            }
        }
    }

    if removed > 0 {
        let serialized = serde_json::to_vec_pretty(&doc)
            .context("re-serializing pruned ro-crate-metadata.json")?;
        std::fs::write(&descriptor, serialized)
            .with_context(|| format!("writing pruned {}", descriptor.display()))?;
    }
    Ok(removed)
}

/// Write every file under `src_dir` into the zip writer `out` at its
/// `src_dir`-relative path, Deflated. Directories are emitted as explicit
/// entries (trailing `/`) so empty dirs survive the round-trip; entries are
/// written in sorted order for determinism.
pub fn zip_dir(src_dir: &Path, out: &mut (impl std::io::Write + std::io::Seek)) -> Result<()> {
    use std::io::Read;
    use zip::write::SimpleFileOptions;

    let mut writer = zip::ZipWriter::new(out);
    let options = SimpleFileOptions::default().compression_method(zip::CompressionMethod::Deflated);

    for entry in walkdir::WalkDir::new(src_dir).sort_by_file_name() {
        let entry = entry.with_context(|| format!("walking {}", src_dir.display()))?;
        let abs = entry.path();
        let rel = abs
            .strip_prefix(src_dir)
            .with_context(|| format!("stripping {} from {}", src_dir.display(), abs.display()))?;
        if rel.as_os_str().is_empty() {
            // The root dir itself — no entry.
            continue;
        }
        let rel_str = rel.to_string_lossy().replace('\\', "/");

        if entry.file_type().is_dir() {
            writer
                .add_directory(format!("{rel_str}/"), options)
                .with_context(|| format!("adding zip directory {rel_str}"))?;
        } else if entry.file_type().is_file() {
            writer
                .start_file(&rel_str, options)
                .with_context(|| format!("starting zip entry {rel_str}"))?;
            let mut f = std::fs::File::open(abs)
                .with_context(|| format!("opening {}", abs.display()))?;
            let mut buf = Vec::new();
            f.read_to_end(&mut buf)
                .with_context(|| format!("reading {}", abs.display()))?;
            std::io::Write::write_all(&mut writer, &buf)
                .with_context(|| format!("writing zip entry {rel_str}"))?;
        }
    }

    writer.finish().context("finalizing zip archive")?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::{Cursor, Read};

    // --- Task 1: tier classifier ----------------------------------------

    #[test]
    fn classify_maps_paths_to_expected_tiers() {
        let cases: &[(&str, DepositTier)] = &[
            (
                "runtime/outputs/differential_expression/de_results.tsv",
                DepositTier::A,
            ),
            ("runtime/outputs/x/agent-claude.log", DepositTier::C),
            // `view_data/` is a regenerable UI projection of the result tables
            // — Tier C, dropped from deposits (not RO-Crate-registered, not a
            // re-execution input).
            ("runtime/outputs/x/view_data/mean_variance.json", DepositTier::C),
            ("runtime/cache/conda-envs/e/f", DepositTier::E),
            ("runtime/r-libs/DESeq2/DESCRIPTION", DepositTier::E),
            ("runtime/outputs/x/scripts/01.R", DepositTier::B),
            ("runtime/outputs/x/env.lock", DepositTier::B),
            ("manifest-sha512.txt", DepositTier::D),
            (".git/config", DepositTier::E),
            ("runtime/outputs/x/intermediates/t.tsv", DepositTier::E),
            (
                "runtime/outputs/x/state.patch.applied.json",
                DepositTier::C,
            ),
            ("ro-crate-metadata.json", DepositTier::A),
        ];
        for (path, expected) in cases {
            let got = classify(Path::new(path));
            assert_eq!(
                got, *expected,
                "classify({path:?}) = {got:?}, expected {expected:?}"
            );
        }
    }

    #[test]
    fn is_kept_keeps_a_and_b_only() {
        assert!(is_kept(DepositTier::A), "tier A must be kept");
        assert!(is_kept(DepositTier::B), "tier B must be kept");
        assert!(!is_kept(DepositTier::C), "tier C must be dropped");
        assert!(!is_kept(DepositTier::D), "tier D must be dropped");
        assert!(!is_kept(DepositTier::E), "tier E must be dropped");
    }

    // --- Task 2: export_depositable_package ------------------------------

    /// Build a tiny fixture package under `root` exercising each tier.
    fn build_fixture_package(root: &Path) {
        let write = |rel: &str, body: &str| {
            let p = root.join(rel);
            std::fs::create_dir_all(p.parent().expect("fixture path has parent"))
                .expect("create fixture parent dir");
            std::fs::write(&p, body).expect("write fixture file");
        };
        write("runtime/outputs/t/de_results.tsv", "gene\tpadj\nA\t0.01\n"); // A
        write("runtime/outputs/t/agent-claude.log", "log line\n"); // C
        write("runtime/cache/x/y", "cached bytes\n"); // E
        write("runtime/outputs/t/scripts/s.R", "print('hi')\n"); // B
        write(".git/config", "[core]\n"); // E / explicit .git skip
        write("manifest-sha512.txt", "stale manifest\n"); // D
        write(
            "ro-crate-metadata.json",
            r#"{"@context":"https://w3id.org/ro/crate/1.1/context","@graph":[{"@id":"ro-crate-metadata.json","@type":"CreativeWork","about":{"@id":"./"}},{"@id":"./","@type":"Dataset","hasPart":[]}]}"#,
        ); // A
        write("bagit.txt", "BagIt-Version: 1.0\nTag-File-Character-Encoding: UTF-8\n");
    }

    #[test]
    fn export_copies_only_a_and_b_and_reseals() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let src = tmp.path().join("src");
        let dst = tmp.path().join("dst");
        build_fixture_package(&src);

        let report = export_depositable_package(&src, &dst).expect("export succeeds");

        // A + B present.
        assert!(
            dst.join("runtime/outputs/t/de_results.tsv").is_file(),
            "tier-A de_results.tsv must be copied"
        );
        assert!(
            dst.join("runtime/outputs/t/scripts/s.R").is_file(),
            "tier-B scripts/s.R must be copied"
        );
        assert!(
            dst.join("ro-crate-metadata.json").is_file(),
            "tier-A ro-crate-metadata.json must be copied"
        );
        // C / E / .git absent.
        assert!(
            !dst.join("runtime/outputs/t/agent-claude.log").exists(),
            "tier-C log must NOT be copied"
        );
        assert!(
            !dst.join("runtime/cache").exists(),
            "tier-E runtime/cache must NOT be copied"
        );
        assert!(
            !dst.join(".git").exists(),
            ".git must NOT be copied"
        );

        // The manifest was regenerated (D is skipped at copy then rebuilt by
        // reseal): it exists and lists the kept files only.
        let manifest_path = dst.join("manifest-sha512.txt");
        assert!(manifest_path.is_file(), "manifest-sha512.txt must be regenerated");
        let manifest = std::fs::read_to_string(&manifest_path).expect("read manifest");
        assert!(
            manifest.contains("runtime/outputs/t/de_results.tsv"),
            "manifest must list kept tier-A table, got:\n{manifest}"
        );
        assert!(
            !manifest.contains("agent-claude.log"),
            "manifest must NOT list the dropped tier-C log, got:\n{manifest}"
        );
        assert!(
            !manifest.contains("runtime/cache"),
            "manifest must NOT list dropped tier-E cache, got:\n{manifest}"
        );

        // No path in dst classifies as C/D/E except regenerated D manifests.
        for entry in walkdir::WalkDir::new(&dst) {
            let entry = entry.expect("walk dst");
            if !entry.file_type().is_file() {
                continue;
            }
            let rel = entry.path().strip_prefix(&dst).expect("strip dst");
            let tier = classify(rel);
            let basename = rel.file_name().unwrap_or_default().to_string_lossy();
            let is_regenerated_manifest =
                basename == "manifest-sha512.txt" || basename == "tagmanifest-sha512.txt";
            assert!(
                is_kept(tier) || is_regenerated_manifest,
                "exported file {} classified as {:?} but is not a regenerated manifest",
                rel.display(),
                tier
            );
        }

        assert!(report.kept >= 3, "expected >=3 kept files, got {}", report.kept);
        assert!(report.dropped >= 3, "expected >=3 dropped files, got {}", report.dropped);
        assert_eq!(report.dst, dst, "report.dst must echo the dst arg");
    }

    /// The export must preserve symlinks under KEPT paths as symlinks (recreated
    /// verbatim), not dereference or skip them. Uses a symlink under a Tier-B
    /// `scripts/` dir (the shipped conda env is no longer bundled — the
    /// re-executable deposit installs its env from the recorded lock instead).
    #[test]
    #[cfg(unix)]
    fn export_preserves_symlinks_under_kept_paths() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let src = tmp.path().join("src");
        let dst = tmp.path().join("dst");
        build_fixture_package(&src);

        // A relative symlink alongside a kept (Tier-B) script.
        let scripts = src.join("runtime/outputs/t/scripts");
        std::os::unix::fs::symlink("s.R", scripts.join("s-link.R")).unwrap();

        export_depositable_package(&src, &dst).expect("export succeeds");

        let link = dst.join("runtime/outputs/t/scripts/s-link.R");
        let meta = std::fs::symlink_metadata(&link).expect("kept symlink must exist");
        assert!(
            meta.file_type().is_symlink(),
            "symlink under a kept path must be preserved AS a symlink, not dereferenced/skipped"
        );
        assert_eq!(
            std::fs::read_link(&link).unwrap(),
            std::path::PathBuf::from("s.R"),
            "symlink target must be recreated verbatim (relative)"
        );
    }

    /// Regression: export must RE-RECORD `runtime/audit-proof-report.json` over
    /// the deposit graph, not copy the source package's report verbatim. The
    /// prune in step 3 drops embedded `C:`/`A:` Claim / InvariantVerdict nodes,
    /// so a copied report can ship a stale `cross_graph_integrity = fail` about
    /// nodes the deposit no longer carries — which a downloader's offline
    /// `replay` recomputes as `pass` and flags as a recorded-vs-fresh
    /// divergence. After export the report must reflect the deposit's own graph.
    #[test]
    fn export_re_records_audit_proof_over_deposit_graph() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let src = tmp.path().join("src");
        let dst = tmp.path().join("dst");
        build_fixture_package(&src);

        // Plant a stale source report whose cross_graph_integrity verdict is a
        // sentinel `fail` that no fresh run over the (claim-free) fixture graph
        // could produce. A verbatim copy preserves it; a re-record overwrites it.
        let stale = r#"{
          "schema_version": "0.0.0-STALE",
          "ecaa_version": "0.0.0-STALE",
          "min_reader_version": "0.0.0-STALE",
          "evaluator": {"name": "stale", "version": "0.0.0-STALE"},
          "verdicts": [
            {"id":"cross_graph_integrity","status":"fail","detail":"SENTINEL_STALE_VERDICT_MUST_BE_REGENERATED","n_inspected":99,"n_violations":7}
          ]
        }"#;
        std::fs::write(src.join("runtime/audit-proof-report.json"), stale)
            .expect("plant stale source audit-proof report");

        export_depositable_package(&src, &dst).expect("export succeeds");

        let report_path = dst.join("runtime/audit-proof-report.json");
        assert!(report_path.is_file(), "deposit must carry an audit-proof report");
        let body = std::fs::read_to_string(&report_path).expect("read deposit report");

        // Sentinel detail + stale version markers gone ⇒ regenerated, not copied.
        assert!(
            !body.contains("SENTINEL_STALE_VERDICT_MUST_BE_REGENERATED"),
            "deposit audit-proof report was copied verbatim (stale sentinel survived):\n{body}"
        );
        assert!(
            !body.contains("0.0.0-STALE"),
            "deposit audit-proof report retained stale version markers (not regenerated):\n{body}"
        );

        // The re-recorded cross_graph_integrity must reflect the deposit graph
        // (no embedded Claim nodes) — never the planted `fail`.
        let doc: serde_json::Value =
            serde_json::from_str(&body).expect("deposit report is valid JSON");
        let verdicts = doc["verdicts"].as_array().expect("verdicts array");
        let cgi = verdicts
            .iter()
            .find(|v| v["id"].as_str() == Some("cross_graph_integrity"))
            .expect("cross_graph_integrity verdict present");
        assert_ne!(
            cgi["status"].as_str(),
            Some("fail"),
            "re-recorded cross_graph_integrity must reflect the claim-free deposit graph, not the stale planted fail: {cgi}"
        );
    }

    #[test]
    fn classify_drops_runtime_operational_telemetry() {
        // Harness operational telemetry at the runtime root → Tier C (dropped).
        for rel in [
            "runtime/LOG.jsonl",
            "runtime/invocations.jsonl",
            "runtime/dispatches.jsonl",
            "runtime/session-metrics.jsonl",
            "runtime/harness-health.json",
            "runtime/install-log.jsonl",
            "runtime/picker-decisions.jsonl",
            "runtime/policy-opens.jsonl",
            "runtime/.execution_status.json",
        ] {
            assert_eq!(
                classify(Path::new(rel)),
                DepositTier::C,
                "{rel} must be Tier C (operational telemetry)"
            );
        }
        // Audit / provenance sidecars at the runtime root stay Tier A (kept).
        for rel in [
            "runtime/audit-proof-report.json",
            "runtime/claim-verification.json",
            "runtime/decisions.jsonl",
            "runtime/proofs.jsonl",
            "runtime/assumptions.jsonl",
            "runtime/cost-ledger.jsonl",
            "runtime/reexecution.json",
            "runtime/repair-status.json",
        ] {
            assert_eq!(
                classify(Path::new(rel)),
                DepositTier::A,
                "{rel} must stay Tier A (audit/provenance)"
            );
        }
        // Anchored to the runtime root: a same-named file inside a task output
        // directory is NOT swept up.
        assert_eq!(
            classify(Path::new("runtime/outputs/t/harness-health.json")),
            DepositTier::A,
            "a same-named file under a task output dir must not be dropped"
        );
    }

    #[test]
    fn dedup_drops_byte_data_duplicate_output_table() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let dst = tmp.path();
        let de = dst.join("runtime/outputs/differential_expression");
        std::fs::create_dir_all(&de).expect("mkdir");
        // Two tables with byte-identical DATA rows, differing only in the header.
        let data = "ENSG1\t1.0\t0.01\nENSG2\t-2.0\t0.40\n";
        std::fs::write(de.join("de_results.tsv"), format!("gene_id\tlog2fc\tpadj\n{data}")).unwrap();
        std::fs::write(de.join("de_table.tsv"), format!("gene\tlog2fc\tpadj\n{data}")).unwrap();
        // A genuinely-different table must be left alone.
        std::fs::write(de.join("vst.tsv"), "gene\tv\nENSG1\t5\n").unwrap();
        // Descriptor: both tables have a File + #action; de_results is ALSO
        // consumed downstream (one extra mention), so it must win and be kept.
        std::fs::write(
            dst.join("ro-crate-metadata.json"),
            r##"{"@graph":[
              {"@id":"runtime/outputs/differential_expression/de_results.tsv","@type":"File"},
              {"@id":"#action/runtime/outputs/differential_expression/de_results.tsv","@type":"CreateAction","result":{"@id":"runtime/outputs/differential_expression/de_results.tsv"}},
              {"@id":"runtime/outputs/differential_expression/de_table.tsv","@type":"File"},
              {"@id":"#action/runtime/outputs/differential_expression/de_table.tsv","@type":"CreateAction","result":{"@id":"runtime/outputs/differential_expression/de_table.tsv"}},
              {"@id":"#consume","object":{"@id":"runtime/outputs/differential_expression/de_results.tsv"}}
            ]}"##,
        )
        .unwrap();

        let n = dedup_duplicate_output_tables(dst).expect("dedup ok");
        assert_eq!(n, 1, "exactly the unconsumed duplicate must be deleted");
        assert!(de.join("de_results.tsv").exists(), "consumed twin must be kept");
        assert!(!de.join("de_table.tsv").exists(), "unconsumed duplicate must be deleted");
        assert!(de.join("vst.tsv").exists(), "a distinct table must be untouched");

        // The prune then drops the deleted table's File entity AND its
        // #action/<path> CreateAction, leaving no de_table reference.
        let removed = prune_rocrate_dangling(dst).expect("prune ok");
        assert!(removed >= 2, "File + #action must both be pruned, got {removed}");
        let doc: serde_json::Value = serde_json::from_slice(
            &std::fs::read(dst.join("ro-crate-metadata.json")).unwrap(),
        )
        .unwrap();
        let ids: Vec<&str> = doc["@graph"]
            .as_array()
            .unwrap()
            .iter()
            .filter_map(|e| e["@id"].as_str())
            .collect();
        assert!(
            !ids.iter().any(|i| i.contains("de_table.tsv")),
            "no de_table File or #action node may survive: {ids:?}"
        );
        assert!(ids.iter().any(|i| i.contains("de_results.tsv")), "de_results kept");
    }

    #[test]
    fn deposit_profiles_drop_the_right_surface() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let src = tmp.path().join("src");
        let w = |rel: &str, body: &str| {
            let p = src.join(rel);
            std::fs::create_dir_all(p.parent().expect("parent")).expect("mkdir");
            std::fs::write(p, body).expect("write");
        };
        w(
            "ro-crate-metadata.json",
            r##"{"@context":"https://w3id.org/ro/crate/1.1/context","@graph":[{"@id":"ro-crate-metadata.json","@type":"CreativeWork","about":{"@id":"./"}},{"@id":"./","@type":"Dataset","name":"x","description":"y","hasPart":[]},{"@id":"#action/keep","@type":"CreateAction","result":{"@id":"runtime/outputs/a_step/protected_model.rds"}}]}"##,
        );
        w("bagit.txt", "BagIt-Version: 1.0\nTag-File-Character-Encoding: UTF-8\n");
        // bloat / policy docs (lean profiles drop)
        w("package.ttl", "@prefix x: <urn:y> .\n");
        w("ro-crate-preview.html", "<html></html>\n");
        w("runtime/ed-cf-self-assessment.json", "{}\n");
        // git-log lineage already present in the source (as when re-exporting a
        // full deposit): lean profiles must drop it, full keeps it.
        w("runtime/execution-lineage.txt", "abc123 commit msg\n");
        w("policies/interpretation-policy.json", "{}\n");
        w("policies/container.json", "{}\n");
        // audit/provenance (all profiles keep)
        w("runtime/audit-proof-report.json", r#"{"verdicts":[]}"#);
        w("runtime/claim-verification.json", r#"{"verdicts":[]}"#);
        w("runtime/outputs/de/de_results.tsv", "g\tp\nA\t0.01\n");
        // re-execution tier (minimal drops; re-executable + full keep)
        w("runtime/outputs/de/scripts/01.R", "print(1)\n");
        w("runtime/outputs/de/env.lock", "lock\n");
        w("inputs/counts.tsv", "x\n");
        w("lib/measure.py", "pass\n");
        w("runtime/plotting/VERSION", "1\n");
        // readability inputs: WORKFLOW.json (tasks alphabetical: a_step,z_step;
        // exec order reversed at the top to prove the reorder), a README with
        // the emit footer, execution-order.json + a per-step output table.
        w(
            "WORKFLOW.json",
            r#"{"version":"1","workflow_id":"wf","tasks":{"z_step":{"id":"z_step","depends_on":["a_step"]},"a_step":{"id":"a_step","depends_on":[]}},"execution_order":["a_step","z_step"]}"#,
        );
        w(
            "README.md",
            "# Title — ECAA analysis package\n\n## 1. The answer\n\nsee outputs\n\n\
             ## 4. Re-run it\n\n```\nrun\n```\n\n\
             _Generated deterministically by the ECAA compiler from the workflow plan._\n",
        );
        w(
            "runtime/execution-order.json",
            r#"{"workflow_id":"wf","order":[{"index":0,"task_id":"a_step","output_dir":"runtime/outputs/a_step/"},{"index":1,"task_id":"z_step","output_dir":"runtime/outputs/z_step/"}]}"#,
        );
        w("runtime/outputs/a_step/result.tsv", "g\tp\nA\t0.01\n");
        // Leaner-minimal inputs: a transparency artifact to KEEP+REGISTER, plus
        // operational/re-exec/duplicate files the minimal must DROP.
        w("runtime/outputs/a_step/agent-code.json", r#"{"prompt":"p","executed_code":"x"}"#); // register
        w("runtime/outputs/a_step/determinism-env.json", r#"{"pkg_root":"/x"}"#); // drop (minimal)
        w("runtime/outputs/a_step/task-spec.json", "{}"); // drop (minimal)
        w("runtime/outputs/a_step/figures/v.png", "PNG"); // keep
        w("runtime/outputs/a_step/figures/v.pdf", "PDF"); // drop (minimal), keep full
        w("runtime/outputs/a_step/qc_summary.json", "{}"); // drop (minimal)
        w("runtime/inputs/a_step/provisioning.json", "{}"); // drop (minimal)
        w("runtime/typed-blocker.json", "{}"); // drop (minimal)
        // z_step: a content-EMPTY agent-code.json (only boilerplate prompt) — drop
        // in minimal; the populated a_step/agent-code.json (executed_code "x") stays.
        w("runtime/outputs/z_step/result.tsv", "g\tp\nB\t0.02\n");
        w("runtime/outputs/z_step/agent-code.json", r#"{"prompt":"p","executed_code":"","response_text":""}"#);
        // Further minimal drops: the ~1 MB verifier trace + the empty dependency
        // lock (re-exec metadata) + a content-empty curated_pools (vs a non-empty
        // one that must survive).
        w("runtime/verifier-decisions.jsonl", "{\"kind\":\"unification_failed\"}\n"); // drop (minimal)
        w("runtime/dependency-lock.json", r#"{"r":[],"python":[],"conda":[]}"#); // drop (minimal)
        w("runtime/outputs/a_step/curated_pools.json", r#"{"x":[],"y":[]}"#); // empty -> drop (minimal)
        w("runtime/outputs/z_step/curated_pools.json", r#"{"de":["deseq2","edger"]}"#); // non-empty -> keep
        // RE-EXECUTION WORKING DATA under stage-output subdirs (the large-deposit
        // root cause): serialized binary objects + re-staged inputs. Minimal must
        // DROP these (they are not provenance-referenced); re-executable + full
        // KEEP them. A serialized object is never a result table, so it is only a
        // zero-dark File — safe to drop.
        w("runtime/outputs/a_step/normalized_counts/sct_residuals.rds", "BINARY-RDS"); // drop (minimal)
        w("runtime/outputs/a_step/normalized_counts/raw_hvg.h5ad", "BINARY-H5AD"); // drop (minimal)
        w("runtime/outputs/data_acquisition/data/da/big_input_matrix.txt", "x\ty\n1\t2\n"); // drop (minimal): re-staged input
        // A serialized object that IS a CreateAction result must be KEPT even in
        // minimal (provenance-load-bearing). The metadata graph above references
        // it as a result, so it lands in `protected`.
        w("runtime/outputs/a_step/protected_model.rds", "BINARY-PROTECTED"); // keep (all): is a CreateAction result

        let run = |prof: DepositProfile| -> std::path::PathBuf {
            let d = tmp.path().join(format!("dst-{prof}"));
            export_depositable_package_with_profile(&src, &d, prof).expect("export");
            d
        };

        // Full keeps everything.
        let full = run(DepositProfile::Full);
        for f in ["policies/interpretation-policy.json", "package.ttl",
                  "runtime/outputs/de/scripts/01.R", "inputs/counts.tsv",
                  "runtime/execution-lineage.txt"] {
            assert!(full.join(f).exists(), "full must keep {f}");
        }

        // Re-executable: drops policy docs + bloat; keeps re-exec tier + audit + results.
        let re = run(DepositProfile::ReExecutable);
        for f in ["policies/interpretation-policy.json", "policies/container.json",
                  "package.ttl", "ro-crate-preview.html", "runtime/ed-cf-self-assessment.json",
                  "runtime/execution-lineage.txt"] {
            assert!(!re.join(f).exists(), "re-executable must drop {f}");
        }
        for f in ["runtime/outputs/de/scripts/01.R", "inputs/counts.tsv", "lib/measure.py",
                  "runtime/audit-proof-report.json", "runtime/claim-verification.json",
                  "runtime/outputs/de/de_results.tsv",
                  // re-executable KEEPS stage working data (it is re-executable)
                  "runtime/outputs/a_step/normalized_counts/sct_residuals.rds",
                  "runtime/outputs/a_step/normalized_counts/raw_hvg.h5ad",
                  "runtime/outputs/data_acquisition/data/da/big_input_matrix.txt"] {
            assert!(re.join(f).exists(), "re-executable must keep {f}");
        }

        // Minimal: drops policy docs + bloat + re-exec tier; keeps audit + results.
        let min = run(DepositProfile::MinimalAudit);
        for f in ["policies/interpretation-policy.json", "package.ttl",
                  "runtime/outputs/de/scripts/01.R", "runtime/outputs/de/env.lock",
                  "inputs/counts.tsv", "lib/measure.py", "runtime/plotting/VERSION",
                  "runtime/execution-lineage.txt",
                  // root cause: re-execution working data under stage-output
                  // subdirs — serialized objects + re-staged inputs — now dropped
                  "runtime/outputs/a_step/normalized_counts/sct_residuals.rds",
                  "runtime/outputs/a_step/normalized_counts/raw_hvg.h5ad",
                  "runtime/outputs/data_acquisition/data/da/big_input_matrix.txt"] {
            assert!(!min.join(f).exists(), "minimal must drop {f}");
        }
        for f in ["runtime/claim-verification.json", "runtime/audit-proof-report.json",
                  "runtime/outputs/de/de_results.tsv",
                  // a serialized object that IS a CreateAction result is
                  // provenance-load-bearing → kept even in minimal
                  "runtime/outputs/a_step/protected_model.rds"] {
            assert!(min.join(f).exists(), "minimal must keep {f}");
        }

        // Every profile carries the human-readable audit report, sourced from
        // the sidecars, with the key audit/provenance sections present.
        for d in [&full, &re, &min] {
            assert!(d.join("AUDIT-REPORT.md").is_file(), "AUDIT-REPORT.md must be in every profile");
        }
        let body = std::fs::read_to_string(min.join("AUDIT-REPORT.md")).unwrap();
        for h in ["# Audit & provenance report", "## Audit-proof invariants",
                  "## Claim verification"] {
            assert!(body.contains(h), "audit report must contain section {h:?}");
        }

        // Readability transforms apply to every profile (their inputs —
        // WORKFLOW.json, README.md, execution-order.json — are Tier-A, kept in
        // all three).
        for d in [&full, &re, &min] {
            assert!(d.join("ARTIFACTS.md").is_file(), "ARTIFACTS.md in every profile");

            // README navigation appended, original footer preserved.
            let readme = std::fs::read_to_string(d.join("README.md")).unwrap();
            assert!(readme.contains("## Package navigation"), "README nav section");
            assert!(readme.contains("AUDIT-REPORT.md"), "README links audit report");
            assert!(readme.contains("ARTIFACTS.md"), "README links artifact map");
            assert!(readme.contains("Steps, in execution order"), "README inline exec table");
            assert!(readme.contains("_Generated deterministically"), "README footer preserved");

            // WORKFLOW.json reordered: tasks block last, a_step before z_step,
            // and value-equal (every task + the execution_order survive).
            let wf_txt = std::fs::read_to_string(d.join("WORKFLOW.json")).unwrap();
            let after = &wf_txt[wf_txt.find("\"tasks\"").expect("tasks key")..];
            assert!(
                after.find("a_step").unwrap() < after.find("z_step").unwrap(),
                "tasks must be in execution order (a_step before z_step), got: {after}"
            );
            let wf: serde_json::Value =
                serde_json::from_str(&wf_txt).expect("reordered WORKFLOW.json parses");
            assert_eq!(wf["tasks"].as_object().unwrap().len(), 2, "both tasks survive reorder");
            assert_eq!(wf["execution_order"], serde_json::json!(["a_step", "z_step"]));
        }

        // Per-step artifact section is present and lists the producing step.
        let artifacts = std::fs::read_to_string(min.join("ARTIFACTS.md")).unwrap();
        assert!(artifacts.contains("## Per-step outputs"), "per-step section");
        assert!(artifacts.contains("a_step"), "per-step lists a_step");
        assert!(artifacts.contains("result.tsv"), "per-step lists the step output");

        // Leaner minimal: operational / re-exec / duplicate files dropped …
        for f in ["runtime/outputs/a_step/determinism-env.json",
                  "runtime/outputs/a_step/task-spec.json",
                  "runtime/outputs/a_step/qc_summary.json",
                  "runtime/outputs/a_step/figures/v.pdf",
                  "runtime/inputs/a_step/provisioning.json",
                  "runtime/typed-blocker.json",
                  "runtime/verifier-decisions.jsonl",
                  "runtime/dependency-lock.json",
                  "runtime/outputs/a_step/curated_pools.json"] {
            assert!(!min.join(f).exists(), "minimal must drop {f}");
        }
        // … while the transparency artifact + the PNG figure + the NON-empty
        // curated_pools are kept …
        // a_step/agent-code.json has executed_code "x" → content-bearing, KEPT;
        // z_step/agent-code.json is empty → content-empty, DROPPED in minimal.
        for f in ["runtime/outputs/a_step/agent-code.json",
                  "runtime/outputs/a_step/figures/v.png",
                  "runtime/outputs/z_step/curated_pools.json"] {
            assert!(min.join(f).exists(), "minimal must keep {f}");
        }
        assert!(!min.join("runtime/outputs/z_step/agent-code.json").exists(),
            "minimal must drop the content-empty agent-code.json");
        // Full keeps the duplicate/operational files + the empty agent-code +
        // the verifier trace / dependency-lock / empty curated_pools (only minimal drops them).
        for f in ["runtime/outputs/a_step/determinism-env.json",
                  "runtime/outputs/a_step/figures/v.pdf",
                  "runtime/outputs/z_step/agent-code.json",
                  "runtime/verifier-decisions.jsonl",
                  "runtime/dependency-lock.json",
                  "runtime/outputs/a_step/curated_pools.json"] {
            assert!(full.join(f).exists(), "full must keep {f}");
        }

        // Zero dark payload: every kept file (bar BagIt/descriptor structural
        // files) is declared in the `@graph` and the root `hasPart`.
        let zero_dark = |root: &std::path::Path| {
            let meta: serde_json::Value = serde_json::from_slice(
                &std::fs::read(root.join("ro-crate-metadata.json")).unwrap(),
            )
            .unwrap();
            let ids: std::collections::HashSet<String> = meta["@graph"]
                .as_array()
                .unwrap()
                .iter()
                .filter_map(|e| e["@id"].as_str().map(String::from))
                .collect();
            let structural = ["ro-crate-metadata.json", "ro-crate-preview.html",
                "bagit.txt", "bag-info.txt", "manifest-sha512.txt", "tagmanifest-sha512.txt"];
            for e in walkdir::WalkDir::new(root) {
                let e = e.unwrap();
                if !e.file_type().is_file() { continue; }
                let rel = e.path().strip_prefix(root).unwrap()
                    .to_string_lossy().replace('\\', "/");
                if structural.contains(&rel.as_str()) { continue; }
                assert!(ids.contains(&rel), "dark payload (not in @graph): {rel}");
            }
        };
        zero_dark(&min);
        zero_dark(&full);
        // The kept transparency artifact is among the registered entities.
        let ids: std::collections::HashSet<String> = serde_json::from_slice::<serde_json::Value>(
            &std::fs::read(min.join("ro-crate-metadata.json")).unwrap()).unwrap()
            ["@graph"].as_array().unwrap().iter()
            .filter_map(|e| e["@id"].as_str().map(String::from)).collect();
        assert!(ids.contains("runtime/outputs/a_step/agent-code.json"),
            "agent-code.json must be registered in @graph");
    }

    #[test]
    fn prune_rocrate_drops_absent_keeps_present() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let dst = tmp.path();

        // A present file and an absent file, both referenced in @graph.
        std::fs::write(dst.join("present.tsv"), "x\n").expect("write present file");
        let descriptor = r##"{
          "@graph": [
            {"@id": "ro-crate-metadata.json", "@type": "CreativeWork"},
            {"@id": "./", "@type": "Dataset", "hasPart": [{"@id": "present.tsv"}, {"@id": "removed.log"}]},
            {"@id": "#step-x", "@type": "HowToStep", "result": {"@id": "removed.log"}},
            {"@id": "https://w3id.org/ro/crate/1.1", "@type": "CreativeWork"},
            {"@id": "present.tsv", "@type": "File"},
            {"@id": "removed.log", "@type": "File"}
          ]
        }"##;
        std::fs::write(dst.join("ro-crate-metadata.json"), descriptor)
            .expect("write descriptor");

        let removed = prune_rocrate_dangling(dst).expect("prune succeeds");
        assert_eq!(removed, 1, "exactly the absent removed.log entry must be pruned");

        let doc: serde_json::Value = serde_json::from_slice(
            &std::fs::read(dst.join("ro-crate-metadata.json")).expect("read pruned descriptor"),
        )
        .expect("parse pruned descriptor");
        let ids: Vec<&str> = doc["@graph"]
            .as_array()
            .expect("graph array")
            .iter()
            .filter_map(|e| e["@id"].as_str())
            .collect();
        assert!(ids.contains(&"present.tsv"), "present file entry must be kept");
        assert!(!ids.contains(&"removed.log"), "absent file entry must be dropped");
        assert!(ids.contains(&"#step-x"), "fragment id must be kept");
        assert!(
            ids.contains(&"https://w3id.org/ro/crate/1.1"),
            "IRI id must be kept"
        );
        assert!(ids.contains(&"./"), "root self-reference must be kept");

        // Reference scrub: no surviving entry may still reference the pruned id
        // (else consumers like runcrate choke on the unresolvable @id).
        let graph = doc["@graph"].as_array().expect("graph array");
        let root = graph
            .iter()
            .find(|e| e["@id"] == "./")
            .expect("root entry");
        let has_part: Vec<&str> = root["hasPart"]
            .as_array()
            .map(|a| a.iter().filter_map(|x| x["@id"].as_str()).collect())
            .unwrap_or_default();
        assert!(
            !has_part.contains(&"removed.log"),
            "pruned id must be scrubbed from hasPart, got {has_part:?}"
        );
        assert!(
            has_part.contains(&"present.tsv"),
            "present ref must survive in hasPart, got {has_part:?}"
        );
        let step = graph
            .iter()
            .find(|e| e["@id"] == "#step-x")
            .expect("step entry");
        assert!(
            step.get("result").is_none(),
            "a single-object reference to the pruned id must be removed, got {step:?}"
        );
    }

    // --- Task 3: zip_dir round-trip --------------------------------------

    #[test]
    fn zip_dir_round_trips() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let src = tmp.path().join("tree");
        std::fs::create_dir_all(src.join("sub")).expect("create sub dir");
        std::fs::write(src.join("a.txt"), b"alpha contents").expect("write a.txt");
        std::fs::write(src.join("sub/b.txt"), b"beta contents").expect("write b.txt");

        let mut cursor = Cursor::new(Vec::new());
        zip_dir(&src, &mut cursor).expect("zip_dir succeeds");

        let mut archive = zip::ZipArchive::new(cursor).expect("re-open zip");
        let read_entry = |archive: &mut zip::ZipArchive<Cursor<Vec<u8>>>, name: &str| -> Vec<u8> {
            let mut f = archive
                .by_name(name)
                .unwrap_or_else(|_| panic!("entry {name} present in archive"));
            let mut buf = Vec::new();
            f.read_to_end(&mut buf).expect("read zip entry");
            buf
        };
        assert_eq!(
            read_entry(&mut archive, "a.txt"),
            b"alpha contents",
            "a.txt bytes must round-trip"
        );
        assert_eq!(
            read_entry(&mut archive, "sub/b.txt"),
            b"beta contents",
            "sub/b.txt bytes must round-trip"
        );
    }
}
