//! A3 — every committed `testdata/**/ro-crate-metadata.json` fixture must
//! match the ECAA v0.2 descriptor contract:
//!
//!   (a) its `ro-crate-metadata.json` descriptor entry declares ALL 6 required
//!       `conformsTo` profile IRIs (read from core's canonical
//!       `ecaa_workflow_types::consts::REQUIRED_PROFILE_IRIS`, not hardcoded);
//!   (b) it contains NO malformed EDAM IRI in the `<word>:<digits>` colon form
//!       (`https://edamontology.org/operation:3222`) — EDAM IRIs are normative
//!       only in the underscore form (`.../operation_3222`).
//!
//! REGEN DEPENDENCY (read before treating a failure as a regression):
//! the committed fixtures under `testdata/emitted-packages/` are CURRENTLY
//! STALE — they were emitted by an older code path that wrote only 4 conformsTo
//! IRIs and the malformed colon-form EDAM IRIs. This test asserts the CORRECT
//! END STATE, so it WILL FAIL until the fixtures are regenerated by the built
//! emitter. The regeneration is intentionally NOT done here (it needs a built
//! emitter binary, which this crate must not invoke at test-author time). Once
//! the orchestrator rebuilds and regenerates the corpus, this gate goes green
//! and then permanently guards against fixture drift.

use std::path::{Path, PathBuf};

/// Repo root = two ancestors up from `crates/ecaa-conformance`.
fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("crates/")
        .parent()
        .expect("repo root")
        .to_path_buf()
}

/// Recursively collect every `ro-crate-metadata.json` under `testdata/`.
fn collect_fixtures(root: &Path, out: &mut Vec<PathBuf>) {
    let entries = match std::fs::read_dir(root) {
        Ok(e) => e,
        Err(e) => panic!("read_dir({}) failed: {e}", root.display()),
    };
    for entry in entries {
        let entry = entry.expect("dir entry");
        let path = entry.path();
        let ft = entry.file_type().expect("file type");
        if ft.is_dir() {
            collect_fixtures(&path, out);
        } else if path.file_name().and_then(|n| n.to_str()) == Some("ro-crate-metadata.json") {
            out.push(path);
        }
    }
}

/// Parse the `ro-crate-metadata.json` descriptor entry's `conformsTo` IRIs.
fn conforms_to_iris(metadata: &serde_json::Value) -> Vec<String> {
    let graph = metadata["@graph"]
        .as_array()
        .expect("@graph must be an array");
    let descriptor = graph
        .iter()
        .find(|e| e["@id"] == "ro-crate-metadata.json")
        .expect("descriptor entry (@id == ro-crate-metadata.json) must exist");
    match descriptor["conformsTo"].as_array() {
        Some(arr) => arr
            .iter()
            .filter_map(|c| c["@id"].as_str().map(str::to_string))
            .collect(),
        None => Vec::new(),
    }
}

/// Scan the raw JSON text for the malformed EDAM colon-form IRI. We scan the
/// raw bytes (not parsed values) so a colon-form IRI anywhere in the document
/// — `@id`, free-text, nested object — is caught. Returns the offending
/// substrings (deduped, sorted) for a precise failure message.
fn malformed_edam_iris(raw: &str) -> Vec<String> {
    const PREFIX: &str = "https://edamontology.org/";
    let mut hits: Vec<String> = Vec::new();
    let bytes = raw.as_bytes();
    let mut search_from = 0;
    while let Some(rel) = raw[search_from..].find(PREFIX) {
        let start = search_from + rel;
        let mut i = start + PREFIX.len();
        // Consume the term label (ASCII letters).
        let label_start = i;
        while i < bytes.len() && bytes[i].is_ascii_alphabetic() {
            i += 1;
        }
        let has_label = i > label_start;
        // A malformed IRI is `<word>:<digit...>`. The normative form uses `_`.
        if has_label && i < bytes.len() && bytes[i] == b':' {
            let digits_start = i + 1;
            let mut j = digits_start;
            while j < bytes.len() && bytes[j].is_ascii_digit() {
                j += 1;
            }
            if j > digits_start {
                hits.push(raw[start..j].to_string());
            }
        }
        search_from = start + PREFIX.len();
    }
    hits.sort();
    hits.dedup();
    hits
}

#[test]
fn every_testdata_fixture_declares_six_iris_and_underscore_edam() {
    let testdata = repo_root().join("testdata");
    assert!(
        testdata.is_dir(),
        "testdata/ must exist at {}",
        testdata.display()
    );

    let mut fixtures: Vec<PathBuf> = Vec::new();
    collect_fixtures(&testdata, &mut fixtures);
    fixtures.sort();
    assert!(
        !fixtures.is_empty(),
        "expected at least one testdata/**/ro-crate-metadata.json fixture"
    );

    let required: &[&str] = ecaa_workflow_types::consts::REQUIRED_PROFILE_IRIS;
    let mut iri_failures: Vec<String> = Vec::new();
    let mut edam_failures: Vec<String> = Vec::new();

    for fixture in &fixtures {
        let rel = fixture
            .strip_prefix(repo_root())
            .unwrap_or(fixture)
            .display()
            .to_string();
        let raw = std::fs::read_to_string(fixture)
            .unwrap_or_else(|e| panic!("reading {}: {e}", fixture.display()));
        let metadata: serde_json::Value = serde_json::from_str(&raw)
            .unwrap_or_else(|e| panic!("parsing {}: {e}", fixture.display()));

        // (a) all 6 required conformsTo IRIs present.
        let declared = conforms_to_iris(&metadata);
        let missing: Vec<&str> = required
            .iter()
            .copied()
            .filter(|iri| !declared.iter().any(|d| d.as_str() == *iri))
            .collect();
        if !missing.is_empty() {
            iri_failures.push(format!(
                "{rel}: missing {} required conformsTo IRI(s) {missing:?} (declared {declared:?})",
                missing.len()
            ));
        }

        // (b) no malformed colon-form EDAM IRI.
        let bad = malformed_edam_iris(&raw);
        if !bad.is_empty() {
            edam_failures.push(format!("{rel}: malformed colon-form EDAM IRI(s) {bad:?}"));
        }
    }

    assert!(
        iri_failures.is_empty() && edam_failures.is_empty(),
        "A3 fixture-conformance failed over {} fixture(s).\n\
         NOTE: the committed fixtures are STALE by design — this gate asserts the \
         CORRECT END STATE and goes green only AFTER the orchestrator regenerates the \
         testdata corpus with the built emitter (6 conformsTo IRIs + underscore-form \
         EDAM IRIs). Do NOT hand-edit fixtures to silence this; regenerate them.\n\
         --- conformsTo failures ({}) ---\n{}\n\
         --- EDAM colon-form failures ({}) ---\n{}",
        fixtures.len(),
        iri_failures.len(),
        iri_failures.join("\n"),
        edam_failures.len(),
        edam_failures.join("\n"),
    );
}

#[cfg(test)]
mod self_tests {
    use super::malformed_edam_iris;

    #[test]
    fn detects_colon_form_and_ignores_underscore_form() {
        let colon = r#"{"@id":"https://edamontology.org/operation:3222"}"#;
        assert_eq!(
            malformed_edam_iris(colon),
            vec!["https://edamontology.org/operation:3222".to_string()],
            "colon-form EDAM IRI must be flagged"
        );

        let underscore = r#"{"@id":"https://edamontology.org/operation_3222"}"#;
        assert!(
            malformed_edam_iris(underscore).is_empty(),
            "underscore-form EDAM IRI must NOT be flagged"
        );

        // Non-EDAM colon IRIs (e.g. w3id profile IRIs) must not be flagged.
        let other = r#"{"@id":"https://w3id.org/ro/wfrun/process/0.5"}"#;
        assert!(
            malformed_edam_iris(other).is_empty(),
            "non-EDAM IRIs must NOT be flagged"
        );
    }

    #[test]
    fn dedups_repeated_colon_iris() {
        let raw = r#"a https://edamontology.org/topic:3169 b https://edamontology.org/topic:3169"#;
        assert_eq!(
            malformed_edam_iris(raw),
            vec!["https://edamontology.org/topic:3169".to_string()]
        );
    }
}
