//! Task 8 — integration tests for `run_replay` against the real Himes
//! bulk RNA-seq package fixture (`testdata/replay/himes-parent/`).
//!
//! # Fixture
//! `testdata/replay/himes-parent/` is a trimmed slice of the paper's Himes
//! case-study package (session 57bd1b53-…, bulk_rnaseq-20260711T154822 — the
//! run whose numbers the paper reports: 72 candidate claims, apeglm LFC
//! shrinkage, 4,030 significant genes). Only the files these two tests need
//! survive:
//!   - `ro-crate-metadata.json`, `policies/`, runtime sidecars
//!   - `runtime/outputs/data_acquisition/data/himes-inputs/{counts.tsv,samples.csv}`
//!   - `runtime/outputs/differential_expression/{scripts/01_deseq2_de.R,de_results.tsv,determinism-env.json}`
//!   - `runtime/{determinism-shim.json,execution-order.json,audit-proof-report.json,claim-verification.json}`
//!
//! The `01_deseq2_de.R` header resolves the package root from the injected
//! `PACKAGE`/`PKG_ROOT` env vars (set by `replay::script_runner`) with a
//! script-relative fallback, rather than a hardcoded path, so the execute tier
//! can stage and run it from a scratch dir. See `testdata/replay/README.md`
//! for how this fixture relates to the paper deposit.
//!
//! The recorded `runtime/audit-proof-report.json` was regenerated by running
//! `ecaa-workflow-audit-proof` directly on this trimmed fixture so that
//! re-verify is self-consistent (the fixture is its own baseline).

/// **replay_himes_verify_tier_passes_offline** — always runs, fully offline.
///
/// Calls `run_replay(fixture, Tier::Verify)` and asserts the verdict is
/// `ReplayVerdict::Pass`. The recorded `audit-proof-report.json` was produced
/// by running the same verifier on the trimmed fixture, so the re-verify diff
/// must be zero-divergence.
///
/// Also compares the stable subset of the report against the committed golden
/// file (`testdata/replay/himes-golden-report.json`): verdict,
/// `reader_matches_writer`, all check ids/statuses/diverged flags, and the
/// per-check recorded/fresh values.  Volatile fields (`evaluated_at`, any
/// scratch-path fields) are not present in the golden and are ignored.
#[test]
fn replay_himes_verify_tier_passes_offline() {
    let pkg = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../testdata/replay/himes-parent"
    );
    let opts = ecaa_workflow_core::replay::ReplayOptions {
        tier: ecaa_workflow_core::replay::Tier::Verify,
        scratch_dir: None,
        bounds: None,
        allow_rebuild: false,
        reader_version: "0.2".into(),
        trust: ecaa_workflow_core::replay::PackageTrust::Trusted,
    };
    let rep = ecaa_workflow_core::replay::run_replay(std::path::Path::new(pkg), &opts)
        .expect("run_replay must not error on the himes fixture");
    assert_eq!(
        rep.verdict,
        ecaa_workflow_core::replay::ReplayVerdict::Pass,
        "Tier::Verify on himes-parent with matching recorded report must yield Pass;\
         \nreverify={:?}",
        rep.reverify,
    );
    // Sanity: reverify was populated, reexecute was not.
    assert!(
        rep.reverify.is_some(),
        "reverify must be Some for Tier::Verify"
    );
    assert!(
        rep.reexecute.is_none(),
        "reexecute must be None for Tier::Verify"
    );

    // ── Golden-report assertion ──────────────────────────────────────────────
    // Compare the stable subset of the live report against the committed
    // golden file.  We extract only the fields that are deterministic and
    // independent of wall-clock time or scratch directory paths.
    let golden_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../testdata/replay/himes-golden-report.json"
    );
    let golden_raw =
        std::fs::read_to_string(golden_path).expect("himes-golden-report.json must be readable");
    let golden: serde_json::Value =
        serde_json::from_str(&golden_raw).expect("himes-golden-report.json must be valid JSON");

    // Serialize the live report to JSON and parse back so we work with the
    // same key/value structure as the golden.
    let live_raw = serde_json::to_string(&rep).expect("rep must serialize to JSON");
    let live: serde_json::Value =
        serde_json::from_str(&live_raw).expect("live report must parse back");

    // Assert stable top-level fields.
    assert_eq!(
        live.get("verdict"),
        golden.get("verdict"),
        "verdict must match golden"
    );
    assert_eq!(
        live.get("reader_version"),
        golden.get("reader_version"),
        "reader_version must match golden"
    );

    // Assert reader_matches_writer.
    let live_rmw = live
        .pointer("/reverify/reader_matches_writer")
        .expect("reverify.reader_matches_writer must be present");
    let golden_rmw = golden
        .pointer("/reverify/reader_matches_writer")
        .expect("golden reverify.reader_matches_writer must be present");
    assert_eq!(
        live_rmw, golden_rmw,
        "reader_matches_writer must match golden"
    );

    // Assert per-check stable fields: check id, recorded, fresh, diverged.
    let live_checks = live
        .pointer("/reverify/checks")
        .and_then(|v| v.as_array())
        .expect("reverify.checks must be an array");
    let golden_checks = golden
        .pointer("/reverify/checks")
        .and_then(|v| v.as_array())
        .expect("golden reverify.checks must be an array");

    assert_eq!(
        live_checks.len(),
        golden_checks.len(),
        "check count must match golden: live={} golden={}",
        live_checks.len(),
        golden_checks.len()
    );

    for (i, (live_c, golden_c)) in live_checks.iter().zip(golden_checks.iter()).enumerate() {
        for field in &["check", "recorded", "fresh", "diverged"] {
            assert_eq!(
                live_c.get(field),
                golden_c.get(field),
                "check[{i}].{field} must match golden:\n  live   = {:?}\n  golden = {:?}",
                live_c.get(field),
                golden_c.get(field)
            );
        }
    }
}

/// **replay_himes_execute_tier_reproduces_de_table** — CI-gated.
///
/// Skips automatically unless `ECAA_REPLAY_EXEC_TEST=1` is set in the
/// environment. Runs entirely in the `bio-min` container: the fixture ships
/// no conda env but carries the recorded `env.explicit.lock`, so replay's
/// `InstallFromLock` path `conda create`s the DESeq2/apeglm stack into the
/// image and runs `01_deseq2_de.R` through it. Requires `docker` and network
/// access to the conda registries pinned in the lock. When enabled, calls
/// `run_replay(fixture, Tier::Execute)` and asserts that `de_results.tsv`
/// classifies as `ByteIdentical` or `SemanticEquivalent`.
#[test]
fn replay_himes_execute_tier_reproduces_de_table() {
    // CI-gated: needs docker + network (installs the recorded env from the
    // lock into bio-min); skip when the gate env var is absent.
    if std::env::var("ECAA_REPLAY_EXEC_TEST").is_err() {
        return;
    }
    let pkg = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../testdata/replay/himes-parent"
    );
    let opts = ecaa_workflow_core::replay::ReplayOptions {
        tier: ecaa_workflow_core::replay::Tier::Execute,
        scratch_dir: None,
        bounds: None,
        allow_rebuild: false,
        reader_version: "0.2".into(),
        trust: ecaa_workflow_core::replay::PackageTrust::Trusted,
    };
    let rep = ecaa_workflow_core::replay::run_replay(std::path::Path::new(pkg), &opts)
        .expect("run_replay must not error on the himes fixture");
    let de = rep
        .reexecute
        .expect("reexecute must be Some for Tier::Execute")
        .report
        .per_artifact
        .iter()
        .find(|a| a.artifact_path.ends_with("de_results.tsv"))
        .expect("de_results.tsv must appear in per_artifact")
        .bucket
        .clone();
    assert!(
        matches!(
            de,
            ecaa_workflow_core::reexecution::ReexecutionBucket::ByteIdentical
                | ecaa_workflow_core::reexecution::ReexecutionBucket::SemanticEquivalent
        ),
        "de_results.tsv must reproduce as ByteIdentical or SemanticEquivalent, got {de:?}"
    );
}
