//! Task 8 — integration tests for `run_replay` against the real Himes
//! bulk RNA-seq package fixture (`testdata/replay/himes-parent/`).
//!
//! # Fixture
//! `testdata/replay/himes-parent/` is a trimmed copy of a real completed
//! package (9bffd538-… bulk_rnaseq-20260623T124057) containing only the
//! files needed for these two tests:
//!   - `ro-crate-metadata.json`, `policies/`, runtime sidecars
//!   - `runtime/outputs/data_acquisition/data/himes-inputs/{counts.tsv,samples.csv}`
//!   - `runtime/outputs/differential_expression/{scripts/01_deseq2_de.R,de_results.tsv,determinism-env.json}`
//!   - `runtime/{determinism-shim.json,execution-order.json,audit-proof-report.json,claim-verification.json}`
//!
//! The recorded `runtime/audit-proof-report.json` was generated by running
//! `ecaa-workflow-audit-proof` directly on the trimmed fixture so that
//! re-verify is self-consistent (the fixture is its own baseline).

/// **replay_himes_verify_tier_passes_offline** — always runs, fully offline.
///
/// Calls `run_replay(fixture, Tier::Verify)` and asserts the verdict is
/// `ReplayVerdict::Pass`. The recorded `audit-proof-report.json` was produced
/// by running the same verifier on the trimmed fixture, so the re-verify diff
/// must be zero-divergence.
#[test]
fn replay_himes_verify_tier_passes_offline() {
    let pkg = concat!(env!("CARGO_MANIFEST_DIR"), "/../../testdata/replay/himes-parent");
    let opts = ecaa_workflow_core::replay::ReplayOptions {
        tier: ecaa_workflow_core::replay::Tier::Verify,
        scratch_dir: None,
        bounds: None,
        allow_rebuild: false,
        reader_version: "0.2".into(),
    };
    let rep = ecaa_workflow_core::replay::run_replay(std::path::Path::new(pkg), &opts)
        .expect("run_replay must not error on the himes fixture");
    assert_eq!(
        rep.verdict,
        ecaa_workflow_core::replay::ReplayVerdict::Pass,
        "Tier::Verify on himes-parent with matching recorded report must yield Pass;\
         \nreverify={:?}",
        rep.reverify,
    );
    // Sanity: reverify was populated, reexecute was not.
    assert!(
        rep.reverify.is_some(),
        "reverify must be Some for Tier::Verify"
    );
    assert!(
        rep.reexecute.is_none(),
        "reexecute must be None for Tier::Verify"
    );
}

/// **replay_himes_execute_tier_reproduces_de_table** — CI-gated.
///
/// Skips automatically unless `ECAA_REPLAY_EXEC_TEST=1` is set in the
/// environment. Requires R/DESeq2 on the host. When enabled, calls
/// `run_replay(fixture, Tier::Execute)` and asserts that `de_results.tsv`
/// classifies as `ByteIdentical` or `SemanticEquivalent`.
#[test]
fn replay_himes_execute_tier_reproduces_de_table() {
    // CI-gated: needs R + DESeq2; skip when the gate env var is absent.
    if std::env::var("ECAA_REPLAY_EXEC_TEST").is_err() {
        return;
    }
    let pkg = concat!(env!("CARGO_MANIFEST_DIR"), "/../../testdata/replay/himes-parent");
    let opts = ecaa_workflow_core::replay::ReplayOptions {
        tier: ecaa_workflow_core::replay::Tier::Execute,
        scratch_dir: None,
        bounds: None,
        allow_rebuild: false,
        reader_version: "0.2".into(),
    };
    let rep = ecaa_workflow_core::replay::run_replay(std::path::Path::new(pkg), &opts)
        .expect("run_replay must not error on the himes fixture");
    let de = rep
        .reexecute
        .expect("reexecute must be Some for Tier::Execute")
        .report
        .per_artifact
        .iter()
        .find(|a| a.artifact_path.ends_with("de_results.tsv"))
        .expect("de_results.tsv must appear in per_artifact")
        .bucket
        .clone();
    assert!(
        matches!(
            de,
            ecaa_workflow_core::reexecution::ReexecutionBucket::ByteIdentical
                | ecaa_workflow_core::reexecution::ReexecutionBucket::SemanticEquivalent
        ),
        "de_results.tsv must reproduce as ByteIdentical or SemanticEquivalent, got {de:?}"
    );
}
