#!/usr/bin/env python3
"""Generate synthetic input stubs for the L2 per-atom plot smoke test.

Reads ``runtime/plot-atoms-enumeration.json`` (generated by
``enumerate_plot_atoms.py``) and writes one input directory per atom under
``testdata/plot-stubs/<atom_id>/input/``.

Each stub directory contains:
  - ``manifest.json``  — minimal manifest that satisfies the renderer.
  - One or more ``*.tsv`` files   — synthetic numeric data, 50 rows.

The synthetic data columns are inferred from the renderer module's
doc-comment "Expected inputs" section and from well-known filename
conventions (e.g. ``de_table.tsv``, ``qc_metrics.tsv``).

Renderers are tolerant by design: they fall through to
``FigureManifest.skipped`` rather than raising when an artifact is
absent. The stubs ensure at least one figure per stage resolves from
``written`` rather than ``skipped``.
"""
from __future__ import annotations

import json
import random
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
ENUM_FILE = REPO_ROOT / "runtime" / "plot-atoms-enumeration.json"
STUB_ROOT = REPO_ROOT / "testdata" / "plot-stubs"

N_ROWS = 50
random.seed(42)

# ---------------------------------------------------------------------------
# Column generators
# ---------------------------------------------------------------------------

def _without_advancing_rng(fn):
    state = random.getstate()
    try:
        return fn()
    finally:
        random.setstate(state)


def _floats(n: int = N_ROWS, lo: float = 0.0, hi: float = 1.0) -> list[float]:
    return [round(random.uniform(lo, hi), 6) for _ in range(n)]

def _log2fc(n: int = N_ROWS) -> list[float]:
    return [round(random.gauss(0, 2), 4) for _ in range(n)]

def _pvals(n: int = N_ROWS) -> list[float]:
    return [round(10 ** random.uniform(-10, -0.1), 8) for _ in range(n)]

def _gene_names(n: int = N_ROWS) -> list[str]:
    return [f"GENE{i:03d}" for i in range(n)]

def _sample_names(n: int = N_ROWS) -> list[str]:
    return [f"sample_{i:02d}" for i in range(n)]

def _cell_names(n: int = N_ROWS) -> list[str]:
    return [f"cell_{i:04d}" for i in range(n)]

def _chromosomes(n: int = N_ROWS) -> list[str]:
    chroms = [str(i) for i in range(1, 23)] + ["X", "Y"]
    return [random.choice(chroms) for _ in range(n)]

def _positions(n: int = N_ROWS) -> list[int]:
    return [random.randint(1_000_000, 250_000_000) for _ in range(n)]

def _clusters(n: int = N_ROWS, k: int = 8) -> list[str]:
    return [str(random.randint(0, k - 1)) for _ in range(n)]

def _celltypes(n: int = N_ROWS) -> list[str]:
    types = ["T cell", "B cell", "NK cell", "Monocyte", "Dendritic"]
    return [random.choice(types) for _ in range(n)]


def write_tsv(path: Path, columns: dict[str, list]) -> None:
    """Write a tab-separated file from a {header: values} dict."""
    path.parent.mkdir(parents=True, exist_ok=True)
    headers = list(columns.keys())
    rows = list(zip(*columns.values()))
    with open(path, "w") as f:
        f.write("\t".join(headers) + "\n")
        for row in rows:
            f.write("\t".join(str(v) for v in row) + "\n")


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        json.dump(data, f, indent=2)


# ---------------------------------------------------------------------------
# Per-stage stub writers
# ---------------------------------------------------------------------------

def _stub_differential_expression(stub_dir: Path) -> None:
    comp_dir = stub_dir / "comparison_1"
    write_tsv(comp_dir / "de_table.tsv", {
        "feature": _gene_names(),
        "log2fc": _log2fc(),
        "pvalue": _pvals(),
        "adj_pvalue": _pvals(),
        "baseMean": _floats(lo=1, hi=10000),
    })
    write_json(stub_dir / "manifest.json", {
        "comparisons": [{"id": "comparison_1", "table_path": "comparison_1/de_table.tsv"}]
    })


def _stub_normalization(stub_dir: Path) -> None:
    run_dir = stub_dir / "run"
    write_tsv(run_dir / "mean_variance.tsv", {
        "feature": _gene_names(),
        "mean": _floats(lo=0, hi=100),
        "variance": _floats(lo=0, hi=500),
    })
    write_json(stub_dir / "manifest.json", {
        "runs": [{"id": "run", "mean_variance_path": "run/mean_variance.tsv", "n_hvg": 20}]
    })


def _stub_batch_correction(stub_dir: Path) -> None:
    comp_dir = stub_dir / "batch1"
    # Integration stats JSON
    write_json(comp_dir / "integration_stats.json", {
        "mixing_pre": round(random.uniform(0.2, 0.4), 4),
        "mixing_post": round(random.uniform(0.6, 0.9), 4),
    })
    embedding = _without_advancing_rng(lambda: {
        "cell": _cell_names(),
        "umap_1": _floats(lo=-8, hi=8),
        "umap_2": _floats(lo=-8, hi=8),
        "batch": [random.choice(["batch_a", "batch_b"]) for _ in range(N_ROWS)],
    })
    write_tsv(comp_dir / "integrated_embeddings.tsv", embedding)
    write_json(stub_dir / "manifest.json", {
        "compartments": [{"id": "batch1", "mixing_pre": 0.35, "mixing_post": 0.75}]
    })


def _stub_clustering(stub_dir: Path) -> None:
    run_dir = stub_dir / "run"
    clusters = _clusters()
    write_tsv(run_dir / "cluster_labels.tsv", {
        "cell": _cell_names(),
        "cluster": clusters,
        "x": _floats(lo=-10, hi=10),
        "y": _floats(lo=-10, hi=10),
    })
    write_json(run_dir / "cluster_sizes.json", {
        cluster: clusters.count(cluster) for cluster in sorted(set(clusters), key=str)
    })
    write_json(stub_dir / "manifest.json", {
        "runs": [{"id": "run", "n_clusters": 8}]
    })


def _stub_dimensionality_reduction(stub_dir: Path) -> None:
    run_dir = stub_dir / "run"
    write_tsv(run_dir / "embedding.tsv", {
        "x": _floats(lo=-10, hi=10),
        "y": _floats(lo=-10, hi=10),
    })
    variance_ratio = [round(v, 4) for v in sorted(_floats(lo=0.01, hi=0.3), reverse=True)[:20]]
    write_json(run_dir / "variance_ratio.json", variance_ratio)
    write_json(stub_dir / "manifest.json", {
        "runs": [{"id": "run"}]
    })


def _stub_cell_type_annotation(stub_dir: Path) -> None:
    run_dir = stub_dir / "run"
    write_tsv(run_dir / "celltype_labels.tsv", {
        "cell": _cell_names(),
        "celltype": _celltypes(),
        "x": _floats(lo=-10, hi=10),
        "y": _floats(lo=-10, hi=10),
    })
    write_json(stub_dir / "manifest.json", {
        "runs": [{"id": "run", "celltypes": [
            {"id": ct, "n_cells": random.randint(5, 50), "markers": []}
            for ct in ["T cell", "B cell", "NK cell", "Monocyte", "Dendritic"]
        ]}]
    })


def _stub_quality_control(stub_dir: Path) -> None:
    write_tsv(stub_dir / "qc_metrics.tsv", {
        "sample": [f"sample_{i % 5:02d}" for i in range(N_ROWS)],
        "metric": [random.choice(["n_genes", "n_counts", "pct_mito"]) for _ in range(N_ROWS)],
        "value": _floats(lo=0, hi=5000),
    })
    summary = _without_advancing_rng(lambda: {
        "n_samples": 5,
        "n_cells": random.randint(5_000, 20_000),
        "median_genes": random.randint(500, 3_000),
        "median_pct_mito": round(random.uniform(0.02, 0.12), 4),
    })
    write_json(stub_dir / "summary_stats.json", summary)
    write_json(stub_dir / "manifest.json", {
        "per_sample_metrics": {
            f"sample_{i:02d}": {
                "n_genes": random.randint(200, 3000),
                "pct_mito": round(random.uniform(0, 0.2), 4),
            }
            for i in range(5)
        }
    })


def _stub_trajectory_analysis(stub_dir: Path) -> None:
    run_dir = stub_dir / "run"
    write_tsv(run_dir / "pseudotime.tsv", {
        "cell": _cell_names(),
        "pseudotime": _floats(lo=0, hi=1),
        "x": _floats(lo=-10, hi=10),
        "y": _floats(lo=-10, hi=10),
        "branch": [str(random.randint(0, 2)) for _ in range(N_ROWS)],
    })
    write_json(stub_dir / "manifest.json", {
        "runs": [{"id": "run", "pseudotime_path": "run/pseudotime.tsv"}]
    })


def _stub_cell_cell_communication(stub_dir: Path) -> None:
    pairs = [(ct1, ct2) for ct1 in ["T cell", "B cell", "Monocyte"]
             for ct2 in ["T cell", "B cell", "Monocyte"]][:N_ROWS]
    interactions = [
        {"source": s, "target": t, "n_pairs": random.randint(1, 100),
         "strength": round(random.uniform(0.01, 1.0), 4),
         "pathway": random.choice(["MHC", "TIGIT", "CXCL", "CCL"])}
        for s, t in pairs[:N_ROWS]
    ]
    write_json(stub_dir / "manifest.json", {"interactions": interactions})


def _stub_spatial_clustering(stub_dir: Path) -> None:
    # tissue_overlay reads coords_table with x, y, value
    # morans_i_scatter reads morans_i_table with gene, morans_i, p_value
    # neighborhood_enrichment reads neighborhood_table with source, target, score
    write_tsv(stub_dir / "coords.tsv", {
        "x": _floats(lo=0, hi=500),
        "y": _floats(lo=0, hi=500),
        "value": [str(random.randint(0, 5)) for _ in range(N_ROWS)],
    })
    write_tsv(stub_dir / "morans_i.tsv", {
        "gene": _gene_names(),
        "morans_i": _floats(lo=-1, hi=1),
        "p_value": _pvals(),
    })
    write_tsv(stub_dir / "neighborhood.tsv", {
        "source": [str(random.randint(0, 5)) for _ in range(N_ROWS)],
        "target": [str(random.randint(0, 5)) for _ in range(N_ROWS)],
        "score": _floats(lo=0, hi=1),
    })
    write_json(stub_dir / "manifest.json", {
        "coords_table": "coords.tsv",
        "morans_i_table": "morans_i.tsv",
        "neighborhood_table": "neighborhood.tsv",
    })


def _stub_variant_filtering(stub_dir: Path) -> None:
    write_tsv(stub_dir / "summary_stats.tsv", {
        "chrom": _chromosomes(),
        "pos": _positions(),
        "pvalue": _pvals(),
        "gene": [f"GENE{i}" for i in range(N_ROWS)],
    })
    write_json(stub_dir / "manifest.json", {"summary_stats": "summary_stats.tsv"})


def _stub_colocalization(stub_dir: Path) -> None:
    write_tsv(stub_dir / "summary_stats.tsv", {
        "chrom": _chromosomes(),
        "pos": _positions(),
        "pvalue": _pvals(),
        "gene": [f"GENE{i}" for i in range(N_ROWS)],
    })
    write_tsv(stub_dir / "coloc_table.tsv", {
        "locus": [f"locus_{i}" for i in range(20)],
        "pp.h0": _floats(n=20, lo=0, hi=0.1),
        "pp.h1": _floats(n=20, lo=0, hi=0.2),
        "pp.h2": _floats(n=20, lo=0, hi=0.2),
        "pp.h3": _floats(n=20, lo=0, hi=0.2),
        "pp.h4": _floats(n=20, lo=0.5, hi=1.0),
    })
    write_json(stub_dir / "manifest.json", {
        "summary_stats": "summary_stats.tsv",
        "coloc_table": "coloc_table.tsv",
        "miami_top": "summary_stats.tsv",
        "miami_bottom": "summary_stats.tsv",
    })


def _stub_validate_colocalization(stub_dir: Path) -> None:
    write_tsv(stub_dir / "coloc_table.tsv", {
        "locus": [f"locus_{i}" for i in range(20)],
        "pp.h0": _floats(n=20, lo=0, hi=0.1),
        "pp.h1": _floats(n=20, lo=0, hi=0.2),
        "pp.h2": _floats(n=20, lo=0, hi=0.2),
        "pp.h3": _floats(n=20, lo=0, hi=0.2),
        "pp.h4": _floats(n=20, lo=0.5, hi=1.0),
    })
    write_json(stub_dir / "manifest.json", {"coloc_table": "coloc_table.tsv"})


def _stub_biological_interpretation(stub_dir: Path) -> None:
    write_tsv(stub_dir / "enrichment.tsv", {
        "term": [f"GO:000{i:04d}" for i in range(N_ROWS)],
        "p_value": _pvals(),
        "adj_p_value": _pvals(),
        "n_overlap": [random.randint(1, 50) for _ in range(N_ROWS)],
    })
    write_json(stub_dir / "manifest.json", {
        "enrichments": [
            {"id": f"term_{i}", "term": f"GO:000{i:04d}",
             "p_value": round(10 ** random.uniform(-8, -0.5), 8),
             "adj_p_value": round(10 ** random.uniform(-6, -0.5), 8),
             "n_overlap": random.randint(1, 50), "n_set": 100, "n_universe": 20000}
            for i in range(30)
        ]
    })


def _stub_peak_calling(stub_dir: Path) -> None:
    # profile_pileup reads profile_table: position, signal, group?
    # coverage_track reads coverage_table: chrom, pos, depth
    # peak_saturation reads saturation_table: depth, peaks_called, group?
    write_tsv(stub_dir / "profile.tsv", {
        "position": list(range(-500, N_ROWS - 500)),
        "signal": _floats(lo=0, hi=50),
        "group": [random.choice(["H3K27ac", "H3K4me3"]) for _ in range(N_ROWS)],
    })
    write_tsv(stub_dir / "coverage.tsv", {
        "chrom": ["chr1"] * N_ROWS,
        "pos": [i * 100 for i in range(N_ROWS)],
        "depth": [random.randint(1, 100) for _ in range(N_ROWS)],
    })
    write_tsv(stub_dir / "saturation.tsv", {
        "depth": sorted([random.randint(100_000, 50_000_000) for _ in range(N_ROWS)]),
        "peaks_called": [random.randint(1000, 100_000) for _ in range(N_ROWS)],
        "group": ["sample_01"] * N_ROWS,
    })
    write_json(stub_dir / "manifest.json", {
        "profile_table": "profile.tsv",
        "coverage_table": "coverage.tsv",
        "saturation_table": "saturation.tsv",
    })


def _stub_differential_accessibility(stub_dir: Path) -> None:
    comp_dir = stub_dir / "comparison_1"
    starts = [100_000 + i * 900 for i in range(N_ROWS)]
    write_tsv(comp_dir / "differential_peaks.tsv", {
        "peak": [f"chr1:{start}-{start + 250}" for start in starts],
        "log2fc": _log2fc(),
        "pvalue": _pvals(),
        "adj_pvalue": _pvals(),
        "baseMean": _floats(lo=20, hi=3000),
    })
    write_json(stub_dir / "manifest.json", {
        "comparisons": [
            {"id": "treated_vs_control", "table_path": "comparison_1/differential_peaks.tsv"}
        ]
    })


def _stub_peak_annotation(stub_dir: Path) -> None:
    features = ["promoter", "exon", "intron", "intergenic", "UTR"]
    write_tsv(stub_dir / "peak_annotation.tsv", {
        "peak": [f"chr1:{100_000 + i * 700}-{100_250 + i * 700}" for i in range(N_ROWS)],
        "feature_class": [random.choice(features) for _ in range(N_ROWS)],
        "nearest_gene": _gene_names(),
        "distance_to_tss": [random.randint(-150_000, 150_000) for _ in range(N_ROWS)],
    })
    write_json(stub_dir / "manifest.json", {"annotation_table": "peak_annotation.tsv"})


def _stub_motif_enrichment(stub_dir: Path) -> None:
    consensuses = ["ACGTAC", "TATAAA", "GCGCGC", "AACCGG", "TTGCAC", "CGTATA"]
    write_tsv(stub_dir / "enriched_motifs.tsv", {
        "motif_id": [f"MOTIF_{i:02d}" for i in range(N_ROWS)],
        "family": [random.choice(["bZIP", "ETS", "HOX", "GATA", "NF-kB"]) for _ in range(N_ROWS)],
        "adj_p_value": _pvals(),
        "fold_enrichment": _floats(lo=1.2, hi=12.0),
        "consensus": [consensuses[i % len(consensuses)] for i in range(N_ROWS)],
    })
    write_json(stub_dir / "manifest.json", {"motif_table": "enriched_motifs.tsv"})


def _stub_quantification(stub_dir: Path) -> None:
    # peptide_coverage reads coverage_table: position, coverage
    # ridgeline reads intensity_table: group, value
    write_tsv(stub_dir / "coverage.tsv", {
        "position": list(range(1, N_ROWS + 1)),
        "coverage": [random.randint(0, 10) for _ in range(N_ROWS)],
    })
    write_tsv(stub_dir / "intensity.tsv", {
        "group": [f"sample_{i % 5:02d}" for i in range(N_ROWS)],
        "value": _floats(lo=10, hi=25),
    })
    write_json(stub_dir / "manifest.json", {
        "coverage_table": "coverage.tsv",
        "intensity_table": "intensity.tsv",
    })


def _stub_isoform_calling(stub_dir: Path) -> None:
    # isoform_structure reads isoform_table: transcript, exon_starts, exon_ends
    # (comma-separated), strand?
    # sashimi reads junction_table: junction ("start-end" string), count
    starts = [[100 + i * 500, 800 + i * 500] for i in range(10)]
    ends   = [[200 + i * 500, 900 + i * 500] for i in range(10)]
    write_tsv(stub_dir / "isoforms.tsv", {
        "transcript": [f"ENST{i:09d}" for i in range(10)],
        "exon_starts": [",".join(str(s) for s in row) for row in starts],
        "exon_ends":   [",".join(str(e) for e in row) for row in ends],
        "strand": ["+"] * 10,
    })
    write_tsv(stub_dir / "junctions.tsv", {
        "junction": [f"{200 + i * 500}-{800 + i * 500}" for i in range(10)],
        "count": [random.randint(10, 1000) for _ in range(10)],
    })
    write_json(stub_dir / "manifest.json", {
        "isoform_table": "isoforms.tsv",
        "junction_table": "junctions.tsv",
    })


def _stub_multi_omics_integration(stub_dir: Path) -> None:
    n = 5
    matrix = [[round(random.uniform(0, 1), 4) for _ in range(n)] for _ in range(n)]
    modalities = ["RNA", "ATAC", "Protein", "Methylation", "CNV"][:n]
    write_json(stub_dir / "manifest.json", {
        "modality_concordance_matrix": matrix,
        "row_labels": modalities,
        "col_labels": modalities,
        "factor_variance": [
            {"factor": f"Factor{i}", "variance": round(random.uniform(0.05, 0.3), 4)}
            for i in range(1, 6)
        ],
    })


def _stub_taxonomic_profiling(stub_dir: Path) -> None:
    # taxonomic_stacked_bar reads abundance_table with sample, taxon, abundance
    # diversity_violin reads diversity_table with group, value (canonical key for "diversity" alias)
    #   and diversity_col="value" is passed explicitly to fix the canonical remapping
    samples = [f"sample_{i:02d}" for i in range(10)]
    taxa = [f"Species_{i}" for i in range(5)]
    write_tsv(stub_dir / "abundances.tsv", {
        "sample": [s for s in samples for _ in taxa],
        "taxon": [t for _ in samples for t in taxa],
        "abundance": _floats(n=50, lo=0, hi=0.4),
    })
    # diversity_table: group + diversity columns (multiple rows per group for violin)
    groups = ["cohort_A", "cohort_B"]
    write_tsv(stub_dir / "diversity.tsv", {
        "group": [g for g in groups for _ in range(15)],
        "diversity": _floats(n=30, lo=1, hi=4),
    })
    write_json(stub_dir / "manifest.json", {
        "abundance_table": "abundances.tsv",
        "diversity_table": "diversity.tsv",
    })


def _stub_data_acquisition(stub_dir: Path) -> None:
    write_json(stub_dir / "manifest.json", {
        "samples": [
            {"id": f"sample_{i:02d}", "size_bytes": random.randint(1_000_000, 10_000_000_000),
             "study_id": f"study_{i % 3}"}
            for i in range(20)
        ]
    })


def _stub_preprocessing(stub_dir: Path) -> None:
    write_json(stub_dir / "manifest.json", {
        "samples": [
            {"id": f"sample_{i:02d}", "n_in": random.randint(1_000_000, 50_000_000),
             "n_out": random.randint(800_000, 40_000_000)}
            for i in range(10)
        ]
    })


def _stub_reporting(stub_dir: Path) -> None:
    n = 4
    write_json(stub_dir / "manifest.json", {
        "concordance_matrix": [
            [round(random.uniform(0.7, 1.0), 3) for _ in range(n)] for _ in range(n)
        ],
        "row_labels": [f"Method{i}" for i in range(n)],
        "col_labels": [f"Method{i}" for i in range(n)],
        "pathway_overlap": [
            {"term": f"Pathway_{i}", "set_a": random.randint(5, 50), "set_b": random.randint(5, 50),
             "overlap": random.randint(1, 20)}
            for i in range(20)
        ],
    })


def _stub_final_reporting(stub_dir: Path) -> None:
    # final_reporting scans parent dir for stage subdirs; minimal manifest is enough
    write_json(stub_dir / "manifest.json", {
        "upstream": [
            {"stage_id": "differential_expression",
             "figures": [{"id": "volcano", "path": "volcano.png", "title": "Volcano plot"}]}
        ]
    })


def _stub_benchmarking(stub_dir: Path) -> None:
    write_tsv(stub_dir / "benchmarking.tsv", {
        "method": [f"method_{i % 5}" for i in range(N_ROWS)],
        "metric": [random.choice(["precision", "recall", "f1"]) for _ in range(N_ROWS)],
        "value": _floats(lo=0, hi=1),
        "ci_low": _floats(lo=0, hi=0.5),
        "ci_high": _floats(lo=0.5, hi=1),
    })
    write_json(stub_dir / "manifest.json", {"benchmarking_path": "benchmarking.tsv"})


def _stub_primary_endpoint(stub_dir: Path) -> None:
    write_tsv(stub_dir / "survival.tsv", {
        "time": _floats(lo=0, hi=60),
        "event": [str(random.randint(0, 1)) for _ in range(N_ROWS)],
        "group": [random.choice(["treatment", "control"]) for _ in range(N_ROWS)],
    })
    write_tsv(stub_dir / "forest.tsv", {
        "label": ["Overall", "Age <65", "Age >=65", "Female", "Male"],
        "effect": [0.72, 0.68, 0.81, 0.74, 0.70],
        "ci_lo": [0.55, 0.49, 0.58, 0.52, 0.51],
        "ci_hi": [0.94, 0.95, 1.12, 1.04, 0.97],
        "weight": [100, 45, 55, 48, 52],
    })
    write_json(stub_dir / "manifest.json", {
        "survival_table": "survival.tsv",
        "forest_table": "forest.tsv",
    })


def _stub_exploratory_analysis(stub_dir: Path) -> None:
    # decomposition_panel + acf_pacf_panel both read series_table: time, value
    # Needs 120+ evenly-spaced points for decomposition to work
    n_series = 120
    write_tsv(stub_dir / "series.tsv", {
        "time": list(range(n_series)),
        "value": [10 + 5 * (i % 12) / 12 + random.gauss(0, 1) for i in range(n_series)],
    })
    write_json(stub_dir / "manifest.json", {"series_table": "series.tsv"})


def _stub_forecasting_inference(stub_dir: Path) -> None:
    # forecast_ribbon reads forecast_table: time, forecast, lower, upper, actual?
    # anomaly_timeline reads anomaly_table: time, value, is_anomaly
    write_tsv(stub_dir / "forecast.tsv", {
        "time": list(range(N_ROWS)),
        "forecast": _floats(lo=0, hi=100),
        "lower": _floats(lo=0, hi=50),
        "upper": _floats(lo=50, hi=150),
        "actual": _floats(lo=0, hi=100),
    })
    write_tsv(stub_dir / "anomaly.tsv", {
        "time": list(range(N_ROWS)),
        "value": _floats(lo=0, hi=100),
        "is_anomaly": [str(1 if random.random() > 0.9 else 0) for _ in range(N_ROWS)],
    })
    write_json(stub_dir / "manifest.json", {
        "forecast_table": "forecast.tsv",
        "anomaly_table": "anomaly.tsv",
    })


def _stub_population_definition(stub_dir: Path) -> None:
    # consort_diagram reads manifest.population_flow dict with CONSORT stage keys
    write_json(stub_dir / "manifest.json", {
        "population_flow": {
            "enrolled": 500,
            "enrolled_excluded": "Ineligible (n=50)",
            "randomized": 450,
            "allocated": 450,
            "allocated_excluded": "Withdrew (n=10)",
            "followed_up": 440,
            "followed_up_excluded": "Lost to follow-up (n=5)",
            "analyzed": 435,
        }
    })


def _stub_vdj_repertoire(stub_dir: Path) -> None:
    # public_clonotype_size_bar checks is_public == "true" (string, not "1")
    write_tsv(stub_dir / "vdj_per_cell.tsv", {
        "cell": _cell_names(),
        "chain": [random.choice(["TRA", "TRB", "IGH", "IGL"]) for _ in range(N_ROWS)],
        "cdr3_length": [random.randint(8, 20) for _ in range(N_ROWS)],
        "v_segment": [f"TRAV{random.randint(1, 30)}" for _ in range(N_ROWS)],
        "clonotype_id": [f"clone_{random.randint(0, 20)}" for _ in range(N_ROWS)],
    })
    write_tsv(stub_dir / "clonotype_table.tsv", {
        "clonotype_id": [f"clone_{i}" for i in range(20)],
        "frequency": _floats(n=20, lo=0.001, hi=0.1),
        "is_public": ["true" if i % 3 == 0 else "false" for i in range(20)],
        "n_members": [str(random.randint(1, 50)) for _ in range(20)],
    })
    write_tsv(stub_dir / "diversity_table.tsv", {
        "sample": [f"sample_{i:02d}" for i in range(10)],
        "shannon": _floats(n=10, lo=1, hi=4),
        "gini": _floats(n=10, lo=0, hi=1),
        "chao1": _floats(n=10, lo=10, hi=500),
    })
    write_json(stub_dir / "manifest.json", {
        "vdj_per_cell_path": "vdj_per_cell.tsv",
        "clonotype_table_path": "clonotype_table.tsv",
        "diversity_table_path": "diversity_table.tsv",
    })


def _stub_hla_peptidomics(stub_dir: Path) -> None:
    # binder_rank_histogram + allele_presentation_heatmap read from binders.tsv
    # (rank, allele, peptide)
    # neoantigen_per_patient_bar reads from neoantigens.tsv (patient, peptide, allele, rank)
    write_tsv(stub_dir / "peptides.tsv", {
        "peptide": [f"PEPTIDE{i:03d}" for i in range(N_ROWS)],
        "length": [random.randint(8, 15) for _ in range(N_ROWS)],
        "score": _floats(lo=0, hi=100),
    })
    write_tsv(stub_dir / "binders.tsv", {
        "peptide": [f"PEPTIDE{i:03d}" for i in range(N_ROWS)],
        "allele": [
            random.choice(["HLA-A*02:01", "HLA-B*07:02", "HLA-C*07:02"]) for _ in range(N_ROWS)
        ],
        "rank": _floats(lo=0.01, hi=3.0),
    })
    write_tsv(stub_dir / "neoantigens.tsv", {
        "patient": [f"patient_{random.randint(0, 9):02d}" for _ in range(N_ROWS)],
        "peptide": [f"PEPTIDE{i:03d}" for i in range(N_ROWS)],
        "allele": [random.choice(["HLA-A*02:01", "HLA-B*07:02"]) for _ in range(N_ROWS)],
        "rank": _floats(lo=0.01, hi=2.0),
    })
    write_json(stub_dir / "manifest.json", {
        "peptides_path": "peptides.tsv",
        "binders_path": "binders.tsv",
        "neoantigens_path": "neoantigens.tsv",
    })


def _stub_crispr_screen(stub_dir: Path) -> None:
    write_tsv(stub_dir / "sgrna_assignments.tsv", {
        "cell": _cell_names(),
        "sgrna": [f"sgRNA_{random.randint(0, 20):03d}" for _ in range(N_ROWS)],
        "umi_count": [random.randint(1, 50) for _ in range(N_ROWS)],
        "perturbation": [f"target_{random.randint(0, 9)}" for _ in range(N_ROWS)],
    })
    write_json(stub_dir / "manifest.json", {"assignments_path": "sgrna_assignments.tsv"})


def _stub_ribo_seq(stub_dir: Path) -> None:
    write_tsv(stub_dir / "psite_offset.tsv", {
        "read_length": list(range(25, 25 + N_ROWS)),
        "offset": [random.randint(10, 16) for _ in range(N_ROWS)],
    })
    write_tsv(stub_dir / "frame_counts.tsv", {
        "frame": ["frame0", "frame1", "frame2"],
        "count": [45000, 12000, 9000],
    })
    write_tsv(stub_dir / "te_results.tsv", {
        "gene": _gene_names(),
        "log2fc_te": _log2fc(),
        "pvalue": _pvals(),
        "log2fc_rna": _log2fc(),
        "log2fc_ribo": _log2fc(),
    })
    write_json(stub_dir / "manifest.json", {
        "psite_offset_path": "psite_offset.tsv",
        "frame_counts_path": "frame_counts.tsv",
        "te_results_path": "te_results.tsv",
    })


def _stub_dtu(stub_dir: Path) -> None:
    # dtu_volcano reads "dProportion" column, not "log2fc"
    write_tsv(stub_dir / "dtu.tsv", {
        "transcript": [f"ENST{i:09d}" for i in range(N_ROWS)],
        "gene": [f"GENE{i % 10:03d}" for i in range(N_ROWS)],
        "dProportion": _floats(lo=-0.5, hi=0.5),
        "pvalue": _pvals(),
        "adj_pvalue": _pvals(),
        "usage_treatment": _floats(lo=0, hi=1),
        "usage_control": _floats(lo=0, hi=1),
    })
    write_json(stub_dir / "manifest.json", {"dtu_path": "dtu.tsv"})


def _stub_enhancer_activity(stub_dir: Path) -> None:
    # renderer reads "rna_count", "dna_count", "activity_score" columns
    write_tsv(stub_dir / "activity.tsv", {
        "enhancer": [f"ENH_{i:05d}" for i in range(N_ROWS)],
        "rna_count": [random.randint(1, 1000) for _ in range(N_ROWS)],
        "dna_count": [random.randint(1, 1000) for _ in range(N_ROWS)],
        "activity_score": _floats(lo=0.1, hi=5.0),
        "pvalue": _pvals(),
    })
    write_json(stub_dir / "manifest.json", {"activity_path": "activity.tsv"})


def _stub_methylation_expression(stub_dir: Path) -> None:
    # renderer reads "methylation" and "expression" columns (not "methylation_fc")
    write_tsv(stub_dir / "correlations.tsv", {
        "gene": _gene_names(),
        "methylation": _floats(lo=0, hi=1),
        "expression": _log2fc(),
        "correlation": _floats(lo=-1, hi=1),
        "pvalue": _pvals(),
    })
    write_json(stub_dir / "manifest.json", {"correlations_path": "correlations.tsv"})


def _stub_regulatory_variants(stub_dir: Path) -> None:
    overlaps_peak = _without_advancing_rng(
        lambda: ["true" if random.random() > 0.35 else "false" for _ in range(N_ROWS)]
    )
    write_tsv(stub_dir / "cis_scores.tsv", {
        "variant": [f"chr1_{i * 1000}" for i in range(N_ROWS)],
        "variant_id": [f"chr1_{i * 1000}" for i in range(N_ROWS)],
        "log2fc": _log2fc(),
        "pvalue": _pvals(),
        "n_peaks_overlap": [random.randint(0, 20) for _ in range(N_ROWS)],
        "overlaps_peak": overlaps_peak,
    })
    write_json(stub_dir / "manifest.json", {"scores_path": "cis_scores.tsv"})


def _stub_chromatin_contacts(stub_dir: Path) -> None:
    # renderer reads "chrom_a", "chrom_b" (not "chrom1", "chrom2")
    # distance must be >0 for distance_decay_curve; bias toward cis for cis_trans_ratio
    chroms = ["chr1", "chr2", "chr3", "chr4", "chr5"]
    chrom_a = [random.choice(chroms[:3]) for _ in range(N_ROWS)]
    chrom_b = [ca if random.random() > 0.3 else random.choice(chroms[:3]) for ca in chrom_a]
    write_tsv(stub_dir / "contacts.tsv", {
        "chrom_a": chrom_a,
        "chrom_b": chrom_b,
        "count": [random.randint(1, 1000) for _ in range(N_ROWS)],
        "distance": [random.randint(5000, 2_000_000) for _ in range(N_ROWS)],
    })
    write_json(stub_dir / "manifest.json", {"contacts_path": "contacts.tsv"})


def _stub_chromatin_loops(stub_dir: Path) -> None:
    # loop_size_distribution needs "size" column; loop_volcano + differential_loop_arc
    # use differential_loops.tsv
    write_tsv(stub_dir / "loops.tsv", {
        "loop_id": [f"loop_{i}" for i in range(N_ROWS)],
        "chrom": ["chr1"] * N_ROWS,
        "start1": [i * 10000 for i in range(N_ROWS)],
        "end1": [i * 10000 + 200 for i in range(N_ROWS)],
        "start2": [i * 10000 + 50000 for i in range(N_ROWS)],
        "end2": [i * 10000 + 50200 for i in range(N_ROWS)],
        "size": [random.randint(5000, 500_000) for _ in range(N_ROWS)],
    })
    write_tsv(stub_dir / "differential_loops.tsv", {
        "loop_id": [f"loop_{i}" for i in range(N_ROWS)],
        "start": [i * 10000 for i in range(N_ROWS)],
        "end": [i * 10000 + 50000 for i in range(N_ROWS)],
        "log2fc": _log2fc(),
        "pvalue": _pvals(),
    })
    write_json(stub_dir / "manifest.json", {
        "loops_path": "loops.tsv",
        "differential_loops_path": "differential_loops.tsv",
    })


def _stub_peak_to_gene(stub_dir: Path) -> None:
    # peak_to_gene_arc reads "peak_start" and "tss" columns (not "peak")
    write_tsv(stub_dir / "links.tsv", {
        "peak": [f"chr1_{i * 500}_{i * 500 + 500}" for i in range(N_ROWS)],
        "peak_start": [i * 500 for i in range(N_ROWS)],
        "tss": [i * 500 + random.randint(1000, 100_000) for i in range(N_ROWS)],
        "gene": [f"GENE{i % 20:03d}" for i in range(N_ROWS)],
        "score": _floats(lo=0, hi=1),
        "distance": [random.randint(0, 500_000) for _ in range(N_ROWS)],
        "cluster": _clusters(),
    })
    write_json(stub_dir / "manifest.json", {"links_path": "links.tsv"})


def _stub_joint_wnn(stub_dir: Path) -> None:
    # cluster_composition_bar reads "x", "y", "cluster", "rna_weight", "atac_weight"
    write_tsv(stub_dir / "wnn_embedding.tsv", {
        "cell": _cell_names(),
        "x": _floats(lo=-10, hi=10),
        "y": _floats(lo=-10, hi=10),
        "cluster": _clusters(),
        "rna_weight": _floats(lo=0.3, hi=0.7),
        "atac_weight": _floats(lo=0.3, hi=0.7),
    })
    write_json(stub_dir / "manifest.json", {"embedding_path": "wnn_embedding.tsv"})


def _stub_barcode_pairing(stub_dir: Path) -> None:
    # barcode_pairing reads pairing_summary.json with {flows: [{source, target, n}]}
    write_json(stub_dir / "pairing_summary.json", {
        "flows": [
            {"source": "Raw barcodes", "target": "Demultiplexed", "n": 8000},
            {"source": "Demultiplexed", "target": "Paired", "n": 7200},
            {"source": "Demultiplexed", "target": "Unpaired", "n": 800},
        ]
    })
    write_json(stub_dir / "manifest.json", {
        "summary_path": "pairing_summary.json",
    })


def _stub_diablo(stub_dir: Path) -> None:
    # diablo_components_scatter reads "comp1", "comp2", "group" columns
    # diablo_loadings_heatmap reads "feature", "modality", "loading_comp1" columns
    # modality_concordance_heatmap reads concordance.tsv: modality_a, modality_b, correlation
    write_tsv(stub_dir / "components.tsv", {
        "cell": _cell_names(),
        "comp1": _floats(lo=-3, hi=3),
        "comp2": _floats(lo=-3, hi=3),
        "group": [random.choice(["A", "B"]) for _ in range(N_ROWS)],
    })
    write_tsv(stub_dir / "loadings.tsv", {
        "feature": _gene_names(),
        "modality": [random.choice(["RNA", "Protein"]) for _ in range(N_ROWS)],
        "loading_comp1": _floats(lo=-1, hi=1),
    })
    modalities = ["RNA", "Protein", "Methylation", "ATAC"]
    pairs = [(a, b) for a in modalities for b in modalities]
    concordance = _without_advancing_rng(lambda: {
        "modality_a": [a for a, _ in pairs],
        "modality_b": [b for _, b in pairs],
        "correlation": _floats(n=len(pairs), lo=0.1, hi=0.95),
    })
    write_tsv(stub_dir / "concordance.tsv", concordance)
    n = 4
    matrix = [[round(random.uniform(0, 1), 4) for _ in range(n)] for _ in range(n)]
    write_json(stub_dir / "manifest.json", {
        "components_path": "components.tsv",
        "loadings_path": "loadings.tsv",
        "concordance_path": "concordance.tsv",
        "modality_concordance_matrix": matrix,
        "row_labels": modalities,
        "col_labels": modalities,
        "factor_variance": [
            {"factor": f"comp_{i}", "variance": round(random.uniform(0.05, 0.3), 4)}
            for i in range(1, 6)
        ],
    })


def _stub_snf(stub_dir: Path) -> None:
    n = 5
    matrix = [[round(random.uniform(0, 1), 4) for _ in range(n)] for _ in range(n)]
    write_tsv(stub_dir / "snf_matrix.tsv", {
        "sample": [f"sample_{i:02d}" for i in range(N_ROWS)],
        **{f"sample_{j:02d}": _floats() for j in range(n)},
    })
    clusters = _without_advancing_rng(lambda: {
        "cluster": [str(i) for i in range(4)],
        "n_samples": [random.randint(5, 20) for _ in range(4)],
    })
    write_tsv(stub_dir / "clusters.tsv", clusters)
    write_json(stub_dir / "manifest.json", {
        "fused_matrix_path": "snf_matrix.tsv",
        "clusters_path": "clusters.tsv",
        "modality_concordance_matrix": matrix,
        "row_labels": [f"M{i}" for i in range(n)],
        "col_labels": [f"M{i}" for i in range(n)],
        "factor_variance": [
            {"factor": f"f{i}", "variance": round(random.uniform(0.05, 0.3), 4)}
            for i in range(1, 6)
        ],
        "cluster_assignments": {f"sample_{i:02d}": random.randint(0, 3) for i in range(N_ROWS)},
    })


# Map from stage_id (last dotted segment of renderer_module) to stub writer.
_STUB_MAP = {
    "differential_expression": _stub_differential_expression,
    "normalization": _stub_normalization,
    "batch_correction": _stub_batch_correction,
    "clustering": _stub_clustering,
    "dimensionality_reduction": _stub_dimensionality_reduction,
    "cell_type_annotation": _stub_cell_type_annotation,
    "quality_control": _stub_quality_control,
    "trajectory_analysis": _stub_trajectory_analysis,
    "cell_cell_communication": _stub_cell_cell_communication,
    "spatial_clustering": _stub_spatial_clustering,
    "variant_filtering": _stub_variant_filtering,
    "colocalization": _stub_colocalization,
    "validate_colocalization": _stub_validate_colocalization,
    "biological_interpretation": _stub_biological_interpretation,
    "peak_calling": _stub_peak_calling,
    "differential_accessibility": _stub_differential_accessibility,
    "peak_annotation": _stub_peak_annotation,
    "motif_enrichment": _stub_motif_enrichment,
    "quantification": _stub_quantification,
    "isoform_calling": _stub_isoform_calling,
    "multi_omics_integration": _stub_multi_omics_integration,
    "taxonomic_profiling": _stub_taxonomic_profiling,
    "data_acquisition": _stub_data_acquisition,
    "preprocessing": _stub_preprocessing,
    "reporting": _stub_reporting,
    "final_reporting": _stub_final_reporting,
    "benchmarking": _stub_benchmarking,
    "primary_endpoint": _stub_primary_endpoint,
    "exploratory_analysis": _stub_exploratory_analysis,
    "forecasting_inference": _stub_forecasting_inference,
    "population_definition": _stub_population_definition,
    "vdj_repertoire": _stub_vdj_repertoire,
    "hla_peptidomics": _stub_hla_peptidomics,
    "crispr_screen": _stub_crispr_screen,
    "ribo_seq": _stub_ribo_seq,
    "dtu": _stub_dtu,
    "enhancer_activity": _stub_enhancer_activity,
    "methylation_expression": _stub_methylation_expression,
    "regulatory_variants": _stub_regulatory_variants,
    "chromatin_contacts": _stub_chromatin_contacts,
    "chromatin_loops": _stub_chromatin_loops,
    "peak_to_gene": _stub_peak_to_gene,
    "joint_wnn": _stub_joint_wnn,
    "barcode_pairing": _stub_barcode_pairing,
    "diablo": _stub_diablo,
    "snf": _stub_snf,
}


def main() -> None:
    if not ENUM_FILE.exists():
        print(
            f"ERROR: {ENUM_FILE} not found. Run: python3 scripts/enumerate_plot_atoms.py "
            "> runtime/plot-atoms-enumeration.json",
            file=sys.stderr,
        )
        sys.exit(1)

    with open(ENUM_FILE) as f:
        atoms = json.load(f)

    written = 0
    skipped = 0
    for atom in atoms:
        atom_id = atom["atom_id"]
        stage_id = atom["stage_id"]
        stub_dir = STUB_ROOT / atom_id / "input"

        writer = _STUB_MAP.get(stage_id)
        if writer is None:
            print(f"  SKIP  {atom_id}: no stub writer for stage_id={stage_id}", file=sys.stderr)
            skipped += 1
            continue

        stub_dir.mkdir(parents=True, exist_ok=True)
        try:
            writer(stub_dir)
            print(f"  OK    {atom_id}  ({stage_id})")
            written += 1
        except Exception as e:
            print(f"  ERROR {atom_id}: {e}", file=sys.stderr)

    print(f"\nGenerated stubs: {written}, skipped (no writer): {skipped}", file=sys.stderr)


if __name__ == "__main__":
    main()
