#!/usr/bin/env python3
"""
Small-subset / non-archetype request: SME explicitly asks for ONLY a
specific 3-4 analyses (no full archetype). Verifies the emitted DAG
contains the user's requested atoms + their compulsory dependencies +
final_reporting + no superfluous archetype "padding" stages.

Acceptance:
  - Emitted DAG has fewer than the canonical archetype's full task
  count for the dominant modality (e.g., bulk_rnaseq archetype is
  ~32; subset request should land under 20).
  - Emitted DAG MUST include the explicit user-requested atom types.
  - Emitted DAG MUST NOT include atoms the user explicitly excluded.
  - Connectivity: no stranded nodes.
"""

import glob
import json
import os
import sys
import time
import urllib.error
import urllib.request

SERVER = os.environ.get("ECAA_SERVER_URL", "http://127.0.0.1:3000")
PACKAGE_ROOT = os.environ.get("ECAA_PACKAGE_ROOT", "/tmp/swfc-packages-test")
PREFIX = "/api/v1/chat"
POLL = 4
PER_TURN = 240


def http(method, path, body=None, timeout=PER_TURN):
    url = SERVER + path
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    if body is not None:
        req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            raw = r.read()
            try:
                return r.status, json.loads(raw) if raw else None
            except json.JSONDecodeError:
                return r.status, raw.decode(errors="replace")
    except urllib.error.HTTPError as e:
        return e.code, e.read().decode(errors="replace")


def poll_until(sid, targets, timeout):
    deadline = time.time() + timeout
    while time.time() < deadline:
        code, body = http("GET", f"{PREFIX}/session/{sid}/state", timeout=10)
        kind = "unknown"
        if code == 200 and isinstance(body, dict):
            st = body.get("state")
            kind = st.get("kind") if isinstance(st, dict) else str(st)
        if kind in targets:
            return kind
        time.sleep(POLL)
    return kind


PROMPT = """I have a single bulk RNA-seq counts matrix from a small mouse
liver experiment — 6 mice, 3 treated vs 3 control. Counts are already
generated by featureCounts. I do NOT want any alignment, QC of raw
reads, or trimming — those are done. I only want three things:
(1) DESeq2 normalization and differential expression between treated
vs control with adjusted p-value, (2) a volcano plot of the DE
results, and (3) a short final report. Nothing else — no pathway
enrichment, no batch correction, no figures beyond the volcano.
"""


def main():
    code, body = http("POST", f"{PREFIX}/session", body={})
    if code != 200:
        print(f"FAIL session: {code} {body}")
        return 1
    sid = body["session_id"]
    print(f"session: {sid}")

    code, body = http("POST", f"{PREFIX}/session/{sid}/turn", body={"message": PROMPT})
    if code not in (200, 202):
        print(f"FAIL first turn: {code} {body}")
        return 1

    naive = [
        "Counts are already aligned and QC'd, please skip those. "
        "Just the three things I asked for.",
        "Use the default DESeq2 settings. No additional analyses.",
        "Please call propose_summary_confirmation now so I can confirm.",
        "Lock in just those three. Put up the summary card.",
        "Yes, proceed with what I described.",
    ]
    for i in range(8):
        kind = poll_until(
            sid, {"pending_confirmation", "ready_to_emit", "emitted", "blocked"}, PER_TURN
        )
        if kind in ("pending_confirmation", "ready_to_emit", "emitted"):
            break
        if kind == "blocked":
            print(f"FAIL blocked after turn {i+1}")
            return 1
        http("POST", f"{PREFIX}/session/{sid}/turn", body={"message": naive[i % len(naive)]})

    kind = poll_until(sid, {"pending_confirmation", "ready_to_emit", "emitted"}, 30)
    if kind not in ("pending_confirmation", "ready_to_emit", "emitted"):
        print(f"FAIL stuck in {kind}")
        return 1
    if kind != "emitted":
        http("POST", f"{PREFIX}/session/{sid}/confirm", body={})
        kind = poll_until(sid, {"ready_to_emit", "emitted"}, 60)
        if kind == "ready_to_emit":
            http("POST", f"{PREFIX}/session/{sid}/turn",
                 body={"message": "(confirmed — please continue)"})
            kind = poll_until(sid, {"emitted"}, 60)
            if kind != "emitted":
                http("POST", f"{PREFIX}/session/{sid}/turn",
                     body={"message": "Please call emit_package now."})
                kind = poll_until(sid, {"emitted"}, 60)
    if kind != "emitted":
        print(f"FAIL never emitted, state={kind}")
        return 1

    deadline = time.time() + 30
    wf = None
    while time.time() < deadline:
        matches = sorted(
            glob.glob(f"{PACKAGE_ROOT}/{sid}-*/WORKFLOW.json"),
            key=os.path.getmtime, reverse=True,
        )
        if matches:
            with open(matches[0]) as f:
                wf = json.load(f)
                wf["__path"] = matches[0]
                break
        time.sleep(2)
    if wf is None:
        print("FAIL: WORKFLOW.json not found")
        return 1

    tasks = set(wf.get("tasks", {}).keys())
    n = len(tasks)
    print(f"emitted: {wf['__path']}")
    print(f"task_count: {n}")
    print(f"tasks: {sorted(tasks)}")

    # Acceptance: must include DE + volcano (= reporting) + final.
    required_substr = ["differential_expression", "final_reporting"]
    missing = [r for r in required_substr if not any(r in t for t in tasks)]
    if missing:
        print(f"FAIL: missing required substrings {missing}")
        return 1

    # Subset shouldn't have raw_qc / alignment / sequence_trimming (the user said NO to these)
    forbidden_substr = ["sequence_trimming", "alignment", "raw_qc"]
    illegal = [f for f in forbidden_substr if any(f in t for t in tasks)]
    if illegal:
        print(f"WARN: subset contained {illegal} (user said skip)")
        # Soft warn, don't fail — compiler may still include for safety

    if n >= 25:
        print(
            f"WARN: subset task count {n} is close to the full archetype shape "
            "(~32 expected for bulk_rnaseq); subset reduction may be ineffective"
        )

    print("PASS small-subset")
    return 0


if __name__ == "__main__":
    sys.exit(main())
